### ISSUE TITLE
Add support for EEL 0.12.X?

### ISSUE THREAD

**Issue by alepodj** [brentvollebregt/auto-py-to-exe#100]
Hello

While upgrading EEL from 0.11.x to 0.12.x via `pip install --upgrade EEL` the following error is thrown:

```
ERROR: auto-py-to-exe 2.7.4 has requirement Eel==0.11.0, but you'll have eel 0.12.4 which is incompatible.
```

EEL installs successully, will this mean i wont be able to pack eel 0.12.x apps with auto-py-to-exe?

pip freeze
```
Eel==0.12.4
auto-py-to-exe==2.7.4
```

Thanks

**Comment by alepodj** [comment]
I guess i should have tried before asking. Tried and it seems to work so far no issues.

Thanks

**Comment by brentvollebregt** [comment]
If this application still works with the new version then I will be happy to update it - I'll test it now. The reason I had added that constraint was due to Eel previously making some changes that broke this project.
