### ISSUE TITLE
[Suggestion] Add "Experimental" Branch

### ISSUE THREAD

**Issue by Savvasun** [brentvollebregt/auto-py-to-exe#102]
**Add a branch** that can be used to add completely new features that may need a little more attention but can improve the program and will most likely be merged with "develop" or "master" at some point.  

* New changes **may** break the *main* program but the feature will be though out and be pretty much fixed before being added to the branch.

* It could be used to fix *very* large issues that are too large to fix on "master".

* ***The best use yet***: Use it to merge pull requests from forks of this repo to have the ability to implement them **without breaking or ruining the main code**.

**Comment by brentvollebregt** [comment]
I'm not sure if I support merging incomplete code from PRs; what would be the benefit of merging incomplete features rather than making sure they are ok in PR stage?

`develop` is currently used for ongoing development before releases, if this break, it's not a huge issue.

**Comment by Savvasun** [comment]
>I'm not sure if I support merging incomplete code

I don't support that either. I meant that the feature would be pretty thought out during the time it was suggested in the pull request. 

I think the branch is sort of a quick stage for new features where people can merge code from pull requests into and owners of the repo can tweak it further. It doesn't have to be a branch of the same magnitude as "develop". It can just be a quick stage that gets it ready to turn into an actual feature.

**Comment by brentvollebregt** [comment]
I see what you mean when thinking of it as an extra space where a maintained can make changes but I'm fine with making those sorts of changes in develop as this repository doesn't get a significant amount of pull requests.

Do you have an example of an active repository that uses this? I'm not opposed to the idea, I just feel like it might be a bit of an overkill and that branch may slowly drift behind develop overtime.

**Comment by Savvasun** [comment]
I can't really reference any repos that do this except my own. I use it to think about and experiment on ideas that are even too wild for `develop`.

**Although** big repos like "vscode" have close to hundreds of branches (made by the other devs) where (the main) devs achieve similar tasks. Smaller repos that don't have thousands of devs could use such a branch.

**Comment by brentvollebregt** [comment]
I think you may be thinking of feature branches like in a git-flow model where many branches are created off develop and merged back into develop when complete.

If that is the case, that is already what is being done; PRs are feature branches. Though I do most of my changes directly on the develop branch due to permissions and it saves me effort later.

**Comment by Savvasun** [comment]
Ok then, that makes sense.
