### ISSUE TITLE
[Small Issue] Current-Command command specifications don't match text in ui

### ISSUE THREAD

**Issue by Savvasun** [brentvollebregt/auto-py-to-exe#103]
The command specifications in the Current Command textarea should match the descriptions that are written in "( )"s above the buttons in the UI:

| What it says   | What the UI shows |
|----------------|-------------------|
| `--noconsole`  | `--windowed`      |
| `--nowindowed` | `--console`       |

* [ ] The file that needs to be fixed is `configurations.js`
    * A possible fix for this could be getting command data from the the `index.html` file

***This issue is informative as well as a request. I may be able to fix this myself soon.***

**Comment by brentvollebregt** [comment]
Yep, this is incorrect, when you click the "Console Based" it should show `--console` and when clicking "Window Based" it should show `--windowed`.

Looking at `options.map(x => x.option_strings)` in the UI, it seems this option has three possible strings per state (console / window). A solution to this would be to always try to get the second string but use the first if there is no second; looks like this handles each option well still - verification: `options.map(x => x.option_strings[x.option_strings.length === 1 ? 0 : 1])`.

I'll put a commit into develop now, thanks heaps for this.
