### ISSUE TITLE
Not Compatible with Mnemonic

### ISSUE THREAD

**Issue by h4Ck3D001** [brentvollebregt/auto-py-to-exe#106]
Hi,
So my script uses Mnemonic, when i convert the Script to an exe i get this Error:
Traceback (most recent call last):
  File "MyPath", line 19, in <module>
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\mnemonic\mnemonic.py", line 72, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MyName\\AppData\\Local\\Temp\\_MEI124882\\mnemonic\\wordlist/english.txt'

**Comment by brentvollebregt** [comment]
It looks like mnemonic is looking in `./mnemonic\wordlist` for `english.txt` (as stated in the error). Have you included this file?

**Comment by h4Ck3D001** [comment]
@brentvollebregt So if you use One Directory and download the File from the Github and put it in the Directory, it works, but the problem is, it wont work with One File. (Here is the Github Link: https://github.com/trezor/python-mnemonic)

**Comment by brentvollebregt** [comment]
So you're saying when you use One Directory and add the file english.txt in manually, it works, but if you use One File and don't add english.txt manually, it doesn't work?

Why are you not adding english.txt in the one file option? You added it when using One Directory so it would make sense to also add it for the One File method.

**Comment by h4Ck3D001** [comment]
@brentvollebregt Because it searches for the File in the Temp Directory because it creates it automatically so that won't work

**Comment by brentvollebregt** [comment]
Have you added the file using the additional file section? Then it will be put in the bundled executable.

I recommend making sure adding the additional file works as one directory before trying one folder as you can see inside it to check you got the path right.

**Comment by brentvollebregt** [comment]
Closing due to no further information provided for over three months.
