### ISSUE TITLE
Runs but doesn't allow file to be uploaded

### ISSUE THREAD

**Issue by Caswell1000** [brentvollebregt/auto-py-to-exe#109]
Hi

Thanks for a super programme. I installed it on the x86 machine, it runs and show page but when I click brouse it does not open file prowser, also the current command space is empty, I has a good one running in a 64bit machine but I want to create a 32bi version of executable.

![image](https://user-images.githubusercontent.com/35820171/87152680-73271900-c2b6-11ea-924d-a1d2d65444bc.png)

**Comment by brentvollebregt** [comment]
Are there any errors in the Chrome DevTools console or the terminal window that auto-py-to-exe is running from?

**Comment by Caswell1000** [comment]
Hi, 
thanks, the pc does not have chrome, could that be the issue, I don't see any errors, let me install chrome, the other PC that had a similar issue also did not have chrome.
Regards
CN

**Comment by Caswell1000** [comment]
That seems to have fixed the problem, after installing Chrome it was A for away

![image](https://user-images.githubusercontent.com/35820171/87161873-6958e200-c2c5-11ea-8513-2f2a70a5d905.png)

**Comment by brentvollebregt** [comment]
Are you able to see the console on the other browser? What browser was it?

**Comment by Caswell1000** [comment]
It's sorted now, it was a matter of installing chrome, the browser was explorer. The major issue now is tkinter TCL not loading. Thanks very much for your help, we can close this issue now.
