### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ilove3q** [brentvollebregt/auto-py-to-exe#11]
Hello, i had used this app to build a miniGame called Sonar Treasure Hunt. But it has some error there:
So, how to fix it? thank you very much
Traceback (most recent call last):
  File "C:\Users\TRAN\AppData\Roaming\Python\Python36\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Users\TRAN\AppData\Roaming\Python\Python36\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "C:\Users\TRAN\AppData\Roaming\Python\Python36\site-packages\bottle_websocket\plugin.py", line 5, in wrapper
    callback(request.environ.get('wsgi.websocket'), *args, **kwargs)
  File "C:\Users\TRAN\AppData\Roaming\Python\Python36\site-packages\eel\__init__.py", line 129, in _websocket
    return_val = _exposed_functions[message['name']](*message['args'])
  File "run.py", line 72, in convert
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by brentvollebregt** [comment]
Could you please put your code on something like pastebin and link it here so I can take a look at it?

**Comment by brentvollebregt** [comment]
The error is occurring on the call to pyinstaller. Could you paste the contents of the textarea below the title "Current Command" in the interface before you compile here.

It seems that windows cannot find pyinstaller or one of the files you have referenced in the UI. Make sure that all the filenames you have provided the interface are correct and can be found.

**Comment by ilove3q** [comment]
@brentvollebregt : that "Current Command":  pyinstaller -y  "D:/Python/VS code/miniGame/trouve_tresor.py"

**Comment by brentvollebregt** [comment]
If you run that command in the current working directory you used to execute run.py, do any errors appear?

**Comment by ilove3q** [comment]
Thanks @brentvollebregt, I just succeeded as soon as I installed the pyinstaller. I think that this topic can close

**Comment by brentvollebregt** [comment]
pyinstaller is in the requirements.txt file. The readme installation instructions cover installing requirements.

**Comment by ilove3q** [comment]
I have tried many ways to install the pyinstaller succeeded. I used succeeded this command: easy_install pyinstaller. I think that we should add some lines in the program to check whether the pyinstaller program is successful

**Comment by changchethu** [comment]
C:\Users\chang>pip install chatterbot
Collecting chatterbot
  Using cached https://files.pythonhosted.org/packages/6c/0e/dac0d82f34f86bf509cf5ef3e2dfc5aa7d444bd843a2330ceb7d854f84f2/ChatterBot-1.0.5-py2.py3-none-any.whl
Collecting pint>=0.8.1 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/15/9d/bf177ebbc57d25e9e296addc14a1303d1e34d7964af5df428a8332349c42/Pint-0.9-py2.py3-none-any.whl
Collecting pyyaml<5.2,>=5.1 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/a2/50/d42aa0b14fd7b04d287fa739c16e49d9eb79d364a6aa0c5df6ecdeef3dd4/PyYAML-5.1-cp37-cp37m-win32.whl
Collecting nltk<4.0,>=3.2 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/6f/ed/9c755d357d33bc1931e157f537721efb5b88d2c583fe593cc09603076cc3/nltk-3.4.zip
Collecting mathparse<0.2,>=0.1 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/c3/e5/4910fb85950cb960fcf3f5aabe1c8e55f5c9201788a1c1302b570a7e1f84/mathparse-0.1.2-py3-none-any.whl
Collecting python-dateutil<2.8,>=2.7 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl
Collecting sqlalchemy<1.3,>=1.2 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/21/ed/7eb53305b43ca51774a458d7c292f3bc7664d7a9bbb5bac4149fa34756b9/SQLAlchemy-1.2.18.tar.gz
Collecting pymongo<4.0,>=3.3 (from chatterbot)
  Downloading https://files.pythonhosted.org/packages/1e/4e/bec80279eae8fc279316d73d3f8d0dc8bc088f122ea1444ef8fb3bb93ced/pymongo-3.7.2-cp37-cp37m-win32.whl (305kB)
    100% |████████████████████████████████| 307kB 1.5MB/s
Collecting pytz (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting spacy<2.2,>=2.1 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/77/f3/eb5aece989ecca541c4b5a439cb8a86fe5254b1521925b547609fb3aaf64/spacy-2.1.3.tar.gz
  Installing build dependencies ... error
  Complete output from command c:\users\chang\appdata\local\programs\python\python37-32\python.exe c:\users\chang\appdata\local\programs\python\python37-32\lib\site-packages\pip install --ignore-installed --no-user --prefix C:\Users\chang\AppData\Local\Temp\pip-build-env-qoa07ymg\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel>0.32.0.<0.33.0 Cython cymem>=2.0.2,<2.1.0 preshed>=2.0.1,<2.1.0 murmurhash>=0.28.0,<1.1.0 thinc==7.0.0.dev6:
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/c8/b0/cc6b7ba28d5fb790cf0d5946df849233e32b8872b6baca10c9e002ff5b41/setuptools-41.0.0-py2.py3-none-any.whl
  Collecting wheel>0.32.0.<0.33.0
    Using cached https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
  Collecting Cython
    Using cached https://files.pythonhosted.org/packages/0a/80/519ca446605826488935c9a2be44bca604d640786b0c3308abd9c9f28002/Cython-0.29.6-cp37-cp37m-win32.whl
  Collecting cymem<2.1.0,>=2.0.2
    Using cached https://files.pythonhosted.org/packages/eb/cb/4ff546a491f764f67284572d25c57927e3f17103adf979bc99d90128f3eb/cymem-2.0.2-cp37-cp37m-win32.whl
  Collecting preshed<2.1.0,>=2.0.1
    Using cached https://files.pythonhosted.org/packages/00/52/ef641ebb40e287b95e9742e7f3120dca0350d92b3d0ef050e5133acf8931/preshed-2.0.1-cp37-cp37m-win32.whl
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached https://files.pythonhosted.org/packages/22/e9/411be1845f1ac07ae3bc40a4b19ba401819baed4fa63b4f5ef28b2300eb4/murmurhash-1.0.2.tar.gz
  Collecting thinc==7.0.0.dev6
    Using cached https://files.pythonhosted.org/packages/f2/bf/3685c4718b547583bfe3a3d54db8f0f992e30b49db1ecbce8e5d8a4c7604/thinc-7.0.0.dev6.tar.gz
  Collecting blis<0.3.0,>=0.2.1 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/59/9e/84a83616cbe5daa94909da38b780e93bf566dc2113c3dc35d7b4cad52f63/blis-0.2.4.tar.gz
  Collecting thinc_gpu_ops<0.1.0,>=0.0.1 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/a4/ad/11ab80a24bcedd7dd0cfabaedba2ceaeca11f1aaeeff432a3d2e63ca7d02/thinc_gpu_ops-0.0.4.tar.gz
  Collecting numpy>=1.7.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/61/be/b4d697563d4a211596a350414a87612204a8bb987c4c1b34598cd4904f55/numpy-1.16.2-cp37-cp37m-win32.whl
  Collecting wrapt<1.11.0,>=1.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/a0/47/66897906448185fcb77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz
  Collecting plac<1.0.0,>=0.9.6 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
  Collecting tqdm<5.0.0,>=4.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl
  Collecting six<2.0.0,>=1.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
  Collecting wasabi<1.1.0,>=0.0.9 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/76/6c/0376977df1ba9f0ec27835d80456d9284c79737cb5205649451db1181f01/wasabi-0.2.1-py3-none-any.whl
  Collecting srsly<1.1.0,>=0.0.5 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/05/df/6ad3ad1d2747b0ef17e674c8cf7f0cb5e5c0056ee6e9b2ebc88e55871cd4/srsly-0.0.5.tar.gz
  Installing collected packages: setuptools, wheel, Cython, cymem, preshed, murmurhash, numpy, blis, thinc-gpu-ops, wrapt, plac, tqdm, six, wasabi, srsly, thinc
    Running setup.py install for murmurhash: started
      Running setup.py install for murmurhash: finished with status 'done'
    Running setup.py install for blis: started
      Running setup.py install for blis: finished with status 'error'
      Complete output from command c:\users\chang\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\chang\\AppData\\Local\\Temp\\pip-install-enbcac76\\blis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\chang\AppData\Local\Temp\pip-record-m9t2vlbt\install-record.txt --single-version-externally-managed --prefix C:\Users\chang\AppData\Local\Temp\pip-build-env-qoa07ymg\overlay --compile:
      BLIS_COMPILER? None
      running install
      running build
      running build_py
      creating build
      creating build\lib.win32-3.7
      creating build\lib.win32-3.7\blis
      copying blis\about.py -> build\lib.win32-3.7\blis
      copying blis\benchmark.py -> build\lib.win32-3.7\blis
      copying blis\__init__.py -> build\lib.win32-3.7\blis
      creating build\lib.win32-3.7\blis\tests
      copying blis\tests\common.py -> build\lib.win32-3.7\blis\tests
      copying blis\tests\test_dotv.py -> build\lib.win32-3.7\blis\tests
      copying blis\tests\test_gemm.py -> build\lib.win32-3.7\blis\tests
      copying blis\tests\__init__.py -> build\lib.win32-3.7\blis\tests
      copying blis\cy.pyx -> build\lib.win32-3.7\blis
      copying blis\py.pyx -> build\lib.win32-3.7\blis
      copying blis\cy.pxd -> build\lib.win32-3.7\blis
      copying blis\__init__.pxd -> build\lib.win32-3.7\blis
      running build_ext
      error: [WinError 2] The system cannot find the file specified
      msvc
      py_compiler msvc
      {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'HOSTTYPE': 'x86_64', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LANG': 'C.UTF-8', 'OLDPWD': '/home/matt/repos/flame-blis', 'VIRTUAL_ENV': '/home/matt/repos/cython-blis/env3.6', 'USER': 'matt', 'PWD': '/home/matt/repos/cython-blis', 'HOME': '/home/matt', 'NAME': 'LAPTOP-OMKOB3VM', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'SHLVL': '1', 'LOGNAME': 'matt', 'PATH': '/home/matt/repos/cython-blis/env3.6/bin:/tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5:/mnt/c/Users/matt/Documents/cmder/vendor/conemu-maximus5/ConEmu:/mnt/c/Python37/Scripts:/mnt/c/Python37:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/LLVM/bin:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/nodejs:/mnt/c/Users/matt/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/matt/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/matt/AppData/Roaming/npm:/snap/bin:/mnt/c/Program Files/Oracle/VirtualBox', 'PS1': '(env3.6) \\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 'VAGRANT_HOME': '/home/matt/.vagrant.d/', 'LESSOPEN': '| /usr/bin/lesspipe %s', '_': '/home/matt/repos/cython-blis/env3.6/bin/python'}
      clang -c C:\Users\chang\AppData\Local\Temp\pip-install-enbcac76\blis\blis\_src\config\bulldozer\bli_cntx_init_bulldozer.c -o C:\Users\chang\AppData\Local\Temp\tmpshgg0tt0\bli_cntx_init_bulldozer.o -O2 -funroll-all-loops -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude\windows-x86_64 -I.\frame\3\ -I.\frame\ind\ukernels\ -I.\frame\1m\ -I.\frame\1f\ -I.\frame\1\ -I.\frame\include -IC:\Users\chang\AppData\Local\Temp\pip-install-enbcac76\blis\blis\_src\include\windows-x86_64

      ----------------------------------------
  Command "c:\users\chang\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\chang\\AppData\\Local\\Temp\\pip-install-enbcac76\\blis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\chang\AppData\Local\Temp\pip-record-m9t2vlbt\install-record.txt --single-version-externally-managed --prefix C:\Users\chang\AppData\Local\Temp\pip-build-env-qoa07ymg\overlay --compile" failed with error code 1 in C:\Users\chang\AppData\Local\Temp\pip-install-enbcac76\blis\

  ----------------------------------------
Command "c:\users\chang\appdata\local\programs\python\python37-32\python.exe c:\users\chang\appdata\local\programs\python\python37-32\lib\site-packages\pip install --ignore-installed --no-user --prefix C:\Users\chang\AppData\Local\Temp\pip-build-env-qoa07ymg\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel>0.32.0.<0.33.0 Cython cymem>=2.0.2,<2.1.0 preshed>=2.0.1,<2.1.0 murmurhash>=0.28.0,<1.1.0 thinc==7.0.0.dev6" failed with error code 1 in None

please help to solve this error

**Comment by brentvollebregt** [comment]
@changchethu I'm sorry, how is this related to auto-py-to-exe or even this issue?

**Comment by siddharthsharma189b** [comment]
@changchethu Did you find the solution for this, I am facing the same error.

**Comment by brentvollebregt** [comment]
@siddharthsharma189b what error are you getting and what actions are you performing to get this error?

**Comment by siddharthsharma189b** [comment]
@brentvollebregt I m trying to install chatterbot package

**Comment by brentvollebregt** [comment]
@siddharthsharma189b how is that related to auto-py-to-exe?

**Comment by siddharthsharma189b** [comment]
@brentvollebregt it is not related to auto-py-to-exe, but I wanted to know from @changchethu if he resolved the error he has shared above as I am facing the same while installing chatterbot

**Comment by brentvollebregt** [comment]
@siddharthsharma189b, if you look at the other reports made by @changchethu, you can see that they reported this at gunthercox/ChatterBot#1699 and got a response.
