### ISSUE TITLE
Cannot import name 'Timer'

### ISSUE THREAD

**Issue by PySimpleGUI** [brentvollebregt/auto-py-to-exe#112]
I downloaded the files from GitHub and tried to run the run.py file.  

```
C:\Python\PycharmProjects\GitHub\auto-py-to-exe>python run.py
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from auto_py_to_exe import __main__ as apte
  File "C:\Python\PycharmProjects\GitHub\auto-py-to-exe\auto_py_to_exe\__main__.py", line 10, in <module>
    from . import ui
  File "C:\Python\PycharmProjects\GitHub\auto-py-to-exe\auto_py_to_exe\ui.py", line 5, in <module>
    import eel
  File "C:\Python\Anaconda3\lib\site-packages\eel\__init__.py", line 4, in <module>
    from gevent.threading import Timer
ImportError: cannot import name 'Timer'
```

**Comment by brentvollebregt** [comment]
I just tested a fresh clone into a fresh Python environment and it worked fine. 

Could you please provide reproduction steps and details of your environment. Without exact steps to reproduce your situation, I cannot do anything.

**Comment by PySimpleGUI** [comment]
The steps were
Download zip
Unzip zip
Perform the run like you see in the original error.

On Windows 10.  Running Python 3.6

**Comment by PySimpleGUI** [comment]
Here's the eel info from pip:

```
Name: Eel
Version: 0.13.2
Summary: For little HTML GUI applications, with easy Python/JS interop
Home-page: https://github.com/samuelhwilliams/Eel
Author: Chris Knott
Author-email: chrisknott@hotmail.co.uk
License: UNKNOWN
Location: c:\python\anaconda3\lib\site-packages
Requires: whichcraft, bottle, future, bottle-websocket
Required-by:

```

**Comment by brentvollebregt** [comment]
In the README under [Running Locally Via Github (no install)](https://github.com/brentvollebregt/auto-py-to-exe#running-locally-via-github-no-install), step 3 states:

> Execute `python -m pip install -r requirements.txt`

This step is not in your steps to reproduce - please do this before running the application.

**Comment by PySimpleGUI** [comment]
Ah

That did it.  I'm really sorry that I failed to follow instructions.  Doh!

Thanks for the quick and patient support.
