### ISSUE TITLE
Permissions error with compiled python file

### ISSUE THREAD

**Issue by YourKalamity** [brentvollebregt/auto-py-to-exe#113]
I have converted a python file that does work as a regular python file, it downloads a couple of things off the web and moves them around.
However after compiled with auto-py-to-exe, the file falls into a Permission Error when it tries to write to anything

**Comment by brentvollebregt** [comment]
When running your Python script, did you run it with elevated permissions? If so, you also will need to run the executable with elevated permissions.

If you're getting a permission error and don't know why I recommend double-checking what you think is happening and compare it to what is actually happening.

**Comment by YourKalamity** [comment]
I'm not sure why but rerunning auto-py-to-exe fixed it

**Comment by DINOTICK-Dev** [comment]
I had this same issue and elevating permissions didn't work for me...

**Comment by brentvollebregt** [comment]
@DINOTICK-Dev what is the exception and traceback?
