### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by AmericanTrucker20** [brentvollebregt/auto-py-to-exe#117]
While trying to install pyinstaller im getting this error

File "setup.py", line 63
      file=sys.stderr)
          ^
  SyntaxError: invalid syntax

Can somebody help me please?

**Comment by brentvollebregt** [comment]
Can you please provide the full error and traceback - I can't even tell what this file is. 
Also what command are you executing?

**Comment by AmericanTrucker20** [comment]
okay, I have pasted the whole error on a txt file for your convenience, I am trying to install auto-py-to-exe with the following command: 
pip install auto-py-to-exe

My python version: 2.7.18
My pip version: 20.2.2

[error.txt](https://github.com/brentvollebregt/auto-py-to-exe/files/5094415/error.txt)

**Comment by brentvollebregt** [comment]
Looks like this is an issue with setuptools not auto-py-to-exe - I was having a similar issue a couple of days ago with newer versions of setuptools in Python 2.7.

From issues I read online, you need setuptools<45 but I didn't get around to following that through completely.

Could you validate that setuptools is working as expected by installing some other libraries that use setuptools. Techincally this error is occurring when setting up pyinstaller.

**Comment by AmericanTrucker20** [comment]
Hey sorry for not replying. I really don't understand what you mean by setuptools as I'm totally new to Python. But after checking the version of my setup tools, I came to know the version of my setup tools is 41.2.0, I think I need to upgrade right?

**Comment by brentvollebregt** [comment]
PyInstaller no longer supports Python 2.7 so no longer does this tool. You will need to uninstall PyInstaller 4 and install PyInstaller 3.6.

**Comment by AmericanTrucker20** [comment]
Hey, sorry for not responding for such a long time. I tried many ways of fixing it but it didn't work, however I got my friend to do it and the app works fine. Thanks a lot for your help. Have a great time.
