### ISSUE TITLE
Your pip is changed?

### ISSUE THREAD

**Issue by HenryKang1** [brentvollebregt/auto-py-to-exe#118]
When I install yours I face the trojan warn from my vaccine.
I think there is something wrong with your pip. Coudl you check it please?

**Comment by brentvollebregt** [comment]
My pip? I'm not quite sure what you're trying to say here. My pip is working fine.

Could you please explain your problem further.

**Comment by brentvollebregt** [comment]
Almost 3 months have passed with no further elaboration from @HenryKang1 so I'll close this issue.
