### ISSUE TITLE
why I can't hide the console of app

### ISSUE THREAD

**Issue by ilove3q** [brentvollebregt/auto-py-to-exe#12]
Hello,
When i convert to exe, i chose "window based", but in folder "output" of the "auto-py-to-exe-master", the app hide the console, but in folder "__pycache__" in this directory, the app don't hide the consle

**Comment by brentvollebregt** [comment]
What is this "pycache" folder you are talking about? I cannot find it so have been unable to reproduce the issue.

**Comment by ilove3q** [comment]
the location of the "pycache" is D:\Python\VS code\GameGraphie\Basic\__pycache__, and the location of the output is: D:\Python\auto-py-to-exe-master\output\catanimation

**Comment by brentvollebregt** [comment]
I'm sorry but I can't see how this __pycache__ folder is an issue? It is not part of the package that is generated at all so you don't need to run anything inside it. It feels like you are leaving out something important here.

Do you know what [__pycache__](https://stackoverflow.com/questions/16869024/what-is-pycache) is? Is this what you are talking about? You don't need to run the files manually, it's for processes relating to the compiler to deal with. You can delete them if you want or not. Leaving them there will make the script run faster when run locally.

**Comment by ilove3q** [comment]
thanks madam, you can close this topic
