### ISSUE TITLE
Why defender found virus on my exe ? 

### ISSUE THREAD

**Issue by lilcsz** [brentvollebregt/auto-py-to-exe#122]
Defender: Trojan:Win32/Fuery.C!cl
Virustotal: https://www.virustotal.com/gui/file/d550722a37725534dde5a1a4fbe8605daa32b83e5a1e32e3ee1035da8794035b/detection

**Comment by brentvollebregt** [comment]
From [my post that is linked in this tool and the README](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#my-antivirus-detected-the-exe-as-a-virus): 

> This is your anti-virus vendors fault. Check out [this](https://github.com/pyinstaller/pyinstaller/issues/2501#issuecomment-286230354). There is nothing I or PyInstaller can do to stop this.

**Comment by brentvollebregt** [comment]
I have seen this pop up a lot more recently, for those reading this, you have a few options:
- Tell your antivirus that these files are fine
- Switch to a different and more accurate anti-virus
- Notify your antivirus vendor about the false positive

This is assuming you haven't tried to package something malicious. If you have tried to package something malicious, there is no reason you should be complaining about this; the antivirus has done its job.

**Comment by brentvollebregt** [comment]
From pyinstaller/pyinstaller#4852:

> @TheMineTuberYT please feel free to recompile the bootloaders. They are what the antivirus is scanning. AFAIK the reason is that they were cross-compiled for windows, from Linux, so antivirus can be touchy. See https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html for details on how to do this.
> 
> As for proof its not a virus? The source code is available in the bootloader folder of this repository.

**Comment by ptApol0** [comment]
Eu consegui criar o arquivo mas não consigo enviar por email, também usei o virus total que considerou o arquivo como trojam

**Comment by brentvollebregt** [comment]
@ptApol0 please read my comments above in regards to virus detection. Is something not clear?
