### ISSUE TITLE
Save project state [Feature request]

### ISSUE THREAD

**Issue by OverLordGoldDragon** [brentvollebregt/auto-py-to-exe#127]
Currently I have to keep the tab open to preserve my settings, and the closest I can get to a save is by screenshotting everything and manually re-entering later. Would be nice to have a "save/load project" option for projects with lengthy configs.

**Comment by brentvollebregt** [comment]
Like the import and export config options that are in the settings tab and noted in the [application arguments (`--config`)](https://github.com/brentvollebregt/auto-py-to-exe#arguments)?

**Comment by OverLordGoldDragon** [comment]
@brentvollebregt Yeah - my bad, didn't see.
