### ISSUE TITLE
.exe file is massive

### ISSUE THREAD

**Issue by maartenbithub** [brentvollebregt/auto-py-to-exe#131]
I like to see that auto-py-to-exe only keeps the parts of the library that are used in the script. Now a 55kb .py file becomes a 314mb  .exe file

**Comment by brentvollebregt** [comment]
pyinstaller most likely sees other modules in your environment and is adding them automatically. 

A really easy way to get around this is to create a new/clean virtual environment, install auto-py-to-exe into it, install the required modules for your project and then use the auto-py-to-exe in this virtual environment to package your script. Doing it this way will mean pyinstaller doesn't see the packages you don't need bundled.
