### ISSUE TITLE
Add the ability to save the output destination in the config json file.

### ISSUE THREAD

**Issue by unbeatable-101** [brentvollebregt/auto-py-to-exe#132]
Could this be added? It would be better than changing it every time.

**Comment by brentvollebregt** [comment]
It could be added but the reason I left it out is because if the config is moved between machines it could be put in an undesired location.

**Comment by unbeatable-101** [comment]
What about just saving it not in the config file, but on the machine?

**Comment by brentvollebregt** [comment]
Hmm, I'm not very keen on setting a value for every instance. If you package one project in one directory and then package another project in another directory, the output of the two shouldn't really end up in the same place.

I provided `--output-dir` for easily being able to change the output directory. Maybe put your command with `--output-dir` in a batch/shell script to obscure it?

**Comment by unbeatable-101** [comment]
I'll do that, thanks!
