### ISSUE TITLE
Failed to execute script pyi_rth_pkgres

### ISSUE THREAD

**Issue by 42isTheAnswer42** [brentvollebregt/auto-py-to-exe#135]
hi there,
thanks a lot for deploying your software. Im failing at running my compiled exe-file.
maybe you can help me out?When it's compiled and I run it I always get a window saying 
"Failed to execute script pyi_rth_pkgres"
I tried python 2.7 and python 3,8

**Comment by brentvollebregt** [comment]
There is a help post linked in the ui and the readme of the repo; did you read the debugging section ( https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging )? What was the error you found after following the steps?

**Comment by 42isTheAnswer42** [comment]
I got it fixed with adding import base64 as statement at the script beginning.
Thx for your support!
