### ISSUE TITLE
Pip does not support python 3.8 or higher

### ISSUE THREAD

**Issue by Zahrem** [brentvollebregt/auto-py-to-exe#136]
Hello, 

I tried to install the requirements by doing [pip install -r requirements.txt] 
I get a lot of errors. Will you ever upgrade it to 3.8 or higher? 
If so, it'd be very helpful!

Thanks.

**Comment by brentvollebregt** [comment]
Did you look at #74 with the title "Missing Python 3.8 support"? All details and updates can be found in there.

**Comment by brentvollebregt** [comment]
Did you look at #74 with the title "Missing Python 3.8 support"? All details and updates can be found in there.
