### ISSUE TITLE
Failed to install dependencies

### ISSUE THREAD

**Issue by hosseinzamaninasab** [brentvollebregt/auto-py-to-exe#137]
ERROR: Command errored out with exit status 1

**Comment by brentvollebregt** [comment]
Could you please give some more details on your issue? I have no clue what you've done to get this message.

**Comment by hosseinzamaninasab** [comment]
When i try to install it with pip: 
`Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\hossein\appdata\local\programs\python\python39\python.exe' 'c:\users\hossein\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Hossein\AppData\Local\Temp\pip-build-env-tuzvzoy8\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.17 ; platform_python_implementation == '"'"'CPython'"'"''
       cwd: None
  Complete output (27 lines):
  Collecting setuptools>=40.8.0
    Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting Cython>=3.0a5
    Using cached Cython-3.0a6-py2.py3-none-any.whl (1.0 MB)
  Collecting cffi>=1.12.3
    Using cached cffi-1.14.3-cp39-cp39-win_amd64.whl (179 kB)
  Collecting greenlet>=0.4.17
    Using cached greenlet-0.4.17.tar.gz (61 kB)
  Collecting pycparser
    Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
  Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
  Installing collected packages: setuptools, wheel, Cython, pycparser, cffi, greenlet
      Running setup.py install for greenlet: started
      Running setup.py install for greenlet: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\hossein\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hossein\\AppData\\Local\\Temp\\pip-install-3u1e_eac\\greenlet\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hossein\\AppData\\Local\\Temp\\pip-install-3u1e_eac\\greenlet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Hossein\AppData\Local\Temp\pip-record-6e3d3m6g\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\Hossein\AppData\Local\Temp\pip-build-env-tuzvzoy8\overlay' --compile --install-headers 'C:\Users\Hossein\AppData\Local\Temp\pip-build-env-tuzvzoy8\overlay\Include\greenlet'
           cwd: C:\Users\Hossein\AppData\Local\Temp\pip-install-3u1e_eac\greenlet\
      Complete output (5 lines):
      running install
      running build
      running build_ext
      building 'greenlet' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\users\hossein\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hossein\\AppData\\Local\\Temp\\pip-install-3u1e_eac\\greenlet\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hossein\\AppData\\Local\\Temp\\pip-install-3u1e_eac\\greenlet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Hossein\AppData\Local\Temp\pip-record-6e3d3m6g\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\Hossein\AppData\Local\Temp\pip-build-env-tuzvzoy8\overlay' --compile --install-headers 'C:\Users\Hossein\AppData\Local\Temp\pip-build-env-tuzvzoy8\overlay\Include\greenlet' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hossein\appdata\local\programs\python\python39\python.exe' 'c:\users\hossein\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Hossein\AppData\Local\Temp\pip-build-env-tuzvzoy8\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.17 ; platform_python_implementation == '"'"'CPython'"'"'' Check the logs for full command output.`

**Comment by unbeatable-101** [comment]
Download [this](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

**Comment by brentvollebregt** [comment]
This looks like it is an issue with building gevent when reading the error. Did you read the help post that is linked in the README? I discuss how to install a pre-build distribution on gevent [here](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#possible-gevent-issue).

Either get the pre-built distribution or you could go down the route of @unbeatable-101's recommendation which will work also.

**Comment by hosseinzamaninasab** [comment]
Ok, thanks.
