### ISSUE TITLE
Py Converted to Exe make antivirus think that's virus but it's not

### ISSUE THREAD

**Issue by BluelyTASer** [brentvollebregt/auto-py-to-exe#138]
i ran an count.exe of my count.py script and it runs fine but the issue is that antivirus think it's a virus.
![105](https://user-images.githubusercontent.com/59511669/99159360-582c4180-26ba-11eb-9ffc-f7306db267c0.PNG)

**Comment by brentvollebregt** [comment]
Did you look at #122? Looks like it's your answer. 

Let me know if this is not along the same line.

**Comment by ReddyKilowatt** [comment]
This has been happening with Python ".exe makers" since Python 2.3"
