### ISSUE TITLE
the  --add-data  params has errors

### ISSUE THREAD

**Issue by xingag** [brentvollebregt/auto-py-to-exe#14]
i want to convert one python file which depend on a common python file to exe file.when i choose the Console Window style with console Based,the exe file works well . but,when i choose the window based(hide the console),the exe file cause error. What is the cause of this.

**Comment by xingag** [comment]
<img width="476" alt="snipaste_2018-05-29_15-11-16" src="https://user-images.githubusercontent.com/5069818/40643698-905a583a-6353-11e8-9fba-bf9aa74305d3.png">

**Comment by brentvollebregt** [comment]
Add the debug flag located in the advance tab and create another package with this setting. Then run the executable using cmd to preserve output. You should see your error there. What is it?
