### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR running auto-py-to-exe

### ISSUE THREAD

**Issue by andreabisello** [brentvollebregt/auto-py-to-exe#143]
on python 3.8.4 on windows 10 updated
on just installed pip install auto-py-to-exe
running auto-py-to-exe
i obtain
![image](https://user-images.githubusercontent.com/2149815/100514224-1a77f000-3173-11eb-901b-0ef187840668.png)

**Comment by brentvollebregt** [comment]
This looks pretty similar to gevent/gevent#1708. What version of gevent do you have installed? Might pay to try and downgrade it.

**Comment by andreabisello** [comment]
@brentvollebregt version is 20.9.0 .

**Comment by brentvollebregt** [comment]
Have you tried down-grading?

**Comment by andreabisello** [comment]
with 20.6.2 or 20.5.2 error is different
![image](https://user-images.githubusercontent.com/2149815/100591180-b03b8880-32f5-11eb-9579-12b7c98790be.png)
but still not working.
i need to try on my personal computer out of the work organization because some months ago i tried this project and it worked, i will take a look at the configurations

**Comment by brentvollebregt** [comment]
Are there any errors in the DevTools (you can open them using F12)

**Comment by andreabisello** [comment]
@brentvollebregt 
no
![image](https://user-images.githubusercontent.com/2149815/106378395-b6f18500-63a4-11eb-98a0-23519215428b.png)

**Comment by brentvollebregt** [comment]
@andreabisello could you please:
1.Create a clean virtual environment
2. Install auto-py-to-exe in this environment
3. Run auto-py-to-exe and see if this happens again.

**Comment by andreabisello** [comment]
@brentvollebregt  i updated everything and not it works, even without the use of a venv.
thanks for the tool, it works very well!
