### ISSUE TITLE
auto-py-to-exe not run me

### ISSUE THREAD

**Issue by Deleted-accounts** [brentvollebregt/auto-py-to-exe#144]
I can not run the great tool auto-py-to-exe
Screenshot attached:
![image](https://user-images.githubusercontent.com/74473446/101091493-e6605d00-35c0-11eb-9450-98179a93468f.png)

**Comment by brentvollebregt** [comment]
What version of gevent is in the environment you are using?

**Comment by brentvollebregt** [comment]
Related: gevent/gevent#1260

**Comment by Deleted-accounts** [comment]
Thank you very much, now it works great!

**Comment by brentvollebregt** [comment]
What specifically did you do to fix this issue?

**Comment by Deleted-accounts** [comment]
pip install -U gevent
Thanks
