### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ramsh\AppData\Local\Temp\pip-build-ay95ymcz\gevent

### ISSUE THREAD

**Issue by Pranav13589** [brentvollebregt/auto-py-to-exe#146]
i am a beginner i don't know how to solve such errors 
and it is also showing 
" You are using pip version 7.1.2, however version 20.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command. "
(in yellow color)

**Comment by Pranav13589** [comment]
i have written ( py -3.5 -m pip install auto-py-to-exe --user ) in command prompt

**Comment by brentvollebregt** [comment]
That message is not an error. What actually has gone wrong? Do you have an error and stackt trace?
