### ISSUE TITLE
error in: "One File"

### ISSUE THREAD

**Issue by IvanPy-Exe** [brentvollebregt/auto-py-to-exe#147]
the main file is: шаблон.py
I also import: server in it.py and player.py
I also have to upload to" onefile " the format: Subdex_Bold.ttf

also, all additional files I save to: "."
in the file шаблон.exe, in the code шаблон.py, on the line: font = pygame.font.Font('Subdex_Bold.ttf', 26) the error occurs: "wrong file path"!

( if that I activated: pygame.init() )

Help me!

**Comment by IvanPy-Exe** [comment]
![image](https://user-images.githubusercontent.com/72767917/102258448-ffe99900-3f1e-11eb-8f81-4b9c70932e12.png)
![image](https://user-images.githubusercontent.com/72767917/102258646-2e677400-3f1f-11eb-8a32-f5e0ad7a01ef.png)

**Comment by IvanPy-Exe** [comment]
![image](https://user-images.githubusercontent.com/72767917/102259031-a766cb80-3f1f-11eb-96e1-ac178263a921.png)
![image](https://user-images.githubusercontent.com/72767917/102259344-09bfcc00-3f20-11eb-9237-279c9e6f16ba.png)

**Comment by brentvollebregt** [comment]
Were you able to get this working as one-directory (not one file)?

**Comment by IvanPy-Exe** [comment]
> Were you able to get this working as one-directory (not one file)?

Yes, I could, but this is a little different. I really do not understand why the address in "onefile" is not the one that was set. this problem only affects the font.ttf file.
