### ISSUE TITLE
my .exe file is not working

### ISSUE THREAD

**Issue by rzzzvikashkumar** [brentvollebregt/auto-py-to-exe#148]
there was problem in my script.

**Comment by rzzzvikashkumar** [comment]
I have created my .exe from auto-py-to-exe but it gives error.
Then i created in onedir mode and it also gives error.
![script_VfKRTsstd0](https://user-images.githubusercontent.com/75368279/102325944-c742d180-3fa9-11eb-9f08-0207d5c2036a.png)
To resolve this i copy cloudscraper folder from other sources to its output/script/ and it works.

**But how to do same thing when i create single .exe file instead of one directory.**

**Comment by unbeatable-101** [comment]
https://stackoverflow.com/a/64586862/14509818
try this

**Comment by AndresQuiVal** [comment]
Give a check on this:
https://stackoverflow.com/questions/65046032/error-creating-exe-pyinstaller-with-cloudscraper-module-python/65332172#65332172

**Comment by rzzzvikashkumar** [comment]
> https://stackoverflow.com/a/64586862/14509818
> try this

This worked.
