### ISSUE TITLE
Whole directory to exe

### ISSUE THREAD

**Issue by EikeAhlers** [brentvollebregt/auto-py-to-exe#149]
converting 1 script without dependencies works perfect. But what if i have a whole directory to convert? adding the whole folder does not work

**Comment by brentvollebregt** [comment]
How would you run said directory of scripts? I have never heard of a way to run multiple scripts at once - each needs their own process.

**Comment by EikeAhlers** [comment]
No i want to run 1 script with imports from other scripts.

Thanks for the help, probally a beginner question

Brent Vollebregt <notifications@github.com> schrieb am Sa., 19. Dez. 2020,
21:02:

**Comment by brentvollebregt** [comment]
Did you read the help blog post that I have put in the REAMDE and the UI? In [that post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#how-do-i-convert-all-my-python-files), I state:

> Add the entry point in the script location. PyInstaller searches for imports to get the rest of the Python files required to run, so as long as you use the `import` keyword, your files will be added.

Might pay to give it a read before asking here 👍
