### ISSUE TITLE
cannot import name askopenfilename

### ISSUE THREAD

**Issue by Tohaan** [brentvollebregt/auto-py-to-exe#15]
#python run.py 
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from tkinter.filedialog import askopenfilename, askdirectory, askopenfilenames
ImportError: cannot import name askopenfilename
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Apareceu este erro, sou leigo ainda , pode me esclarecer do que  se trata?
como resolver?

I use Parrot workStation , and Firefox Browser

**Comment by brentvollebregt** [comment]
What version of python are you running?

**Comment by Tohaan** [comment]
Sim, o python 2.7 está instalado mas o erro ainda aparece
