### ISSUE TITLE
ModuleNotFoundError: No module named 'pyautogui' on Python 3.8.6

### ISSUE THREAD

**Issue by aquib-sh** [brentvollebregt/auto-py-to-exe#151]
I tried creating exe multiple times, each time after running the output file it gave me  `ModuleNotFoundError: No module named 'pyautogui' `. It runs perfectly with .py file and I do not have more than 1 version of Python installed. pyautogui is also installed but it seems that it doesn't compile while creating exe using autopytoexe.

**Comment by Okeke-Divine** [comment]
It has a problem maybe use pip to install pyinstaller

**Comment by aquib-sh** [comment]
I tried uninstalling pyinstaller and auto-py-to-exe and installed them again. Still didn't work.

**Comment by brentvollebregt** [comment]
@aquib-sh did you read the help post that I wrote up that is linked in the README, in the top of the UI and at the bottom of the UI after packaging a script?

Searching for "ModuleNotFoundError" in this post helped me immediately find the heading ["ModuleNotFoundError: No module named x / ImportError: No module named x"](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#modulenotfounderror-no-module-named-x-importerror-no-module-named-x). I highly recommend giving this a read (that is why I have put it in so many places).

From the post:

> To fix this in the UI, open the advanced tab and find the --hidden-import input. Simply paste the module name into this input and then repackage. If the original error is still appearing, you have done this incorrectly.

Alternatively, if you have put the module in here and the error is still occurring, make sure that the library you're trying to add is installed in the same distribution of Python that auto-py-to-exe is using - I have seen quite a few people get confused by this kind of situation before.

**Comment by aquib-sh** [comment]
> @aquib-sh did you read the help post that I wrote up that is linked in the README, in the top of the UI and at the bottom of the UI after packaging a script?
> 
> Searching for "ModuleNotFoundError" in this post helped me immediately find the heading ["ModuleNotFoundError: No module named x / ImportError: No module named x"](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#modulenotfounderror-no-module-named-x-importerror-no-module-named-x). I highly recommend giving this a read (that is why I have put it in so many places).
> 
> From the post:
> 
> > To fix this in the UI, open the advanced tab and find the --hidden-import input. Simply paste the module name into this input and then repackage. If the original error is still appearing, you have done this incorrectly.
> 
> Alternatively, if you have put the module in here and the error is still occurring, make sure that the library you're trying to add is installed in the same distribution of Python that auto-py-to-exe is using - I have seen quite a few people get confused by this kind of situation before.

 File "c:\program files\python38\lib\site-packages\PyInstaller\building\api.py", line 532, in assemble
    raise SystemExit(_MISSING_BOOTLOADER_ERRORMSG)
SystemExit: 
Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>

This is what it gave me after hidden-import... it doesn't make any sense I am using Windows 10 and I already have both GCC and Microsoft VS tools

**Comment by brentvollebregt** [comment]
@aquib-sh if you search for "`PyInstaller does not include a pre-compiled bootloader for your platform`" in Google, there are a couple of discussions at:

- https://stackoverflow.com/questions/60010544/pyinstaller-pre-compiled-bootloader-not-found-and-build-fails
- https://github.com/pyinstaller/pyinstaller/issues/4318

In the PyInstaller issue linked above and also hinted in the SO answers, it may be your antivirus removing these. Check that your antivirus is not removing PyInstaller related files.

**Comment by aquib-sh** [comment]
> @aquib-sh if you search for "`PyInstaller does not include a pre-compiled bootloader for your platform`" in Google, there are a couple of discussions at:
> 
> * https://stackoverflow.com/questions/60010544/pyinstaller-pre-compiled-bootloader-not-found-and-build-fails
> * [pyinstaller/pyinstaller#4318](https://github.com/pyinstaller/pyinstaller/issues/4318)
> 
> In the PyInstaller issue linked above and also hinted in the SO answers, it may be your antivirus removing these. Check that your antivirus is not removing PyInstaller related files.
> 
> Original comment replied to (deleted)

yes, I found it thats why deleted it

**Comment by aquib-sh** [comment]
I am putting the detailed solution here of how I was able to solve this issue.

After hidden import it gave
Gave Bootloader not precompiled error

steps taken:
cloning the pyinstaller github repo
python setup.py install
cd bootloader
python ./waf all --target-arch=64bit

placed the folder of output to exception in windows antivirus

adding modules to hidden import that had problem:
pyautogui
wave
aifc
pyaudio

THIS SOLVED THE ISSUE, HOPE SOMEONE WILL FIND USEFUL.
