### ISSUE TITLE
Not importing wxPython module

### ISSUE THREAD

**Issue by marcinconn** [brentvollebregt/auto-py-to-exe#157]
Despite many attempts( as a hidden import: wx, wxPyhton, wxPython as wx) the exe file doesn't want to launch. I did console version and only running this in Commend Prompt showed: No module named 'wx'.
Python version: 3.9
Auto-py-to-exe: 2.8.0

**Comment by brentvollebregt** [comment]
If you execute `pip list`, are auto-py-to-exe and wx in the output?

**Comment by marcinconn** [comment]
yes. Downgrade to Python 3.7 helps and all works fine

**Comment by brentvollebregt** [comment]
Did you have more than one distribution of Python installed when you tried the first time?

Could you create a virtual environment using Python 3.9, add your dependencies, add auto-py-to-exe and then use the installation of auto-py-to-exe in the virtual environment to package your script? Does it still fail?
