### ISSUE TITLE
Exe compiles fine but does not run when I double-click it

### ISSUE THREAD

**Issue by Nanobot567** [brentvollebregt/auto-py-to-exe#163]
I compiled a python file using auto-py-to-exe and everything worked fine, according to the console, but when I tried to run the .exe, nothing happened.

Here is my python code:

```
import pyautogui as p

p.alert("sup")
p.alert("this is a lame test")
```

If you need the console output as well, here it is:

[console output.txt](https://github.com/brentvollebregt/auto-py-to-exe/files/6267079/console.output.txt)

**Comment by brentvollebregt** [comment]
Ok, that is only the console output from the packaging stage. What about the output in the console when following the debugging steps in the common issues post?

**Comment by Nanobot567** [comment]
Ok, I followed the debugging steps and the program works now :) Thank you!

**Comment by brentvollebregt** [comment]
For others that come here: please read the help post! I have literally linked it at the bottom of the UI itself after packaging a script, the README of this repo and many other places others come for help.
