### ISSUE TITLE
No OPENSSL_Applink

### ISSUE THREAD

**Issue by ken1882** [brentvollebregt/auto-py-to-exe#165]
I'm on Windows 10 19041, Python 3.8.5, pyinstaller 4.2 and autopytoexe 2.8.0. After converting the following simple code to exe and run it gives me error `OPENSSL_Uplink(00007FFE3C559D30,08): no OPENSSL_Applink` and crashed. 

any idea to fix this? thanks.

```
import requests

with open('test.txt', 'w') as fp:
  fp.write(requests.get("https://www.google.com").content)
```

**Comment by brentvollebregt** [comment]
What is the command in the text field under the "Current Command" heading? 
If you execute this yourself, do you get the same result?

**Comment by ken1882** [comment]
> 
> 
> What is the command in the text field under the "Current Command" heading?
> If you execute this yourself, do you get the same result?

The command is `pyinstaller --noconfirm --onedir --console  test.py` and yeah still the same error, so it's a pyinstaller issue?

**Comment by brentvollebregt** [comment]
My vote you be yes, this is a pyinstaller issue. If you run the command yourself, do you still get the issue?
I would recommend running this in an empty directory containing only your test.py file.

**Comment by ken1882** [comment]
Turns out it seems is the openssl issue due to my python is using different version than the Windows itself, maybe because I had compiled openssl natively myself before in order to use it in my another C project so it messed up. I used another clean Win10 VM and run the same command it works perfectly, thanks.
