### ISSUE TITLE
Virus with Exe by Auto-Py-To-Exe and Pyinstaller

### ISSUE THREAD

**Issue by FranyBoston27** [brentvollebregt/auto-py-to-exe#167]
Hello everybody. When I create a file with Auto-Py-To-Exe and with pyinstaller MalwareBytes the application blocks me and Micosoft Defender SmartScreen warns me of the app launch. I leave the link to VirusTotal and hope someone can help me
https://www.virustotal.com/gui/file/6a9225dd357a4925fb1fb35ccd28b87108611735a4297e5fe8d103e652f12982/detection

**Comment by brentvollebregt** [comment]
Did you read the help post?

**Comment by FranyBoston27** [comment]
> 
> 
> Did you read the help post?

Where is it?

**Comment by asimo10** [comment]
malwarebytes is stupid and thinks that the exe file is a virus

**Comment by asimo10** [comment]
theres nothing to worry about just whitelist the file and run it

**Comment by brentvollebregt** [comment]
> Where is it?

@FranyBoston27 the help post is linked:
 - [In this project's README](https://github.com/brentvollebregt/auto-py-to-exe#issues-using-the-tool)
 - At the top of the tool
 - At the bottom of the tool after every build
 - In the description and the pinned comment on the help video linked in the README

I highly encourage people to read the post first before asking questions - there is a reason a wrote it and linked it in so many places. Did you read the README before making this issue?

**Comment by FranyBoston27** [comment]
> 
> 
> > Where is it?
> 
> @FranyBoston27 the help post is linked:
> 
>     * [In this project's README](https://github.com/brentvollebregt/auto-py-to-exe#issues-using-the-tool)
> 
>     * At the top of the tool
> 
>     * At the bottom of the tool after every build
> 
>     * In the description and the pinned comment on the help video linked in the README
> 
> 
> I highly encourage people to read the post first before asking questions - there is a reason a wrote it and linked it in so many places. Did you read the README before making this issue?

Yeah, but I hadn't seen that part

**Comment by brentvollebregt** [comment]
@FranyBoston27 sorry, which part? Did it not pop up at the bottom of the UI for you?

**Comment by FranyBoston27** [comment]
> 
> 
> @FranyBoston27 sorry, which part? Did it not pop up at the bottom of the UI for you?

I don't seen this part
![AutoPyToExe](https://user-images.githubusercontent.com/79326795/116782489-b0e57000-aa89-11eb-8d34-43a12b72e802.png)

**Comment by brentvollebregt** [comment]
I assume you have seen the reference to #122 - let me know if this needs to stay open for some reason.
