### ISSUE TITLE
Seems to convert okay but then when I run the .exe nothing happens.

### ISSUE THREAD

**Issue by LesMack00** [brentvollebregt/auto-py-to-exe#17]
output from conversion set to one file and no console.

> 

Cleaning file structure
77 INFO: PyInstaller: 3.3.1
77 INFO: Python: 3.6.5
77 INFO: Platform: Windows-7-6.1.7601-SP1
80 INFO: wrote D:\Users\gblmac\Downloads\auto-py-to-exe-master (3)\auto-py-to-exe-master\PMFinder.spec
82 INFO: UPX is not available.
85 INFO: Extending PYTHONPATH with paths
['D:\\Users\\gblmac\\Desktop\\Python programs\\PMs',
 'D:\\Users\\gblmac\\Downloads\\auto-py-to-exe-master '
 '(3)\\auto-py-to-exe-master']
86 INFO: checking Analysis
86 INFO: Building Analysis because out00-Analysis.toc is non existent
86 INFO: Initializing module dependency graph...
89 INFO: Initializing module graph hooks...
92 INFO: Analyzing base_library.zip ...
3134 INFO: running Analysis out00-Analysis.toc
3134 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\gblmac\appdata\local\programs\python\python36-32\python.exe
3914 INFO: Caching module hooks...
3924 INFO: Analyzing D:\Users\gblmac\Desktop\Python programs\PMs\PMFinder.py
4082 INFO: Loading module hooks...
4082 INFO: Loading module hook "hook-encodings.py"...
4176 INFO: Loading module hook "hook-pydoc.py"...
4177 INFO: Loading module hook "hook-xml.py"...
4430 INFO: Loading module hook "hook-_tkinter.py"...
4582 INFO: checking Tree
4582 INFO: Building Tree because out00-Tree.toc is non existent
4582 INFO: Building Tree out00-Tree.toc
4640 INFO: checking Tree
4640 INFO: Building Tree because out01-Tree.toc is non existent
4640 INFO: Building Tree out01-Tree.toc
4688 INFO: Looking for ctypes DLLs
4688 INFO: Analyzing run-time hooks ...
4690 INFO: Including run-time hook 'pyi_rth__tkinter.py'
4697 INFO: Looking for dynamic libraries
4884 INFO: Looking for eggs
4884 INFO: Using Python library c:\users\gblmac\appdata\local\programs\python\python36-32\python36.dll
4884 INFO: Found binding redirects: 
[]
4894 INFO: Warnings written to D:\Users\gblmac\Downloads\auto-py-to-exe-master (3)\auto-py-to-exe-master\build\PMFinder\warnPMFinder.txt
4941 INFO: Graph cross-reference written to D:\Users\gblmac\Downloads\auto-py-to-exe-master (3)\auto-py-to-exe-master\build\PMFinder\xref-PMFinder.html
5360 INFO: checking PYZ
5361 INFO: Building PYZ because out00-PYZ.toc is non existent
5361 INFO: Building PYZ (ZlibArchive) D:\Users\gblmac\Downloads\auto-py-to-exe-master (3)\auto-py-to-exe-master\build\PMFinder\out00-PYZ.pyz
5934 INFO: Building PYZ (ZlibArchive) D:\Users\gblmac\Downloads\auto-py-to-exe-master (3)\auto-py-to-exe-master\build\PMFinder\out00-PYZ.pyz completed successfully.
5954 INFO: checking PKG
5954 INFO: Building PKG because out00-PKG.toc is non existent
5954 INFO: Building PKG (CArchive) out00-PKG.pkg
8118 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
8189 INFO: Bootloader c:\users\gblmac\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\runw.exe
8189 INFO: checking EXE
8190 INFO: Building EXE because out00-EXE.toc is non existent
8190 INFO: Building EXE from out00-EXE.toc
8190 INFO: Appending archive to EXE D:\Users\gblmac\Downloads\auto-py-to-exe-master (3)\auto-py-to-exe-master\dist\PMFinder.exe
8217 INFO: Building EXE from out00-EXE.toc completed successfully.
Moving project to: D:/Users/gblmac/Desktop/Python programs/Exe's\
Cleaning file structure
Complete.

> 
I have tried using many different versions of py2exe, I have ensured that the SCRIPTS PATH is correct for build_exe, It all looks correct but just doesnt work when I run it.
Any help?

**Comment by brentvollebregt** [comment]
Regarding that the python script runs properly by itself then this may have been caused by incorrect configuration or third party modules. 
The best way to find what the issue is, is to select the -d flag's button in the advanced tab and then re-package it. This will mean the exe is now in a debugging mode. Open up cmd and then run the exe using cmd e.g. "C:/folder/path/myexe.exe". 
Any errors will be preserved in the console which you were previously missing.﻿

**Comment by brentvollebregt** [comment]
What are they errors that were provided?

**Comment by LesMack00** [comment]
The only error I get is here:
![image](https://user-images.githubusercontent.com/40140427/41249207-5b701058-6dab-11e8-8ed5-b98729891bcf.png)
When I close the exe window as it doesn't work properly, I don't even get this window when not run in debug it just doesn't start.

**Comment by brentvollebregt** [comment]
Please make this script console based as you will then not have to go through all the windows. Also can you please paste the command that is being executed next time?

**Comment by LesMack00** [comment]
On the CMD terminal i am executing _"D:\Users\gblmac\Desktop\Python programs\Exe's\PMFinder.exe"_ and now that it is set to console I am at least getting my program window but when I try to use the "GO" button my itemlist doesnt show.

Here is the console window ouptut:

> [15260] LOADER: sys.prefix is C:\Users\gblmac\AppData\Local\Temp\_MEI11882
> [15260] LOADER: Setting runtime options
> [15260] LOADER: Bootloader option: pyi-windows-manifest-filename PMFinder.exe.ma
> nifest
> [15260] LOADER: Initializing python
> [15260] LOADER: Overriding Python's sys.path
> [15260] LOADER: Post-init sys.path is C:\Users\gblmac\AppData\Local\Temp\_MEI118
> 82\base_library.zip;C:\Users\gblmac\AppData\Local\Temp\_MEI11882
> [15260] LOADER: Setting sys.argv
> [15260] LOADER: setting sys._MEIPASS
> [15260] LOADER: importing modules from CArchive
> [15260] LOADER: extracted struct
> [15260] LOADER: callfunction returned...
> [15260] LOADER: extracted pyimod01_os_path
> [15260] LOADER: callfunction returned...
> [15260] LOADER: extracted pyimod02_archive
> [15260] LOADER: callfunction returned...
> [15260] LOADER: extracted pyimod03_importers
> [15260] LOADER: callfunction returned...
> [15260] LOADER: Installing PYZ archive with Python modules.
> [15260] LOADER: PYZ archive: out00-PYZ.pyz
> [15260] LOADER: Running pyiboot01_bootstrap.py
> [15260] LOADER: Running pyi_rth__tkinter.py
> [15260] LOADER: Running PMFinder.py

and I am executing the following program:

```
from tkinter import *

def part_search():
    # The sole purpose of this function is to update elements, not creating them.
    listbox.delete(0,END)
    mtext = ment.get()
    print(mtext)
    mlabel2.config(text=mtext)
    msearch = open(r"PMs.txt")
    print('again')
    for line in msearch:
          if mtext in line:
              listbox.insert(END, str(line))

    listbox.config(yscrollcommand=scrollbar.set,width=0, justify=LEFT)
    scrollbar.config(command=listbox.yview)
    msearch.close()

    return

# This code is your original code for creating the first elements
mGui = Tk()
mGui.configure(bg="orange")
ment = StringVar()


mGui.geometry ("1000x500+200+300")
mGui.title ("Parts Finder")

mlabel1 = Label(mGui, text="Type in search term:\n PM Name, Area, Markcode e.g. 11.1.1", font="Times 16", bg="orange")
mlabel1.pack()
mentry = Entry(textvariable=ment, font="Times 20", width = 50, bg="orange")
mentry.pack()
mentry.focus()

mbutton = Button(mGui, text ="Go", font="Times 30", command = part_search, bg="grey")
mbutton.pack()

# here is the moved code from the function
Finder = ()
scrollbar = Scrollbar(mGui)
scrollbar.pack(side=RIGHT, fill=Y)
listbox = Listbox(mGui)
listbox.pack(fill=BOTH, expand=1)
listbox.configure(justify=CENTER, bg="orange", font="Times 16")
mlabel2 = Label(mGui)
mlabel2.pack()

while True:
    mGui.update_idletasks()
    mGui.update() 
```
Is there anything else you need?

**Comment by brentvollebregt** [comment]
Sorry, when saying command I meant the content of the textarea below the "Current Command" label.
When running this code when not packaged, it provides an initial error _tkinter.TclError: unknown option "-justify" and then a NameError: name 'mlabel2' is not defined when clicking the Go button.
When packaging the script myself that you provided, by simply running the exectuable in cmd I was provided with:
```powershell
PS C:\Users\Brent\GitHub\auto-py-to-exe\output\a> .\a.exe
Traceback (most recent call last):
  File "a.py", line 45, in <module>
  File "tkinter\__init__.py", line 1330, in configure
  File "tkinter\__init__.py", line 1321, in _configure
_tkinter.TclError: unknown option "-justify"
[5948] Failed to execute script a
```
This _tkinter.TclError as stated before is your issue.
After removing the text "justify=CENTER" from line 45 and re-packaging it now works fine.

**Comment by LesMack00** [comment]
I figured out what the issue was with it not working as expected, although I was adding an additional file "PMs.txt" it was being added to the assets directory when the program was looking in the root directory.
I changed
`msearch = open(r"PMs.txt")`
to
`msearch = open(r"assets/PMs.txt")`
and it works fine now.
thanks. :)

**Comment by brentvollebregt** [comment]
Oh right, you had never mentioned anything about an additional file.
Another tip is that you can change "assets/" to "." to the file can sit in the root.

**Comment by LesMack00** [comment]
Yes I saw that on the UI, but I wanted to keep the txt file separate. thanks for the help.
