### ISSUE TITLE
New Feature: Selecting Python  interpreter during config

### ISSUE THREAD

**Issue by goran-ristic-dev** [brentvollebregt/auto-py-to-exe#171]
Hi,
Maybe this question is for pyinstaller. Im sorry if i have made mistake. 
I have multiple projects, written in different Python versions (3.7.x,  3.9), and
by default,  3.7 is defined in windows path. 
In  the auto-py-to-exe logger, during conversion  to exe I have noticed that Python from the path is used instead of one defined in venv.
So, my question is:
Is it possible to somehow define which python interpreter will ne used in pyinstaller, and if it is, can you add this option to auto-py-to-exe gui?
Thanks in advance for response and for making such great GUI interface for pyinstaller!
😀💪👍

**Comment by brentvollebregt** [comment]
auto-py-to-exe directly calls PyInstaller at runtime. This means whichever distribution of Python auto-py-to-exe is running on will be the distribution that PyInstaller uses.

Unless we move the call to PyInstaller into its own process, I cannot see a way of doing this. We were previously calling PyInstaller in a new process but that was not an ideal implementation - I am not keen on going back to this.

All I can say is make sure you are running the auto-py-to-exe installed in your target Python distribution. With multiple distributions of Python installed and auto-py-to-exe potentially installed in more than one, you will need to be wary of which one you are actually running. On Windows, you can use `where auto-py-to-exe` to identify where the binary is that will be executed.
