### ISSUE TITLE
not compatible with python 3.7 x86?

### ISSUE THREAD

**Issue by apoklyps3** [brentvollebregt/auto-py-to-exe#18]
I get an error when fetching requirments

`
Command "c:\users\vali\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vali\\AppData\\Local\\Temp\\pip-install-scgbaab1\\greenlet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Vali\AppData\Local\Temp\pip-record-ib7f2f8v\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Vali\AppData\Local\Temp\pip-install-scgbaab1\greenlet\
`

**Comment by brentvollebregt** [comment]
Looks like an error with greenlet. Quite understandable that they won't be supporting 3.7 quite yet due to how new it is.
I'll update the readme, thank you for reporting this.
