### ISSUE TITLE
Can't access file

### ISSUE THREAD

**Issue by toivocat** [brentvollebregt/auto-py-to-exe#184]
It gives me this error at the bottom:

win32ctypes.pywin32.pywintypes.error: (1920, 'LoadLibraryEx', 'The file cannot be accessed by the system')

Project output will not be moved to output folder
Complete.

But it was working a few weeks ago.

**Comment by brentvollebregt** [comment]
Have you read the help post that is linked at the bottom of the UI after each build (and many other places)? I discuss this issue in it.

Also, #166, #141 already discuss this.

**Comment by toivocat** [comment]
And yes I looked at it.

**Comment by brentvollebregt** [comment]
Are you using Python from the Windows Store?

**Comment by toivocat** [comment]
no

**Comment by brentvollebregt** [comment]
Are you using Windows? If so, could you execute "where python" in cmd and pass the output here.

**Comment by toivocat** [comment]
it says it's here: C:\Users\Diana\AppData\Local\Microsoft\WindowsApps\python.exe

**Comment by toivocat** [comment]
My name isn't Diana this was my gramas computer that she gave to me

**Comment by brentvollebregt** [comment]
That output shows that whenever you execute "python", it is using Python from the Windows store.

How are you running auto-py-to-exe? If you are running it using `auto-py-to-exe` from cmd, can you pass the result of `where auto-py-to-exe`.

**Comment by toivocat** [comment]
I downloaded it from pip and I have a shortcut on my desktop

**Comment by toivocat** [comment]
because the cmd commands don't work.

**Comment by toivocat** [comment]
Could you just send me the code? Then I could copy then past it in a .py file because I know it was made with tkinter.

**Comment by brentvollebregt** [comment]
Cool, that hints to me that it will be using the default Python distribution which is most likely Python from the Windows Store. 

Unless you can show me different, that it's not using Python from the Windows Store, then I say this is your issue (as outlined in the other issues and the help post).

**Comment by brentvollebregt** [comment]
> Could you just send me the code? 

This is a git repo, all the code is right here for you??

**Comment by toivocat** [comment]
I downloaded python from python.org/downloads/

**Comment by toivocat** [comment]
It downloads two .py files nether of them work.

**Comment by brentvollebregt** [comment]
Please follow the [README](https://github.com/brentvollebregt/auto-py-to-exe) on how to install and run the application - of course downloading the two individual Python scripts will not work, you do not have all the dependent files.

From the information you have provided above, I do not believe you are running the tool with a Python distribution that is not from the Windows Store. You may have installed another distribution from python.org but potentially have not configured your environment correctly to use this distribution.

**Comment by toivocat** [comment]
I can't because those commands are for linux I think but they don't work in cmd.

**Comment by brentvollebregt** [comment]
@toivocat can you please point out the commands that "are for linux". 
As far as I'm aware, they will work on Windows regarding you have Python installed (and git if you are installing via GitHub).

**Comment by toivocat** [comment]
$ pip install auto-py-to-exe
$ auto-py-to-exe
$ git clone https://github.com/brentvollebregt/auto-py-to-exe.git
$ cd auto-py-to-exe
$ python setup.py install
$ auto-py-to-exe

cmd gives me this error:
'$' is not recognized as an internal or external command,
operable program or batch file.

**Comment by brentvollebregt** [comment]
You don't need to execute `$`

**Comment by toivocat** [comment]
ok but if I just type in auto-py-to-exe it says:

'auto-py-to-exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by brentvollebregt** [comment]
Have you installed auto-py-to-exe?

**Comment by toivocat** [comment]
yes

**Comment by brentvollebregt** [comment]
If you installed auto-py-to-exe, there should be a binary file in the "Scripts" folder in the root of your Python distribution (something like `C:\Python37` - will depend on where you put it when you installed it) named `auto-py-to-exe.exe` - does this exist? If not, then it has not been installed.

**Comment by toivocat** [comment]
it says it's here:
C:\Users\Diana\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts

also at the bottom it sayes:
WARNING: The scripts auto-py-to-exe.exe and autopytoexe.exe are installed in 'C:\Users\Diana\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

do you know how I can fix that

**Comment by brentvollebregt** [comment]
You said you were not using Python from the Windows Store, but right there it shows you still are. How do I know? [Read this](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#loadlibraryex-the-file-cannot-be-accessed-by-the-system).

Python from the Windows Store is not supported when not using a virtual environment.

Also, these GitHub issues are for issues about the tool auto-py-to-exe - however every question except your first one seems to be about your own environment setup.

**Comment by toivocat** [comment]
You idiot how many times did I say I got it from python.org/downloads/? I also don't get stuff from the windows store on by computer because one the windows store has slow downloads and two my computer is really slow witch would take it like a day to download python!

**Comment by toivocat** [comment]
Sorry about all this. I finally figured it out! It has nothing to do with this it is my stupid anti-virus software which keeps putting the executable in quarantine!
