### ISSUE TITLE
hook-gevent freeze and waits for data from the previous script to be entered.

### ISSUE THREAD

**Issue by Micah89x** [brentvollebregt/auto-py-to-exe#185]
Hello,

Every time when I compile a script to exe, the console window displaying me the "input" from the old script which I compiled to exe. When I press ENTER the script compiles correctly, but it is quite annoying.

Previously, even as I had scripts with input data from the user the auto-py-to-exe did not wait for the data.

I have Python 3.9.1 64 bit, Pyinstaller 4.3 and newest Auto-Py-To-Exe.

**Comment by brentvollebregt** [comment]
This looks similar to #162 which we did not get to the bottom of - what libraries are you using in your script?

Also if you create a clean virtual environment, install auto-py-to-exe and your dependencies, do you still have the same issue?

**Comment by Micah89x** [comment]
I've already tried on another version of Python and Auto-py-to-exe with no results.

I noticed that the problem came up after compiling to exe script in which subprocesses and getpass were used, I mistakenly set the auto-py-to-exe options to noconsole. I generates an .exe file from the gui not from the console.

**Comment by brentvollebregt** [comment]
Does either noconsole or console mode generate an executable and the other doesn't?

**Comment by Micah89x** [comment]
Both modes are waiting for data. Looks like that gui is kept somewhere cache in the system.

**Comment by brentvollebregt** [comment]
Sorry, so is all working now?

**Comment by Micah89x** [comment]
Works only with cmd/powershell, from GUI doesn't.

**Comment by brentvollebregt** [comment]
Could you please provide a basic script that does not package in auto-py-to-exe? Preferably in text please.

**Comment by Micah89x** [comment]
I can try to pack the simple script with the print command and anyway while generating the auto-py-to-exe will stop at hook-gevent and waiting to type anything. This is an input from a script that was packed a few days earlier. After all a script is successfully packed when you press enter button, but why Auto-py-to-exe remember data from another script?

**Comment by brentvollebregt** [comment]
My best guess is that you packaged a script that worked, went to package a new script (days later that failed) and it failed. You then went into the output folder and the previously packaged script is still there as you did not remove it.

I cannot be 100% sure though, it is not entirely clear what you are doing - this is simply my guess.

**Comment by Micah89x** [comment]
The problem occurs when I use the mega.py module. In this problematic script I had something like this:
`import getpass
from mega import Mega

email = input("Email address : ")
password = getpass.getpass("Password : ")

mega = Mega()
m = mega.login(email,password)
file = m.upload("C:/temp/req.txt")
m.get_upload_link(file)`

**Comment by brentvollebregt** [comment]
@Micah89x will it only fail packaging if you:
1. import getpass
2. import mega 
3. Get an email and password from the user
4. Create an instance of Mega
5. Login and upload a file to Mega

I feel like there may be some unrequited extra steps here.

I'm trying to get a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) - even if it is as basic as a single import, that is all I need.

**Comment by Micah89x** [comment]
Importing only mega.py is already causing the problem.

**Comment by brentvollebregt** [comment]
@Micah89x I used the following script (test.py):

```python
from mega import Mega
print('success')
```

Running this locally prints "success". However when it tried to execute `pyinstaller test.py`, it would not build at all and I was getting a message associated to:

> SystemExit: Unable to find "c:\users\user\test-environment\.venv\lib\site-packages\<package>.dist-info" when adding binary and data files.

Were you getting this also? I actually have just seen you never provided an error at all.

**Comment by Micah89x** [comment]
I don't get any error, there's a problem that I've described before - hook-gevent freeze and waiting for data from old script (GUI) and from command line work properly.

**Comment by brentvollebregt** [comment]
I just tried the script above that prints "success" after the import again and all seems to be fine.

I'll close this for now but if I can get an example of something that is broken, we can open this back up.
