### ISSUE TITLE
Open in Edge's app mode when Chrome isn't available

### ISSUE THREAD

**Issue by llluuulll** [brentvollebregt/auto-py-to-exe#187]
Hi
I already know and use auto-py-to-exe.
I have make a fresh install of python 3.9.6 and pip install auto-py-to-exe on it.
Then run auto-py-to-exe, but instead of showing up as usual in his own window he show up as new tab inside microsoft edge browser.
why ?

**Comment by brentvollebregt** [comment]
If you execute the following, what is the output:

```python
from eel import chrome
chrome_instance_path = chrome.find_path()
print(chrome_instance_path)
print(chrome_instance_path is not None and os.path.exists(chrome_instance_path))
```

**Comment by llluuulll** [comment]
i can directly tell you i don't have Chrome on this new computer, no need to run the script.
There is only Edge which is more privacy oriented, but, setup to use Chrome engine as search engine because Bing ... you know is not that well.

**Comment by brentvollebregt** [comment]
> instead of showing up as usual in his own window he show up as new tab inside microsoft edge browser

If you do not have Chrome installed, then this is working as designed.

From the README:

> To have the interface displayed in the images, you will need chrome. If chrome is not installed or --no-chrome is supplied, the default browser will be used.

**Comment by llluuulll** [comment]
Thx for answering.

Ok ... is what it is ... is not the end of the world ...
It is at least shown as browser tab.
Maybe a good signal to look further than Chrome.

**Comment by brentvollebregt** [comment]
Looks like there is some chat about Edge's App Mode now that it uses Chromium: ChrisKnott/Eel#251

If this gets put into an upcoming release of Eel, I'm happy to throw it in.

**Comment by llluuulll** [comment]
Hi, thx for sharing.

This post request is already more than a year old.
And as i see Eel dev cycle is slow.

Well, let's hope Eel do so.

**Comment by brentvollebregt** [comment]
Looks like this has finally made it in: https://github.com/python-eel/Eel/commit/094d4463ff99dd737e50bc2dabdda603a81b8817

Will look into what is needed for this soon.

**Comment by brentvollebregt** [comment]
This should be sorted now. Will put a new release out with the changes a bit later.
