### ISSUE TITLE
exe not opening

### ISSUE THREAD

**Issue by bonnybabukachappilly** [brentvollebregt/auto-py-to-exe#189]
I couldn't open the exe file. My project consist of node packages which are not using but needed in the directory.

**Comment by brentvollebregt** [comment]
Could you provide some more details? What do you mean by "I couldn't open the exe file" - you can't run it at all or it runs and immediately crashes?

Also did you read the help post before creating this issue?

**Comment by bonnybabukachappilly** [comment]
Sorry, I found out the issues. I ran the program via command prompt and found the issues and fixed it. I was new and I didn't find anything on the web and decided to post here. Sorry for the trouble.
