### ISSUE TITLE
pyqt4 Computer Vision application

### ISSUE THREAD

**Issue by hananabilabd** [brentvollebregt/auto-py-to-exe#19]
Hello Sir i tried using this tools with my [project](https://github.com/hananabilabd/Computer-Vision-and-Neural-Machine-Interface-for-Upper-Limb-Prostheses)  it outputs nothing i know that um using pyqt4 and TensorFlow which may even hard to install so it's too hard to convert to .exe ,, but is there is any chances i can do that ?

**Comment by hananabilabd** [comment]
and can i do that on linux ?

**Comment by brentvollebregt** [comment]
In terms of the project, have you actually tried? You won't know until you have tried.
There are definitely some big libraries there with very complex structures so you may have a hard time trying to make sure that all imports are satisfied and all files a present; but I believe it will be possible.

Also for being able to use this on linux, I have not tried it myself but it seems pyinstaller will create an executable binary. I'm not sure what you're aiming for but [this](https://stackoverflow.com/a/32157287) might help.

Also is there an issue here?

**Comment by brentvollebregt** [comment]
@hananabilabd is there still an issue here?
