### ISSUE TITLE
can't find cacert.pem

### ISSUE THREAD

**Issue by elieobeid7** [brentvollebregt/auto-py-to-exe#191]
I got many errors. To reproduce, install[ Firestore python library](https://firebase.google.com/docs/firestore/quickstart).

Try to call some function and do some call, then try packaging it.

![Capture](https://user-images.githubusercontent.com/660142/128637591-e5e1cd0c-4964-4cd4-8180-2b72f928822e.PNG)

**Comment by brentvollebregt** [comment]
Are you providing this pem file? If so, you need to add it as an additional file and fix up any references.
