### ISSUE TITLE
Missing config file parameters

### ISSUE THREAD

**Issue by madtatu-development** [brentvollebregt/auto-py-to-exe#197]
These 2 settings are NOT stored in the json configuration file when set, and this would be great and useful:

![{36B7FB8F-D075-4C35-8DB1-D12149C33E82}](https://user-images.githubusercontent.com/73760229/132322842-9a349ab6-969c-40cb-94e0-4f5fdabc8fd0.png)

- Possible you could add it ?

**Comment by brentvollebregt** [comment]
The recursion limit toggle is stored in the JSON configuration file.

The output directory is not stored in the JSON configuration file. When developing this feature, I consciously made the decision to leave the output directory from the values being stored. This is because if someone uses the configuration file on a machine that did not create the config, the file could appear in an odd place by default.

**Comment by madtatu-development** [comment]
Fair point, may I suggest a golden middle way for your kind consideration ?

A) when somebody set the output folder, a question popup to ask if the settings wish to be included in the config file. 
B) possibility to manually include this in config file by editing it, and if  it is there, it is not ignored. 

What do you think ?

**Comment by brentvollebregt** [comment]
I think B is a good option - will make sure to add some documentation for it 👍

**Comment by brentvollebregt** [comment]
@madtatu-development sorry for the delay, I have just put this change into develop. Are you able to try it out?

You can add the output directory to `nonPyinstallerOptions.outputDirectory`, for example:

```json
{
 "version": "auto-py-to-exe-configuration_v1",
 "pyinstallerOptions": [
    [Contents of array removed for brevity]
 ],
 "nonPyinstallerOptions": {
  "increaseRecursionLimit": true,
  "manualArguments": "",
  "outputDirectory": "C:\\Temp\\output"    <--- like this
 }
}
```

**Comment by madtatu-development** [comment]
Sorry for the slow response, happy to test it, as soon as I got home, latest by the end of this week.

**Comment by madtatu-development** [comment]
So, here I am BIG thanks for your patience!

I had tested, but unless I am seriously overlooking something, it does not work yet, unfortunately. 

What I did:
1. Copy the correct line from your post above
2. I had manually edited autopyexe json config file and pase the copied line.
3. I added an extra comma after the previous config line as shown above in your post
4. started autopyexe and loaded the config file
5. compared output directory input field

Please have look at the screenshot:

![{A610DDC0-0C5B-4E27-9091-23DAD052BE7E}](https://user-images.githubusercontent.com/73760229/135834552-479ca259-b43e-4c2d-b7ac-114efee3d625.png)

Did I overlook something ?

**Comment by brentvollebregt** [comment]
@madtatu-development what branch are you using?

**Comment by madtatu-development** [comment]
If I understood your question correctly:

![image](https://user-images.githubusercontent.com/73760229/135836664-1b824a2e-b45c-4f30-b09d-b104fcdef576.png)

**Comment by brentvollebregt** [comment]
This has not been put in the master branch yet as I was wanting to test first.

In git, we have branches that point to different states of the codebase. This repos/codebases main branch is master,

![image](https://user-images.githubusercontent.com/19944838/135838609-80ce25eb-ebea-4228-8089-f9c682ca585a.png)

however if you change this to develop, it will contain the new changes to be tested,

![image](https://user-images.githubusercontent.com/19944838/135838744-d620b81f-674c-441d-93d4-6bc0ad0edbf3.png)

From here, you can download the repo as a zip (using the green button), reinstall auto-py-to-exe by first uninstalling your current version and then installing the version in the downloaded zip as outlined [here](https://github.com/brentvollebregt/auto-py-to-exe/tree/develop#installing-via-github).

After installing the version in develop, it will be then ready to test.

**Comment by madtatu-development** [comment]
Oh, I see, terribly sorry, I never did this before. Thanks for explaining, I appreciate it!

I did it as you instructed, and confirm, to be working perfectly!! AWESOME ! And huge help, big thanks for added this in!!!!

Just for curiosity, to better understand how GIT works. Ss soon as you put it into master, all users will have this change when upgrading using pip install auto-to-py-exe --upgrade? This is super cool.

**Comment by brentvollebregt** [comment]
No need to be sorry, a good learning experience. You nailed it with the master branch process setup and going back to the normal version / version from PyPI.

I'll merge the code in now and get a release out.

**Comment by brentvollebregt** [comment]
Version 2.10.1 is now out: https://pypi.org/project/auto-py-to-exe/

**Comment by madtatu-development** [comment]
Sweet awesomeness, THANK YOU!!! It was a HUGE HELP!! 

May I ask one last question ?

Could you consider to add a CMD argument option (or any other way) to be able to call autopyexe with the json config file to automatically load config file at autopyexestartup ? Would be an amazing thing, for use, whom has to regenerate executable very often

**Comment by brentvollebregt** [comment]
There already is: ` --config`. From the README:

> Provide a configuration file (json) to pre-fill the UI. These can be generated in the settings tab.

To use this, execute `auto-py-to-exe --config yourconfigfile.json`.

**Comment by madtatu-development** [comment]
SORRY, you right, I overlooked it. Many thanks, have a lovely day!
