### ISSUE TITLE
module forms not found

### ISSUE THREAD

**Issue by xiaolaba** [brentvollebregt/auto-py-to-exe#199]
hi, we have used to test this tool and try to build GUI EXE under win10, build ok, run time error with module forms not found.

we have try another tool of 'pyinstaller', build ok, run ok.
`pyinstaller --onefile rodriguez.py'

No idea what to do and seeing FQA that was not help. it is new to python and because of the source code was clone from the repo here, https://github.com/JosephEoff/Rodriguez

would you mind to take a look and advise what would be done for a python beginner.

GUI looks like this,
[curve_tracer_GUI_neat](https://github.com/xiaolaba/Curve_Tracer_testing/raw/main/curve_tracer_GUI_neat.JPG)

**Comment by brentvollebregt** [comment]
What is the error you are getting? Are you able to copy and paste it here?

**Comment by xiaolaba** [comment]
> 
> 
> What is the error you are getting? Are you able to copy and paste it here?

thanks for the reply, let's try that when back to town later on
