### ISSUE TITLE
Reporting small Bug 

### ISSUE THREAD

**Issue by hananabilabd** [brentvollebregt/auto-py-to-exe#20]
um using PyQt4 and always use 
Ui_MainWindow, QMainWindow = loadUiType('GP.ui') 
so i don't have to convert my ui every time to .py .. so when i tried this great tool ,, when it outputs .exe i ran it , i found out there is an error which says that GP.ui is not found ,, and when i put the GP.ui  with the .exe in the same folder it ran perfectly 
so make sure you handle this small Bug 
Regards

**Comment by brentvollebregt** [comment]
In the interface under "Additional Files" there is a section where you can add files that are not python scripts. This is meant for things like images, data-sets and things like your .ui files. 
You can't expect for pyinstaller to copy all the files that you call (like GP.ui) as a lot of the time they are created a runtime, so it is up to you to simply add them to the package using an extra command. This extra command has been implemented into the interface as a simple file reference field.
If you want to import GP.ui from the base directory, I recommend changing "assets/" to ".".

I felt this was clear enough and am honestly not sure how to make this more clear without ruining the interface.

**Comment by hananabilabd** [comment]
Thanks a lot 
Another Question did you try to convert a python script that contain TensorFlow (Computer Vision library )) , i Tried with [mine](https://github.com/hananabilabd/Computer-Vision-and-Neural-Machine-Interface-for-Upper-Limb-Prostheses) , nut with there is no successs

**Comment by brentvollebregt** [comment]
No I have not, what was the error/issue? Maybe you could report it to [pyinstaller](https://github.com/pyinstaller/pyinstaller) if it is a significant issue

**Comment by brentvollebregt** [comment]
@hananabilabd is there still an issue here?

**Comment by hananabilabd** [comment]
No Thanks
