### ISSUE TITLE
Exe doesn't work

### ISSUE THREAD

**Issue by Nextross** [brentvollebregt/auto-py-to-exe#207]
I'm using Python 3.9.5. I wrote a script that will display a notification after starting the .exe, but when I tried to start it, it gives me this error:
```Traceback (most recent call last):
  File "svatky.py", line 14, in <module>
    toast.show_toast("Dnes má svátek", dnes, duration=5)
  File "win10toast\__init__.py", line 127, in show_toast
  File "win10toast\__init__.py", line 93, in _show_toast
  File "pkg_resources\__init__.py", line 1130, in resource_filename
  File "pkg_resources\__init__.py", line 342, in get_provider
  File "pkg_resources\__init__.py", line 886, in require
  File "pkg_resources\__init__.py", line 772, in resolve
pkg_resources.DistributionNotFound: The 'win10toast' distribution was not found and is required by the application
```

It worked as a script in terminal. Do you know where it issues could be?

**Comment by brentvollebregt** [comment]
Looks like `win10toast` is something you should add as a hidden import

**Comment by Nextross** [comment]
Still the same error appears. [Here](https://pastebin.com/ggKWKuw6)'s the code, you can have a look.

**Comment by brentvollebregt** [comment]
This does not look like an issue with auto-py-to-exe but the library you are using. 

Searching for `pkg_resources.DistributionNotFound: The 'win10toast' distribution was not found and is required by the application` in Google came up with this: jithurjacob/Windows-10-Toast-Notifications#25 - I recommend you take a look at the issue.

**Comment by Legorooj** [comment]
@brentvollebregt you may want to consider adding support for some of PyInstaller's new options. This issue should in theory be fixed by adding `--collect-metadata=win10toast` to the command.

**Comment by brentvollebregt** [comment]
@Legorooj thanks heaps for the tip. I can't see `--collect-metadata` as a valid argument, maybe you meant `--copy-metadata` or one of the other `--collect-X` args?

**Comment by Legorooj** [comment]
@brentvollebregt my bad, I did mean `--copy-metadata` haha. I keep calling it the wrong thing because all the others are named differently.
