### ISSUE TITLE
Access Denied File

### ISSUE THREAD

**Issue by SherlockBrayen** [brentvollebregt/auto-py-to-exe#208]
"Unable to access file '{0}'{1}".format(fname, exception_msg)
Exception: Unable to access file '

**Comment by brentvollebregt** [comment]
If you have found an issue with auto-py-to-exe, please give clear reproduction steps and a copy of the full stacktrace/error where possible.

**Comment by DINOTICK-Dev** [comment]
I had this same issue and had high hopes cause I thought there would be an answer here :(

**Comment by brentvollebregt** [comment]
@DINOTICK-Dev are you able to provide the full error? The original issue didn't contain enough information to look into this,
