### ISSUE TITLE
ModuleNotFoundError on existing module and fine working script

### ISSUE THREAD

**Issue by PierreBarreau** [brentvollebregt/auto-py-to-exe#209]
Hi (first question on GitHub, hope  I'm doing it good)

I'm facing an issue on the import of the Cisco Meraki SDK (an SDK to manage network devices), it's the first time where hidden-imports or paths can't solve my issue. I'm using:

 - Python 3.7.4
 - meraki-1.12.0
 - auto-py-to-exe-2.10.1
 - pyinstaller-4.6

The command I use to compile on auto_py_to_exe : `pyinstaller --noconfirm --onefile --console --no-embed-manifest  "path/to/file/list_all_clients.py"`.

The error appear when launching the exe compiled as shown bellow (code working perferctly in .py):

![image](https://user-images.githubusercontent.com/34342495/139876082-f628c581-920b-452f-ad4b-80975f2fa02d.png)

I think the issue comes from the format of the import in the __init__py of meraki. But I'm not good enough understand and solve this. In the code of __init__.py, the line is written like this 

![image](https://user-images.githubusercontent.com/34342495/139876378-98d8df0f-8173-489a-b93c-15dd1713b24f.png)

If changing the order of the imports, to be sure it's not related to one : 

![image](https://user-images.githubusercontent.com/34342495/139877396-63e31cfe-6cc7-43e2-97a7-ee96d1f6de0a.png)

I get the same error : 

![image](https://user-images.githubusercontent.com/34342495/139877692-7f5e8443-bd05-40c6-9e83-94c078c610be.png)

I tried to modify the line to be "import rest_session" but unsuccessfully (doing it like this make the .py fail too). I think it comes from the . which for me means it's in current repository.

I also tried to add a path to the lib repository : `pyinstaller --noconfirm --onefile --console --no-embed-manifest --paths "path/to/lib/meraki"  "path/to/file/list_all_clients.py"` without success. Same for the hidden imports.

I don't know if I gave enough information to try to debug. 

Thanks in advance,

**Comment by brentvollebregt** [comment]
By any chance have you named one of your files `meraki.py`? Second question would be just to check if you have run your script by itself (without turning it into an exe).

**Comment by PierreBarreau** [comment]
I don't have any file named `meraki.py` and yes I already ran the script as `.py` without any failure. 

I also tried to move my lib repository from it's original position in the Python3-6 repository (where pip putted it) into the repository of my script (still working in `.py` but still not working as `.exe` (even with the hidden-imports and paths)

**Comment by brentvollebregt** [comment]
@PierreBarreau could you please provide a **minimal** reproducible example?
