### ISSUE TITLE
Problem in EXE generation

### ISSUE THREAD

**Issue by GaneshJJ** [brentvollebregt/auto-py-to-exe#21]
Hi Brent , I am new to coding and python too .........But I am a Chemical Engineer and building some small and very simple programs , one of it is Multicomponent Distillation.
When I tried to convert it to EXE using ur Program , I am getting some error or something that I don't know , help me `please

![capture](https://user-images.githubusercontent.com/31261598/43063576-dc1f4766-8e79-11e8-8917-2e72683ec02a.PNG)
![capture](https://user-images.githubusercontent.com/31261598/43063613-fb60007a-8e79-11e8-8021-a71ab28d37d4.PNG)
![capture](https://user-images.githubusercontent.com/31261598/43063658-1b19b438-8e7a-11e8-9e1a-bc1a405b107b.PNG)
![capture](https://user-images.githubusercontent.com/31261598/43063766-710b8e02-8e7a-11e8-964e-a74f10ce5e7f.PNG)
![capture](https://user-images.githubusercontent.com/31261598/43063797-8f64ac80-8e7a-11e8-8b26-7a62100200f4.PNG)

Belo is my code
`import math
print("This Program will Let You Calculate No. of stages in Distillation Column for Mulcomponent System as well as Binary System\n")
print("[ Press 1 for Defining Multicomponent System , 2 for Defining Binary System , Enter to close ] \n")
inp =input("Define System = ")
if inp == "1":
    print("\nYou have Chosen Multi-Component Distillation System\n")
    print("Please Press Yes to Start or Enter to Close\n")
    Start=input("Start = ")
    if Start=="Yes":
        print("\nPlease Enter LKd ( Light Key component in Distillate)\n") 
        LKd =float(input("LKd = "))
        print("\nPlease Enter LKd ( Heavy Key component in Distillate)\n")
        HKd =float(input("HKd = "))
        print("\nPlease Enter LKd ( Light Key component in Bottom)\n")
        LKb =float(input("LKb = "))
        print("\nPlease Enter LKd ( Heavy Key component in Bottom)\n")
        HKb =float(input("HKb = "))
        print("\nDo you have Average Relative Volatility ? (Yes or No)\n")
        ans =input("Yes or No = ")
        if ans=="Yes":
            print("\nPlease Enter Average Relative Volatility\n")
            A_avg =float(input("A_avg = "))
        elif ans=="No":
            print("Please Enter Relative Volatility of Individual Components\n")
            A1 =float(input("Relative Volatility of More Volatile Component is = "))
            A2 =float(input("Relative Volatility of Less Volatile Component is = "))
            A_avg =math.sqrt(A1*A2)
        N = math.log((LKd/HKd)*(HKb/LKb))/math.log(A_avg)
        a =int(N)
        b =N-a
        if b==0:
            print('\nThe no. of Stages are {0}'.format(N))
        elif b<0:
            print('\nThe no. of Stages required for Multicomponent Distillation System is {0}'.format(a-1))
        elif b>0:
            print('\nThe no. of Stages required for Multicomponent Distillation System is {0}'.format(a+1))
        print("\nPlease Enter to Close\n")
        input()
    else:
        print("Closing Programme")
elif inp == "2":
    print("\nYou have Chosen Binary Component System\n")
    print("Please Press Yes to Start or Enter to Close\n")
    Start=input("Start = ")
    if Start=="Yes":
        print("\nPlease Enter Xd and Xb (Concentration of more Volatile Component in Overhead Product and in Bottom Product)\n")
        Xd=float(input("Xd = "))
        Xb=float(input("Xb = "))
        print("\nDo you know average volatility of the system?(answer in yes or no)")
        ans1 = input("Answer: ")
        if ans1 == "yes" or ans1 == "YES" or ans1 == "Yes":
            A_avg=float(input("A_avg = "))
            N= (math.log((Xd/(1-Xd))*((1-Xb)/Xb))/math.log(A_avg))
            a = int(N)
            b = N-a
            if b==0:
                print('\nThe minimum no. of Theoritical Stages Required as per Fenske Equation is {0}'.format(a))
                print("\nThank You For Using Program Press Enter to Close")
                input()
            else:
                print('\nThe minimum no. of Theoritical Stages Required as per Fenske Equation is {0}'.format(a+1))
                print("\nThank You For Using Program Press Enter to Close")
                input()
                
        else:
            print("\nPlease enter the individual relative volatility \n")
            a1 = float(input("Relative volatility of more volatile component: "))
            a2 = float(input("Relative volatility of less volatile component: "))
            A_avg=math.sqrt(a1*a2)
            N= (math.log((Xd/(1-Xd))*((1-Xb)/Xb))/math.log(A_avg))
            a = int(N)
            b = N-a
            if b==0:
                print('\nThe minimum no. of Theoritical Stages Required as per Fenske Equation is {0}'.format(a))
                print("\nThank You For Using Program Press Enter to Close")
                input()
            else:
                print('\nThe minimum no. of Theoritical Stages Required as per Fenske Equation is {0}'.format(a+1))
                print("\nThank You For Using Program Press Enter to Close")
                input()
    else:
        print("Closing Programme")
elif inp == "":
    print("\nThank you for Using Our Program , Closing Now [ Enter to Confirm ] ")
    input()
`

**Comment by brentvollebregt** [comment]
A couple questions I have:
1. What bit Python version are you packaging this on? (If you open the Python shell it will say 64 bit or 32 bit)
2. Are you trying to run this on your computer?

Things you could try to fix this:
- In advanced there is a button with "--noupx" in it; select this before packaging.
- If that doesn't work, try looking [here](https://www.reddit.com/r/starbound/comments/5609yt/cwindowssystem32msvcp140_dll_is_either_not/) it may be an issue with your C++ redistributable. Could try getting a newer version [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

Also just a good tip for next time, surround your code in three ` instead of 1 in GitHub, or just send a link to a [pastebin](https://pastebin.com/) entry. Not a big issue, I got the code running.

**Comment by GaneshJJ** [comment]
Thanks For your valuable time brent , I am using python 3.6.6

Earlier I was having 3.7...........but I was having problem in installing auto py to exe , so I am using 3.6 now ,there is no problem with c++ redistribuatable...........as I recently updated it..

and I am trying to run it on Computer.
Sir I am rookie in this , but for my project purpose I am learning it bit by bit.

I will try "--noupx"

**Comment by GaneshJJ** [comment]
Thank You so much Brent ,
Generated EXE successfully and its working fine , I used " Do not use UPX" and Console window "Console based"
