### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by madtatu-development** [brentvollebregt/auto-py-to-exe#210]
Background:

after I couldnt create the EXE after updating to Python 3.10,0, I had decided to go back to 3.9.7
since I am using ssd image base backup, I simply restored an earlier OS image where python wasnt installed at all to ensure there is no garbage left e.g. from an uninstall proces.
I installed python 3.9.7 x64 on windows 10 latest version, just as it was before.
Problem:

for some reason, the EXACT SAME code with the EXACT same json settings file, which was perfectly compiled to exe and executed earlier, now, throws the following error during execution:
ImportError: Module 'pythoncom' isn't in frozen sys.path ['C:\Users\Master\AppData\Local\Temp\_MEI47642\base_library.zip', 'C:\Users\Master\AppData\Local\Temp\_MEI47642\lib-dynload', 'C:\Users\Master\AppData\Local\Temp\_MEI47642']

All required dirs are added.

All modules and submodules are imported.

Cache emptied.

Both python and python/scripts added to os syst path variable

Still not work. what previously worked like a charm.

I am sure the problem is on my side, eventhough it is same evironment, code and process, but there is no miracle, something must had been changed what i overlook otherwise it would not give an error.
May I ask if you could guide me, what he heck could be the problem ?

**Comment by brentvollebregt** [comment]
This may be an issue with mixed architectures for pywin32 and Python as [hinted here](https://stackoverflow.com/a/17950140). I would recommend reinstalling pywin32 through pip and seeing if that helps.
