### ISSUE TITLE
IndexError: tuple index out of range (Python 3.10)

### ISSUE THREAD

**Issue by brentvollebregt** [brentvollebregt/auto-py-to-exe#215]
Recently PyInstaller 4.6 was released which added support for Python 3.10. As of auto-py-to-exe v2.11.0, PyInstaller 4.6 is a requirement.

It has been [noted](https://github.com/brentvollebregt/auto-py-to-exe/issues/205#issuecomment-958462879) that PyInstaller 4.6 does not fully support Python 3.10 due to a bug in CPython. The PyInstaller discussion related to this issue can be found [here](https://github.com/pyinstaller/pyinstaller/issues/6301) and the associated CPython bug can be found [here](https://bugs.python.org/issue45757).

This bug cannot be fixed in auto-py-to-exe or PyInstaller so we must wait for a new Python 3.10.x release with a fix.

**Comment by Barak911** [comment]
**I found a solution to this problem.** 
This is a python 3.10 bug, and after applying the fix everything related to pyinstaller started working properly.

"
so basically you have to go to the folder "Python310\Lib" and edit the file 'dis.py'.
In the 'dis.py' file you have to find this "def _unpack_opargs" and inside the else statement write a new line with this: "extended_arg = 0".

I did something like that:

        else:
            arg = None
            extended_arg = 0 
        yield (i, op, arg)
and everything is working fine now.
"
https://github.com/pyinstaller/pyinstaller/issues/6301#issuecomment-974927257

**Comment by RandMental** [comment]
Above dis.py edit solution from Barak911 solved the  IndexError: tuple index out of range -- python 3.10 #213

**Comment by SupCa** [comment]
> extended_arg = 0

TSYM Worked perfectly!!

**Comment by brentvollebregt** [comment]
Python 3.10.1 fixes this now and I have added a warning to auto-py-to-exe in 2.14.0. Closing as this is no longer an issue regarding Python 3.10.1 is not used.

**Comment by 4ggm** [comment]
pls help

**Comment by bobbob8113** [comment]
yo

**Comment by bobbob8113** [comment]
i can't find so basically you have to go to the folder "Python310\Lib" and edit the file 'dis.py'.
In the 'dis.py' file you have to find this "def _unpack_opargs" and inside the else statement write a new line with this: "extended_arg = 0".

**Comment by brentvollebregt** [comment]
@bobbob8113 I recommend upgrading to Python 3.10.1 or above if you have the option to

**Comment by bobbob8113** [comment]
I have python 3.10.4 and it still give the same errors

**Comment by brentvollebregt** [comment]
@bobbob8113 you may have Python 3.10.4, but are you 100% sure it's being used? Did you previously (or still do) have Python 3.10.0 installed?

**Comment by bobbob8113** [comment]
Ye previsously but i update alrdy and using anaconda

**Comment by brentvollebregt** [comment]
@bobbob8113 are there any warnings at the top of auto-py-to-exe? Maybe something that says "You are using Python 3.10.0. This version of Python has a bug that causes PyInstaller to fail."?

**Comment by lloydyu24** [comment]
Why am I still getting the "You are using Python 3.10.0. This version of Python has a bug that causes PyInstaller to fail.
Please upgrade to Python 3.10.1 or above." message after updating my Python to the latest Python 3.10.4?

**Comment by brentvollebregt** [comment]
@lloydyu24 the line that controls that message [is here](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/auto_py_to_exe/utils.py#L96) - the only way you can get the message is if you are running Python 3.10.0.

Maybe you have installed another installation of Python (3.10.4) but are still running auto-py-to-exe with the previous installation (3.10.0).

**Comment by shinyong1** [comment]
> **이 문제에 대한 해결책을 찾았습니다.** 이는 Python 3.10 버그이며, 수정 사항을 적용한 후 pyinstaller 관련 모든 것이 제대로 작동하기 시작했습니다.
> 
> " 즉, 기본적으로 "Python310\Lib" 폴더로 가서 'dis.py' 파일을 편집해야 합니다. 'dis.py' 파일에서 "def _unpack_opargs"를 찾아 else 문 안에 "extended_arg = 0"이라는 새 줄을 작성해야 합니다.
> 
> 저는 다음과 같은 일을 했습니다.
> 
> ```
>     else:
>         arg = None
>         extended_arg = 0 
>     yield (i, op, arg)
> ```
> 
> 그리고 지금은 모든 것이 잘 작동하고 있습니다. " [pyinstaller/pyinstaller#6301 (주석)](https://github.com/pyinstaller/pyinstaller/issues/6301#issuecomment-974927257)

감사합니다. 에러를 잘 해결 했습니다.  너무 너무 감사합니다.
