### ISSUE TITLE
exe wont open

### ISSUE THREAD

**Issue by polrbare** [brentvollebregt/auto-py-to-exe#217]
sorry if im missing something simple, im new to all this,

while the conversion worked as intended, the output exe did not open correctly, giving me the error "the application has failed to start side-by-side configuration is incorrect..."

![error](https://user-images.githubusercontent.com/93643395/142340511-15156d2d-6357-4434-865a-260aaef6723a.JPG)
 
any help would be great!

**Comment by brentvollebregt** [comment]
Looks like you're seeing this: https://github.com/pyinstaller/pyinstaller/issues/6371.

For the moment, using PyInstaller 4.6 should work, regarding you are not using Python 3.10. This should be fixed in the next PyInstaller release.
