### ISSUE TITLE
change pyinstaller temp directory

### ISSUE THREAD

**Issue by rstudiocode** [brentvollebregt/auto-py-to-exe#218]
Hello, I noticed that when auto-py-to-exe creates an .exe file, it first stores it in a temporary folder before putting it in the output folder. I would like to know how to change the location of this temporary folder. Indeed, my antivirus incorrectly detects the file created in the temporary folder and quarantines it. this error results:
image
![image](https://user-images.githubusercontent.com/63545838/142480399-4c0487ae-1074-4b01-8127-9b30372c60a0.png)

I could very well add an exclusion to the C: \Users\Alexa\AppData\Local\Temp\folder
but it could be dangerous for the computer. So I would like to make sure that the temporary folder is created in C: \ Users \ Alexa \ Downloads \ tempor
To avoid risks: this folder would be only devoted to auto-py-to-exe temp files. I would add an exclusion only for this folder. ?
Thanks in advance for your answer.

**Comment by brentvollebregt** [comment]
This is a pretty fair request and will be nice to get around the antivirus issues I see a lot of people having.

Passing the temporary directory as an argument will be the best option as it's usually created on startup.

**Comment by brentvollebregt** [comment]
@rstudiocode I've just added the argument `--build-directory-override` to develop. Could you checkout develop and see if it works for you? Argument details have been added to the README on the develop branch.

**Comment by brentvollebregt** [comment]
This feature has been released in v2.12.0
