### ISSUE TITLE
Autopytoexe not clickable

### ISSUE THREAD

**Issue by arinzejustin** [brentvollebregt/auto-py-to-exe#221]
Not is clickable..... All button seems to be disabled

**Comment by brentvollebregt** [comment]
Can you please provide a reproduction case? It works for me - sometimes you may need to give it a couple of seconds.

**Comment by arinzejustin** [comment]
It does not work for me in the chrome browser..... So I have to print the URL and open in firefox

**Comment by brentvollebregt** [comment]
Are there any errors in dev tools or the console when using Chrome?

**Comment by brentvollebregt** [comment]
@arinzejustin I've just added a change to the develop branch which includes logging in the browsers dev tools when inisialising the UI. Are you able to checkout develop and see if you can see these messages? You should see:

- `Getting initialisation data`: Will always see this (regarding you are using develop)
- `Received initialisation data`: When the data has been received from the Python backend
- `Application initialised`: When everything should be loaded

These logs will make it into the next release (whenever that is).

**Comment by arinzejustin** [comment]
> Are there any errors in dev tools or the console when using Chrome?

**No**

**Comment by brentvollebregt** [comment]
When using the develop branch, can you see those messages?

**Comment by arinzejustin** [comment]
No...
I discovered that the issues was from my chrome, because after reinstalling the chrome it starts work fine

**Comment by brentvollebregt** [comment]
> No...

Did you use the develop branch?

**Comment by arinzejustin** [comment]
Yes

**Comment by brentvollebregt** [comment]
What commit is your git HEAD pointing to? Also is the language "Chinese Traditional" in the language dropdown?

I'm finding it hard to understand how you cannot see these new messages even though you have `develop` checked out.

**Comment by arinzejustin** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/81859469/144043385-51fd4c61-e9ba-4bb8-9809-87b6157e758e.png)

The language dropdown appears to be empty

**Comment by brentvollebregt** [comment]
Ok, looks like the UI has not been initialised. 

What commit is your git HEAD pointing to? If you execute `git log`, what commit hash is `HEAD` beside?
