### ISSUE TITLE
graphical interface does not show up

### ISSUE THREAD

**Issue by DG119** [brentvollebregt/auto-py-to-exe#224]
Hello guys, the graphical interface won't show up, and the terminal is just stuck there.
![1](https://user-images.githubusercontent.com/93947664/144524053-87504fae-cc82-481b-9b72-2cb3b6a80726.png)

It worked fine previously, I have no idea what happened. I tried to pip uninstall and pip install it, nothing has changed.
There's no error message whatsoever.

Thanks in advance for any helps!

**Comment by DG119** [comment]
Actually, I remembered. I updated my python to Python 3.9.9
Could this be the reason?

**Comment by brentvollebregt** [comment]
> Actually, I remembered. I updated my python to Python 3.9.9
> Could this be the reason?

I don't believe this will be the issue.

If you execute `auto-py-to-exe --no-chrome`, does the UI appear after selecting a browser (if it asks)?

**Comment by DG119** [comment]
> 

Hi, thanks for the reply first of all. And no, nothing appeared, the same thing happened just like my previous screenshot.

**Comment by DG119** [comment]
Yep, it's working fine now after the restart. Sorry for the trouble.
