### ISSUE TITLE
JSON issues

### ISSUE THREAD

**Issue by FU510N-510** [brentvollebregt/auto-py-to-exe#226]
Im attempting to convert a few files and a folder to an exe. Everything works fin except for the JSON file. After I convert the files into an exe and open it It says No such file or directory: 'users.json'. Even though the file was put in the root directory.

**Comment by brentvollebregt** [comment]
Sounds like you might be not referencing the file correctly - have you read the [help post linked in both the tool and the README](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/)?

Have you tried packaging to one directory?
