### ISSUE TITLE
tkiner not found on Windows 10 + python 3.6

### ISSUE THREAD

**Issue by emuhedo** [brentvollebregt/auto-py-to-exe#23]
Installed by pip, after run got just 

Error: tkinter not found
For linux, you can install tkinter by executing: "sudo apt-get install python3-tk"

But since I am on WIndows 10 environment not sure how to proceed. Googling usually returns that this library should be part of vanila python installation.

**Comment by brentvollebregt** [comment]
Actually, I was installing a version of Python today and noticed that in the optional features, there is a checkbox for "td/tk and IDLE" which is checked by default. Was this checked when you installed Python? (if you did the default instillation then there is no worry). This makes sure tkinter is installed when installing Python.

**Comment by brentvollebregt** [comment]
@emuhedo any advances on this?

**Comment by brentvollebregt** [comment]
This issue is being closed because it has been inactive for more than two months.

**Comment by ThatsTheSpirit** [comment]
Same problem on Win8.1 Python 3.7

**Comment by brentvollebregt** [comment]
@ThatsTheSpirit is tkinter available in your distribution? Typically it is installed by default unless you uncheck a box when installing Python.

**Comment by ThatsTheSpirit** [comment]
@brentvollebregt Problem solved by reinstalling python

**Comment by flo-abgrund** [comment]
Hi there everyone.
I still have this problem on Ubuntu and I also reinstalled python and tkinter. Any suggestions on that?

**Comment by brentvollebregt** [comment]
@flo-abgrund are you sure tkinter is installed? If you open up a Python 3 shell and import it, does it throw an error?

**Comment by flo-abgrund** [comment]
@brentvollebregt thanks for your quick reply! yes, it is installed and doesn't throw an error. I am not sure what could cause this.

**Comment by brentvollebregt** [comment]
Can you confirm that the installation of Python you just tested with is the same installation of Python that auto-py-to-exe is using?

You can find the location of auto-py-to-exe using `whereis auto-py-to-exe` I believe. Using a similar technique to find where your Python installation is and then check that auto-py-to-exe is in the correct place relative to it.

**Comment by flo-abgrund** [comment]
auto-py-to-exe is in `/home/USER/.local/bin/` whereas Python lies in `/usr/bin/`

**Comment by brentvollebregt** [comment]
Ah yes, I didn't realise it would be placed in a different location compared to Windows.

Are you able to verify that the installation of Python you used to test tkinter was installed is the same installation of Python that is running auto-py-to-exe?

**Comment by flo-abgrund** [comment]
Ah yeah, it works now. I somehow had to install it via `pip3.8 install auto-py-to-exe`. don't know why, though, since python3.8 is my default python installation.

anyhoo, thanks very much for your efforts on that!
