### ISSUE TITLE
Hidden Import Error

### ISSUE THREAD

**Issue by MarketingPip** [brentvollebregt/auto-py-to-exe#234]
I am assuming this is my own user based issue but can't find these hidden imports.

Error example(s):
888560 INFO: Analyzing hidden import 'psycopg2'

888810 INFO: Analyzing hidden import 'pysqlite'

888820 ERROR: Hidden import 'pysqlite' not found

888835 INFO: Analyzing hidden import 'MySQLdb'

888842 ERROR: Hidden import 'MySQLdb' not found

895794 WARNING: Hidden import "pkg_resources.py2_warn" not found!

896465 WARNING: Hidden import "pkg_resources.markers" not found!

In my list is - 
sqlalchemy
psycopg2
pysqlite
MySQLdb
pkg_resources

Have the modules needed installed. Advice would be appreciated in advanced!

**Comment by brentvollebregt** [comment]
This would definitely be a question for pyinstaller - the command at the bottom of the UI shows what is being executed.

First thing that I would check though is that you're running auto-py-to-exe in the same environment as the environment that has these modules installed. I find it's quite common for people to install modules in one Python installation and then run auto-py-to-exe from a virtual environment thus no longer having access to the original packages.

**Comment by MarketingPip** [comment]
Hey @brentvollebregt ,

Feel dumb as same problem almost I was having here. [Issue #225 ](https://github.com/brentvollebregt/auto-py-to-exe/issues/225)

I tried again - after just literally moving the folder of my script - up a sub-folder and re-opening Auto-Py-To-Exe.

Said the hidden modules didn't import - which before my EXE wouldn't start all all requiring the MySQL DB being served. (with the same error message)

But now it built properly even with the same error messages showing. So I am thinking possibly a PyInstaller problem. 

Thanks for quick reply as usual. And hope you are having an awesome weekend!
