### ISSUE TITLE
Ready made exe available?

### ISSUE THREAD

**Issue by JB-DX** [brentvollebregt/auto-py-to-exe#239]
With Python 3.8.2 I get errors:

```
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size change
d, may indicate binary incompatibility. Expected 144 from C header, got 152 from
 PyObject
Error: tkinter not found
```
I did install tkinter it, but no improvements.

I'm pretty annoyed fighting with the module mess of python.

Isn't there  an auto-py-exe.exe available, that I just could download and use?
I don't program with python, only need to convert a developer tool into an exe to have a one-file solution to pass on to others.

**Comment by brentvollebregt** [comment]
Where do you get these errors? What did you do to get them?

No, there is not an executable version of auto-py-to-exe - if there was, it would be much harder to package third-party packages.

**Comment by JB-DX** [comment]
I use python distributed by the ESP32 developer package, installed in P:\ESP32-Compiler-Tools
I invoke: python -m auto_py_to_exe (see below)  
auto_py_to_exe is the folder containing your stuff.

```
P:\ESP32-Compiler-Tools\tools\idf-python\3.8.7>python -m auto_py_to_exe
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size change
d, may indicate binary incompatibility. Expected 144 from C header, got 152 from
 PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size change
d, may indicate binary incompatibility. Expected 144 from C header, got 152 from
 PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size change
d, may indicate binary incompatibility. Expected 144 from C header, got 152 from
 PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size change
d, may indicate binary incompatibility. Expected 144 from C header, got 152 from
 PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size change
d, may indicate binary incompatibility. Expected 144 from C header, got 152 from
 PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size change
d, may indicate binary incompatibility. Expected 144 from C header, got 152 from
 PyObject
Error: tkinter not found
For linux, you can install tkinter by executing: "sudo apt-get install python3-t
k"

```

**Comment by brentvollebregt** [comment]
Are you sure you have tkinter installed? Based on this error, the application was not able to import tkinter.

See the [source throwing the error here](https://github.com/brentvollebregt/auto-py-to-exe/blob/e9ab4776398154e8d5f2a90e1b975704b441ee73/auto_py_to_exe/dialogs.py#L16).

**Comment by JB-DX** [comment]
I had the same thoughts, and thus installed it a second time, but that told that it was already installed. I'm pretty clueless what's going on.

**Comment by brentvollebregt** [comment]
If you try to import tkinter yourself in a separate script and run the script - does it work? Make sure you are using the same installation of Python as the one that you are executing auto-py-to-exe with.
