### ISSUE TITLE
Unable to run "run.py" nor auto-py-to-exe.

### ISSUE THREAD

**Issue by Syed-Hussaini2** [brentvollebregt/auto-py-to-exe#24]
Error:
Error: PyInstaller not found
Please install PyInstaller using: "python -m pip install PyInstaller"

-------------------------------------------
C:\WINDOWS\system32>pip install PyInstaller
Requirement already satisfied: PyInstaller in c:\python27\lib\site-packages (3.3.1)
Requirement already satisfied: macholib>=1.8 in c:\python27\lib\site-packages (from PyInstaller) (1.11)
Requirement already satisfied: pefile>=2017.8.1 in c:\python27\lib\site-packages (from PyInstaller) (2018.8.8)
Requirement already satisfied: future in c:\python27\lib\site-packages (from PyInstaller) (0.16.0)
Requirement already satisfied: setuptools in c:\python27\lib\site-packages (from PyInstaller) (39.0.1)
Requirement already satisfied: dis3 in c:\python27\lib\site-packages (from PyInstaller) (0.1.2)
Requirement already satisfied: altgraph>=0.15 in c:\python27\lib\site-packages (from macholib>=1.8->PyInstaller) (0.16.1)
------------------------------

PyInstaller has been installed already, however I am receiving this error.

**Comment by brentvollebregt** [comment]
Do you have more than one version of Python installed?

**Comment by brentvollebregt** [comment]
I put these errors in to allow people to understand that PyInstaller was not installed. Are you 100% sure that the Python you are running this script with has Pyinstaller installed?

**Comment by brentvollebregt** [comment]
How are you running this project? Through PyPI or downloading/cloning from the repo?

**Comment by mshemadarshini** [comment]
does this works with pyqt4/ pyqt5 if i want to convert them to executable ?

**Comment by brentvollebregt** [comment]
Yes, PyInstaller can package PyQt applications

**Comment by mshemadarshini** [comment]
This doesn't work as it say can't execute the file.

**Comment by brentvollebregt** [comment]
Are you looking at the actual output that this is producing? If you executed your executable with something that preserves output, you will most likely find errors that you are missing.

You could also build the executable in debugging mode I recommend following [my small debugging tutorial](https://nitratine.net/blog/post/common-issues-when-using-auto-py-to-exe/#debugging) to get an idea of how to do this.

Also how does this relate to this issue (#24)? This issue covers not being able to run auto-py-to-exe which you clearly are able to do.

**Comment by mshemadarshini** [comment]
whats the point of converting into executable when you cant actually execute them? The file failed to execute and I finding ways to convert the file. It is working well when i run them using shell or pycharm, but I'm facing difficulty to convert them as executable as I wanted to deploy them into separate machine.

**Comment by brentvollebregt** [comment]
Did you bother to read that section I linked? Did you debug the application? I have helped a lot of people solve issues just like this and 95% of them are due to the person incorrectly configuring the build.

**Comment by brentvollebregt** [comment]
Closing due to now being off topic (if was was at the beginning)
