### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by matpsycho** [brentvollebregt/auto-py-to-exe#240]
Hi Brent,
I have run auto-py-to-exe as admin from cmd, and in the end an error occured: 
PermissionError: [Errno 13] Permission denied: 'Microsoft\\Protect\\Recovery\\Recovery.dat'
Then "Project output will not be moved to output folder Completed"
The program has run successfully, until this error occured today.
Please help me.

**Comment by brentvollebregt** [comment]
Can you provide the whole traceback and exception please?

**Comment by matpsycho** [comment]
> Can you provide the whole traceback and exception please?

Thanks for your attention. I have solved this problem by reinstall the module and I've only saved a screenshot. Hope it could help.
![图片](https://user-images.githubusercontent.com/20368949/153356486-8fc2afe0-8f5d-4118-b28c-0d92c3c93eeb.png)

**Comment by brentvollebregt** [comment]
That looks like a bit of an odd file to be accessed - I imagine this file has permissions on it that you cannot get around easily.

Being unable to reproduce this will probably mean that this will be closed.

**Comment by matpsycho** [comment]
Yes, this file is only assessed when run as admin from cmd, if not the file's directory c:/..../AppData/Local/....

**Comment by brentvollebregt** [comment]
Without getting a full stack trace, there isn't much I can do sorry. If we get more info, I'm happy to re-open.
