### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by AmirHosseinCV** [brentvollebregt/auto-py-to-exe#245]
### Environment:
Python 3.10 (Installed from python.org)  - Virtual environment
### Error message:
```
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "spotdl\providers\ytm_provider.py", line 18, in <module>
  File "ytmusicapi\ytmusic.py", line 102, in __init__
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\AmirCV\\AppData\\Local\\Temp\\_MEI213882\\ytmusicapi\\locales'
[26528] Failed to execute script 'main' due to unhandled exception!
```

### Imported packages:
[SpotDL](https://github.com/spotDL/spotify-downloader)

### My code:
```python
from spotdl.console import console_entry_point
url = input("Enter the url:")
sys.argv = [sys.argv[0], url]
console_entry_point()
```

**Comment by brentvollebregt** [comment]
[ytmusicapi has a locales folder](https://github.com/sigma67/ytmusicapi/tree/master/ytmusicapi/locales) that is not automatically included by PyInstaller - you need to manually include it

**Comment by brentvollebregt** [comment]
This looks like a PyInstaller issue - do you still get these errors when using the generated command at the bottom of the UI?

**Comment by AmirHosseinCV** [comment]
@brentvollebregt Yes. So I'll close my issue. Thank you for your time and the great project.
