### ISSUE TITLE
missing Library\bin folder in output directory 

### ISSUE THREAD

**Issue by LaserGobble** [brentvollebregt/auto-py-to-exe#246]
Hi!

I used auto-py-to-exe on a .py program that - besides other things - streams and then displays webcam images. 

The command I executed was 
pyinstaller --noconfirm --onedir --windowed --clean "path-to-where-my-program-is\\main-program.py"

Everything worked fine, but once I tried to start my .exe, instead of my GUI the following error message showed up:

![image](https://user-images.githubusercontent.com/100295589/155341139-5157c1d8-49df-4eb9-a339-6762f9912883.png)

Both folders "Library" and "bin" did not exist at that point. I could solve the issue by manually adding the required folders (no content, just empty folders). Generating the .exe on another device (both Windows 10) using the same command led to errors as well.

My .exe does work now, but I wonder what was going on here. Does anybody know the source of this error? Thanks in advance.

**Comment by LaserGobble** [comment]
Oh and I'm using python version 3.9.7 and auto-py-to-exe version 2.13.0 :)

**Comment by brentvollebregt** [comment]
Check out "[FileNotFoundError: [Errno 2] No such file or directory](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#filenotfounderror-errno-2-no-such-file-or-directory)" in the help post I have written - you will need to add the folder using the "Additional Files" section in the UI.

**Comment by LaserGobble** [comment]
Thanks, I'll make sure to include that the next time.
