### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by PaoloBezzina** [brentvollebregt/auto-py-to-exe#249]
I am trying to build an exe of a program which outputs a pdf using the borb library. Whenever i run the program normally using python, everything works perfectly. However when I compile the exe I get an 'Assertion Error' for some library imports. (find attached image)

I tried getting a local version of this library and including it when building the app, and still no success.

![image](https://user-images.githubusercontent.com/72805355/156379495-04379128-5872-4f25-93e4-bfa9e016172b.png)

**Comment by brentvollebregt** [comment]
Without any details of that error, I cannot help.
