### ISSUE TITLE
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### ISSUE THREAD

**Issue by xman213** [brentvollebregt/auto-py-to-exe#250]
I am making a app the is composed of 12 .py files. I convert it to a exe and the main.py file runs just fine. when the program calls for a driffrent py file I get this "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases."

How would I fix this?

**Comment by brentvollebregt** [comment]
Are you trying to call another script using `python`, as in the binary?

The python binary may not exist on the host - you need to import scripts and then execute functions within them.

**Comment by xman213** [comment]
I had something like this to call the file,

import myfile
subprocess.call(["python", "myfile.py", shell = False])

not sure if thats exactly what I had because im at school but I am 99% sure
thats what I did.

**Comment by brentvollebregt** [comment]
You cannot make those kind of calls when packaging a script like this. You need to import the scripts and call functions from within them.

**Comment by xman213** [comment]
ok

**Comment by perfectans** [comment]
[[Solved] Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases](https://perfectans.net/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store-or-disable-this-shortcut-from-settings-manage-app-execution-aliases/)

**Comment by brentvollebregt** [comment]
@perfectans I ask that you remove your most recent comment here as it is not related to this specific issue. I would rather people see relevant solutions sorry.
