### ISSUE TITLE
Output Directory not in exportet Configuration

### ISSUE THREAD

**Issue by savejeff** [brentvollebregt/auto-py-to-exe#254]
Hi!, 
absolutly love the tool. 

one thing, i frequently stumple over: the Output Directory is not sorted in the exporter Config JSON File. 
I always have to change it at every start up. if I forget it, it will export the compile application to the python installation directory. 

Would it be possible to include this path in the export. then I could just start up the tool, import the config and compile it straight away. 

thx!

**Comment by brentvollebregt** [comment]
Check out #197 - I added this a bit ago but you need to add it manually
