### ISSUE TITLE
CSS Not loading

### ISSUE THREAD

**Issue by Irtiza90** [brentvollebregt/auto-py-to-exe#258]
The CSS doesn't seem to be loading for some reason, I have an active internet connection the Google Chrome Icon isn't appearing as well, But when i open chrome normally it works fine for some whatever reason

![image](https://user-images.githubusercontent.com/61447963/160816678-de79045d-8b62-4ca3-893e-311e6a4ff419.png)

**Comment by Irtiza90** [comment]
And now it gives this after i reload
![image](https://user-images.githubusercontent.com/61447963/160818322-ffc4d0ce-a56a-4227-864b-062470cb8f40.png)

**Comment by brentvollebregt** [comment]
If you look at the console where auto-py-to-exe is running from, is it still running? Are there any errors?

**Comment by Irtiza90** [comment]
After reloading the app it works @brentvollebregt
