### ISSUE TITLE
Multiple .py files?

### ISSUE THREAD

**Issue by robertmlinden** [brentvollebregt/auto-py-to-exe#26]
Amazing application! Well done.

Does it support code distributed over multiple files?

**Comment by brentvollebregt** [comment]
Yes, as long as your project imports the other file, they will be added. This is exactly like importing os or time, your scripts (modules) are just located in a different place which can be found by PyInstaller.

**Comment by brentvollebregt** [comment]
Since there is no issue there, I am closing this issue.
