### ISSUE TITLE
multiple windows when using "joblib" package for parallel computing

### ISSUE THREAD

**Issue by 22Watt** [brentvollebregt/auto-py-to-exe#262]
Hi all,
     I made a project which uses "joblib" package for parallel computing. When I run the exe, there are many windows when performing parallel computing

**Comment by brentvollebregt** [comment]
If you run your main Python script (before it's packaged) by double-clicking on it, does it do the same?

**Comment by 22Watt** [comment]
> If you run your main Python script (before it's packaged) by double-clicking on it, does it do the same?

When running in Pycharm before packaged, it is normal

**Comment by brentvollebregt** [comment]
@22Watt do you get the same result when double-clicking on the script? Wanting to see how your script runs without a pre-existing stdout.
