### ISSUE TITLE
静态文件始终打包失败

### ISSUE THREAD

**Issue by yanghuizhi** [brentvollebregt/auto-py-to-exe#266]
When I add static file (*.png), I always fail to pack, even when I use PyInstaller, I still can't find how to fix this problem  
i need help

![image](https://user-images.githubusercontent.com/29268369/166129792-de5646ba-00e2-423d-9809-a0262a935c12.png)
![image](https://user-images.githubusercontent.com/29268369/166129807-015a81be-8cc0-4780-a5b7-d6b2ea6f8133.png)

**Comment by brentvollebregt** [comment]
If you insert one of your file paths into the script below, what's the output?

```py
path = r"D:/PythonFiles/Python/GUI_..."  # Insert your path here

import os

if os.path.isfile(path):
    print("path exists")
else:
    print("path doesn't exist")
```
