### ISSUE TITLE
Prompt opens for a second then closes

### ISSUE THREAD

**Issue by Franziac** [brentvollebregt/auto-py-to-exe#28]
When I try to run run.py it just opens the prompt for a second and then closes. I don't see any errors.

**Comment by brentvollebregt** [comment]
Most of the time this is not an issue with auto-py-to-exe or PyInstaller but incorrect configuration (which is ok). This means you will then need to enable debugging for the project to investigate the issue and hold on to any output.

To enable debugging, go into the "Advanced" section and under the title "How to generate" put 'all' in the box beside --debug. This will print out messages to the console to help you debug.

When debugging, make sure you selected the "Console Based" button and using "One Directory" will help remove basic problems; you can switch back to "One File" when there are no more bugs and then fix the ones associated with "One File".

After re-packaging your project, open up cmd, use the cd command to change directories to where the exe is located and then execute ./my_project.exe (substitute the names). This will run the executable and any errors you were missing before will be output to the console.

**Comment by Franziac** [comment]
I think you didn't quite understand. When I run the auto-py-to-exe.exe or
whatever the name was your program won't open on my computer just some
empty command prompt. But I got my program converted to exe with some other
program so it doesn't really matter for me. I just wanted to inform you
with this issue in case others are having it too.

Brent Vollebregt <notifications@github.com> kirjoitti su 4. marraskuuta
2018 klo 1.04:

**Comment by brentvollebregt** [comment]
Oh right, you mean that actuall script that runs auto-py-to-exe. If you execute it though cmd, this will preserve the output which may contain errors. These would be helpful to identify what is going on.

**Comment by Franziac** [comment]
I'm pretty sure I didn't get any errors...

Brent Vollebregt <notifications@github.com> kirjoitti su 11. marraskuuta
2018 klo 1.55:

**Comment by brentvollebregt** [comment]
With no information on properly reproducing this and no stack trace or individual error given, then I am going to close this issue as nothing can come out of this.

I believe that if you executed this script using something that will preserve output (like the terminal/cmd) you will find that an error is appearing. This script keeps alive from a blocking statement, thus will only stop once the blocking conditions are no longer met (managed by Eel) or an error has occurred; I believe the latter is occurring.

If you do decide to preserve the error, you can comment it and I will look at it. But as of now, this issue provides no information so I am closing it.
