### ISSUE TITLE
I have tried my best through many ways to solve this issue, Plz Help...........PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_usb required by hook for module D:\Python IDE\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-usb.py. Please check whether module __PyInstaller_hooks_0_usb actually exists and whether the hook is compatible with your version of D:\Python IDE\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-usb.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.  Project output will not be moved to output folder Complete. 

### ISSUE THREAD

**Issue by hamza0491** [brentvollebregt/auto-py-to-exe#280]
**Quick Checks For You**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+) looking for an issue similar to mine
- [x] I have made sure my applicaiton/script runs before trying to package

**Describe the bug**

**To Reproduce**

> If you have example code, please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

**Expected behavior**

**Screenshots**

**Your Environment:**
- Python version (`python --version`):
- auto-py-to-exe version (`pip show auto-py-to-exe`):
- PyInstaller version (`pip show pyinstaller`):
- Eel version (`pip show eel`): 

**Additional context**

**Comment by hamza0491** [comment]
I have installed manual different library files to resolve the usb.core hook error but it does not work for me.. thanks

**Comment by brentvollebregt** [comment]
Can you please fill out the template - those fields are all there for a reason. Can you also make the title more concise please.
