### ISSUE TITLE
Can't add a folder to my program folder

### ISSUE THREAD

**Issue by claudito1991** [brentvollebregt/auto-py-to-exe#281]
Hi there i'm doing a simple desktop application with PysimpleGUI and trying to make an executable with auto-py-to-exe.

I believe my issue it¡s very simple. I need a folder in the folder of my executable. I've tried to create that folder select the source and the destination but i don't see it created in the output folder. I even added the "." before the folder name to place it on root folder but that didn't work either. How should i do this?
![folder](https://user-images.githubusercontent.com/30451301/172745879-6e43df18-a0b8-42bc-bc9f-76fb0575ed8a.png)

**Comment by brentvollebregt** [comment]
You can just use `tablas_salida` - this will create the folder in the output.
Have you tried using one-directory mode? It will help you identify what is going on.
