### ISSUE TITLE
Settings are not being saved

### ISSUE THREAD

**Issue by MysteriousShadow** [brentvollebregt/auto-py-to-exe#283]
This is more of a feature request than a bug, but if the settings such as the icon dir, onefile option, etc can be saved it would save a lot of time for me. 

For example, I have a specific logo I want to use for my exes, and everytime I compile an exe, I have to enter the path of that logo.

**Comment by brentvollebregt** [comment]
I just tested this using auto-py-to-exe v2.20.1 and the configuration I exported and then imported did restore the icon file, onefile option and console window (plus more).

Which options are not working for you?

**Comment by MysteriousShadow** [comment]
Yes that works. I guess what I'm trying to say is that there is no autosave feature.

**Comment by brentvollebregt** [comment]
I'm a bit confused, looking back at the description of this issue:

> ... but if the settings such as the icon dir, onefile option, etc can be saved it would save a lot of time for me.

If you export the settings to JSON, these fields will be included.

> For example, I have a specific logo I want to use for my exes, and everytime I compile an exe, I have to enter the path of that logo.

Icons / additional files are contained in the exported settings JSON file.

The export feature does not auto-save as it is an export - I wouldn't want people's specific exports overwritten when they are playing around with the tool. Are you expecting the same settings to re-appear in the UI after closing and re-opening?

**Comment by MysteriousShadow** [comment]
Yes

**Comment by brentvollebregt** [comment]
I'm not sure that is a great feature - if you want to save your state and bring it back use the export and import feature
