### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\xrkzl\\AppData\\Local\\pyinstaller\\bincache00_py310_64bit\\python310.dll'

### ISSUE THREAD

**Issue by CosmicLOL** [brentvollebregt/auto-py-to-exe#284]
Cannot find ('python310.dll', 'C:\Users\xrkzl\AppData\Local\pyinstaller\bincache00_py310_64bit\python310.dll', 1, 'b')
78528 ERROR: An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "C:\Users\xrkzl\AppData\Local\Temp\tmp82p7j8wl\main.spec", line 24, in <module>
    exe = EXE(
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\api.py", line 506, in __init__
    self.pkg = PKG(
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\api.py", line 206, in __init__
    self.__postinit__()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\api.py", line 297, in assemble
    CArchiveWriter(self.name, srctoc + mytoc, pylib_name=pylib_name)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 313, in __init__
    super().__init__(archive_path, logical_toc)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 51, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 75, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 375, in add
    self._write_file(source, dest, type, compress=compress)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 397, in _write_file
    length = os.stat(source).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\xrkzl\\AppData\\Local\\pyinstaller\\bincache00_py310_64bit\\python310.dll'

Does anyone know how to fix it?

**Comment by brentvollebregt** [comment]
Are you able to fill out the template you cleared before simply pasting your error please? I could look into this if I can get some reproduction steps and other info (all in the template)

**Comment by CosmicLOL** [comment]
Current Command:
pyinstaller --noconfirm --onefile --console --icon "C:/Users/xrkzl/OneDrive/Desktop/Tool Source/pfppfp.ico"

**Comment by CosmicLOL** [comment]
Output in the "Auto Py To Exe" Application:
Running auto-py-to-exe v2.20.1
Building directory: C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik
Provided command: pyinstaller --noconfirm --onefile --console --icon "C:/Users/xrkzl/OneDrive/Desktop/Tool Source/pfppfp.ico"  "C:/Users/xrkzl/OneDrive/Desktop/Tool Source/main.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console --icon C:/Users/xrkzl/OneDrive/Desktop/Tool Source/pfppfp.ico C:/Users/xrkzl/OneDrive/Desktop/Tool Source/main.py --distpath C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik\application --workpath C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik\build --specpath C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik

43654 INFO: PyInstaller: 5.1
43657 INFO: Python: 3.10.1
43679 INFO: Platform: Windows-10-10.0.19044-SP0
43684 INFO: wrote C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik\main.spec
43693 INFO: UPX is not available.
43718 INFO: Extending PYTHONPATH with paths
['C:\\Users\\xrkzl\\OneDrive\\Desktop\\Tool Source']
44512 INFO: checking Analysis
44516 INFO: Building Analysis because Analysis-00.toc is non existent
44523 INFO: Initializing module dependency graph...
44540 INFO: Caching module graph hooks...
44575 INFO: Analyzing base_library.zip ...
50779 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
50786 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\Python310\\lib'
52494 INFO: Caching module dependency graph...
52747 INFO: running Analysis Analysis-00.toc
52785 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Program Files\Python310\python.exe
53086 INFO: Analyzing C:\Users\xrkzl\OneDrive\Desktop\Tool Source\main.py
53441 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
59904 INFO: Processing pre-find module path hook site from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
59908 INFO: site: retargeting to fake-dir 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\fake-modules'
66201 INFO: Processing module hooks...
66219 INFO: Loading module hook 'hook-anyio.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
67081 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
67103 INFO: Loading module hook 'hook-Crypto.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
67776 INFO: Loading module hook 'hook-eel.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
67936 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
67952 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
67960 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
67964 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
67972 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
68099 INFO: Loading module hook 'hook-gevent.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
68941 INFO: Determining a mapping of distributions to packages...
77260 WARNING: Unable to find package for requirement zope.interface from package gevent.
77265 WARNING: Unable to find package for requirement zope.event from package gevent.
77270 INFO: Packages required by gevent:
['setuptools', 'cffi', 'greenlet']
78813 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
78821 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
78992 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
79002 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
79018 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
80194 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
80628 WARNING: Hidden import "pkg_resources.py2_warn" not found!
80633 WARNING: Hidden import "pkg_resources.markers" not found!
80649 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
80664 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
82663 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
82674 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
83157 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
83162 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
83168 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
83188 INFO: Loading module hook 'hook-zope.interface.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
83210 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
83429 INFO: checking Tree
83450 INFO: Building Tree because Tree-00.toc is non existent
83455 INFO: Building Tree Tree-00.toc
83565 INFO: checking Tree
83572 INFO: Building Tree because Tree-01.toc is non existent
83578 INFO: Building Tree Tree-01.toc
83717 INFO: checking Tree
83730 INFO: Building Tree because Tree-02.toc is non existent
83746 INFO: Building Tree Tree-02.toc
83770 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
83849 INFO: Looking for ctypes DLLs
83985 INFO: Analyzing run-time hooks ...
83998 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
84006 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
84024 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
84041 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
84051 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
84091 INFO: Looking for dynamic libraries
86401 INFO: Looking for eggs
86422 INFO: Using Python library C:\Program Files\Python310\python310.dll
86437 INFO: Found binding redirects: 
[]
86455 INFO: Warnings written to C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik\build\main\warn-main.txt
86659 INFO: Graph cross-reference written to C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik\build\main\xref-main.html
86711 INFO: checking PYZ
86732 INFO: Building PYZ because PYZ-00.toc is non existent
86748 INFO: Building PYZ (ZlibArchive) C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik\build\main\PYZ-00.pyz
88471 INFO: Building PYZ (ZlibArchive) C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik\build\main\PYZ-00.pyz completed successfully.
88511 INFO: checking PKG
88516 INFO: Building PKG because PKG-00.toc is non existent
88522 INFO: Building PKG (CArchive) main.pkg
An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "C:\Users\xrkzl\AppData\Local\Temp\tmpwuell6ik\main.spec", line 24, in <module>
    exe = EXE(
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\api.py", line 506, in __init__
    self.pkg = PKG(
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\api.py", line 206, in __init__
    self.__postinit__()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\api.py", line 297, in assemble
    CArchiveWriter(self.name, srctoc + mytoc, pylib_name=pylib_name)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 313, in __init__
    super().__init__(archive_path, logical_toc)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 51, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 75, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 375, in add
    self._write_file(source, dest, type, compress=compress)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\archive\writers.py", line 397, in _write_file
    length = os.stat(source).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\xrkzl\\AppData\\Local\\pyinstaller\\bincache00_py310_64bit\\python310.dll'

Project output will not be moved to output folder
Complete.****

**Comment by brentvollebregt** [comment]
@CosmicLOL these are not reproduction steps. I can help if you fill out the template you cleared.

**Comment by CosmicLOL** [comment]
@brentvollebregt Im now having a different issue when trying to convert
OSError: [Errno 22] Invalid argument

**Comment by CosmicLOL** [comment]
Running auto-py-to-exe v2.20.1
Building directory: C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h
Provided command: pyinstaller --noconfirm --onefile --console --icon "C:/Users/xrkzl/OneDrive/Desktop/Tool Source/pfp.ico"  "C:/Users/xrkzl/OneDrive/Desktop/Tool Source/main.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console --icon C:/Users/xrkzl/OneDrive/Desktop/Tool Source/pfp.ico C:/Users/xrkzl/OneDrive/Desktop/Tool Source/main.py --distpath C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\application --workpath C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\build --specpath C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h

160974 INFO: PyInstaller: 5.1
160987 INFO: Python: 3.10.1
161002 INFO: Platform: Windows-10-10.0.19043-SP0
161017 INFO: wrote C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\main.spec
161033 INFO: UPX is not available.
161049 INFO: Extending PYTHONPATH with paths
['C:\\Users\\xrkzl\\OneDrive\\Desktop\\Tool Source']
161336 INFO: checking Analysis
161339 INFO: Building Analysis because Analysis-01.toc is non existent
161355 INFO: Reusing cached module dependency graph...
161390 INFO: Caching module graph hooks...
161470 INFO: running Analysis Analysis-01.toc
161472 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Program Files\Python310\python.exe
161518 INFO: Analyzing C:\Users\xrkzl\OneDrive\Desktop\Tool Source\main.py
161664 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
163584 INFO: Processing pre-find module path hook site from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
163591 INFO: site: retargeting to fake-dir 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\fake-modules'
165802 INFO: Processing module hooks...
165803 INFO: Loading module hook 'hook-anyio.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
166172 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
166181 INFO: Loading module hook 'hook-Crypto.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
166459 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
166461 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
166480 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
166482 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
166496 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
166548 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
166555 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
166619 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
166623 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
166635 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
167234 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
167278 WARNING: Hidden import "pkg_resources.py2_warn" not found!
167289 WARNING: Hidden import "pkg_resources.markers" not found!
167305 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
167322 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
168141 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
168160 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
168174 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
168236 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
168347 INFO: checking Tree
168349 INFO: Building Tree because Tree-03.toc is non existent
168351 INFO: Building Tree Tree-03.toc
168396 INFO: checking Tree
168409 INFO: Building Tree because Tree-04.toc is non existent
168425 INFO: Building Tree Tree-04.toc
168484 INFO: checking Tree
168502 INFO: Building Tree because Tree-05.toc is non existent
168504 INFO: Building Tree Tree-05.toc
168522 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks'...
168556 INFO: Looking for ctypes DLLs
168591 INFO: Analyzing run-time hooks ...
168597 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
168610 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
168626 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
168630 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
168640 INFO: Including run-time hook 'C:\\Users\\xrkzl\\AppData\\Roaming\\Python\\Python310\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
168664 INFO: Looking for dynamic libraries
169642 INFO: Looking for eggs
169647 INFO: Using Python library C:\Program Files\Python310\python310.dll
169649 INFO: Found binding redirects: 
[]
169657 INFO: Warnings written to C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\build\main\warn-main.txt
169734 INFO: Graph cross-reference written to C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\build\main\xref-main.html
169753 INFO: checking PYZ
169771 INFO: Building PYZ because PYZ-01.toc is non existent
169786 INFO: Building PYZ (ZlibArchive) C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\build\main\PYZ-01.pyz
170529 INFO: Building PYZ (ZlibArchive) C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\build\main\PYZ-01.pyz completed successfully.
170551 INFO: checking PKG
170569 INFO: Building PKG because PKG-01.toc is non existent
170585 INFO: Building PKG (CArchive) main.pkg
171932 INFO: Building PKG (CArchive) main.pkg completed successfully.
171939 INFO: Bootloader C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
171953 INFO: checking EXE
171969 INFO: Building EXE because EXE-01.toc is non existent
171985 INFO: Building EXE from EXE-01.toc
171987 INFO: Copying bootloader EXE to C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\application\main.exe.notanexecutable
172045 INFO: Copying icon to EXE
172063 INFO: Copying icons from ['C:\\Users\\xrkzl\\OneDrive\\Desktop\\Tool Source\\pfp.ico']
An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\xrkzl\OneDrive\Desktop\auto-py-to-exe-master\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "C:\Users\xrkzl\AppData\Local\Temp\tmplt35uf8h\main.spec", line 24, in <module>
    exe = EXE(
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\api.py", line 524, in __init__
    self.__postinit__()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\building\api.py", line 629, in assemble
    icon.CopyIcons(build_name, self.icon)
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\utils\win32\icon.py", line 213, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\utils\win32\icon.py", line 148, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "C:\Users\xrkzl\AppData\Roaming\Python\Python310\site-packages\PyInstaller\utils\win32\icon.py", line 115, in __init__
    file.seek(e.dwImageOffset, 0)
OSError: [Errno 22] Invalid argument

Project output will not be moved to output folder
Complete.

**Comment by brentvollebregt** [comment]
> Are you able to fill out the template you cleared before simply pasting your error please? I could look into this if I can get some reproduction steps and other info (all in the template)

> CosmicLOL these are not reproduction steps. I can help if you fill out the template you cleared.
