### ISSUE TITLE
Set auto-py-to-exe language via command line args or config file

### ISSUE THREAD

**Issue by Mrgaton** [brentvollebregt/auto-py-to-exe#286]
Hello, I would like to be able to run the auto py to exe directly from the language that I would like, but I can't find a way to do it. It would be nice if it could be started with x language by arguments or by the configuration file, thanks

**Comment by brentvollebregt** [comment]
That sounds like a good idea - a command line argument would be the best idea in my opinion

**Comment by brentvollebregt** [comment]
This feature has being released in 2.21.0

**Comment by Mrgaton** [comment]
Thanks
