### ISSUE TITLE
Importing config file duplicates additional files

### ISSUE THREAD

**Issue by TheGeeKing** [brentvollebregt/auto-py-to-exe#290]
**Quick Checks For You**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+) looking for an issue similar to mine
- [x] I have made sure my applicaiton/script runs before trying to package

**Describe the bug**
Importing a configuration file doesn't reset the additional files fields and add/duplicate files.

**To Reproduce**
1. Go to `Settings`
2. Import a configuration file with additional file in it
3. If you had previous files in the additional files section their will still be there
4. If you import once again the config file, additional files will be duplicated

**Expected behavior**
The additional files fields should be cleared as stated when importing the config file: `Override current configuration? All previously inserted values will be erased.`

**Screenshots**
State 0:
![image](https://user-images.githubusercontent.com/58857539/180999632-c1cd49f6-c4b4-4771-8c05-c1994390dd12.png)

After imported a config file:
![image](https://user-images.githubusercontent.com/58857539/180999741-4d457405-f617-4b40-86bc-c46c27493fe3.png)

If you import once again a config file:
![image](https://user-images.githubusercontent.com/58857539/180999878-473a62df-3c51-4595-b0d6-6a3461b504ec.png)

**Your Environment:**
- Python version (`python --version`): 3.10.4
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.21.0
- PyInstaller version (`pip show pyinstaller`): 5.1
- Eel version (`pip show eel`): 0.14.0

**Comment by brentvollebregt** [comment]
Ah yep, I see the issue here. There are also many other places like "Advanced -> What to bundle, where to search" that will have a similar issue.

I feel like the best method would be to re-initialise the UI to clear everything before applying the configuration.

**Comment by brentvollebregt** [comment]
@TheGeeKing sorry for the delay on this - I have a proposed change in [bugfix/290-import-config-not-clearing-values](https://github.com/brentvollebregt/auto-py-to-exe/tree/bugfix/290-import-config-not-clearing-values).

A couple of things worth noting:
- This will now reload the whole window when importing the config - this is done to make sure that all fields are reset and validated before adding the data
- I was originally going with a method to clear each input and then validate them before replacing the config but this got a bit messy

**Comment by TheGeeKing** [comment]
Hi @brentvollebregt,

No problem for the delay.

Yeah, I think this solution is perfect, it simply reset the window by reloading it and doesn't need extra step to validate them. It requires less code and makes it error proof for future updates.

Thanks for this great tool!

**Comment by brentvollebregt** [comment]
This has just been merged into master and has been released as part of auto-py-to-exe v2.21.1.

Thank you very much for the clear bug report, it really makes a difference!
