### ISSUE TITLE
avoid writing into fallback folder

### ISSUE THREAD

**Issue by ZackaryW** [brentvollebregt/auto-py-to-exe#291]
**Quick Checks For You**
- [X] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [X] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+) looking for an issue similar to mine
- [X] I have made sure my applicaiton/script runs before trying to package

**Describe the bug**
there should be an option to prevent moving completed folder to cwd or at least mitigate rewriting files if it already exists

my folder structure is
repo 
- [app]
- output
- - [app]

i build the app using `One Directory`, the folder is in use and it directly writes into my source code

**Expected behavior**
should never happen if the target fallback directory already has file

**Comment by brentvollebregt** [comment]
If this application is writing into your "source code", I feel like you should move directories as this tool writes to "./output" by default - this is somewhere we definitely would not expect to see source code.

**Comment by ZackaryW** [comment]
@brentvollebregt  that is not the case, 
the package is not named as `output`, if one directory mode is selected and the utility detects the folder is currently in use, it will move itself to the os.cwd directory, which is the root directory of the repo, overwriting the source package folder with the output

**Comment by ZackaryW** [comment]
![image](https://user-images.githubusercontent.com/36378555/181358631-b7ba0b33-0ec3-403f-9591-910b987f7599.png)
im explicitly referring to these instances
![image](https://user-images.githubusercontent.com/36378555/181358694-7ac78ac7-d6e6-4738-b90d-2bc3a80d2ea3.png)
i expect them to be generated at `./output` but they are moved to the root directory

**Comment by brentvollebregt** [comment]
I notice you output directory input is empty. Did the UI load like that or did you remove it?

**Comment by ZackaryW** [comment]
i noticed just now that the output directory occasionally shows empty value after loading the config.
It seems to be a rare occasion

**Comment by brentvollebregt** [comment]
Are you able to reproduce this consistently? If not, I won't be able to identify what's wrong.
