### ISSUE TITLE
The app is frozen on the start screen

### ISSUE THREAD

**Issue by congdan-62** [brentvollebregt/auto-py-to-exe#294]
**Quick Checks For You**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [ ] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+) looking for an issue similar to mine
- [ ] I have made sure my applicaiton/script runs before trying to package

**Describe the bug**
The app is frozen on the start screen. The start screen with a white half circle running forever.
**To Reproduce**
I uninstalled app then install again but the issue not gone

> If you have example code, please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

**Expected behavior**

**Screenshots**
![Screenshot 2022-08-04 213148](https://user-images.githubusercontent.com/25891295/183002472-df5a5db3-3dd3-4413-a25b-30e39eef00d4.jpg)

**Your Environment:**
- Python version (`python --version`): python v 3.10.4
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.21.1
- PyInstaller version (`pip show pyinstaller`): 5.1
- Eel version (`pip show eel`): 0.14.0

**Additional context**

**Comment by brentvollebregt** [comment]
Are there any errors in the DevTools console (F12)? Also are there any errors in the console where you started auto-py-to-exe from?

**Comment by congdan-62** [comment]
I don't know. I just start this app by enter 'auto-py-to-exe' in cmd window. My OS is win 10.

**Comment by congdan-62** [comment]
> Are there any errors in the DevTools console (F12)? Also are there any errors in the console where you started auto-py-to-exe from?

I don't know, but in cmd window I just enter auto-py-to-exe and the app start then frozen on the start screen, event on vs code the result is same. I use pyinstaller to convert py file to exe file have no error.

**Comment by brentvollebregt** [comment]
Unless you can pass what is in the DevTools console, there isn't much I can help with sorry
