### ISSUE TITLE
Stuck after failed command

### ISSUE THREAD

**Issue by jatin69** [brentvollebregt/auto-py-to-exe#3]
Nice work overall. Just a minor bug I encountered.
When i click the `convert button` without a valid command. The pyinstaller returns error, and the `convert button` gets permanently stuck at `converting` state. I have to manually close the app, restart it, provide all the file paths again, a lot of work when there are a lot of external files.
checking the cmd reveals this `FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dist/'` , so maybe we can catch this exception, and aim for a fix.
A fix would improve the user experience.

![bugfix](https://user-images.githubusercontent.com/13359891/37508474-3690cbfa-2919-11e8-877b-940b796daa6e.PNG)

**Comment by brentvollebregt** [comment]
This is actually something I forgot to think about. I'll look into a fix.

**Comment by brentvollebregt** [comment]
This should do it. Thank you very much for pointing this out.
