### ISSUE TITLE
win32com error

### ISSUE THREAD

**Issue by arcontechnologies** [brentvollebregt/auto-py-to-exe#301]
Hi,
I'm new to this tool and followed a tutorial but failed to get it up and running. 

My environment :
- Anaconda
- python : 3.9.13
- Windows 10

auto-py-to-exe command :
`pyinstaller --noconfirm --onedir --console --debug "all" --add-data "D:/robot_install/data;data/" --add-data "D:/robot_install/emails_traites;emails_traites/" --add-data "D:/robot_install/libraries;libraries/" --add-data "D:/robot_install/log;log/" --add-data "D:/robot_install/model;model/" --add-data "D:/robot_install/templates;templates/" --hidden-import "win32com" --hidden-import "win32comext" --hidden-import "win32ctypes"  "D:/robot_install/robotscheduler.py"`

Issue Description : 
my robotscheduler work fine when executing related .py. But when using auto-py-to-exe it triggered an error  related to win32com :

![image](https://user-images.githubusercontent.com/17960609/184538822-d92b22eb-e200-4445-9fc2-8564dd36c189.png)

and then I copied manually the win32com from anaconda env and got this error :

![image](https://user-images.githubusercontent.com/17960609/184538907-fac4766d-67c4-40bc-bf9f-9bf73bf5a477.png)

any insight on this ?

**Comment by brentvollebregt** [comment]
Looks similar to #46 - try adding win32api to the --hidden-import input field in the advanced tab

**Comment by arcontechnologies** [comment]
Actually it turned out that when my OutLook client is open it triggers this error. I tested it with Outlook closed and no issue so far. Seems this one one is acting as an exclusive open.
For those who encounter this error. try first to execute the program with Outlook client closed.
