### ISSUE TITLE
Linux support to make exe's

### ISSUE THREAD

**Issue by SirenGlitch** [brentvollebregt/auto-py-to-exe#302]
You cannot make exe's on Linux. I know Linux can't run them but the out put file I'm getting has no file extension, I am fairly new to Linux so it could just be me not knowing how to run files with no extension but I'm trying to turn my game into and exe for my friend who uses windows, but it just keeps spitting out un-extensioned files. Can you add an option for exe's when running on Linux?

**Comment by brentvollebregt** [comment]
Running auto-py-to-exe on Linux will build executable binaries - executing them in the terminal will run them. Usually, executable binaries on Linux don't have file extensions (from my experience - of course there are many exceptions to this).

Building Windows executables on Linux is not possible out of the box but can be done using [Wine](http://www.winehq.org/) - Wine is used to help run Windows applications on Linux. Running auto-py-to-exe on Wine will mean the output is a Windows executable.

**Comment by brentvollebregt** [comment]
Closing as this is more of an OS-specific binary question and no more questions/statements have been made.
