### ISSUE TITLE
 There is a browse error on mac.

### ISSUE THREAD

**Issue by pyuna** [brentvollebregt/auto-py-to-exe#304]
Execute auto-py-to-exe and click browse, then the tkinter window will appear.
How to make the tkinter window not appear behind?

<img width="912" alt="Screen Shot 2022-08-25 at 3 03 32 PM" src="https://user-images.githubusercontent.com/96897314/186590106-03747110-9bc2-4aa2-85a5-19f5370ab70a.png">

- Python version (`python --version`): 3.9.12
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.22.0
- PyInstaller version (`pip show pyinstaller`): 5.3
- Eel version (`pip show eel`): 0.14.0

- MacOS: Monterey

**Comment by brentvollebregt** [comment]
Unfortunately, I do not own a mac so I'm unable to investigate this sorry.

If you run this script in Python, does it lead to the same issue?

```python
from tkinter import Tk
from tkinter.filedialog import askopenfilename

root = Tk()
root.withdraw()
root.wm_attributes('-topmost', 1)
file_path = askopenfilename(parent=root, filetypes=[('All files', '*')])
root.update()
print(file_path)
```
