### ISSUE TITLE
Arguments are not being read by output EXE

### ISSUE THREAD

**Issue by PoshoDev** [brentvollebregt/auto-py-to-exe#308]
Hello there, big fan of this tool. It has made my life much simpler. 🙂

The Python script I want to convert uses `sys.argv` for command line arguments, they are being read when I do `python myscript.py foo` but not when I do `./myscript.exe foo` using the output EXE file. It _does_ work when I use the `--console` flag though, but since my script is meant to run in the background when run without arguments or double-clicked from Explorer, it is not optimal.

Is there any workaround for this?

**Comment by brentvollebregt** [comment]
I just ran this script and it worked fine:

```python
import sys
import requests

url = "https://webhook.site/c24306fb-4cc8-4201-96e4-e44a3552718d" # Generate from webhook.site
data = {"sys.argv": sys.argv}
r = requests.post(url, json=data, verify=False)
```

To use this
1. Generate a new webhook.site URL and put it in `url
2. Test the script locally using `python demo.py my args are here`, you should see the args appear in the latest request on the site
3. Bundle the script using auto-py-to-exe
4. Test the executable using `demo.exe are my args here`, you should see the args appear in the same way
