### ISSUE TITLE
[Bug] cannot import .py module in same folder as main .py

### ISSUE THREAD

**Issue by jdai** [brentvollebregt/auto-py-to-exe#309]
**Quick Checks For You**
- [x ] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+) looking for an issue similar to mine
- [ x] I have made sure my applicaiton/script runs before trying to package

**Describe the bug**
Traceback (most recent call last):
  File "pyidm.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "pyidm\PyIDM.py", line 24, in <module>
    from dependency import install_missing_pkgs
ModuleNotFoundError: No module named 'dependency'
[2416] Failed to execute script 'pyidm' due to unhandled exception!

above log shows pyidm\dependency.py is not found.

**To Reproduce**

> If you have example code, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Expected behavior**
whole project pyidm can be found in github, used to be in pysimplegui.
as I choose single folder to generate .exe, all .py in the folder or in the subfolder would be included. the structure of the project:
project folder is PyIDM, main code is pyidm.c, it just runs pyidm\PyIDM.py;
pyidm\PyIDM.pyhas "from dependency import install_missing_pkgs"; 
pyidm\dependency.py it has function "def install_missing_pkgs():" it reads PyIDM\requirements.txt which contains package like:
PySimpleGUI>=4.18
pyperclip
plyer
certifi
youtube_dl
pycurl
install_missing_pkgs() check and installs above packages.

**Screenshots**

**Your Environment:**
- Python version (`python --version`): 3.8.1 or 3.10
- auto-py-to-exe version (`pip show auto-py-to-exe`): download from github on Sept 7 2022
- PyInstaller version (`pip show pyinstaller`): 5.3
- Eel version (`pip show eel`): 0.14.0

**Additional context**
The challenges are:
1.project folder contains main py code and subfolders contains icon and source code folder
2.main py is just one line to run sub-main code in subfolder, and the sub-main py code can run directly
3.sub-main code imports several local and public packages, and access requiremtns.txt in main folder
4.code check and install public packages via pip, including pycurl that need refers to Internet (still using pip cmd) 
5.to make pyidm project running, I did change style of "from .<> import" to remove the '.' as it gives error:
    from .version import __version__
ImportError: attempted relative import with no known parent package
In fact I don't know how to import packages in sub folders, with or w/o '.' sometimes work sometimes not

**Comment by brentvollebregt** [comment]
Your script is named "pyidm.py" and the library you are importing is called "pyidm" - did you really run your script before packaging?

**Comment by jdai** [comment]
of course I run my file and it works w/o error. After use your tool:
1.my source folder becomes empty - terrible and I'm struggle to get them back
2.latest convert exe can run but w/o any result - run, done, nothing.
3" the library you are importing is called "pyidm" not that simple. source codes in base, pyidm and icon folders, code refers to many global packages.

**Comment by jdai** [comment]
I suggest you read all filenames of a project, then match them in all source codes, then you won't miss the usage. any local source code - I mean .py - can refer to sub,parallel level or base folder. Also handle all import statement. If your code is smart, it shall handle common requirements.txt or similar.

**Comment by brentvollebregt** [comment]
> I suggest you read all filenames of a project, then match them in all source codes

What source code??? You have no reproduction steps. Please provide proper reproduction steps otherwise I will need to close this.

**Comment by jdai** [comment]
https://github.com/P3NG3R/pyIDM
please try to convert it to exe thus you can find lots of errors. In another thread I already told you how to install pucurl.

**Comment by jdai** [comment]
pls close it, not pysimplegui problem
