### ISSUE TITLE
Will this work on Linux?

### ISSUE THREAD

**Issue by Harvie** [brentvollebregt/auto-py-to-exe#31]
Can i use this on Linux to build .exe files for Windows users?

**Comment by brentvollebregt** [comment]
Read: https://github.com/pyinstaller/pyinstaller/issues/2613, PyInstaller is cross-platform but not a cross-compiler.

Although https://github.com/pyinstaller/pyinstaller/issues/2613#issuecomment-302298224 points out that pyinstaller + wine under docker can work well in many circumstances and notes the repo at [cdrx/docker-pyinstaller](https://github.com/cdrx/docker-pyinstaller).
