### ISSUE TITLE
[bug] Terrible! It removes your project files, why?

### ISSUE THREAD

**Issue by jdai** [brentvollebregt/auto-py-to-exe#310]
this tool is terrible and unacceptable!
it removes your project source folder, change the content. You will find your folder becomes empty!
I spent some time tried to reprogramming my code, why why why you do like this???
you created a sub-folder under your output, buy why you remove input or source folder???

It does generate an .exe run the exe it shows:

Traceback (most recent call last):
  File "pyidm.py", line 11, in <module>
    from pyidm import PyIDM
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "pyidm.py", line 11, in <module>
    from pyidm import PyIDM
ImportError: cannot import name 'PyIDM' from partially initialized module 'pyidm' (most likely due to a circular import) (C:\Users\yzdai\AppData\Local\Temp\_MEI49322\pyidm.pyc)

**Comment by brentvollebregt** [comment]
Please fill out the template you cleared

**Comment by jdai** [comment]
if you write the code, or try to run it for whole folder conversion, you should see it. any code will do. I just want to ask, why this tool removes original code???
I cannot post code because the tool removed my code, original web also becomes 404, but you can get it from here: https://github.com/P3NG3R/pyIDM

**Comment by brentvollebregt** [comment]
> if you write the code, or try to run it for whole folder conversion, you should see it. any code will do.

I just wrote this script and put it in my downloads (an example to be able to reproduce),

```python
print("Hello world"
```

I then bundled it with a globally installed version of auto-py-to-exe and ran it. The original script was still there.

I cannot help with proper reproduction steps.

**Comment by jdai** [comment]
the tool would work for single file. I already give your the project link, run it and you will know what happens.
the reproduce steps is download PyIDM and run it, then use your tool to make .exe
thanks.

**Comment by brentvollebregt** [comment]
> the reproduce steps is download PyIDM and run it, then use your tool to make .exe

I tried to install PyIDM dependencies and was having issues with pycurl not being supported out of the box on Windows - it appears there are some holes in your reproduction steps.

As I asked before, please fill out the template you cleared and provide clear reproduction steps. It seems the title of this issue and the things you're asking are two different things - please make the issue focuses on a single issue otherwise it can lead to the original issue being forgotten.

Thanks.
