### ISSUE TITLE
Decompile

### ISSUE THREAD

**Issue by Zw96042** [brentvollebregt/auto-py-to-exe#311]
Is there anyway to decompile the exe after it's created? I have created an exe a year ago and it works but I want to work on the project again and I have tried unpy2exe but it was still encrypted. Is there any tool I can use to get the source code?

**Comment by brentvollebregt** [comment]
auto-py-to-exe uses PyInstaller in the background - so you will want to search for a tool to decompile PyInstaller bundles.

I haven't done it myself but [pyinstxtractor](https://github.com/extremecoders-re/pyinstxtractor) looks promising.

**Comment by brentvollebregt** [comment]
Just closing as this was a question - if the above didn't make sense, let me know.
