### ISSUE TITLE
How to include models, github files, and other libraries.

### ISSUE THREAD

**Issue by CGMikeG** [brentvollebregt/auto-py-to-exe#314]
Hi,

I am just wondering if there is a way to turn a huge file into an .exe. 

I am currently trying to create a GUI for a program called openmmd. Links below. I don't own the repository but I have always wanted to create a GUI for users to make it easier to use.

https://github.com/peterljq/OpenMMD

I was able to create a simple GUI but not sure how to turn it into working executable.

What the program is suppose to do is to convert a video to a vmd file, something similar to fbx or bvh. But as you can imagine this will have to include a huge python libraries, models, etc.

I was already expecting your program to just compile the GUI but I was not sure how I can make this detect all the other required file.

By the way I am new python, I am just hoping that somebody can point me into the right direction.

My aim is to hopefully to make a stand alone program without the user needing to install python.

Thanks.

**Comment by brentvollebregt** [comment]
Any required binaries/executables can be added by the "--add-binary" in the advanced section. Pretty much any other type of file can be added using the "Additional Files" section.

To get something large working it's a loop of bundling, running, seeing what went wrong, fixing it and repeating this cycle.

**Comment by brentvollebregt** [comment]
@CGMikeG is this an issue or can we close this?
