### ISSUE TITLE
Writing and Reading files is not permanently

### ISSUE THREAD

**Issue by FrenkyDema** [brentvollebregt/auto-py-to-exe#316]
## **Description**

My application use json file to write some information, when i try in my IDE there is no problem.
But when i transform the project in executable application

## **How to Reproduce**
- Create project with a Json file 
- Save text  on file json
- Close application
- Reopen
- File Json was load at previous version

## **My Environment:**
- Python version (`3.10.6`):
- auto-py-to-exe version (`2.23.1`):
- PyInstaller version (`5.4.1`):
- Eel version (`0.14.0`): 

## **Additional context**
Test project -> [TestIOReport](https://github.com/FrenkyDema/TestIOReport/tree/main)

**Comment by brentvollebregt** [comment]
There is quite a bit missing in your reproduction steps - specifically around bundling and running the executable.

Are you using one directory mode to package your application? Also did you follow the debugging steps before creating this issue? (means you would have used one directory before)

**Comment by FrenkyDema** [comment]
> There is quite a bit missing in your reproduction steps - specifically around bundling and running the executable.
> 
> Are you using one directory mode to package your application? Also did you follow the debugging steps before creating this issue? (means you would have used one directory before)

I'm using the one file mode, and if is possible I prefer to maintain that

**Comment by FrenkyDema** [comment]
For the reproduce steps u can check my test project I've linked in the issues report

**Comment by brentvollebregt** [comment]
There is a help post that is linked in the README, top of auto-py-to-exe and bottom of auto-py-to-exe after each build. In this post, I discuss [The Difference Between One Directory and One File](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#the-difference-between-one-directory-and-one-file) - I highly recommend you give that a read.

I believe you are trying to overwrite a file that is part of the initial bundle and are expecting it to stay modified after each run - this is not how one-file mode works. one-file mode unbundles on each run meaning all modified files within the bundles are reset.

**Comment by FrenkyDema** [comment]
Oooo I understand, so to edit files and have permanent changes there is no way to have everything as One file?

**Comment by brentvollebregt** [comment]
Changes will be kept when modifying files outside of the unpackaged package (like usual) - it is just the files within the exe that are reset.

Directly from the post I linked before:

> Also due to the files being unpacked to a new temporary directory on execution, the files that you modified added that were in the same directory as the executable will not be there on the next run because they are now in a different unknown folder. This means when creating files, you will want to use an absolute path that is not where the project files are (could use something like APPDATA on Windows).

**Comment by FrenkyDema** [comment]
ok, ok sorry for the inconvenience, now I'll try
