### ISSUE TITLE
Cant generate a exe with a python code

### ISSUE THREAD

**Issue by NatanStein** [brentvollebregt/auto-py-to-exe#317]
Geting this output and it is running recursive:

Running auto-py-to-exe v2.13.0
Building directory: C:\Users\Natan\AppData\Local\Temp\tmpp9m5jf_t
Provided command: pyinstaller --noconfirm --onefile --console --icon "C:/Users/Natan/Downloads/xnbsZaz.ico"  "C:/Users/Natan/Desktop/Solana/elixir/mines.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console --icon C:/Users/Natan/Downloads/xnbsZaz.ico C:/Users/Natan/Desktop/Solana/elixir/mines.py --distpath C:\Users\Natan\AppData\Local\Temp\tmpp9m5jf_t\application --workpath C:\Users\Natan\AppData\Local\Temp\tmpp9m5jf_t\build --specpath C:\Users\Natan\AppData\Local\Temp\tmpp9m5jf_t

29176 INFO: PyInstaller: 4.7
29180 INFO: Python: 3.8.8 (conda)
29189 INFO: Platform: Windows-10-10.0.19041-SP0
29206 INFO: wrote C:\Users\Natan\AppData\Local\Temp\tmpp9m5jf_t\mines.spec
29224 INFO: UPX is not available.
29228 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Natan\\Desktop\\Solana\\elixir']
30071 INFO: checking Analysis
30074 INFO: Building Analysis because Analysis-00.toc is non existent
30082 INFO: Initializing module dependency graph...
30109 INFO: Caching module graph hooks...
30130 INFO: Analyzing base_library.zip ...
36028 INFO: Processing pre-find module path hook distutils from 'c:\\users\\natan\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
36036 INFO: distutils: retargeting to non-venv dir 'c:\\users\\natan\\anaconda3\\lib'
42211 INFO: Caching module dependency graph...
42493 INFO: running Analysis Analysis-00.toc
42525 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\natan\anaconda3\python.exe
42806 INFO: Analyzing C:\Users\Natan\Desktop\Solana\elixir\mines.py
43977 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'c:\\users\\natan\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
60062 INFO: Processing pre-find module path hook site from 'c:\\users\\natan\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
60065 INFO: site: retargeting to fake-dir 'c:\\users\\natan\\anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
85955 INFO: Processing pre-safe import module hook six.moves from 'c:\\users\\natan\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
103626 INFO: Processing pre-safe import module hook win32com from 'c:\\users\\natan\\anaconda3\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.

What should I do?

**Comment by brentvollebregt** [comment]
Can you please fill out the template you cleared - I am unable to see anything hinting at this being recursive
