### ISSUE TITLE
Modules Not Found

### ISSUE THREAD

**Issue by jbarker2160** [brentvollebregt/auto-py-to-exe#32]
I tried to convert the attached program.
[outlooktest.py.txt](https://github.com/brentvollebregt/auto-py-to-exe/files/2605410/outlooktest.py.txt)

I get the error when I try to run the EXE that "No module named 'win32timezone'"

How do I get the program to add this module?

**Comment by brentvollebregt** [comment]
I briefly cover this issue in my post on [Issues When Using auto-py-to-exe](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#modulenotfounderror-no-module-named-x).

> Make sure the module is installed and then add it to --hidden-import in the advanced tab. If you need to add more than one, separate them by a comma (,).

**Comment by brentvollebregt** [comment]
Closing due to no response from @jbarker2160
