### ISSUE TITLE
Application opens and closes

### ISSUE THREAD

**Issue by ljboxf** [brentvollebregt/auto-py-to-exe#321]
**Quick Checks For You**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [X] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+) looking for an issue similar to mine
- [X] I have made sure my application/script runs before trying to package

**Describe the bug**
.py compiled to an exe perfectly but upon opening it instantly closes, I already have `input("Press Enter to continue...")` inside my code and before compiling it functioned as it should, I've now tried rebuilding it with the debug flag but I'm not too sure what's wrong.. Here is the log (https://pastebin.com/aJ16Awah) If anyone can help it's highly appreciated.

**Your Environment:**
- Python version (`python --version`): 3.11.0
- auto-py-to-exe version (`pip show auto-py-to-exe`):  2.23.1
- PyInstaller version (`pip show pyinstaller`): 5.6.1
- Eel version (`pip show eel`): 0.14.0

**Comment by brentvollebregt** [comment]
When you followed the debugging steps in the help post, what did you find? Did you see an error in the console? If so, can you paste it here.

**Comment by ljboxf** [comment]
> When you followed the debugging steps in the help post, what did you find? Did you see an error in the console? If so, can you paste it here.

Thank you for the quick reply! Unfortunately when setting the debug option, building the application and then running it to see what errors may display in console I'm unable to see due to the window closing upon launch.. Only log I have is from the actual build with the debug flag which can be found here -  https://pastebin.com/aJ16Awah

**Comment by brentvollebregt** [comment]
> Unfortunately when setting the debug option, building the application and then running it to see what errors may display in console I'm unable to see due to the window closing upon launch

Are you running the exe from a console? The console shouldn't close if the window closes it as the application doesn't own the console's process.
