### ISSUE TITLE
When run the compiled exe generates 2 instances on windows

### ISSUE THREAD

**Issue by joitronix** [brentvollebregt/auto-py-to-exe#324]
![image](https://user-images.githubusercontent.com/13211515/199579545-b395608b-5abd-4530-9781-e1eeb1781285.png)

Every time y run a compiled exe y see 2 times executed one with les memory than the other anyone knows what happening?

**Comment by joitronix** [comment]
I y close the main app the other close too

**Comment by brentvollebregt** [comment]
When you say "instances", do you mean processes? Not 100% where that screenshot is from.

**Comment by joitronix** [comment]
> When you say "instances", do you mean processes? Not 100% where that screenshot is from.

Yes 2 process, in windows task manager.

**Comment by brentvollebregt** [comment]
These two GitHub issues for PyInstaller should answer your concern; 

- https://github.com/pyinstaller/pyinstaller/issues/3173
- https://github.com/pyinstaller/pyinstaller/issues/2483
