### ISSUE TITLE
Hide Splash after program starts

### ISSUE THREAD

**Issue by sjyuenger** [brentvollebregt/auto-py-to-exe#326]
I Splash a logo image.  Windows 11Pro it is on the top level of the screen and hides everything beneath it.  I need some way to remove this after either a timer or when the program begins to execute.
Any guidance will be thankfully received.
sjFindMyFile@gmail.com
Stephen Yuenger

**Comment by brentvollebregt** [comment]
Could you give a screenshot of this? I don't use Windows 11.

**Comment by sjyuenger** [comment]
Brent,
Happy to, I have a user manual where multiple timed samples of the screen are shown.  FindMyFile Operations<https://www.dropbox.com/scl/fi/do6z4yxfuoqkpb9j7dn8z/Operating-User-Guide.docx?dl=0&rlkey=il7sflof2hgzymiu1c2il0ebv>
Here is a link to the document

**Comment by sjyuenger** [comment]
Brent, I just compiled the program and thought this might be helpful. Regards, Maythesunshinewarmlyonyourface,Maytheroadrisegentlytomeetyourfeet, Maythewindbealwaysatyourbackand,MaytheLordholdyouinthe 


External ( ***@***.***> ***@***.***) 

   <https://protection.inkyphishfence.com/report?id=bmV0b3JnZnQ4NjA2NTk0L3NqeXVlbmdlckBubWJmLnVzLzZlMDk2NDBmNmU0YjVkNGRhMTJmYWY3ZjgwNTcwYmM1LzE2NjgzNjQwMjIuMjI=#key=bd6bb264243709113a602fe4fdd6e39b> Report This Email   <https://www.inky.com/banner-faq> FAQ   <https://www.inky.com/protection-by-inky> GoDaddy Advanced Email Security, Powered by INKY 

 

Brent,

I just compiled the program and thought this audit listing might be helpful.

Regards,

May the sun shine warmly on your face, May the road rise gently to meet your feet,

May the wind be always at your back and, May the Lord hold you in the palms of His hands and say,

“Welcome Home and Well Done”.





Stephen J Yuenger

Independent Consultant

477 NW Dover Court

Port St Lucie, FL 349823

772-418-0150

 ***@***.***> ***@***.***

 ***@***.***> ***@***.***

 

 

 

From: Stephen Yuenger 
Sent: Sunday, November 13, 2022 1:11 PM
To: brentvollebregt/auto-py-to-exe < ***@***.***> ***@***.***>
Subject: RE: [brentvollebregt/auto-py-to-exe] Hide Splash after program starts (Issue #326)
Importance: High

 

Brent,

Happy to, I have a user manual where multiple timed samples of the screen are shown.   <https://shared.outlook.inky.com/link?domain=www.dropbox.com&t=h.eJxFj8tugzAURH8lYtFVg40LBiJFyS7LrvoBGN9LDH5QG5dH1X9vvep2zuiM5juLXmeXU_ZcljlcCFnXNZfezcJtee8MCb0mqIh0_Cj3DaP7nGbRjrW0zUHeZ_Ddouxw_gjgz4-oJOTS9dtN6it98XqC_ap0HVA7ZM_h2I2KRc-UpiC-stdTNqVtC4vzAy4Np7xqSxLGPYIdwN-tEZjHQDjQlpcUOZSikqXsCoYd1tjQqqair0jBefP212AsZyyJIYnDiMpKs6PScB9Mp3T6lLBM-D_5-QXGhFZc.MEQCIH7ntAZi302Fcw-4nHom4aAThrmGsh-eHXRSq7oeQanXAiA25AN-nOxBzU7Rnvvtc9hHZeZzI6m2X7smuxzS2dzDqQ> FindMyFile Operations

Here is a link to the document

**Comment by brentvollebregt** [comment]
Are you able to paste the images here? Just want to make sure they don't disappear after I close this issue (quite often people will delete images and other files from external hosting after the issue is fixed).

**Comment by sjyuenger** [comment]
[Graphical user interface  Description automatically generated]


[Graphical user interface, text, application  Description automatically generated]


































May the sun shine warmly on your face, May the road rise gently to meet your feet,
May the wind be always at your back and, May the Lord hold you in the palms of His hands and say,
***@***.***“Welcome Home and Well ***@***.***
[Logo, company nameDescription automatically generated]
[Logo, company name  Description automatically generated]
Stephen J Yuenger
Independent Consultant
477 NW Dover Court
Port St Lucie, FL 349823
772-418-0150
***@***.******@***.***>
***@***.******@***.***>





From: Stephen Yuenger ***@***.***>
Sent: Sunday, November 13, 2022 2:28 PM
To: brentvollebregt/auto-py-to-exe ***@***.***>; brentvollebregt/auto-py-to-exe ***@***.***>
Cc: Stephen Yuenger ***@***.***>; Author ***@***.***>
Subject: RE: [brentvollebregt/auto-py-to-exe] Hide Splash after program starts (Issue #326)

**Comment by brentvollebregt** [comment]
@sjyuenger, the images don't seem to be showing up in GitHub

**Comment by sjyuenger** [comment]
Sorry, let me try this way.


May the sun shine warmly on your face, May the road rise gently to meet your feet,
May the wind be always at your back and, May the Lord hold you in the palms of His hands and say,
***@***.***“Welcome Home and Well ***@***.***
[Logo, company nameDescription automatically generated]
[Logo, company name  Description automatically generated]
Stephen J Yuenger
Independent Consultant
477 NW Dover Court
Port St Lucie, FL 349823
772-418-0150
***@***.******@***.***>
***@***.******@***.***>

**Comment by brentvollebregt** [comment]
That didn't seem to work either - check out https://github.com/brentvollebregt/auto-py-to-exe/issues/326

**Comment by brentvollebregt** [comment]
Still not - if you look at the issue in GitHub, you will see.

**Comment by sjyuenger** [comment]
Brendt,
I thought I had replied to this with a PDF version of the images. Here is a new copy of those.
I hope this gives you what you need.  In the interim I have shut off using the flash capability.
Regards.
May the sun shine warmly on your face, May the road rise gently to meet your feet,
May the wind be always at your back and, May the Lord hold you in the palms of His hands and say,
***@***.***“Welcome Home and Well ***@***.***
[Logo, company nameDescription automatically generated]
[Logo, company name  Description automatically generated]
Stephen J Yuenger
Independent Consultant
477 NW Dover Court
Port St Lucie, FL 349823
772-418-0150
***@***.******@***.***>
***@***.******@***.***>

**Comment by sjyuenger** [comment]
Brent, I am sorry, I guess I don't know how to post an image to github for you to see.

**Comment by sjyuenger** [comment]
That is what I have done.

![Screenshot 2022-11-12 153601](https://user-images.githubusercontent.com/86953635/203861500-fe4245ed-41ca-4542-9c20-12146be9a623.jpg)
![Screenshot 2022-11-12 154330](https://user-images.githubusercontent.com/86953635/203861521-5ad5b635-7e31-48fa-9832-31a2ffeb849e.jpg)
![Screenshot 2022-11-12 153648](https://user-images.githubusercontent.com/86953635/203861540-7d4da68e-155a-44a8-af23-ec42a3403055.jpg)

**Comment by sjyuenger** [comment]
I was trying to post directly to github()

**Comment by brentvollebregt** [comment]
That splash looks like something that is part of your application and is completely independent of auto-py-to-exe - maybe I'm wrong?

**Comment by sjyuenger** [comment]
Brent,
The image is assigned by auto-py-to-exe in the Splash page.  It is the logo image for my application.
Regards,
Steve
May the sun shine warmly on your face, May the road rise gently to meet your feet,
May the wind be always at your back and, May the Lord hold you in the palms of His hands and say,
***@***.***“Welcome Home and Well ***@***.***
[Logo, company nameDescription automatically generated]
[Logo, company name  Description automatically generated]
Stephen J Yuenger
Independent Consultant
477 NW Dover Court
Port St Lucie, FL 349823
772-418-0150
***@***.******@***.***>
***@***.******@***.***>

**Comment by brentvollebregt** [comment]
Ah, I see what you're talking about now - PyInstaler added the `--splash` option back in v4.4. Your original issue description did not outline your usage of this - it might pay to follow the template next time.

You haven't given a minimal reproducible example to look at so I'm guessing you may not have called `pyi_splash.close()`? I had never used the feature myself but the docs say to do this - read 2.6.6 "Splash Screen" and 2.6.7 in https://readthedocs.org/projects/pyinstaller/downloads/pdf/latest/.

**Comment by sjyuenger** [comment]
Brent,
Ah, I see what you are saying, shows how new I am to github.com.  They sent some training material for me so I guess I need to watch it.
Assumptions as to what they mean by ‘splash page’ is not what I expected, and the fact that it is EXPERIMENTAL is another issue.  I think I’ll wait for it to be upgraded.
Well, I have some more reading as I printed off the manual for PyInstaller, so I guess I will see what it does when I am finished with FindMyFile.exe
Regards,
Steve

**Comment by brentvollebregt** [comment]
All good - I'll close this issue now as we have some form of resolution 👍

**Comment by mariusserafin** [comment]
It will work fine if you just add this to your code:

try:
    import pyi_splash  # type: ignore
    pyi_splash.close()

except ImportError:
    pass
