### ISSUE TITLE
Can't use pip install with Python 3.11

### ISSUE THREAD

**Issue by PahlawanJoey** [brentvollebregt/auto-py-to-exe#327]
Will you support Python 3.11 in the future?

**Comment by brentvollebregt** [comment]
If you pull down the repo and run the project, do you have any issues? I haven't tried it using Python 3.11 yet so need to gauge if there are any issues. If there are none, I can add official support asap.

**Comment by PahlawanJoey** [comment]
I installed the latest Python 3.11 on a new machine and tried pip install but it wouldn't install. I installed Python 3.10.7 and then it worked.

**Comment by brentvollebregt** [comment]
And why wouldn't it install? Some detail on this would be awesome - what you are executing, output from that command, exceptions, tracebacks, etc

**Comment by brentvollebregt** [comment]
@PahlawanJoey on top of my last question, still keen to know if it worked when you pulled down the repo and ran it from source

**Comment by PahlawanJoey** [comment]
@brentvollebregt 
I tried to recreate the traceback but was unsuccessful.
On my new laptop I installed Python 3.11 and when using pip install auto-py-to-exe received something like: "error: subprocess-exited-with-error" (which I checked in my browser history), but can't exactly find what the subproces was that failed.

Good news is, to recreate the error I uninstalled Python 3.10.7 and then installed Python 3.11 again. Then I installed auto-py-to-exe and it was successful. I also just compiled a script into an exe file successfully, so I guess it works, just don't know why it failed before.



Running auto-py-to-exe v2.24.0
Building directory: C:\Users\J04BC~1.SIE\AppData\Local\Temp\tmpiokxn1vt
Provided command: pyinstaller --noconfirm --onefile --console --add-data "C:/Users/XXXXXX/PycharmProjects/XXXXXX/venv/Lib/site-packages/openpyxl;openpyxl/" --add-data "C:/Users/XXXXXX/PycharmProjects/XXXXXX/venv/Lib/site-packages/et_xmlfile;et_xmlfile/" --hidden-import "xml.etree" --hidden-import "xml" --hidden-import "re" --hidden-import "XXXXXX" --hidden-import "openpyxl" --hidden-import "et_xmlfile" --hidden-import "__future__" --hidden-import "xml.etree.ElementTree" --hidden-import "" --hidden-import ""  "C:/Users/XXXXXX/PycharmProjects/XXXXXX/XXXXXX.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console --add-data C:/Users/XXXXXX/PycharmProjects/XXXXXX/venv/Lib/site-packages/openpyxl;openpyxl/ --add-data C:/Users/XXXXXX/PycharmProjects/XXXXXX/venv/Lib/site-packages/et_xmlfile;et_xmlfile/ --hidden-import xml.etree --hidden-import xml --hidden-import re --hidden-import XXXXXX --hidden-import openpyxl --hidden-import et_xmlfile --hidden-import __future__ --hidden-import xml.etree.ElementTree --hidden-import  --hidden-import  C:/Users/XXXXXX/PycharmProjects/XXXXXX/XXXXXX.py --distpath C:\Users\J04BC~1.SIE\AppData\Local\Temp\tmpiokxn1vt\application --workpath C:\Users\J04BC~1.SIE\AppData\Local\Temp\tmpiokxn1vt\build --specpath C:\Users\J04BC~1.SIE\AppData\Local\Temp\tmpiokxn1vt

125603 INFO: PyInstaller: 5.6.2
125624 INFO: Python: 3.11.0
125658 INFO: Platform: Windows-10-10.0.19045-SP0

**Comment by brentvollebregt** [comment]
[v2.24.1](https://github.com/brentvollebregt/auto-py-to-exe/releases/tag/v2.24.1) is just being released now - should be able to use pip to install auto-py-to-exe on Python 3.11 now
