### ISSUE TITLE
Conversion error, don't know where it is.

### ISSUE THREAD

**Issue by qsx6003** [brentvollebregt/auto-py-to-exe#33]
Excuse me, the problem occurred in use. The original code is with the tkinter interface.

![2](https://user-images.githubusercontent.com/44695628/48892338-ceee2580-ee78-11e8-8b5f-8d5eec7c75fd.png)
![3](https://user-images.githubusercontent.com/44695628/48892346-d31a4300-ee78-11e8-9eef-3f571ee995bf.png)

**Comment by brentvollebregt** [comment]
I recommend reading my post on [debugging the result executables](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging).

You are missing errors that are being printed to standard out since you have used "Window Based" and am using nothing to preserve the output.

**Comment by qsx6003** [comment]
> 我建议阅读关于[调试结果可执行文件的](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging)帖子。
> 
> 由于您使用了“基于窗口”并且没有使用任何内容来保留输出，因此您缺少正在打印到标准输出的错误。

**Comment by qsx6003** [comment]
> I recommend reading my post on [debugging the result executables](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging).
> 
> You are missing errors that are being printed to standard out since you have used "Window Based" and am using nothing to preserve the output.

Thank you. Thank you for your technique.
