### ISSUE TITLE
Railroad

### ISSUE THREAD

**Issue by KingKrex69** [brentvollebregt/auto-py-to-exe#337]
**Quick Checks**
I have downloaded railroad and all dependencies

**Describe the bug**
it prints it in console idk why

**To Reproduce**
download the library and compile a file like normal

**Expected behavior**
Clear console

**Screenshots (optional)**

**Your Environment:**
- Python version (`3.11`):
- auto-py-to-exe version (`2.26.0`):
- PyInstaller version (`5.6.2`):
- Eel version (`Version: 0.14.0`): 

**Additional context (optional)**
```py
571 WARNING: Failed to collect submodules for 'pkg_resources._vendor.pyparsing.diagram' because importing 'pkg_resources._vendor.pyparsing.diagram' raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'
```
it prints this in console

**Comment by brentvollebregt** [comment]
> it prints it in console idk why

That's not much to go off, but pyparsing/pyparsing#234 looks similar to your issue - to find this, I searched `module 'railroad' has no attribute 'DiagramItem'` in Google and it was the first link for me.

Is that line printing really the only issue? If that's it, then I don't see it as an issue.
