### ISSUE TITLE
Import from another folder?

### ISSUE THREAD

**Issue by xzzh999** [brentvollebregt/auto-py-to-exe#34]
Hi~ nice work!
When i import a python file from another folder, it can  build, but can't run, why?
how to fix this? btw, i use ```sys.path.append('./another_folder')``` to search the module.

**Comment by brentvollebregt** [comment]
If you explicitly use the import keyword to import, then PyInstaller will find you script and package it.

**Comment by xzzh999** [comment]
@brentvollebregt 
thank you for your reply, after i  set ```--additional-hooks-dir``` to that folder, it worked.
