### ISSUE TITLE
Script Browser Window Suddenly Opening Halfway Off Screen

### ISSUE THREAD

**Issue by carmitrey** [brentvollebregt/auto-py-to-exe#342]
### Discussed in https://github.com/brentvollebregt/auto-py-to-exe/discussions/341

<div type='discussions-op-text'>

<sup>Originally posted by **carmitrey** December  7, 2022</sup>
Up until today, this has worked flawlessly and is a great and easy tool for those looking to distribute apps without needing to worry about having end users download dependencies.

However, starting recently, when I click "Browse" next to the Script Location field, the Finder window is opening half-way off the screen and I cannot figure out how to fix it or move it back. I am unable to simply drag it back into view. 

<img width="1535" alt="Screen Shot 2022-12-07 at 2 54 54 PM" src="https://user-images.githubusercontent.com/76013426/206282490-3758f10c-b737-4c4b-981b-e39972aec34b.png">

I have tried simply rebooting Mac OS but that doesn't seem to fix the issue and wasn't sure maybe there is some caching somewhere that keeps loading the window in this position rather than in the center of my screen.

If it's any help, this seemed to start after I had started using an additional monitor and discontinued using it later.

Appreciate any assistance on figuring out how to move this window back into view.

Thanks!</div>

**Comment by brentvollebregt** [comment]
If you execute the following, do you get the same result:

```python
from tkinter import Tk
from tkinter.filedialog import askopenfilename

root = Tk()
root.withdraw()
root.wm_attributes('-topmost', 1)
file_path = askopenfilename(parent=root)
root.update()
print(f"Result: {file_path}")
```

**Comment by carmitrey** [comment]
> If you execute the following, do you get the same result:
> 
> ```python
> from tkinter import Tk
> from tkinter.filedialog import askopenfilename
> 
> root = Tk()
> root.withdraw()
> root.wm_attributes('-topmost', 1)
> file_path = askopenfilename(parent=root)
> root.update()
> print(f"Result: {file_path}")
> ```

Yes, I get the Tkinter window in the same exact place down in the bottom left as shown in my screenshot.

**Comment by carmitrey** [comment]
@brentvollebregt 
Oddly, if I comment out the line `root.wm_attributes('-topmost', 1)`, the window centers perfectly in the middle of my main monitor again.

**Comment by brentvollebregt** [comment]
I believe we need `root.wm_attributes('-topmost', 1)` so the dialog appears on top of other windows (otherwise users won't see them open).

When you removed the lines, did the dialogs start appearing under others sometimes?

**Comment by carmitrey** [comment]
Yea, that is what that seems to be used for.

At least in my case, it does hide the window behind anything that is
currently displayed, but the window is at least usable.

I am going to try uninstalling the packages today and reinstall them as I
think this is more of an issue with Tkinter than I think it's your library.

Open to any other suggestions but this seems to at least work for the time
being.

Thanks!

**Comment by brentvollebregt** [comment]
With you saying you still have the issue when just running the snippet I gave you, it shows you're right in saying it's not auto-py-to-exe. I have never seen this issue before so am unable to provide any more help sorry.

**Comment by brentvollebregt** [comment]
I'll close this issue for now but if you find auto-py-to-exe is doing something wrong in this context, comment and we can re-open the issue 👌
