### ISSUE TITLE
Converting stuck at hook-gevent

### ISSUE THREAD

**Issue by Yoko11111111** [brentvollebregt/auto-py-to-exe#343]
Hello, I got an issue while using auto-py-to-exe. 

Command:
pyinstaller --noconfirm --onedir --console --icon "P:/D/test/Por/Zuna/ico.ico" --add-data "P:/D/test/Por/Zuna -;Zuna -/"  "P:/D/test/Por/Zuna/test.py"

Full Output:

Running auto-py-to-exe v2.23.1
Building directory: C:\Users\jamu\AppData\Local\Temp\tmpakt8x1hc
Provided command: pyinstaller --noconfirm --onedir --console --icon "P:/D/test/Por/Zuna-Mail-Scraper/ico.ico" --add-data "P:/D/test/Por/Zuna-Mail-Scraper -;Zuna-Mail-Scraper -/"  "P:/D/test/Por/Zuna-Mail-Scraper/example_azure.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onedir --console --icon P:/D/test/Por/Zuna-Mail-Scraper/ico.ico --add-data P:/D/test/Por/Zuna-Mail-Scraper -;Zuna-Mail-Scraper -/ P:/D/test/Por/Zuna-Mail-Scraper/example_azure.py --distpath C:\Users\jamu\AppData\Local\Temp\tmpakt8x1hc\application --workpath C:\Users\jamu\AppData\Local\Temp\tmpakt8x1hc\build --specpath C:\Users\jamu\AppData\Local\Temp\tmpakt8x1hc

190534 INFO: PyInstaller: 5.4.1
190536 INFO: Python: 3.10.7
190560 INFO: Platform: Windows-10-10.0.19044-SP0
190564 INFO: wrote C:\Users\jamu\AppData\Local\Temp\tmpakt8x1hc\example_azure.spec
190569 INFO: UPX is not available.
190601 INFO: Extending PYTHONPATH with paths
['P:\\D\\test\\Por\\Zuna-Mail-Scraper']
192354 INFO: checking Analysis
192356 INFO: Building Analysis because Analysis-00.toc is non existent
192370 INFO: Initializing module dependency graph...
192390 INFO: Caching module graph hooks...
192418 WARNING: Several hooks defined for module 'numpy'. Please take care they do not conflict.
192459 INFO: Analyzing base_library.zip ...
195082 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
195281 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
198389 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
201753 INFO: Caching module dependency graph...
201931 INFO: running Analysis Analysis-00.toc
201965 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\jamu\AppData\Local\Programs\Python\Python310\python.exe
202050 INFO: Analyzing P:\D\test\Por\Zuna-Mail-Scraper\example_azure.py
202904 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
206110 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
211112 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
212883 INFO: Processing pre-safe import module hook six.moves from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
213595 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
213771 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
214266 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
214875 INFO: Loading module hook 'hook-lxml.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
216645 INFO: Loading module hook 'hook-gevent.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...

I did it serveral Times before too and it worked. But now it isnt working anymore. pls help ;)

**Comment by brentvollebregt** [comment]
Looks very similar to #162 and #185.

I just [found this question on SO](https://stackoverflow.com/questions/67256860/auto-py-to-exe-stuck-at-loading-module-hook-hook-gevent-py) - do any of these answers work for you?

**Comment by Yoko11111111** [comment]
No it doesnt

**Comment by brentvollebregt** [comment]
@Yoko11111111 are you able to provide a minimal reproducible example?

**Comment by Yoko11111111** [comment]
> @Yoko11111111 are you able to provide a minimal reproducible example?

I already described what i did above

**Comment by brentvollebregt** [comment]
Ok then, based on what you have given (and I have filled in the blanks with what is easiest):

Python version: 3.9.9
auto-py-to-exe version: 2.26.1

My Python script `343-example.py`:

```python
print ('Works')
```

Command displayed in the UI:

```
pyinstaller --noconfirm --onedir --console --icon "C:/Users/Brent/Pictures/Icons/PythonIcon.ico" --add-data "C:/DemoFiles;DemoFiles/"  "C:/Users/Brent/Downloads/343-example.py"
```

After clicking the convert button, there were no issues and the output exe ran as expected.

Unfortunately I'm unable to reproduce your situation (based on your "minimal reproducible example") so cannot offer any assistance.

**Comment by Yoko11111111** [comment]
Probably some Module or something like that isnt supported?

**Comment by Yoko11111111** [comment]
import ctypes

import requests
from bs4 import BeautifulSoup
import random
from fake_useragent import UserAgent
import user_agent
import re
import time
import os
import json
import csv
from licensing.models import *
from licensing.methods import Key, Helpers
from colorama import Fore

import config

from keyauth import api

import sys
import time
import platform
import os
import hashlib
from time import sleep
from datetime import datetime
from colorama import Fore

**Comment by brentvollebregt** [comment]
[_Minimal reproducible example_](https://en.wikipedia.org/wiki/Minimal_reproducible_example) please

**Comment by Yoko11111111** [comment]
Brother i cant send u the whole thing its like 400 lines

**Comment by brentvollebregt** [comment]
I agree, a minimal reproducible example shouldn't be 400 lines - remove stuff to find the root cause to identify what to put into the minimal reproducible example.
