### ISSUE TITLE
[Suggestion] 'Open Output Folder' button could focus output file or folder

### ISSUE THREAD

**Issue by sunflyfairy** [brentvollebregt/auto-py-to-exe#344]
When I press the 'Open Output Folder' button ,I suggest that the file or folder  just created  can be  selected, the normal code is like below.
```
            import os
            filepath = r"C:\Users\user_name\Desktop\python\pythonProject\output\project_name"
            folder = os.path.dirname(filepath)
            filename = filepath.split('\\')[-1]
            os.popen("explorer /select," + folder + "\\" + filename)
```

**Comment by brentvollebregt** [comment]
Which input does this relate to? These buttons usually help you find your data and files - making it create folders for you seems a bit pointless? Maybe I'm thinking about this the wrong way.

**Comment by sunflyfairy** [comment]
After it create a  file or folder, the button  'Open Folder' can open the output folder, but  it will not activate output folder and select the file or folder just created. If you modify the code like above, it will do that. It will a bit convenient when there are many files in the folder.

**Comment by brentvollebregt** [comment]
Your issue description first said "Open Folder" and now says "Open Output Folder" - this is very confusing. Are you able to add a screenshot with the button you are talking about circled please?

**Comment by sunflyfairy** [comment]
![image](https://user-images.githubusercontent.com/87637658/208796587-eb024756-404b-492f-a8ac-869f225ba773.png)
I'm sorry, I made a mistake at first time. it's this button as above. when I press the button, the output folder will not activate.
It's just my suggest, thanks.

**Comment by brentvollebregt** [comment]
Are you saying the output folder that this button typically opens is not being created after your script is packaged?

**Comment by sunflyfairy** [comment]
The code in utils.py line 31 is :  **os.startfile(folder_directory, 'explore')**
   My suggestion is : 

`            folder = os.path.dirname(folder_directory)
            filename = folder_directory.split('\\')[-1]
            os.popen("explorer /select," + folder + "\\" + filename) `

**Comment by brentvollebregt** [comment]
@sunflyfairy that is not compatible with Mac or Linux.

**Comment by sunflyfairy** [comment]
Can you only modify it on windows?
I see you have a judge on line 30.

**Comment by brentvollebregt** [comment]
I'm starting to see the issue here - is that button not working for you at all? When pressing it, it should open the output directory which was created automatically (if the button is showing).

What OS are you on? Potentially this only works on Windows now that I look at the docs.

**Comment by sunflyfairy** [comment]
I use win10 and it works well. when you press the buttton, it will open the folder , but **the folder wonn't  be activated.**
If you can modify it as my code in windows, the output folder will activate and the folder you created will be selected.

**Comment by brentvollebregt** [comment]
What do you mean it won't be "activated"? You mean the file explorer window will not open? You just said it works well on Windows so I'm confused.

**Comment by sunflyfairy** [comment]
It can open the output folder, but it is not the currently activate window.

**Comment by brentvollebregt** [comment]
I see, so when you press the "Open Output Folder" button, it opens a windows explorer window in the correct directory but it's not focused? (I assume the opened window is flashing in the taskbar). Is this the issue?

**Comment by sunflyfairy** [comment]
Yes, it's the issue. And if there are many folders or files in the output Folder, I will cost a few minutes to find the one just created.

**Comment by brentvollebregt** [comment]
> Yes, it's the issue

If the explorer window isn't focused, Windows will flash its icon yellow on the taskbar by default. You can click on the taskbar item and the folder will be open.

> And if there are many folders or files in the output Folder, I will cost a few minutes to find the one just created.

This sounds like a completely different issue? You want the output file or folder to be highlighted when the Windows explorer window is opened?

Always happy to look at a PR with your recommended fix 👍

**Comment by sunflyfairy** [comment]
You can test my code, then you will see the effect.
Thanks for your feedback.

**Comment by brentvollebregt** [comment]
I have created the branch [feature/344-highlight-output-file-in-windows](https://github.com/brentvollebregt/auto-py-to-exe/tree/feature/344-highlight-output-file-in-windows) with the changes. Pull that down, run it and see if it does what you're expecting.

**Comment by brentvollebregt** [comment]
@sunflyfairy did the changes do what you expected? If so, I can merge them in for everyone.

**Comment by sunflyfairy** [comment]
Thanks, I just got back to the office today. I download the #344,then the  program is not responding.
![image](https://user-images.githubusercontent.com/87637658/218613957-98ce609c-17c3-4a4e-b4cd-65eadef63236.png)

**Comment by brentvollebregt** [comment]
Two days that branch would have worked but now is facing the same issue as https://github.com/brentvollebregt/auto-py-to-exe/issues/364.

I have just rebased the branch to include the fix.

**Comment by sunflyfairy** [comment]
I have just tested it. It is just what I want, thanks.

**Comment by brentvollebregt** [comment]
This was added in v2.30.0 within 6df771eb8e4a104bab25337e0628ae53c0352ffe
