### ISSUE TITLE
A Chinese translation error

### ISSUE THREAD

**Issue by Melendez1209** [brentvollebregt/auto-py-to-exe#345]
# A Chinese translation error
![image](https://user-images.githubusercontent.com/92637479/208924206-f27a084f-052b-47ad-b6f4-e04dcc6f8e2d.png)

all right, I admit it's a I admit that this is not an urgent, important Bug Report.

However, the Chinese translation has a problem here, the correct translation should be "语言". By the way, I couldn't find a file to store the language, so I'm writing this Issue, but I would prefer to go ahead and submit a PR and join the development of this project.

**Comment by Melendez1209** [comment]
all right, I admit that this is not an urgent, important Bug Report.


My English is wrong, too😅

**Comment by brentvollebregt** [comment]
Thanks for pointing this out - do you want to make the fix so your name is by it? The reference for this is at [i18n.js:25](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/auto_py_to_exe/web/js/i18n.js#L25)

**Comment by Melendez1209** [comment]
What I don't understand is why the file is named this, if it were me, I would probably name it "Translation".

**Comment by Melendez1209** [comment]
I would do that.

**Comment by brentvollebregt** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Internationalization_and_localization):

> In computing, internationalization and localization (American) or internationalisation and localisation (British English), often abbreviated **i18n** ...

"i18n" is just a convention.

**Comment by Melendez1209** [comment]
all right.
