### ISSUE TITLE
Error accessing the database (sqlite) after converting py to exe

### ISSUE THREAD

**Issue by supernooba** [brentvollebregt/auto-py-to-exe#35]
I've tried converting my py script (with a database that contains username and password), it runs however, it's not able to access the database. I tried both options in converting either the 'one directory' or 'one file'  but to no avail.

Can you please advise workaround? thank you very much

**Comment by brentvollebregt** [comment]
Did you add the database in the additional files section?

**Comment by brentvollebregt** [comment]
This doesn't show much, you need proof of why it isn't working. Try debugging the application, output is still printed to stdout. You can read my small tutorial on debugging in my post on [Issues When Using auto-py-to-exe](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/).

**Comment by brentvollebregt** [comment]
Closing due to no reply from @supernooba
