### ISSUE TITLE
auto-py-to-exe : 无法将“auto-py-to-exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。

### ISSUE THREAD

**Issue by cancundeyingzi** [brentvollebregt/auto-py-to-exe#352]
PS D:\py\面向对象class> pip install auto-py-to-exe
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: auto-py-to-exe in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (2.17.0)
Requirement already satisfied: Eel==0.12.4 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from auto-py-to-exe) (0.12.4)
Requirement already satisfied: pyinstaller>=4.6 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from auto-py-to-exe) (5.1)
Requirement already satisfied: whichcraft in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from Eel==0.12.4->auto-py-to-exe) (0.6.
1)
Requirement already satisfied: future in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from Eel==0.12.4->auto-py-to-exe) (0.18.2)
Requirement already satisfied: bottle in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from Eel==0.12.4->auto-py-to-exe) (0.12.19)

Requirement already satisfied: bottle-websocket in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from Eel==0.12.4->auto-py-to-exe)
 (0.2.9)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller
>=4.6->auto-py-to-exe) (2022.2)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-py-to
-exe) (2021.9.3)
Requirement already satisfied: altgraph in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-py-to-exe) (0
.17.2)
Requirement already satisfied: setuptools in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-py-to-exe)
(60.9.3)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-
py-to-exe) (0.2.0)
Requirement already satisfied: gevent-websocket in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from bottle-websocket->Eel==0.12.
4->auto-py-to-exe) (0.10.1)
Requirement already satisfied: gevent in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent-websocket->bottle-websocket->Ee
l==0.12.4->auto-py-to-exe) (21.12.0)
Requirement already satisfied: cffi>=1.12.2 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent->gevent-websocket->bottle
-websocket->Eel==0.12.4->auto-py-to-exe) (1.15.0)
Requirement already satisfied: greenlet<2.0,>=1.1.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent->gevent-websocket
->bottle-websocket->Eel==0.12.4->auto-py-to-exe) (1.1.2)
Requirement already satisfied: zope.event in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent->gevent-websocket->bottle-w
ebsocket->Eel==0.12.4->auto-py-to-exe) (4.5.0)
Requirement already satisfied: zope.interface in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent->gevent-websocket->bott
le-websocket->Eel==0.12.4->auto-py-to-exe) (5.4.0)
Requirement already satisfied: pycparser in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.12.2->gevent->gevent-websoc
ket->bottle-websocket->Eel==0.12.4->auto-py-to-exe) (2.21)
WARNING: There was an error checking the latest version of pip.
PS D:\py\面向对象class> auto-py-to-exe
auto-py-to-exe : 无法将“auto-py-to-exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ auto-py-to-exe
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (auto-py-to-exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

python3.10

**Comment by cancundeyingzi** [comment]
Microsoft Windows [版本 10.0.22622.290]
(c) Microsoft Corporation。保留所有权利。

C:\Users\ASUS>pip install auto-py-to-exe
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: auto-py-to-exe in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (2.17.0)
Requirement already satisfied: pyinstaller>=4.6 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from auto-py-to-exe) (5.1)
Requirement already satisfied: Eel==0.12.4 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from auto-py-to-exe) (0.12.4)
Requirement already satisfied: bottle-websocket in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from Eel==0.12.4->auto-py-to-exe) (0.2.9)
Requirement already satisfied: bottle in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from Eel==0.12.4->auto-py-to-exe) (0.12.19)
Requirement already satisfied: whichcraft in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from Eel==0.12.4->auto-py-to-exe) (0.6.1)
Requirement already satisfied: future in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from Eel==0.12.4->auto-py-to-exe) (0.18.2)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-py-to-exe) (0.2.0)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-py-to-exe) (2022.2)
Requirement already satisfied: altgraph in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-py-to-exe) (0.17.2)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-py-to-exe) (2021.9.3)
Requirement already satisfied: setuptools in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller>=4.6->auto-py-to-exe) (60.9.3)
Requirement already satisfied: gevent-websocket in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from bottle-websocket->Eel==0.12.4->auto-py-to-exe) (0.10.1)
Requirement already satisfied: gevent in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent-websocket->bottle-websocket->Eel==0.12.4->auto-py-to-exe) (21.12.0)
Requirement already satisfied: cffi>=1.12.2 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent->gevent-websocket->bottle-websocket->Eel==0.12.4->auto-py-to-exe) (1.15.0)
Requirement already satisfied: greenlet<2.0,>=1.1.0 in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent->gevent-websocket->bottle-websocket->Eel==0.12.4->auto-py-to-exe) (1.1.2)
Requirement already satisfied: zope.event in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent->gevent-websocket->bottle-websocket->Eel==0.12.4->auto-py-to-exe) (4.5.0)
Requirement already satisfied: zope.interface in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from gevent->gevent-websocket->bottle-websocket->Eel==0.12.4->auto-py-to-exe) (5.4.0)
Requirement already satisfied: pycparser in c:\users\asus\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.12.2->gevent->gevent-websocket->bottle-websocket->Eel==0.12.4->auto-py-to-exe) (2.21)
WARNING: There was an error checking the latest version of pip.

C:\Users\ASUS>auto-py-to-exe
'auto-py-to-exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\ASUS>

**Comment by cancundeyingzi** [comment]
解决办法,手动打开exe

**Comment by brentvollebregt** [comment]
Your scripts folder should be in the PATH environment variable so the command line can find the .exe file - this goes for any Python package that has associated executables.

**Comment by cancundeyingzi** [comment]
> 您的脚本文件夹应位于 PATH 环境变量中，以便命令行可以找到.exe文件 - 这适用于具有关联可执行文件的任何 Python 包。

I was able to use it normally before, but I don't know why it suddenly failed today (yesterday), but now it has been solved, thanks!
