### ISSUE TITLE
Problem Getting Spacy module to load

### ISSUE THREAD

**Issue by springuistics** [brentvollebregt/auto-py-to-exe#353]
Hi, the code works very well, but I'm running into one problem.

My program uses SpaCy which requires a NLP module. It seems that auto-py-to-exe is not including this module as I run into the error "Cannot find module 'en_core_web_lg'" (en_core_web_lg is the NLP module it requires). I tried adding this to the "collect-submodules" tab as well as the hidden-import, but no dice. 

Has anyone else had the same problem and/or does anyone have any advice on how to solve?

Thanks

**Comment by brentvollebregt** [comment]
I searched in Google for "pyinstaller en_core_web_lg" and found this issue on GitHub: https://github.com/explosion/spaCy/issues/3831. It appears this issue can be fixed with a [PyInstaller hook](https://pyinstaller.org/en/stable/hooks.html).
