### ISSUE TITLE
unhandle python exception and that shutdown when running this exe

### ISSUE THREAD

**Issue by Ann-b17051106** [brentvollebregt/auto-py-to-exe#356]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package 

**Describe the bug**
The exe can open normally，but the part with win32com.client import Dispatch can run something correct,but the window will shutdown unnormally.All those problems are not exsits on running .py file
The console window show "unhandle python exception" and shutdown imediately.
The GUI used is PyQt5.
**To Reproduce**

> If you have example code, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

My pyinstaller command is "pyinstaller --icon "icon_file_path" -D .\AutoOperate.py"

**Expected behavior**
When i run this part this window not be shutdown and that i can run another part of this exe.

**Your Environment:**
- Python version (`python --3.8`):
- auto-py-to-exe version (`2.26.1`):
- PyInstaller version (`Version: 5.7.0`):
- Eel version (`Version: 0.14.0`): 

**Additional context (optional)**

**Comment by brentvollebregt** [comment]
Thank for reporting this, are you able to supply a minimal reproducable example for the reproduction steps? This will help me see what's going on.

**Comment by Ann-b17051106** [comment]
Thanks for replying me, I find the point.This problem due to all excels should be added including  the excels are create by exe.

**Comment by brentvollebregt** [comment]
Can this issue be closed then?

**Comment by Ann-b17051106** [comment]
Yes，thanks a lot！
