### ISSUE TITLE
Tensorflow error when executing

### ISSUE THREAD

**Issue by jsgaston** [brentvollebregt/auto-py-to-exe#357]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package 

**Describe the bug**
The exe doesnt run (gives an error with Tensorflow module)

**To Reproduce**

```python
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.models import *
from keras.layers import *
print('Tensorflow version: {}'.format(tf.__version__))

import matplotlib.pyplot as plt
#plt.style.use('seaborn')

import warnings
warnings.filterwarnings('ignore')

import yfinance as yf
import datetime as dt

os.system("pause")
```

**Expected behavior**
No error should appear

**Screenshots (optional)**

**Your Environment:**
- Python version 3.9
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.28.0
- PyInstaller version (`pip show pyinstaller`): 5.7.0
- Eel version (`pip show eel`): 22.3.1

**Additional context (optional)**
callected all modules

**Comment by brentvollebregt** [comment]
Please fill out the template - you haven't even said what your issue is!

**Comment by brentvollebregt** [comment]
> the example code is sufficient to see the error with tensorflow when running execute.

Sufficient code is not what I'm looking for, we need a minimal reproducible example to potentially identify the library that is causing the issue - are things like `warnings` and `datetime` really needed?

Also, your description of the error still says "The exe doesnt run (gives an error with Tensorflow module)" - can you please supply the error you are getting?
