### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jsgaston** [brentvollebregt/auto-py-to-exe#358]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package 

**Describe the bug**
I run the exe and this error appears, and after that the cmd closes.

**To Reproduce**
![error](https://user-images.githubusercontent.com/69969971/215605952-c01faaa2-519a-417b-a740-13e555388e42.jpg)

1. Go to '...' the exe file, and run it
![added](https://user-images.githubusercontent.com/69969971/215610418-ec6617b1-70dc-4224-b32e-59c96cc2bd7c.jpg)

> If you have example code, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

```python
# libraries for webscraping, parsing and getting stock data
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
import yfinance as yf
import time

# for plotting and data manipulation
import pandas as pd
import matplotlib.pyplot as plt
import plotly
import plotly.express as px

# NLTK VADER for sentiment analysis
import nltk
from nltk import *
nltk.downloader.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# for getting current date and time to print 'last updated'
from datetime import datetime


# Get All Tickers from Dow Jones Index
df_dow_jones = pd.read_html("https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average")[1]
tickers = df_dow_jones['Symbol'].tolist()
print("tickers",tickers)
# Scrape the Date, Time and News Headlines Data
finwiz_url = 'https://finviz.com/quote.ashx?t='
news_tables = {}
```

**Expected behavior**
again, error when running the executable

**Screenshots (optional)**
image (that is what I  see (error) when running the executable)

**Your Environment:**
- Python version (`python --version`):3.9.13
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.28.0
- PyInstaller version (`pip show pyinstaller`):5.7.0
- Eel version (`pip show eel`): 0.14.0

**Additional context (optional)**
Please help, I have many errors in the executable with lots of .py that don't get error when running.

**Comment by brentvollebregt** [comment]
Again, can you please provide a [**minimal reproducible example**](https://stackoverflow.com/help/minimal-reproducible-example), I imagine a lot of your source code provided is not needed to reproduce the error.

Take a look at https://github.com/vaexio/vaex/issues/1823 - adding the hook `hook-frozendict.py` might help you fix your issue. I found this by searching "pyinstaller no such file or directory frozendict VERSION" in Google - they have a similar issue.

> hook-frozendict.py:
> 
> ```python
> from pathlib import Path
> import frozendict
> 
> datas = [(Path(frozendict.__path__[0]) / 'VERSION', 'frozendict')]
> ```
