### ISSUE TITLE
Project output will not be moved to output

### ISSUE THREAD

**Issue by SwezyTryhard** [brentvollebregt/auto-py-to-exe#359]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package 

**Describe the bug**
A clear and concise description of what the bug is. If you have an error message, please paste it here (not in a screenshot).

**To Reproduce**
Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):

```python
# If you have example code, please provide a minimal reproducible example: 
# https://stackoverflow.com/help/minimal-reproducible-example

print("Hello World")
```

**Expected behavior**

**Your Environment:**
- Python version (`python --version`):
- auto-py-to-exe version (`pip show auto-py-to-exe`):
- PyInstaller version (`pip show pyinstaller`):
- Eel version (`pip show eel`):

**Comment by SwezyTryhard** [comment]
Error : Project output will not be moved to output folder
           Complete.

**Comment by brentvollebregt** [comment]
Please fill out the template and make sure to read the help post
