### ISSUE TITLE
Script with external libraries 

### ISSUE THREAD

**Issue by NightmareLele135** [brentvollebregt/auto-py-to-exe#36]

**Comment by NightmareLele135** [comment]
i'm trying to convert a file but i've got some external libraries and some of these need some files so i add them to the part of the converter in which you add other files but when i open the  file converted it closes themself automatically. Please help me!

**Comment by brentvollebregt** [comment]
Did you read the [help post linked in the readme](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/)?

**Comment by brentvollebregt** [comment]
Closed due to no response from @NightmareLele135
