### ISSUE TITLE
error when running the executable

### ISSUE THREAD

**Issue by jsgaston** [brentvollebregt/auto-py-to-exe#361]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package 

**Describe the bug**
I added many libraries to collect all, and processed to do the conversion with autopy, but when runing the exe, an error appears, and the webbrowser app doesnt show what's suposed (image of the error)

**To Reproduce**
Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):
1. Go to '...' run the program and the error will appear

```python
############################################### tabs
from ast import Return
from cgitb import text

from enum import auto
from fileinput import filename
from operator import index
from pdb import Restart
import time

from typing import Text
import dash
import dash_bootstrap_components as dbc
import numpy as np
import plotly.graph_objs as go
from dash import Input, Output, dcc, html
###################################################clusters

import pandas as pd
import plotly.graph_objs as go

from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
#################################################del appv2
# -*- coding: utf-8 -*-
from genericpath import exists
from itertools import count
from re import X
from turtle import color
#from typing_extensions import assert_type
import pandas as pd
import numpy as np
from pandas import DataFrame
#from DataFrame import iloc

import pylab
from statsmodels.graphics.gofplots import qqplot
import statsmodels.api as sm
import math

import plotly.express as px
import plotly.graph_objects as go

from statsmodels.graphics.gofplots import qqplot_2samples
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

from dash import Dash, dcc, html, Input, Output
from sklearn.model_selection import train_test_split
from sklearn import linear_model, tree, neighbors
from sklearn import metrics, datasets
import dash
from dash import dcc, Dash, dash_table
from dash import html
from dash.dependencies import Input, Output

import plotly.figure_factory as ff

from csv import reader
# Tratamiento de datos
# ==============================================================================
# Gráficos
# ==============================================================================
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns

# Preprocesado y análisis
# ==============================================================================
import statsmodels.api as sm
#from slider import transform_value

# Configuración matplotlib
# ==============================================================================


# Configuración warnings
# ==============================================================================
import warnings
warnings.filterwarnings('ignore')
#####################################################################
######################################################################
import dash
from dash.dependencies import Input, Output, State
import dash_html_components as html
from dash import html
from dash import dcc, html, dash_table, callback, Dash
#####################################################################
import plotly.io as pio
pio.templates
################################################################
import sys
#############################################################
import dash

import pandas as pd
import plotly.graph_objs as go
from dash import Input, Output, dcc, html
from sklearn import datasets
from sklearn.cluster import KMeans

import base64


##############################################################################
from sklearn.neighbors import NearestCentroid
################################################data
from dash import dcc
import io
##########################################montecarlo
import random
################################################data
from sklearn.neighbors import KNeighborsRegressor
####################################################


import base64
import datetime
import io

import dash
from dash.dependencies import Input, Output, State
from dash import dcc, html, dash_table

import pandas as pd

from dash.exceptions import PreventUpdate
from collections import OrderedDict

import webbrowser
from threading import Timer

from statistics import mean
from pathlib import Path
import frozendict



print("Hello World")
```

**Expected behavior**
it should open correctly a plotlydashboard

**Your Environment:**
- Python version (`python --version`): 3.9.13
- auto-py-to-exe version (`pip show auto-py-to-exe`):2.28
- PyInstaller version (`pip show pyinstaller`):5.7.0
- Eel version (`pip show eel`): 0.14.0
![error autopy](https://user-images.githubusercontent.com/69969971/216905925-5d49df95-c16e-438c-8520-735400d7f0ff.png)

**Comment by brentvollebregt** [comment]
Can you please make that code in the reproduction steps a minimal reproducible example. There is a significant amount of imports in there which just make things cloudy to identify what library may be causing the issue.

**Comment by brentvollebregt** [comment]
> but the app uses all those libraries

I understand that, but this is why you make a minimal reproducible example - to identify where the cause is.

You also haven't given reproduction steps - it would be awesome to have these after you provide a minimal reproducible example otherwise we might each get different results.

**Comment by brentvollebregt** [comment]
> sorry ... I can't do a minimal reproducible coz its 7 thousand lines of code ... and if the problem is inside the code ... don't know where .... It might be in one of the modules (its usually that.

That's the point of a minimal reproducible example - you break it down to find the culprit. Then you know where the issue lies and how I can reproduce it, rather than me executing 82 import statements (many of which are duplicated).

> Have you tried making exe those modules?

No, I have not. I'm sorry, but I'm not bundling a dump of the import sections of all your application's files - you need to put some effort in on your side to make me help you easier.

> (when starting it again now: the web browser showed a full page in black with something like a button at one side ... very wierd coz I dont have this in my dashboard == app)

Did you change nothing and get a different result when running the exe?

**Comment by Dattebayooooo** [comment]
> I added all modules and let the cmd promt. And with this, the app worked in exe.

Hi, Can you please share the cli generated command, I have been facing issue to generate **exe**
