### ISSUE TITLE
Module Not Found Error 

### ISSUE THREAD

**Issue by SwezyTryhard** [brentvollebregt/auto-py-to-exe#363]
After convert to exe it says-> ModuleNotFoundError: No module named 'httpx'

**Comment by brentvollebregt** [comment]
Have you read the help post before creating this issue? 

I talk about how to fix this misconfiguration or environment issue athttps://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#modulenotfounderror-no-module-named-x-importerror-no-module-named-x
