### ISSUE TITLE
Info - Updated german translation

### ISSUE THREAD

**Issue by ackhh** [brentvollebregt/auto-py-to-exe#366]
Hi,

I have updated the german translation and submitted a pull request. Hopefully I did everything right - this is the very first time I have done this.

After submitting I noticed a typo I've made. "Augabeverzeichnis" should read "Ausgabeverzeichnis" but I don't know how to edit my translation. Sorry for any inconvenience.

Regards - AcK

P.S: also, the label was not meant to be "bug"

**Comment by brentvollebregt** [comment]
All good, I can sort that for you in #365 👌

**Comment by brentvollebregt** [comment]
I've made then change, is in the PR now 🏄
