### ISSUE TITLE
pywin32-ctypes error

### ISSUE THREAD

**Issue by jman13378** [brentvollebregt/auto-py-to-exe#367]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package 

**Describe the bug**
`pywin32-ctypes` needing to be installed when it already is which is preventing me from using autopytoexe

**To Reproduce**
1. install auto-py-to-exe pyinstaller and pywin32-ctypes
2. open cmd
3. run `auto-py-to-exe`
4. get the error 

**Error**
```diff
C:\Users\jonah>auto-py-to-exe
PyInstaller cannot check for assembly dependencies.
Please install pywin32-ctypes.

pip install pywin32-ctypes

```
**Python**
```python
# If you have example code, please provide a minimal reproducible example: 
# https://stackoverflow.com/help/minimal-reproducible-example

print("Hello World")
```

**Expected behavior**
open the gui
**Your Environment:**
- Python version (`python --version`): 3.11.0
- auto-py-to-exe version (`pip show auto-py-to-exe`):2.30.0
- PyInstaller version (`pip show pyinstaller`):5.8.0
- Eel version (`pip show eel`): 0.14.0

**Comment by brentvollebregt** [comment]
Could you execute the following in powershell and let me know what each line returns (individually - not all together),

```powershell
> where auto-py-to-exe
> where pip
> where python
> pip show auto-py-to-exe
> pip show pyinstaller
> pip show pywin32-ctypes
```

This is to help me check your environment.

Also, have you tried using a virtual environment? If that works, it will immediately point to your environment being the issue.

**Comment by jman13378** [comment]
Hello! i have installed the modules on another computer and it works fine but i get an error about not having modules although it used to work on this other computer

**Comment by brentvollebregt** [comment]
Have you followed the debugging steps I the help post? If so, what error are you seeing?

**Comment by bwheatl** [comment]
I also started having a problem with win32gui and auto-py-to-exe today. When I run auto-py-to-exe i get an error message module win32gui not found. I have run auto-py-to-exe with this code probably 30 times and never had an issue until today.  Thinking about what has changed lately and the only change is I updated Pycharm. JMan13378 are you by any chance using Pycharm?

**Comment by jman13378** [comment]
nope I use VSCode

**Comment by jman13378** [comment]
> Could you execute the following in powershell and let me know what each line returns (individually - not all together),
> 
> ```powershell
> > where auto-py-to-exe
> > where pip
> > where python
> > pip show auto-py-to-exe
> > pip show pyinstaller
> > pip show pywin32-ctypes
> ```
> 
> This is to help me check your environment.
> 
> Also, have you tried using a virtual environment? If that works, it will immediately point to your environment being the issue.

I'll do this when i get home I've been busy

**Comment by bwheatl** [comment]
where auto-py-to-exe where command not working I used gcm (get command)
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     auto-py-to-exe.exe                                 0.0.0.0    C:\Users\bwhea\AppData\Local\Programs\...



gcm pip

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pip.exe                                            0.0.0.0    C:\Users\bwhea\AppData\Local\Programs\...


gcm python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         3.11.11... C:\Users\bwhea\AppData\Local\Programs\...

pip show auto-py-to-exe

Name: auto-py-to-exe
Version: 2.31.1
Summary: Converts .py to .exe using a simple graphical interface.
Home-page: https://github.com/brentvollebregt/auto-py-to-exe
Author: Brent Vollebregt
Author-email: ***@***.***
License: MIT
Location: C:\Users\bwhea\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: Eel, pyinstaller
Required-by:


pip show pyinstaller
Name: auto-py-to-exe
Version: 2.31.1
Summary: Converts .py to .exe using a simple graphical interface.
Home-page: https://github.com/brentvollebregt/auto-py-to-exe
Author: Brent Vollebregt
Author-email: ***@***.***
License: MIT
Location: C:\Users\bwhea\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: Eel, pyinstaller
Required-by:
PS C:\> pip show pyinstaller
Name: pyinstaller
Version: 5.8.0
Summary: PyInstaller bundles a Python application and all its dependencies into a single package.
Home-page: https://www.pyinstaller.org/
Author: Hartmut Goebel, Giovanni Bajo, David Vierra, David Cortesi, Martin Zibricky
Author-email:
License: GPLv2-or-later with a special exception which allows to use PyInstaller to build and distribute non-free programs (including commercial ones)
Location: C:\Users\bwhea\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: altgraph, pefile, pyinstaller-hooks-contrib, pywin32-ctypes, setuptools
Required-by: auto-py-to-exe

pip show pywin32-ctypes
Name: pywin32-ctypes
Version: 0.2.0
Summary: UNKNOWN
Home-page: https://github.com/enthought/pywin32-ctypes
Author: Enthought Inc
Author-email: ***@***.***
License: BSD
Location: C:\Users\bwhea\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires:
Required-by: pyinstaller


Barre' Wheatley
Emerging Technology Coordinator
Cal Farley's Boys Ranch
W - 806-533-1342
C - 806-681-4716

http://www.calfarley.org<http://www.calfarley.org/>

________________________________

**Comment by bwheatl** [comment]
The problem is not Auto-Py-To-Exe. I am getting the same error when I try to execute the program from the windows command prompt.

**Comment by brentvollebregt** [comment]
@bwheatl are you able to get the "Source" values of those gcm commands? Ideally if they aren't under `C:\Users\AppData\Local\Programs\Python\Python311` (especially auto-py-to-exe), it will point to an environment issue.

I recommend using a virtual environment if you are facing something like this - typically this will line everything back up.

**Comment by jman13378** [comment]
> Could you execute the following in powershell and let me know what each line returns (individually - not all together),
> 
> ```powershell
> > where auto-py-to-exe
> > where pip
> > where python
> > pip show auto-py-to-exe
> > pip show pyinstaller
> > pip show pywin32-ctypes
> ```
> 
> This is to help me check your environment.
> 
> Also, have you tried using a virtual environment? If that works, it will immediately point to your environment being the issue.
D:\ripo\Scripts\auto-py-to-exe.exe
D:\ripo\Scripts\pip.exe
D:\ripo\python.exe
```
C:\Users\jonah>pip show auto-py-to-exe
Name: auto-py-to-exe
Version: 2.30.0
Summary: Converts .py to .exe using a simple graphical interface.
Home-page: https://github.com/brentvollebregt/auto-py-to-exe
Author: Brent Vollebregt
Author-email: brent@nitratine.net
License: MIT
Location: D:\ripo\Lib\site-packages\auto_py_to_exe-2.30.0-py3.11.egg
Requires: Eel, pyinstaller
Required-by:
```
```
C:\Users\jonah>pip show pyinstaller
Name: pyinstaller
Version: 5.8.0
Summary: PyInstaller bundles a Python application and all its dependencies into a single package.
Home-page: https://www.pyinstaller.org/
Author: Hartmut Goebel, Giovanni Bajo, David Vierra, David Cortesi, Martin Zibricky
Author-email:
License: GPLv2-or-later with a special exception which allows to use PyInstaller to build and distribute non-free progra
ms (including commercial ones)
Location: D:\ripo\Lib\site-packages
Requires: altgraph, pefile, pyinstaller-hooks-contrib, pywin32-ctypes, setuptools
Required-by: auto-py-to-exe
```
```
Name: pywin32-ctypes
Version: 0.2.0
Summary: UNKNOWN
Home-page: https://github.com/enthought/pywin32-ctypes
Author: Enthought Inc
Author-email: info@enthought.com
License: BSD
Location: D:\ripo\Lib\site-packages
Requires:
Required-by: pyinstaller
```

**Comment by brentvollebregt** [comment]
@jman13378 interesting, all the dependencies appear that they're in the same directory.

Do you still see the same when executing the following:
1. `python -m pip show pywin32-ctypes`: The same output as above?
2. `python -m auto_py_to_exe`: The same error as in your report?

Have you also managed to try using a virtual environment? Typically that will solve these types of errors.

**Comment by brentvollebregt** [comment]
I can't quite see why this isn't working - there must be something else at play. Could you try using a virtual environment on that machine?

**Comment by jman13378** [comment]
i tried on a vm and it's still having this issue

**Comment by brentvollebregt** [comment]
Could you try using a virtual environment (not a virtual machine):

1. Create a virtual environment: `python -m venv .venv`
2. Activate the Python venv: `.venv/Scripts/activate.ps1` (may need to change depending on the terminal you are using)
3. Validate virtual env Python is being used: `where python` (top .exe location should be in the .venv folder)
4. Install auto-py-to-exe: `pip install auto-py-to-exe`
5. Validate correct auto-py-to-exe is available: `where auto-py-to-exe` (top .exe location should be in the .venv folder)
6. Run auto-py-to-exe: `auto-py-to-exe`

**Comment by jman13378** [comment]
```
Microsoft Windows [Version 10.0.19045.2846]
(c) Microsoft Corporation. All rights reserved.

C:\Users\jonah\.venv\Scripts>Activate.ps1

C:\Users\jonah\.venv\Scripts>Activate.ps1

C:\Users\jonah\.venv\Scripts>Activate

(.venv) C:\Users\jonah\.venv\Scripts>where python
C:\Users\jonah\.venv\Scripts\python.exe
D:\ripo\python.exe
D:\msys64\mingw64\bin\python.exe

(.venv) C:\Users\jonah\.venv\Scripts>pip install auto-py-to-exe
Requirement already satisfied: auto-py-to-exe in d:\ripo\lib\site-packages (2.32.0)
Requirement already satisfied: Eel==0.14.0 in d:\ripo\lib\site-packages (from auto-py-to-exe) (0.14.0)
Requirement already satisfied: pyinstaller>=5.8.0 in d:\ripo\lib\site-packages (from auto-py-to-exe) (5.8.0)
Requirement already satisfied: bottle in d:\ripo\lib\site-packages (from Eel==0.14.0->auto-py-to-exe) (0.12.23)
Requirement already satisfied: bottle-websocket in d:\ripo\lib\site-packages (from Eel==0.14.0->auto-py-to-exe) (0.2.9)
Requirement already satisfied: future in d:\ripo\lib\site-packages (from Eel==0.14.0->auto-py-to-exe) (0.18.2)
Requirement already satisfied: pyparsing in d:\ripo\lib\site-packages (from Eel==0.14.0->auto-py-to-exe) (3.0.9)
Requirement already satisfied: whichcraft in d:\ripo\lib\site-packages (from Eel==0.14.0->auto-py-to-exe) (0.6.1)
Requirement already satisfied: setuptools>=42.0.0 in d:\ripo\lib\site-packages (from pyinstaller>=5.8.0->auto-py-to-exe) (65.5.0)
Requirement already satisfied: altgraph in d:\ripo\lib\site-packages (from pyinstaller>=5.8.0->auto-py-to-exe) (0.17.3)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in d:\ripo\lib\site-packages (from pyinstaller>=5.8.0->auto-py-to-exe) (2023.0)
Requirement already satisfied: pefile>=2022.5.30 in d:\ripo\lib\site-packages (from pyinstaller>=5.8.0->auto-py-to-exe) (2022.5.30)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in d:\ripo\lib\site-packages (from pyinstaller>=5.8.0->auto-py-to-exe) (0.2.0)
Requirement already satisfied: gevent-websocket in d:\ripo\lib\site-packages (from bottle-websocket->Eel==0.14.0->auto-py-to-exe) (0.10.1)
Requirement already satisfied: gevent in d:\ripo\lib\site-packages (from gevent-websocket->bottle-websocket->Eel==0.14.0->auto-py-to-exe) (22.10.2)
Requirement already satisfied: zope.event in d:\ripo\lib\site-packages (from gevent->gevent-websocket->bottle-websocket->Eel==0.14.0->auto-py-to-exe) (4.5.0)
Requirement already satisfied: zope.interface in d:\ripo\lib\site-packages (from gevent->gevent-websocket->bottle-websocket->Eel==0.14.0->auto-py-to-exe) (5.5.2)
Requirement already satisfied: greenlet>=2.0.0 in d:\ripo\lib\site-packages (from gevent->gevent-websocket->bottle-websocket->Eel==0.14.0->auto-py-to-exe) (2.0.1)
Requirement already satisfied: cffi>=1.12.2 in d:\ripo\lib\site-packages (from gevent->gevent-websocket->bottle-websocket->Eel==0.14.0->auto-py-to-exe) (1.15.1)
Requirement already satisfied: pycparser in d:\ripo\lib\site-packages (from cffi>=1.12.2->gevent->gevent-websocket->bottle-websocket->Eel==0.14.0->auto-py-to-exe) (2.21)

(.venv) C:\Users\jonah\.venv\Scripts>auto-py-to-exe
PyInstaller cannot check for assembly dependencies.
Please install pywin32-ctypes.

pip install pywin32-ctypes


(.venv) C:\Users\jonah\.venv\Scripts>
```

**Comment by brentvollebregt** [comment]
@jman13378, not that I know this is usually how it works, but the "Requirement already satisfied" messages are hinting the dependencies are sitting outside the virtual env.

Could you try this and show all output:

1. Create a virtual environment: `python -m venv .venv`
2. Activate the Python venv: `.venv/Scripts/Activate.ps1` (may need to change depending on the terminal you are using)
3. Validate virtual env Python is being used: `where python` (top .exe location should be in the .venv folder)
4. Validate virtual env pip is being used: `where pip` (top .exe location should be in the .venv folder)
5. Install auto-py-to-exe: `pip install auto-py-to-exe`
6. Validate correct auto-py-to-exe is available: `where auto-py-to-exe` (top .exe location should be in the .venv folder)
7. Validate pywin32-ctypes is installed: `pip show pywin32-ctypes` (location should be in the .venv folder)
8. Run auto-py-to-exe: `auto-py-to-exe`

**Comment by jman13378** [comment]
Sorry for the inconvenience been busy just got a chance to test this but when i use `where pip` i just get D:\ripo\Scripts\pip.exe

**Comment by jman13378** [comment]
Alright i create a new env and it did open
```
Microsoft Windows [Version 10.0.19045.2846]
(c) Microsoft Corporation. All rights reserved.

C:\Users\jonah>python -m venv pipenv

C:\Users\jonah>pipenv/Scripts/Activate
'pipenv' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jonah>cd pipenv

C:\Users\jonah\pipenv>cd Scripts

C:\Users\jonah\pipenv\Scripts>activate

(pipenv) C:\Users\jonah\pipenv\Scripts>where pip
C:\Users\jonah\pipenv\Scripts\pip.exe
D:\ripo\Scripts\pip.exe

(pipenv) C:\Users\jonah\pipenv\Scripts>where python
C:\Users\jonah\pipenv\Scripts\python.exe
D:\ripo\python.exe
D:\msys64\mingw64\bin\python.exe

(pipenv) C:\Users\jonah\pipenv\Scripts>pip install auto-py-to-exe
Collecting auto-py-to-exe
  Downloading auto_py_to_exe-2.34.0-py2.py3-none-any.whl (178 kB)
     ---------------------------------------- 178.6/178.6 kB 5.4 MB/s eta 0:00:00
Collecting Eel>=0.11.0
  Downloading Eel-0.16.0.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting pyinstaller>=5.8.0
  Downloading pyinstaller-5.10.1-py3-none-win_amd64.whl (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 13.3 MB/s eta 0:00:00
Collecting bottle
  Downloading bottle-0.12.25-py3-none-any.whl (90 kB)
     ---------------------------------------- 90.2/90.2 kB ? eta 0:00:00
Collecting bottle-websocket
  Using cached bottle-websocket-0.2.9.tar.gz (2.0 kB)
  Preparing metadata (setup.py) ... done
Collecting future
  Downloading future-0.18.3.tar.gz (840 kB)
     ---------------------------------------- 840.9/840.9 kB 26.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pyparsing
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting whichcraft
  Using cached whichcraft-0.6.1-py2.py3-none-any.whl (5.2 kB)
Requirement already satisfied: setuptools>=42.0.0 in c:\users\jonah\pipenv\lib\site-packages (from pyinstaller>=5.8.0->a
uto-py-to-exe) (65.5.0)
Collecting altgraph
  Using cached altgraph-0.17.3-py2.py3-none-any.whl (21 kB)
Collecting pyinstaller-hooks-contrib>=2021.4
  Downloading pyinstaller_hooks_contrib-2023.2-py2.py3-none-any.whl (261 kB)
     ---------------------------------------- 262.0/262.0 kB ? eta 0:00:00
Collecting pefile>=2022.5.30
  Downloading pefile-2023.2.7-py3-none-any.whl (71 kB)
     ---------------------------------------- 71.8/71.8 kB 3.8 MB/s eta 0:00:00
Collecting pywin32-ctypes>=0.2.0
  Using cached pywin32_ctypes-0.2.0-py2.py3-none-any.whl (28 kB)
Collecting gevent-websocket
  Using cached gevent_websocket-0.10.1-py3-none-any.whl (22 kB)
Collecting gevent
  Using cached gevent-22.10.2-cp311-cp311-win_amd64.whl (1.5 MB)
Collecting zope.event
  Downloading zope.event-4.6-py2.py3-none-any.whl (6.8 kB)
Collecting zope.interface
  Downloading zope.interface-6.0-cp311-cp311-win_amd64.whl (204 kB)
     ---------------------------------------- 204.1/204.1 kB 12.1 MB/s eta 0:00:00
Collecting greenlet>=2.0.0
  Downloading greenlet-2.0.2-cp311-cp311-win_amd64.whl (192 kB)
     ---------------------------------------- 192.5/192.5 kB 11.4 MB/s eta 0:00:00
Collecting cffi>=1.12.2
  Downloading cffi-1.15.1-cp311-cp311-win_amd64.whl (179 kB)
     ---------------------------------------- 179.0/179.0 kB 10.5 MB/s eta 0:00:00
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: whichcraft, pywin32-ctypes, bottle, altgraph, zope.interface, zope.event, pyparsing, pyin
staller-hooks-contrib, pycparser, pefile, greenlet, future, pyinstaller, cffi, gevent, gevent-websocket, bottle-websocke
t, Eel, auto-py-to-exe
  DEPRECATION: future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproje
ct.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement i
s to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for future ... done
  DEPRECATION: bottle-websocket is being installed using the legacy 'setup.py install' method, because it does not have
a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible rep
lacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for bottle-websocket ... done
  DEPRECATION: Eel is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.
toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is t
o enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for Eel ... done
Successfully installed Eel-0.16.0 altgraph-0.17.3 auto-py-to-exe-2.34.0 bottle-0.12.25 bottle-websocket-0.2.9 cffi-1.15.
1 future-0.18.3 gevent-22.10.2 gevent-websocket-0.10.1 greenlet-2.0.2 pefile-2023.2.7 pycparser-2.21 pyinstaller-5.10.1
pyinstaller-hooks-contrib-2023.2 pyparsing-3.0.9 pywin32-ctypes-0.2.0 whichcraft-0.6.1 zope.event-4.6 zope.interface-6.0


[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(pipenv) C:\Users\jonah\pipenv\Scripts>where auto-py-to-exe
C:\Users\jonah\pipenv\Scripts\auto-py-to-exe.exe
D:\ripo\Scripts\auto-py-to-exe.exe

(pipenv) C:\Users\jonah\pipenv\Scripts>pip show pywin32-ctypes
Name: pywin32-ctypes
Version: 0.2.0
Summary: UNKNOWN
Home-page: https://github.com/enthought/pywin32-ctypes
Author: Enthought Inc
Author-email: info@enthought.com
License: BSD
Location: C:\Users\jonah\pipenv\Lib\site-packages
Requires:
Required-by: pyinstaller

(pipenv) C:\Users\jonah\pipenv\Scripts>auto-py-to-exe

(pipenv) C:\Users\jonah\pipenv\Scripts>
```

**Comment by brentvollebregt** [comment]
Ah there we go, the "Requirement already satisfied" message is now pointing to the virtual env - a bit weird that pip wasn't last time even though Python was pointing to it.

I suppose we can close this now? Seems like it was an environment issue.

**Comment by jman13378** [comment]
but how do we fix it

**Comment by brentvollebregt** [comment]
That worked - `auto-py-to-exe` didn't throw that error now.
