### ISSUE TITLE
How can I add only those libraries that I need and ignore all others?

### ISSUE THREAD

**Issue by Cowboyserg** [brentvollebregt/auto-py-to-exe#372]
Windows 10
Python 3.7
auto-py-to-exe 2.18.2

Hello, can you help me with my problem please?
I used command 
```
pyinstaller --noconfirm --onefile --console --debug "all" --hidden-import "openpyxl" --hidden-import "uuid" --exclude-module "Django" --exclude-module "matplotlib"  "generate.py"
```

I have only 2 import in my `.py` file
```
from openpyxl import Workbook
import uuid
```

I don't know why, but `auto-py-to-exe` tryed to take Django and matplotlib. That is the reason why I added them to `--exclude-module`.
How can I add only this 2 libraries into `exe` file and ignore all other, that `auto-py-to-exe` takes?

In the end I got my `exe` file that works correct, but it weighs 140 MB

**Comment by brentvollebregt** [comment]
In the post that's linked in the README, at the bottom of the UI after every build and in the comment above, there is a section ["The Output Executable is Huge"](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#the-output-executable-is-huge). Give this a read - you need to use a virtual environment to remove these extra libraries from your environment.
