### ISSUE TITLE
Bump Eel version from 0.14.0 to 0.16.0

### ISSUE THREAD

**Issue by Nuzza** [brentvollebregt/auto-py-to-exe#377]
**Quick Checks**
- [X] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [X] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [ ] I have made sure my application/script runs before trying to package (not required for this type of issue)

**Describe the bug**
A clear and concise description of what the bug is. If you have an error message, please paste it here (not in a screenshot).
No bug, just wondering if Eel version 0.16.0 will be added, considering some packages require that version of Eel.

**Your Environment:**
- Python version (`python --version`): 3.8.10
- auto-py-to-exe version (`pip show auto-py-to-exe`): latest
- PyInstaller version (`pip show pyinstaller`): latest
- Eel version (`pip show eel`): 0.14.0

**Comment by brentvollebregt** [comment]
This was brought up in https://github.com/brentvollebregt/auto-py-to-exe/discussions/370 - from this, I put a change on master that used `Eel>=0.11.0` but did not release it.

I have just released it under [2.33.0](https://github.com/brentvollebregt/auto-py-to-exe/releases/tag/v2.33.0)

**Comment by Nuzza** [comment]
@brentvollebregt Thank you for that kind sir.
