### ISSUE TITLE
Can anyone please tell me how to fix this error?

### ISSUE THREAD

**Issue by shmuelazriel** [brentvollebregt/auto-py-to-exe#379]
![image](https://user-images.githubusercontent.com/116635593/226199652-be1d8e22-b2bf-48c4-8ca8-6456cd702f5d.png)

(I'm using Ubuntu)

**Comment by brentvollebregt** [comment]
Have you followed the instructions in the error?

**Comment by shmuelazriel** [comment]
yes, it's worked now
thanks
