### ISSUE TITLE
.ico wont change from a previously used image

### ISSUE THREAD

**Issue by REALtony4twenty** [brentvollebregt/auto-py-to-exe#382]
every time I select a new .ico it wont use it. 

it just uses an old I have used before.

**Comment by brentvollebregt** [comment]
Are you on Windows? Right-click in the folder that the exe is in and click "refresh" (also hitting F5 will perform a similar action).

Windows doesn't always see the change immediately - so this tells it to refresh and you should see the new icon.

Did this work for you? If not, I recommend you fill out the template you cleared.
