### ISSUE TITLE
Issue while making EXE of script which consists pikepdf

### ISSUE THREAD

**Issue by vikramsamak** [brentvollebregt/auto-py-to-exe#383]
![image](https://user-images.githubusercontent.com/95061742/230164125-6feac92d-159a-4529-a6fb-2960cceffefd.png)

how to solve this issue ?

**Comment by brentvollebregt** [comment]
I just did a search in the pikepdf repo's issues and found this: https://github.com/pikepdf/pikepdf/issues/353

You can find this setting in the a advanced section - you will need to add "pikepdf" in a new entry by --copy-metadata 

> It would be awesome if you could fill the issue template out properly thanks. In this current state, it is not very searchable; making others in your situation potentially unable to find this easily.

**Comment by vikramsamak** [comment]
Now I'm using pypdf2 in my project....
It's working fine now 😀
