### ISSUE TITLE
how to aovid the exe file to be decompiled.

### ISSUE THREAD

**Issue by davesliu** [brentvollebregt/auto-py-to-exe#384]
As auto-py-to-exe use the pyinstaller to convert the python script to exe file.
So is there any options of this tool to avoid the generated exe file to be decompiled ?

**Comment by brentvollebregt** [comment]
This is a question for PyInstaller as this tool uses PyInstaller to package the input (as you identified).

Searching for "pyinstaller prevent decompile" on Google will get you some decent answers - it all boils down to how far you want to go.
