### ISSUE TITLE
python function 'exit' raise exception

### ISSUE THREAD

**Issue by boyapavel** [brentvollebregt/auto-py-to-exe#386]
Traceback (most recent call last):
  File "gw_stat_gen.py", line 255, in <module>
  File "gw_stat_gen.py", line 11, in get_list_files
NameError: name 'exit' is not defined
[20944] Failed to execute script 'gw_stat_gen' due to unhandled exception!

line 11 looks like : exit('can not open your directory '+path+' .exit')

**Comment by boyapavel** [comment]
i change fuction exit() to sys.exit() - it`s a good workaround for me.
but why exit() function raise exception like "NameError: name 'exit' is not defined" ?

**Comment by boyapavel** [comment]
for example, i wrote simple python script with exit() function.
script:
`test = ''`
`while test != '2':`
`    test = input('please give me 2 or anything else. 2 - is exit; your choise: ')`
`exit('bye, bye')`
debug attached here.
[test_debug_all.txt](https://github.com/brentvollebregt/auto-py-to-exe/files/11200182/test_debug_all.txt)

**Comment by brentvollebregt** [comment]
I have added a section to the debugging help for this: https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#nameerror-name-exit-is-not-defined.

Here is a snippet from the additions:

> Typically when developing in IDLE, `sys` is automatically imported. This means calls like `exit()` will work in IDLE without having to import `sys` explicitly. However, when packaging, sys is not automatically imported so you will have to import it yourself. This is a simple fix and can be done by adding `import sys` to the top of your script.
