### ISSUE TITLE
Add output directory into json config file

### ISSUE THREAD

**Issue by Paulo1402** [brentvollebregt/auto-py-to-exe#388]
One feature I think it'll work just fine is add settings section's output directory field into the json config file when exported.
Just because when we use another output name convention like "dist" instead of "output" we always need to manually change this field even after import our previously configured json file.

**Comment by brentvollebregt** [comment]
Check out #197 - I added this a bit ago but you need to add it manually

**Comment by Paulo1402** [comment]
Alright, that works fine now, thanks!
