### ISSUE TITLE
after executing the auto-py-to-exe command, the page open link a browser, but it gives the message (initializng) and does not work!

### ISSUE THREAD

**Issue by mehrtok** [brentvollebregt/auto-py-to-exe#389]
after executing the auto-py-to-exe command, the page open link a browser, but it gives the message (initializng) and does not work!

**Comment by brentvollebregt** [comment]
I just tested this myself on a clean VM and it was fine.

Could you please fill out the template you cleared? It would be super helpful to have some reproduction steps, otherwise I can't help with this sorry.

**Comment by bwooshem** [comment]
I had the same issue on a Windows VM that is deliberately not updated for my work. I don't need this fixed urgently as have it working on another computer, but am posting this in case it helps others with debugging. 
Python version: Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Windows version: Windows 10 Education, Version 1809
Browser: Microsoft Edge 44.17763.1.0
I installed Auto Py to Exe using pip version 22.3.1, and it installed the following version of auto-py-to-exe:
auto_py_to_exe-2.34.0-py2.py3-none-any.whl
It will open the UI in Edge, then get stuck with the loading wheel and says "Initializing..." and does not let me select anything.
I'm relatively new to this so it's possible I made an obvious mistake. I'm not sure what you mean by "fill out the template you cleared" but I can try to find other debugging outputs if requested.

**Comment by brentvollebregt** [comment]
@bwooshem were there any errors in the console that you ran this from? Also are there any errors in the console tab in the browser dev tools?

**Comment by bwooshem** [comment]
Not that I saw. I ran Py -m auto_py_to_exe in the Command Window, and no errors or anything printed out there.

**Comment by brentvollebregt** [comment]
@bwooshem thanks for taking a look! 

If you open the browser dev tools in the window that is loading, what are the messages in the console? If there are none, hitting F5 (with the dev tools open) can reload the page and get the messages coming back in.

**Comment by xazityaa** [comment]
> after executing the auto-py-to-exe command, the page open link a browser, but it gives the message (initializng) and does not work!

i fixed this by opening the dev tools with Ctrl shift i then selecting the object that covers the page and pressing del

**Comment by brentvollebregt** [comment]
@xazityaa were there any errors in the console tab in DevTools? Also were they any errors in the console from where you started auto-py-to-exe?
