### ISSUE TITLE
ModuleNotFoundError when I run the .exe

### ISSUE THREAD

**Issue by HaaZee** [brentvollebregt/auto-py-to-exe#39]
In my program I use a module called pyfiglet. When I run my program from the .py it runs fine and well. As soon as I use your program to make it an exe it compiles. Then I try and run the .exe and get this error -
![error](https://user-images.githubusercontent.com/33757920/50116803-13d06680-0243-11e9-94d1-df08b6afe7a7.png)

Also I get this error in your programs terminal -
![other error](https://user-images.githubusercontent.com/33757920/50116860-48442280-0243-11e9-8006-6c3c09097f6d.png)

Not sure how to get around this as I really need my file to be an exe.

Thanks

EDIT: This only apears to happen when I do - from  pyfiglet import Figlet

**Comment by brentvollebregt** [comment]
Did you read the [article I clearly linked](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/) in the README under "Issues Using the Tool"?

If you go to this and do a simple Ctrl+F for `ModuleNotFoundError`, you will be immediately shown:

> [ModuleNotFoundError: No module named 'x'](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#modulenotfounderror-no-module-named-x)
Make sure the module is installed and then add it to --hidden-import in the advanced tab. If you need to add more than one, separate them by a comma (,).
>For example, I have seen this occur with pandas._libs.tslib many of times before so add that to the input by --hidden-import. If you need to add more missing modules, you can use pandas._libs.tslib, my_missing_module.

Also I have had the `ModuleNotFoundError: No module named 'win32com'` quite a few times and cannot figure out what it is, you have any idea?

**Comment by HaaZee** [comment]
I tried the --hidden-import thing and I didn't manage to fix it. I found a way around though doing it manually.
Also I regards to the win32ocm question I tried installing that module but that didn't seem to do anything, just brought up another error. I believe it's related to having a module not working when you try to compile your .py

**Comment by brentvollebregt** [comment]
What was your work around?

**Comment by HaaZee** [comment]
I just hard coded the thing I wanted to bring out. It was the name of my game in a large text format.

This basically - [https://delightlylinux.files.wordpress.com/2014/05/figlet.png](url)

Therefore I didn't need to use the module that was causing issues.

**Comment by brentvollebregt** [comment]
This is an issue with a third party module so I will close this issue.
