### ISSUE TITLE
Dependencies/requirements builder

### ISSUE THREAD

**Issue by hastalamuerte** [brentvollebregt/auto-py-to-exe#393]
Is it possible to parse libs from original file and made a requirements txt file with em , when exe file is building. Thnx for project

**Comment by brentvollebregt** [comment]
Not really - an import in a script doesn't tell you which library it comes from. The import could hint where it comes from, but a package's name on PyPI does not have to match how it is imported in a script. 

Also you may have written your own script that has the same name as a package in PyPI - which could then add the incorrect package.

**Comment by hastalamuerte** [comment]
> Not really - an import in a script doesn't tell you which library it comes from. The import could hint where it comes from, but a package's name on PyPI does not have to match how it is imported in a script. 
> 
> Also you may have written your own script that has the same name as a package in PyPI - which could then add the incorrect package. 

Found that one , maybe can be implemented

**Comment by brentvollebregt** [comment]
Sorry, I'm not sure why something like this is needed in auto-py-to-exe?

Also looking at the source of that library - it appears that it will set the version of a library to the latest in PyPI. No discredit to the authors, but this could cause an incorrect version of a library to be used. This incorrect versioning would not work with this tool as if the script doesn't run before packaging, it certainly won't run as an exe.

> Also [the mapping file](https://github.com/bndr/pipreqs/blob/master/pipreqs/mapping) shows what I was talking about when saying import names can be different to PyPI package names.
