### ISSUE TITLE
Resolving the path of the exe files and not it instance in appdata temp

### ISSUE THREAD

**Issue by VincentHk6** [brentvollebregt/auto-py-to-exe#397]
### Discussed in https://github.com/brentvollebregt/auto-py-to-exe/discussions/394

<div type='discussions-op-text'>

<sup>Originally posted by **VincentHk6** May  4, 2023</sup>
Dear,

I have the following lines in my .py that i convert to an exe one file window based;

source_path = Path(__file__).resolve()
source_dir = source_path.parent

I use the pass to access files as config files, so i just need to keep those files in the same folder as the exe. 
The problem is that once running the exe it resolve a path here d\\AppData\\Local\\Temp\\_MEI209402\\ .

Why is that, what did i miss to avoid this issue?
Best regards
Vincent</div>

**Comment by brentvollebregt** [comment]
In the help post, I discuss ["The Difference Between One Directory and One File"](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#the-difference-between-one-directory-and-one-file).

Files are put in a directory like this when using one-file mode. To not have your files moved into a directory like this, use one-directory mode.

When using one-file, a bootloader is needed to start the exe - [more details on this in the PyInstaller docs here](https://pyinstaller.org/en/stable/advanced-topics.html?highlight=_mei#bootloader).

**Comment by brentvollebregt** [comment]
This is now being discussed in https://github.com/brentvollebregt/auto-py-to-exe/discussions/394
