### ISSUE TITLE
cmd opens 7 times with the window based option

### ISSUE THREAD

**Issue by Skyfay** [brentvollebregt/auto-py-to-exe#401]
Hey, I want to use this software to convert my python problem to an exe. The whole thing works so far, but when starting the exe I have a few problems. 

If I use --windowed, then after pressing the exe 5-8 times a CMD window opens which is closed again directly afterwards. After this process the GUI of my program opens. 

If I use --console, then a console window opens normally and then directly the GUI of my software. 

Of course I don't want to have a console open while my program is running but I also don't want to have this problem with CMD windows opening.

Can anyone help me out here?

Thanks for help :)

**Comment by brentvollebregt** [comment]
Execute your Python script (not the .exe) using pythonw.exe - do you see the same result?

I'm sure you read this but just in case you didn't, from the [help post under "The exe Runs But Does Some Unexpected Things"](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#the-exe-runs-but-does-some-unexpected-things):

> Examples of executables functioning differently include but are not limited to:
> 
> - A console window appearing
> - Console windows appearing and closing
> 
> This difference is most likely because the script is now running in a different environment or started in a different way.

**Comment by Skyfay** [comment]
> Execute your Python script (not the .exe) using pythonw.exe - do you see the same result?

Nothing happens when I try to do that.

**Comment by brentvollebregt** [comment]
Even the GUI doesn't open? This hints there is something wrong with the way you are running it.

**Comment by Skyfay** [comment]
![SJ5ahwcWG3](https://github.com/brentvollebregt/auto-py-to-exe/assets/76796007/3bda73ef-3101-4294-8fdf-f94e9ded1819)

**Comment by brentvollebregt** [comment]
Running your script directly with python.exe is equivalent to the console-based mode and pythonw.exe is equivalent to the window-based mode in auto-py-to-exe. It's expected that the packaged script (output exe) works the same as running the original script using the corresponding python.exe/pythonw.exe.

This means the issue lies outside of auto-py-to-exe from what I can tell and changes need to be made to your script/application to support running outside of an IDE. Your IDE may provide a bit of stuff in the background that you don't get with something like pythonw.exe.

**Comment by Skyfay** [comment]
Can they give me an approach to what I might be looking for here?

**Comment by brentvollebregt** [comment]
I have seen terminal windows appear and disappear rapidly before when using the `subprocess` - maybe you are using that? I haven't seen it in a while but remember seeing something like `shell=True` fixing it.

Aside from that, I'm not sure what you are using and doing. Potentially you have something that may be hiding an exception occurring - this could be making the GUI silently fail to start. If you are using `try` and just throwing away exceptions, it might pay to write them to a log file.

**Comment by Skyfay** [comment]
**Python.exe**
![python](https://github.com/brentvollebregt/auto-py-to-exe/assets/76796007/54df9266-b2d8-49ae-8954-7b729e758ed1)
**PythonW.exe**
![pythonw](https://github.com/brentvollebregt/auto-py-to-exe/assets/76796007/eddd8e49-c4c2-4bc3-a398-6e9f6a476e0b)

**Comment by Skyfay** [comment]
> I have seen terminal windows appear and disappear rapidly before when using the subprocess - maybe you are using that? I haven't seen it in a while but remember seeing something like shell=True fixing it.

I have done this, however the problem still exists. Maybe someone else has an idea?

**Comment by brentvollebregt** [comment]
While I have no other specific ideas, you could start from the ground up by adding small pieces of your application and running pythonw.exe on it every change to identify what is causing the issue.

You can test with pythonw.exe directly and don't need to use auto-py-to-exe to test each iteration.

**Comment by Skyfay** [comment]
> While I have no other specific ideas, you could start from the ground up by adding small pieces of your application and running pythonw.exe on it every change to identify what is causing the issue.
> 
> You can test with pythonw.exe directly and don't need to use auto-py-to-exe to test each iteration.

Is the script simply not allowed to have any console outputs? Or is there the possibility to start normally with python.exe and hide cmd which opens?

**Comment by brentvollebregt** [comment]
python.exe needs a console window - if you are packaging with window-based mode in auto-py-to-exe, you need to test with pythonw.exe which has a few less things in it (from what I understand).

**Comment by Skyfay** [comment]
Yes, but I am trying to find the error. It's very funny, I can't be the only one with the problem. And my code is not very special. I just wonder what triggers this opening of the CMD windows.

**Comment by Skyfay** [comment]
> you could start from the ground up by adding small pieces of your application and running pythonw.exe on it every change to identify what is causing the issue.

> I have seen terminal windows appear and disappear rapidly before when using the `subprocess` - maybe you are using that? I haven't seen it in a while but remember seeing something like `shell=True` fixing it.

Thank you for your tip. I was actually able to fix the problem now. After removing several parts of my code, attention was drawn to one part which uses `subprocess`. I then did some google searching and checked my code and found out that I had completely misunderstood and implemented the  `shell=True `. Now everything works fine. 

Thanks again for your time, and for helping me even though it wasn't directly a problem with auto-py-to-exe. 
I appreciate that very much :)
