### ISSUE TITLE
Question—Unable to import the missing package

### ISSUE THREAD

**Issue by LiuZC233** [brentvollebregt/auto-py-to-exe#402]
**Quick Checks**
- [ X] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [X ] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [X ] I have made sure my application/script runs before trying to package 

**Describe the bug**
Hi. I am using auto-py-to-exe to compile my .py file into an exe file. However, although i am pretty sure I have tried my best to manually import all packages in the hidden_import blank, when I run the exe, it still outputs the same error “missing package”. The missing package is IMC_Denoise and the Github repository is  https://github.com/PENGLU-WashU/IMC_Denoise . 
![DBD6AEAD-CBC9-4B83-9CA9-851E2BC329F4](https://github.com/brentvollebregt/auto-py-to-exe/assets/137216996/6cb9e3bc-9afd-4f4e-9437-39c7258d0cca)

**To Reproduce**
Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):

```python
# If you have example code, please provide a minimal reproducible example: 
# https://stackoverflow.com/help/minimal-reproducible-example

print("Hello World")
```

**Expected behavior**

**Your Environment:**
- Python version (`python --version`): 3.11
- auto-py-to-exe version (`pip show auto-py-to-exe`): the most updated version 
- PyInstaller version (`pip show pyinstaller`):
- Eel version (`pip show eel`):

**Comment by LiuZC233** [comment]
Updates: I have made sure that the package is correctly installed on the site_packages folder in my Python directory. I can directly use import…from… and from…import… to call this specific function but failed doing so for data compilation by using auto-py-to-exe. 
thank you very much for your help!

**Comment by LiuZC233** [comment]
Updates 2: While I segmentalized the package into different separate smaller packages and manually loaded them into the site_packages folder of my python, the error “ _ attempted relative import beyond top-level package_ “ raised. After getting this error resolved, the same error “Module Not Found” appeared again and I don’t know why. Please kindly help me and thank you very much!

**Comment by brentvollebregt** [comment]
Have you run this script (.py file) directly with python.exe in the same environment you are running auto-py-to-exe from?

**Comment by LiuZC233** [comment]
Hi Good morning Brent. Thank you very much for your reply and sorry for my late response. I have tried it and again it showed "ModuleNotFound" error. However, if I selected all lines of codes and run it, it would work.

**Comment by LiuZC233** [comment]
Hi Good morning Brento. Today I have also tried to add my python to the %PATH% and double checked the interpretator I am using which is python 3.11 in Microsoft Visual Studio Code. I checked again if I have the access to required packages IMC_Denoise and the answer is yes. Something that confusing me always is I don't know why I can still use those packages when both IDLE and Pylance (a third-party toolkit that published on the MS VSC Marketplace) say that the package is missing.
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/137216996/993897b6-1f2c-4e66-bdf5-3306451c1fe9)
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/137216996/db7515f9-7818-494f-8151-863240cd9bfc)
Sorry to bother you again.

**Comment by brentvollebregt** [comment]
You will need to make sure your script runs properly without an IDE before you package it with auto-py-to-exe. If the script doesn't work correctly when running it with python.exe, it probably will not work after being packaged.

The first step in the [debugging section in the help post I provide](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging):

> As basic as it sounds, the first step of debugging is to make sure your script works as a .py file before you package it. Instead of running your .py file using IDLE (which automatically imports sys), run your script using the terminal like this: python my_script.py. Any errors that occur here will definitely show up in the output exe.

My recommendation would be to double-check that when running the script with python.exe, make sure it is the same python.exe that you are using auto-py-to-exe with.

For your specific issue - maybe you have a virtual environment where you have your dependencies but you are not running auto-py-to-exe from the same environment.

**Comment by LiuZC233** [comment]
Hi Brevento. First of all please accept my sincerest gratitude for your reply that directed me to the right path. I also apologized for my stupidity and oversight of this common issue. After I implemented the virtual environment of my python program, everything is solved. Thanks again for your help!
