### ISSUE TITLE
Converting py to exe takes a lot of time - issue with loading module hook 'hook-tensorflow.py'

### ISSUE THREAD

**Issue by mkachlicka** [brentvollebregt/auto-py-to-exe#406]
Hey,

How long (more or less) does it take for the app to convert a single py file? It's been almost an hour since it started, and there is no progress - it seems to be stuck on this message:
`232562 INFO: Loading module hook 'hook-tensorflow.py' from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...`

The full output in the app is as follows:
`Running auto-py-to-exe v2.36.0
Building directory: /var/folders/qr/bbjn5vg55gx257pkjrf8jg0w0000gn/T/tmptowlr2sy
Provided command: pyinstaller --noconfirm --onedir --console --add-data "/Users/mkachlicka/Documents/AAAutomatedFluency/functions:functions/" --add-data "/Users/mkachlicka/Documents/AAAutomatedFluency/audio:audio/"  "/Users/mkachlicka/Documents/AAAutomatedFluency/acat_full.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onedir --console --add-data /Users/mkachlicka/Documents/AAAutomatedFluency/functions:functions/ --add-data /Users/mkachlicka/Documents/AAAutomatedFluency/audio:audio/ /Users/mkachlicka/Documents/AAAutomatedFluency/acat_full.py --distpath /var/folders/qr/bbjn5vg55gx257pkjrf8jg0w0000gn/T/tmptowlr2sy/application --workpath /var/folders/qr/bbjn5vg55gx257pkjrf8jg0w0000gn/T/tmptowlr2sy/build --specpath /var/folders/qr/bbjn5vg55gx257pkjrf8jg0w0000gn/T/tmptowlr2sy

86481 INFO: PyInstaller: 5.1
86484 INFO: Python: 3.8.8 (conda)
86511 INFO: Platform: macOS-10.16-x86_64-i386-64bit
86514 INFO: wrote /var/folders/qr/bbjn5vg55gx257pkjrf8jg0w0000gn/T/tmptowlr2sy/acat_full.spec
86524 INFO: UPX is not available.
86527 INFO: Extending PYTHONPATH with paths
['/Users/mkachlicka/Documents/AAAutomatedFluency']
87131 INFO: checking Analysis
87134 INFO: Building Analysis because Analysis-00.toc is non existent
87138 INFO: Initializing module dependency graph...
87143 INFO: Caching module graph hooks...
87151 INFO: Analyzing base_library.zip ...
89335 INFO: Processing pre-find module path hook distutils from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
89339 INFO: distutils: retargeting to non-venv dir '/Users/mkachlicka/opt/anaconda3/lib/python3.8'
92057 INFO: Caching module dependency graph...
92181 INFO: running Analysis Analysis-00.toc
92187 INFO: Analyzing /Users/mkachlicka/Documents/AAAutomatedFluency/acat_full.py
97012 INFO: Processing pre-find module path hook site from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-site.py'.
97015 INFO: site: retargeting to fake-dir '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/fake-modules'
102524 INFO: Processing pre-safe import module hook six.moves from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
108648 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
124695 INFO: Processing pre-safe import module hook win32com from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
136692 INFO: Processing pre-safe import module hook tensorflow from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-tensorflow.py'.
231099 INFO: Processing module hooks...
231101 INFO: Loading module hook 'hook-llvmlite.py' from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
231106 INFO: Loading module hook 'hook-zmq.py' from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
231515 INFO: Loading module hook 'hook-py.py' from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
231801 INFO: Loading module hook 'hook-parso.py' from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
231810 INFO: Loading module hook 'hook-notebook.py' from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
232562 INFO: Loading module hook 'hook-tensorflow.py' from '/Users/mkachlicka/opt/anaconda3/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...`

Do you know if this is normal? It's hard to tell if anything went wrong here since I don't see any error messages or warnings along the way.

Update: I left it running for several hours now, but nothing changed, which is a pretty strong cue for me that something is definitely wrong. Would anyone be able to help with finding the source of the problem here? I'd very much appreciate that.

**Comment by brentvollebregt** [comment]
If you run this outside Anaconda, do you still get the same result?

**Comment by mkachlicka** [comment]
Oh wow, why it didn't occur to me earlier? Thank you so much for the suggestion! Running it outside Anaconda solved the issue, and the script was compiled successfully!
