### ISSUE TITLE
auto-py-to-exe on macOS seems to have buggy windows behavior

### ISSUE THREAD

**Issue by gernophil** [brentvollebregt/auto-py-to-exe#407]
I am using `auto-py-to-exe` (version 2.36.0; installed in a `conda` environment, but using `pip`) on macOS and I am experiencing some buggy window behavior. Some of it appears random, some always. I am starting `auto-py-to-exe` without any additional flags and it opens normally.

Window issue 1:
However, sometimes, when click on "Import Config From JSON File", the opening dialog, where I can select the JSON file does just not open. This luckily happens rarely (estimated in 1 in 30-50 attempts), but if it happens it influences my whole system. I am not able to open any open file dialog in any other app (I tried e.g. Word, Firefox, VSCode). It's really annoying and I did not find a way to solve this. Up to now it always started to work again after some attempts or reboots, but I haven't found a reproducible solution for this yet. I never experienced this with any itNext time it happens, I will copy the terminal output and see if this helps. It was something about `NS...` which refers to the macOS windows system IIRC. I know it's a bit fishing in the dark with this info, but maybe it still helps.

Window issue 2:
Every time I click on "Import Config From JSON File" a black square windows appears, that's on top of everything and only disappears after I close `auto-py-to-exe`. This happens always (see screenshot), and it might be related to windows issue 1.

Windows issue 3:
Ok, for this I am not sure, if it's related to `auto-py-to-exe`, but I haven't used anything else while it happened. And this luckily happens really rare, but it did happened twice yesterday. `auto-py-to-exe` seems to crash my Finder. At least this happened while `auto-py-to-exe` was opened, and I also never experienced that before. Had to reboot the computer completely, since I wasn't able to just restart finder. It immediately crashed again.

![Bildschirmfoto 2023-07-12 um 09 52 18](https://github.com/brentvollebregt/auto-py-to-exe/assets/19264855/ba0e4243-b7ab-472e-b591-0e52f1695dac)

**Comment by brentvollebregt** [comment]
A quick note: I do not own a Mac so am unable to do any testing myself sorry.

**Question 1**

If there was something in the console, this would be suuuper helpful to have 👍 

**Question 2**

Does this look related to #304 by any chance?

If you run this script in Python, does it lead to the same issue?

```python
from tkinter import Tk
from tkinter.filedialog import askopenfilename

root = Tk()
root.withdraw()
root.wm_attributes('-topmost', 1)
file_path = askopenfilename(parent=root)
root.update()
print(file_path)
```

**Question 3**

I haven't heard anything like this before, but it may be related to question 1? Not sure.

**Comment by gernophil** [comment]
Thanks for the reply. Been on vacation the last two weeks, so I don't have any update for questions 1 and 3. For question 2 I executed your small script. This does indeed lead to such a small window too, but this is attached to the opening dialog and fully responsive (see screenshot). I don't think it's exactly the same. The terminal output also looks normal to me:
```
2023-07-31 08:26:11.877 python[2249:48258] +[CATransaction synchronize] called within transaction
``` 
(this line appears multiple times with recent tome and date)

I'll keep you updated, if I run into these errors again.
![Bildschirmfoto 2023-07-31 um 08 26 25](https://github.com/brentvollebregt/auto-py-to-exe/assets/19264855/228767c9-6a34-450d-a479-d41c296196a9)
