### ISSUE TITLE
ModuleNotFoundError: No module named 'gevent'

### ISSUE THREAD

**Issue by Lizzit** [brentvollebregt/auto-py-to-exe#408]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [X] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [X] I have made sure my application/script runs before trying to package 

**Describe the bug**
I've tryed to download the package from github but when i run the "run.py" it throw me the following error:
Traceback (most recent call last):
  File "d:\Programmazione\auto-py-to-exe-master\run.py", line 6, in <module>
    from auto_py_to_exe import __main__ as apte
ages\eel\__init__.py", line 5, in <module>
    from gevent.threading import Timer
  File "C:\Users\Elia\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\Elia\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\Elia\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elia\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

I'm having the same error trying to install the program with pip install auto-py-to-exe and then running auto-py-to-exe

**To Reproduce**
Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):
1. Go to https://github.com/brentvollebregt/auto-py-to-exe/
2. Click on code -> download zip
3. Extract the downloaded folder and open it with vscode
4. Open the run.py file and run it

**Expected behavior**

**Your Environment:**
- Python version 3.11:
- auto-py-to-exe version 2.36.0:
- PyInstaller version  5.13.0:
- Eel version  1.0.0a1:

**Comment by Lizzit** [comment]
After hour of searching i tried to uninstall the library gevent and to reinstall it using python -m install gevent and it worked

**Comment by brentvollebregt** [comment]
Great to hear you found a solution. From you reproduction steps, it appears you have forgotten to install the dependencies as outlined in the [README's steps on running without installing](https://github.com/brentvollebregt/auto-py-to-exe#running-locally-via-github-no-install).
