### ISSUE TITLE
Cannot add icon

### ISSUE THREAD

**Issue by akcoder4** [brentvollebregt/auto-py-to-exe#409]
Traceback (most recent call last):
  File "M.py", line 146, in <module>
  File "tkinter\__init__.py", line 2136, in wm_iconbitmap
_tkinter.TclError: bitmap "matrix.ico" not defined

How to fix this issue?

**Comment by akcoder4** [comment]
![Screenshot (1104)](https://github.com/brentvollebregt/auto-py-to-exe/assets/140523678/641e7a3c-ba5b-4c06-91db-3b2a90a43bd0)

This is actual issue 

M.py is that python file which i want to convert into exe
matrix.ico is that icon i want to add in my exe

please resolve this issue.

**Comment by brentvollebregt** [comment]
Did you read the help post? Providing the stacktrace from the result of following the debugging steps might offer more context.

Also can you please fill out the issue template you cleared - this will give me more info to help resolve your issue.

**Comment by akcoder4** [comment]
![Screenshot (1104)](https://github.com/brentvollebregt/auto-py-to-exe/assets/140523678/3381b9da-c651-4442-98c1-86ee57ad426e)

Sir, thank you for asking and I am glad happy to tell you that the problem is fixed mentioned above.

I tell you the issue happened - The .ico file is not defined means the relative path of the .ico file is mentioned in the .py file.
We need to mention the absolute path of the .ico file in the .py file.

To fix the above issue, follow the steps :

1. Open the .py file
2. Make sure that the .py file and .ico file are in the same folder.
3. Add a variable with raw string and in that string mention the exact path of the .ico file along with the name of the .ico file along with the extension.

ex - icon_path = r"C:\User\lenevo\Desktop\Project\smile.ico"

4. Now, go to the iconbitmap() and in the function use bitmap method to set the absolute path of the .ico file.

ex - root.iconbitmap(bitmap=icon_path)

5. Save the .py file.

That's all!

Use auto py to exe as usual and make sure use the icon option to add icon in the .py file and convert it.

It will definitely help.
Thank you.
