### ISSUE TITLE
Uncaught (in promise) TypeError: o.choices.map is not a function

### ISSUE THREAD

**Issue by RealymanLP** [brentvollebregt/auto-py-to-exe#410]
Heyho, when I open auto py to exe using the command "py -m auto_py_to_exe, I get the following error message in web console. Any ideas?
![grafik](https://github.com/brentvollebregt/auto-py-to-exe/assets/50075062/ccd7b613-71ec-46cb-a8aa-5147d565558d)
The page itself stucks at "Initializing..."

 Already tried to reinstall auto py to exe. Any ideas?

**Comment by brentvollebregt** [comment]
Some questions that might give some context:

1. What has appeared in the console that you ran the command from
2. Can you provide the full output from the (browser) Dev Tools console
3. What version are you running? `py -m auto_py_to_exe --version`

**Comment by richoffpints** [comment]
im having the same issue as this guy

**Comment by brentvollebregt** [comment]
@richoffpints could you provide some insight on these?

1. What has appeared in the console that you ran the command from
2. Can you provide the full output from the (browser) Dev Tools console
3. What version are you running? `py -m auto_py_to_exe --version`

**Comment by richoffpints** [comment]
okay everyone who has the issue with it just saying initalizing, make sure u use sudo, it worked the first time after an hour of not working without it.

**Comment by brentvollebregt** [comment]
@richoffpints were you seeing any errors before you used `sudo`?
