### ISSUE TITLE
FileNotFoundError: The path does not exist.

### ISSUE THREAD

**Issue by saad-24** [brentvollebregt/auto-py-to-exe#411]
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/75729385/8fc3b0fc-8b56-440f-9959-90c471d7a296)

I have put my .py file and additional files in a virtual environment. All my required modules are installed in the virtual environment and the folder having modules installed is also added in auto py to exe. Why I am still getting this?

**Comment by brentvollebregt** [comment]
Have you followed the debugging steps? Could you provide the full output that you saw in the console please.
