### ISSUE TITLE
codesigning with auto-py-to-exe takes ages

### ISSUE THREAD

**Issue by gernophil** [brentvollebregt/auto-py-to-exe#412]
I've ported an app based on Python from Windows to macOS. I can run the app from command line and I was also able to make an .app file an start it on my mac using `auto-py-to-exe`. Now I want to `codesign` (and later `notarize`) it. To do so I set the `codesign_identity` option of `auto-py-to-exe` to my `Developer ID Application` and rerun it. After 2 days it was still running (and I guess collecting information on submodules of the used Python modules). Without the codesigning it takes about 5-10 minutes to build. Any ideas how I could accelerate this or what is happening here? Unfortunately, I am not able to copy the output of `auto-py-to-exe` while it is still running.

Thanks :).

**Comment by brentvollebregt** [comment]
I don't own a Mac myself so I am going to be 0 help on this.

What I can recommend, is for you to run the "Current Command" outside of auto-py-to-exe - does doing this solve the issue? If not, it will be a PyInstaller issue, if it is, it will be an auto-py-to-exe issue (depending on what fails).

**Comment by gernophil** [comment]
Thanks for the reply. I'll try it with the `PyInstaller` command that `auto-py-to-exe` states and then come back to you. On that behalf could you maybe shed some light on [this](https://stackoverflow.com/questions/76873518/whats-the-difference-between-pyinstaller-and-auto-py-to-exe)

**Comment by brentvollebregt** [comment]
auto-py-to-exe is just a UI layer on top of PyInstaller - it calls PyInstaller internally.

Directly from auto-py-to-exe's README.md

> A .py to .exe converter using a simple graphical interface and [PyInstaller](https://pyinstaller.readthedocs.io/en/stable/index.html) in Python.

auto-py-to-exe offers the following on top of PyInstaller:

- A UI to use PyInstaller
- Basic validation on PyInstaller inputs (like paths and .ico file types)
- Builds your script in a temporary directory so there is no need for manual cleanup
- PyInstaller and Python version checks (where some versions can be incompatible)
- Minor default differences where issues typically occur (at the moment we just change the recursion limit)
- Some non-English language support

**Comment by gernophil** [comment]
Ok, thanks for this :).
So, I guess this
>     * Builds your script in a temporary directory so there is no need for manual cleanup
is the reason, why I don't get the `build` folder and the `.spec` file? Wouldn't the `spec` file be good to have though?

**Comment by brentvollebregt** [comment]
Yep, that is the reason. If you want the .spec file, I would recommend using PyInstaller directly. auto-py-to-exe offers JSON configuration files as a substitute.

**Comment by gernophil** [comment]
Ok, here's a little update on the `codesign`: If I run it directly in the command-line (via `PyInstaller`) It takes about 30 minutes to finish. The output of the terminal seems to be the same like in the `auto-py-to-exe` console. However, it is much faster. In the end signing was still not successful, but I think, that's a different issue. It seems like your `auto-py-to-exe` looses a lot of performance from `PyInstaller` (at least using macOS and `codesign`).

**Comment by brentvollebregt** [comment]
That's interesting - I have faced speed issues when running auto-py-to-exe through vs code but running directly in the terminal, I haven't seen any loss in speed.

When you ran auto-py-to-exe, did you have the project open in vs code and run it through the "Run and Debug" option or did you use the terminal?

**Comment by gernophil** [comment]
How do you know I use VSCode ;)? I do actually, but I only use it as a code editor not to run anything. IIRC I tried both, but it did not change anything about the performance. If I run anything (at least Python based) I always start it directly from terminal.

**Comment by brentvollebregt** [comment]
Hmm I see. When the codesigning was processing, were there logs being output? Potentially these could offer some insight.
