### ISSUE TITLE
Translation Dutch added

### ISSUE THREAD

**Issue by barremans** [brentvollebregt/auto-py-to-exe#413]
[i18n.txt](https://github.com/brentvollebregt/auto-py-to-exe/files/12332369/i18n.txt)

Changed .js to .txt for upload

grts
Barre

**Comment by brentvollebregt** [comment]
Thanks @barremans! I've just added these to master in dbcd8fa2bd90274f0bfb38d8d800af2b6dd0eba8.

Are you able to pull the latest changes and validate that they appear correctly before I create a release? I changed the label in the dropdown to `Dutch (Nederlands)` to match the others.

**Comment by barremans** [comment]
Goodmorning Brent I din’t have validate, because i can’t find where the i18n.js file is on my computer. GrtzBarre Verzonden vanuit Mail voor Windows Van: Brent VollebregtVerzonden: maandag 14 augustus 2023 15:08Aan: brentvollebregt/auto-py-to-exeCC: barremans; MentionOnderwerp: Re: [brentvollebregt/auto-py-to-exe] Translation Dutch added (Issue #413) Thanks @barremans! I've just added these to master in dbcd8fa.Are you able to pull the latest changes and validate that they appear correctly before I create a release? I changed the label in the dropdown to Dutch (Nederlands) to match the others.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by barremans** [comment]
I changed a couple of lines, and validate
[i18n.txt](https://github.com/brentvollebregt/auto-py-to-exe/files/12342128/i18n.txt)

**Comment by brentvollebregt** [comment]
I've just pushed the changes into master - if you pull down the changes and those look good, I'll create a release for PyPI.

**Comment by barremans** [comment]
looks good to me

**Comment by brentvollebregt** [comment]
Thanks for the contribution! This has been released in [v2.37.0](https://github.com/brentvollebregt/auto-py-to-exe/releases/tag/v2.37.0) 🚀
