### ISSUE TITLE
error with xgboost

### ISSUE THREAD

**Issue by lz666win** [brentvollebregt/auto-py-to-exe#414]
I try to convert xgboost, a machine learning package to an exe, there is not any error when i convert it, like this:
Running auto-py-to-exe v2.36.0
Building directory: C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1
Provided command: pyinstaller --noconfirm --onefile --console --add-data "E:/lz666/Pytorch-lstm-forecast-main/Pytorch-lstm-forecast-main;Pytorch-lstm-forecast-main/" --add-data "E:/lz666/Pytorch-lstm-forecast-main/Pytorch-lstm-forecast-main/xgboost.dll;."  "E:/lz666/Pytorch-lstm-forecast-main/Pytorch-lstm-forecast-main/xgboost_fsp_left.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console --add-data E:/lz666/Pytorch-lstm-forecast-main/Pytorch-lstm-forecast-main;Pytorch-lstm-forecast-main/ --add-data E:/lz666/Pytorch-lstm-forecast-main/Pytorch-lstm-forecast-main/xgboost.dll;. E:/lz666/Pytorch-lstm-forecast-main/Pytorch-lstm-forecast-main/xgboost_fsp_left.py --distpath C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\application --workpath C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\build --specpath C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1

6159161 INFO: PyInstaller: 5.13.0
6159165 INFO: Python: 3.7.13 (conda)
6159167 INFO: Platform: Windows-7-6.1.7601-SP1
6159171 INFO: wrote C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\xgboost_fsp_left.spec
6159181 INFO: Extending PYTHONPATH with paths
['E:\\lz666\\Pytorch-lstm-forecast-main\\Pytorch-lstm-forecast-main']
6159835 INFO: Appending 'datas' from .spec
6159925 INFO: checking Analysis
6159929 INFO: Building Analysis because Analysis-01.toc is non existent
6159931 INFO: Reusing cached module dependency graph...
6159982 INFO: Caching module graph hooks...
6160189 INFO: running Analysis Analysis-01.toc
6160197 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\ProgramData\Anaconda3\envs\yolov5\python.exe
6160631 INFO: Analyzing E:\lz666\Pytorch-lstm-forecast-main\Pytorch-lstm-forecast-main\xgboost_fsp_left.py
6160677 INFO: Loading module hook 'hook-numpy.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6161473 INFO: Loading module hook 'hook-difflib.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6161659 INFO: Loading module hook 'hook-platform.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6161923 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6162631 INFO: Loading module hook 'hook-xml.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6162674 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6163858 INFO: Loading module hook 'hook-pandas.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6166306 INFO: Loading module hook 'hook-pytz.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6166603 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6170065 INFO: Loading module hook 'hook-scipy.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6170369 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6171075 INFO: Processing pre-safe import module hook distutils from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-distutils.py'.
6171079 INFO: Processing pre-find module path hook distutils from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
6171578 INFO: Loading module hook 'hook-distutils.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6171657 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6171867 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6175538 INFO: Loading module hook 'hook-importlib_metadata.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6176334 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6176950 INFO: Loading module hook 'hook-scipy.linalg.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6177315 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6178362 INFO: Loading module hook 'hook-matplotlib.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6178822 INFO: Loading module hook 'hook-packaging.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6178981 INFO: Processing pre-safe import module hook gi from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-gi.py'.
6179177 INFO: Loading module hook 'hook-PIL.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6179253 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6180818 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6181506 INFO: Loading module hook 'hook-jinja2.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6183369 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6183825 INFO: Processing pre-safe import module hook six.moves from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
6185443 INFO: Loading module hook 'hook-IPython.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6187782 INFO: Loading module hook 'hook-pygments.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6192461 INFO: Loading module hook 'hook-wcwidth.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6192967 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6194186 INFO: Loading module hook 'hook-jedi.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6195197 INFO: Loading module hook 'hook-parso.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6196857 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6198747 INFO: Loading module hook 'hook-certifi.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6204674 INFO: Loading module hook 'hook-pandas.plotting.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6204862 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6207381 INFO: Loading module hook 'hook-PyQt5.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6208639 INFO: Loading module hook 'hook-sklearn.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6209220 INFO: Loading module hook 'hook-sklearn.utils.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6210077 INFO: Loading module hook 'hook-sklearn.cluster.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6210119 INFO: Loading module hook 'hook-sklearn.metrics.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6210211 INFO: Loading module hook 'hook-sklearn.metrics.cluster.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6210325 INFO: Loading module hook 'hook-sklearn.metrics.pairwise.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6210601 INFO: Loading module hook 'hook-sklearn.neighbors.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6210793 INFO: Loading module hook 'hook-sklearn.linear_model.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6212151 INFO: Loading module hook 'hook-scipy.io.matlab.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6212831 INFO: Loading module hook 'hook-sklearn.tree.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6213118 INFO: Processing module hooks...
6213124 WARNING: Hidden import "sklearn.neighbors._typedefs" not found!
6213158 INFO: Loading module hook 'hook-encodings.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6214281 INFO: Loading module hook 'hook-heapq.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6214287 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6214295 INFO: Matplotlib backend selection method: automatic discovery of used backends
6214763 INFO: Trying determine the default backend as first importable candidate from the list: ['Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
6215444 INFO: Selected matplotlib backends: ['Qt5Agg']
6215871 INFO: Loading module hook 'hook-pickle.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6216147 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6216230 INFO: Processing pre-safe import module hook win32com from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
6219097 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6219294 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6219588 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6219785 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6219871 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6219877 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6219885 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6220010 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks'...
6221919 INFO: Looking for ctypes DLLs
6222061 INFO: Analyzing run-time hooks ...
6222085 INFO: Including run-time hook 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
6222093 INFO: Including run-time hook 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
6222101 INFO: Including run-time hook 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
6222111 INFO: Including run-time hook 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
6222117 INFO: Including run-time hook 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
6222129 INFO: Including run-time hook 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_traitlets.py'
6222135 INFO: Including run-time hook 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
6222142 INFO: Including run-time hook 'C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
6222411 INFO: Looking for dynamic libraries
6228563 INFO: Looking for eggs
6228680 INFO: Using Python library C:\ProgramData\Anaconda3\envs\yolov5\python37.dll
6228687 INFO: Found binding redirects: 
[]
6228730 INFO: Warnings written to C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\build\xgboost_fsp_left\warn-xgboost_fsp_left.txt
6229255 INFO: Graph cross-reference written to C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\build\xgboost_fsp_left\xref-xgboost_fsp_left.html
6229582 INFO: checking PYZ
6229591 INFO: Building PYZ because PYZ-01.toc is non existent
6229598 INFO: Building PYZ (ZlibArchive) C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\build\xgboost_fsp_left\PYZ-01.pyz
6233717 INFO: Building PYZ (ZlibArchive) C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\build\xgboost_fsp_left\PYZ-01.pyz completed successfully.
6233934 INFO: checking PKG
6233941 INFO: Building PKG because PKG-01.toc is non existent
6233951 INFO: Building PKG (CArchive) xgboost_fsp_left.pkg
6516703 INFO: Building PKG (CArchive) xgboost_fsp_left.pkg completed successfully.
6516891 INFO: Bootloader C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
6516898 INFO: checking EXE
6516907 INFO: Building EXE because EXE-01.toc is non existent
6516917 INFO: Building EXE from EXE-01.toc
6516922 INFO: Copying bootloader EXE to C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\application\xgboost_fsp_left.exe.notanexecutable
6516929 INFO: Copying icon to EXE
6516934 INFO: Copying icons from ['C:\\ProgramData\\Anaconda3\\envs\\yolov5\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
6516938 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
6516943 INFO: Writing RT_ICON 1 resource with 3752 bytes
6516947 INFO: Writing RT_ICON 2 resource with 2216 bytes
6516951 INFO: Writing RT_ICON 3 resource with 1384 bytes
6516955 INFO: Writing RT_ICON 4 resource with 37019 bytes
6516960 INFO: Writing RT_ICON 5 resource with 9640 bytes
6516963 INFO: Writing RT_ICON 6 resource with 4264 bytes
6516969 INFO: Writing RT_ICON 7 resource with 1128 bytes
6516974 INFO: Copying 0 resources to EXE
6516979 INFO: Embedding manifest in EXE
6516985 INFO: Updating manifest in C:\Users\cp\AppData\Local\Temp\tmp8tbc6kg1\application\xgboost_fsp_left.exe.notanexecutable
6516990 INFO: Updating resource type 24 name 1 language 0
6516996 INFO: Appending PKG archive to EXE
6517571 INFO: Fixing EXE headers
6529960 INFO: Building EXE from EXE-01.toc completed successfully.

Moving project to: C:\Users\cp\output
Complete.

but when I use it, xgboost.dll can not findlike this
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/30901091/ef579560-70b9-4062-aaff-4757ec4f1afc)

can you help me how to convert it completely？

**Comment by brentvollebregt** [comment]
Can you please fill out the template you cleared? Having that full error would make things much easier - the template asks for it to not be in a screenshot.

**Comment by lz666win** [comment]
> Can you please fill out the template you cleared. Having that full error would make things much easier - the template asks for it to not be in a screenshot.

now i got a way to solve. Take this  dir from your conda env Lib\site-packages\xgboost, and add this dir in add-data, then it can work.
