### ISSUE TITLE
Running python 3.6.6 Windows 10

### ISSUE THREAD

**Issue by Y4hL** [brentvollebregt/auto-py-to-exe#42]
using "pip install auto-py-to-exe" install after running "auto-py-to-exe" in cmd, it does not open any new windows nor outputs a error file

**Comment by brentvollebregt** [comment]
All my development is primarily in 3.6.6 so this works fine for me. Did the window pop-up in the background? That can occur on some setups. Also does the command end or wait?

**Comment by Y4hL** [comment]
No windows were opened in the background either, and the command ended after about one second

**Comment by brentvollebregt** [comment]
Interesting. I cannot reproduce this issue, are you able to debug with breakpoints? I'm interested if it's making it to auto_py_to_exe.__main__:280/282

**Comment by Y4hL** [comment]
I will try tomorrow, short on time today

**Comment by liuh886** [comment]
same thing to me

**Comment by brentvollebregt** [comment]
Could you please try the lastest changes? I see Eel v0.10.0 has made breaking changes yesterday

**Comment by brentvollebregt** [comment]
The lastest commit on master has been put on PyPi so you can use pip to install the latest

**Comment by liuh886** [comment]
> The lastest commit on master has been put on PyPi so you can use pip to install the latest

thanks~ now its working

**Comment by brentvollebregt** [comment]
@Y4hL is it now working for you?

**Comment by liuh886** [comment]
auto-py-to-exe is running now as GUI, although still cannot deal with my PyQT5 script

and i think its the problem of pyinstaller

**Comment by brentvollebregt** [comment]
PyQt5 runs just fine after packaging when done properly. Did you read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/)? This can help to debug the issue.

**Comment by brentvollebregt** [comment]
No further information provided so I'm going to assume this was fixed.
