### ISSUE TITLE
How to create a EXE that have icon in the taskbar

### ISSUE THREAD

**Issue by mfirouzin** [brentvollebregt/auto-py-to-exe#43]
How can Create a .EXE File that the icon be visible on the taskbar?
This convertor use the icon file and you can see the icon in the file explorer but when you run it in the taskbar you just see exe files icon
how we can change this to new icon?

**Comment by brentvollebregt** [comment]
The icon that is visible on the taskbar and in the upper left corner of your GUI (if it exists) is controlled by your script. This means if you're using tkinter, PyQt or something else to create your GUI, use the methods provided by the library to set the icon.

If you package a script that does not use a GUI (console application), the icon provided will be what appears in the taskbar.
