### ISSUE TITLE
Stuck in initialisation

### ISSUE THREAD

**Issue by JPB1JPB1** [brentvollebregt/auto-py-to-exe#435]
I was using auto_py_to_exe with sucess....

Now it stucks in initialisation ... waiting for ??

Under W10 in visual studio and python 3.9.12  maximum ( it was failing with 3.10.4.. another issue but not for now)

Any idea , stuck in initialisation ?   Never seen before...

Great project and very usefull
JJ

**Comment by JPB1JPB1** [comment]
Better when i came back with pyinstaller 4.10   not 6.0.0 not 5.13.2 .... 
Any idea....
On going

**Comment by brentvollebregt** [comment]
Is there any output in the console that you started auto-py-to-exe from? Also the auto-py-to-exe UI is Chrome, is there anything in the DevTools console?

**Comment by JPB1JPB1** [comment]
Good news, 
i'm getting Pyinstaller 6.0 starting with the right directory using run.py version __initi__.py 2.41 and not 2.18 ( older version..)...
Thanks for your reply, keep going on the good project and very usefull...
Have a nice day.
jjj

**Comment by brentvollebregt** [comment]
Sounds like you may have been using an outdated version of auto-py-to-exe - great to hear you got this fixed
