### ISSUE TITLE
Why is my exe file located next to the _internal directory and not inside?

### ISSUE THREAD

**Issue by Dzhus1** [brentvollebregt/auto-py-to-exe#436]
![Screenshot_3](https://github.com/brentvollebregt/auto-py-to-exe/assets/71518577/ec533fae-90b7-4642-bb3b-c835dcd6a818)

After using auto-py-to-exe, my exe file is not placed inside the directory, it is located outside of it. Because of this, my entire script breaks down. How can I make bot.exe inside _internal? Previously, all my scripts were inside one directory, how can I get this back?

`{
 "version": "auto-py-to-exe-configuration_v1",
 "pyinstallerOptions": [
  {
   "optionDest": "noconfirm",
   "value": true
  },
  {
   "optionDest": "filenames",
   "value": "C:/Users/user/PycharmProjects/Bot/bot.py"
  },
  {
   "optionDest": "onefile",
   "value": false
  },
  {
   "optionDest": "console",
   "value": true
  },
  {
   "optionDest": "icon_file",
   "value": "C:/Users/user/Desktop/Steam Scout.ico"
  },
  {
   "optionDest": "clean_build",
   "value": false
  },
  {
   "optionDest": "strip",
   "value": false
  },
  {
   "optionDest": "noupx",
   "value": false
  },
  {
   "optionDest": "disable_windowed_traceback",
   "value": false
  },
  {
   "optionDest": "uac_admin",
   "value": false
  },
  {
   "optionDest": "uac_uiaccess",
   "value": false
  },
  {
   "optionDest": "argv_emulation",
   "value": false
  },
  {
   "optionDest": "bootloader_ignore_signals",
   "value": false
  },
  {
   "optionDest": "datas",
   "value": "C:/Users/user/PycharmProjects/Bot/config.json;."
  },
  {
   "optionDest": "datas",
   "value": "C:/Users/user/PycharmProjects/Bot/config;config/"
  }
 ],
 "nonPyinstallerOptions": {
  "increaseRecursionLimit": true,
  "manualArguments": ""
 }
}`

**Comment by brentvollebregt** [comment]
This is a new feature of PyInstaller 6 I believe

**Comment by elfi-ox** [comment]
Hey, you marked this issue as "Closed" so I assume you may have found a solution, you didn't mention it tho and since i'm currently having the same issue, i'd really like to know how did you solve it ?
