### ISSUE TITLE
如何不让创建的程序运行完自动关闭窗口

### ISSUE THREAD

**Issue by gt1226500986** [brentvollebregt/auto-py-to-exe#437]
现在创建的程序运行完会自动关闭运行窗口,如何设置让创建的程序运行完之后手动来关闭运行窗口

**Comment by brentvollebregt** [comment]
English translation (for others curious):

> How to prevent the created program from automatically closing the window after running
> Now the created program will automatically close the running window after running. How to set up the running window to be closed manually after the created program is finished running?

I would recommend giving the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/) a read. Under ["The Terminal Just Opens and Closes But There Are No Errors"](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#the-terminal-just-opens-and-closes-but-there-are-no-errors) I recommend to check it runs properly with python by itself when double-clicking before packaging, and if that's fine follow the debugging steps.
