### ISSUE TITLE
Help to convert to source code

### ISSUE THREAD

**Issue by clemstarosta** [brentvollebregt/auto-py-to-exe#438]
Hello,

My computer has been stolen with all my source code. I only have the executable file folders that I generated with auto-py-to-exe.

I don't have much hope, but is it possible to reverse engineer and convert the source code?

Thanks in advance!

**Comment by brentvollebregt** [comment]
Take a look at #311 - it's a year old but still relevant,

> auto-py-to-exe uses PyInstaller in the background - so you will want to search for a tool to decompile PyInstaller bundles.
> 
> I haven't done it myself but [pyinstxtractor](https://github.com/extremecoders-re/pyinstxtractor) looks promising.
