### ISSUE TITLE
time.sleep() is not working correctly

### ISSUE THREAD

**Issue by revolexGeek** [brentvollebregt/auto-py-to-exe#441]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package 

**Describe the bug**
When running an application through a Python file (.py), the time.sleep(x) command works fine, but after compiling through auto-py-to-exe, it happens that no time.sleep(x) is triggered and the program runs straight through without the necessary stops.

**To Reproduce**
Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):
0. Run python code via `python main.py` and see that everything works fine!
1. Compile code via auto-py-to-exe GUI ~
1.1. Select `One File`
1.2. Select `Console Based`
1.3. Select some icon
1.4. Give it some name in `Advanced` category
1.5. Compile (convert) it.
2. Run converted executable file and see that everything isnt fine with sleeps between function calls.

**A minimal reproducible example:**
```python
import time

def main_sleep_test_example():
    print("Sleep test example")
    while True:
        print("Sleeping...")
        time.sleep(3)
        print("Wake up!")


if __name__ == '__main__':
    main_sleep_test_example()
```

**Live representation of error**
![Error](https://github.com/brentvollebregt/auto-py-to-exe/assets/86723750/a277dc18-b4a6-47e5-a366-62404730b25a)

**Expected behavior**
Delays had to be triggered so that the functioning of the converted program was identical to that of the unconverted program.

**Your Environment:**
- Python version (`python --version`): 3.9.0
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.42.0
- PyInstaller version (`pip show pyinstaller`): 6.1.0
- Eel version (`pip show eel`):  0.16.0

**Comment by brentvollebregt** [comment]
I've just tried to reproduce this with the following,

- Python version: 3.9.9 (only difference)
- auto-py-to-exe version: 2.42.0
- PyInstaller version: 6.1.0
- Eel version: 0.16.0

Unfortunately, this didn't happen for me - do you know if this only happens on Python 3.9.0?

**Comment by revolexGeek** [comment]
> I've just tried to reproduce this with the following,
> 
> * Python version: 3.9.9 (only difference)
> * auto-py-to-exe version: 2.42.0
> * PyInstaller version: 6.1.0
> * Eel version: 0.16.0
> 
> Unfortunately, this didn't happen for me - do you know if this only happens on Python 3.9.0?

I recently changed Python version from 3.8.0 to 3.9.0, while on 3.8.0 everything was great with auto-py-to-exe, but on 3.9.0 suddenly this happens 🤷

**Comment by brentvollebregt** [comment]
Have you tried any other versions of Python above 3.9.0? Did any of those work?

Also if you run `pyinstaller --noconfirm --onefile --console  "path/to/file.py"` (using PyInstaller from your Python 3.9.0 environment) and then run the output exe, does this also have the same issue?

**Comment by MothScientist** [comment]
Checked on 2 versions:
### 1:
- Python version: 3.11.6
- auto-py-to-exe version: 2.42.0
- PyInstaller version: 6.1.0
- Eel version: 0.16.0

__The problem is not observed.__

### 2:
- Python version: 3.9.0
- auto-py-to-exe version: 2.42.0
- PyInstaller version: 6.1.0
- Eel version: 0.16.0

__The problem repeats itself, as stated in the description.__

**Comment by MothScientist** [comment]
I ran it like this: ```pyinstaller --noconfirm --onefile --console "path/to/file.py"``` - the problem repeats, no changes (version 3.9.0)

**Comment by brentvollebregt** [comment]
Thanks for running those, sorry for the late reply. The fact that this still happens when running `pyinstaller ...` shows the issue is with [PyInstaller](https://github.com/pyinstaller/pyinstaller) and not anything specific to auto-py-to-exe.

Unfortunately, there is nothing I can do about this in auto-py-to-exe. Still, you could raise it as a [PyInstaller issue](https://github.com/pyinstaller/pyinstaller/issues) - your demo (code and gif) is excellent and the simple `pyinstaller --noconfirm --onefile --console "path/to/file.py"` command would be ideal to note in the issue as well as your PyInstaller and Python versions.

**Comment by MothScientist** [comment]
Ok, I opened issue in the __pyinstaller__ repository: https://github.com/pyinstaller/pyinstaller/issues/8104.
If something is wrong or forgot to add something, then please write a comment to issue.

**Comment by brentvollebregt** [comment]
Looks excellent!
