### ISSUE TITLE
Output Directory in JSON

### ISSUE THREAD

**Issue by habkorn** [brentvollebregt/auto-py-to-exe#443]
Currently, the Output Directory under 'auto-py-to-exe Specific Options' is not saved in the JSON File.
Bug or feature?
KR

**Comment by brentvollebregt** [comment]
The README states,

> This JSON config export action does not save the output directory automatically as moving hosts could mean different directory structures. If you want to have the output directory in the JSON config, add the directory under `nonPyinstallerOptions.outputDirectory` in the JSON file (will need to create a new key).

This change was made for #197
