### ISSUE TITLE
兄弟 有问题

### ISSUE THREAD

**Issue by xiaokul** [brentvollebregt/auto-py-to-exe#445]
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/119649220/6378ca7c-87ce-4c59-aae1-57861bdd8aeb)
为什么我打开之后显示这样

**Comment by xiaokul** [comment]
我要怎么解决，我的电脑连接有互联网

**Comment by brentvollebregt** [comment]
Are there any errors in the console?
