### ISSUE TITLE
ERROR: Could not build wheels for bottle-websocket, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by zSynctic** [brentvollebregt/auto-py-to-exe#453]
I can't install auto-py-to-exe after formatting my pc, now I always get this error:

```
ERROR: Could not build wheels for bottle-websocket, which is required to install pyproject.toml-based projects
```

**Comment by brentvollebregt** [comment]
This doesn't seem like an auto-py-to-exe issue but more of an environment issue sorry. The issues in this repository are for the project.

You can try running `pip install setuptools wheel` incase you don't have these already. Aside from this, with the lack of context, I can't help with much else.
