### ISSUE TITLE
Failed to execute script pyi_rth_win32comgenpy

### ISSUE THREAD

**Issue by nauticalcoder** [brentvollebregt/auto-py-to-exe#46]
After creating an exe from my Python script, I am getting the following error when attempting to run the .exe.
`Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_win32comgenpy.py", line 47, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\win32com\__init__.py", line 5, in <module>
ImportError: No module named win32api
[27000] Failed to execute script pyi_rth_win32comgenpy`

Pywin32 was installed from the binary installed (after previously installing it from pip).  I haven't found a workaround for this.  The exe's were previously running but it kept throwing an error about a missing win32com module in the console window when auto-py-to-exe ran so I installed pywin32.  Now I am getting the above error.  Reverting the pywin32 installed does not have any effect.

Python 2.7

**Comment by brentvollebregt** [comment]
Is this working before it is packaged? If so, then try adding `win32api` to the --hidden-import input field in the advanced tab

**Comment by nauticalcoder** [comment]
I am not sure exactly what was going on with this but it is building now.  I am not using any --hidden-import's.  I did uninstall everything pywin32 related.  The only pip installed that appears to be win32 related is `pywin32-ctypes`.  I wish I had a better explanation for what fixed it.

**Comment by brentvollebregt** [comment]
win32api is part of the pywin32 package so it must have been getting added. This is handled by PyInstaller; unfortunately I cannot explain why it would have been added if you didn't use it.

**Comment by ronankibharath98** [comment]
> Is this working before it is packaged? If so, then try adding `win32api` to the --hidden-import input field in the advanced tab

I had the same problem in my exe file when converter from python code. But i didn't understand your answer '--hidden-import input field in the advance tab'. Can you please elaborate and help me solving my error.

**Comment by brentvollebregt** [comment]
The UI has an `Advanced` header. If you click on that, it will expand the body. There is an input by `--hidden-import` where you can put the import.

Please open a new issue if you are reporting an issue.

**Comment by gabemorris12** [comment]
I had this same issue, but uninstalling and reinstalling didn't fix it for me. To fix this, I added the ```--hidden-import "pywin32"``` flag and it worked!

**Comment by davidsandbar** [comment]
I had the same issue, I've tried:

- uninstall and reinstall everything which is pywin32, win32com related
- Added on hidden-import pywin32, win32com, pypiwin32, pywintypes
- Added in the path envs/xx/Lib/site-packages
- Added also in Additional files
- Even added a dll --add binary (saw in another forum) Lib/site-packages/pywin32_system32/pythoncom39.dll

Still not working! I don't know what to do! Any idea please?

Error : 
ModuleNotFoundError: No module named 'win32api'
[49272] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!

**Comment by brentvollebregt** [comment]
@davidsandbar are you sure the python installation / venv you are using to run auto-py-to-exe is the same installation / venv you have pywin32 etc installed in?

**Comment by davidsandbar** [comment]
> @davidsandbar are you sure the python installation / venv you are using to run auto-py-to-exe is the same installation / venv you have pywin32 etc installed in?

Many thanks for your help - at the end, what make it works was to open conda shell in admin mode, and run auto-py-to-exe from this window - and it worked
