### ISSUE TITLE
Installed auto-py-to-exe but it doesn't runs the ui

### ISSUE THREAD

**Issue by ArunJothi-prg** [brentvollebregt/auto-py-to-exe#461]
**Quick Checks**

- [x] I have read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package

**Bug Description**
 When I tried to install auto-py-to-exe using pip command `pip install auto-py-to-exe` in the command prompt as an admin , it got installed successfully. But when i try to run the code `auto-py-to-exe` to execute it, it opens chrome but nothing happens after.  

**To Reproduce**

_Steps to reproduce the behavior :_

1. Open 'cmd' as administrator. 
2. Run `pip install auto-py-to-exe`
3. Then to execute, run `auto-py-to-exe`

**Expected behavior**

 I followed the steps to install this package. And I expected that it will run perfectly as I got the needed requirements such as latest python, pip versions & Chrome installed on the system .

**My Environment:**

- Python version (`3.12.1`)
- Pip version(`24.0`)
- auto-py-to-exe version (`2.42.0`)
- PyInstaller version (`5.13.2`)
- Eel version (`0.16.0`)
- with Chrome application                                                                                   

![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/76784241/613bfacc-c238-497b-8fd6-b49dcfda638a)

**Comment by brentvollebregt** [comment]
If you execute `auto-py-to-exe --no-chrome` do you have similar results?
