### ISSUE TITLE
data include skips empty folders

### ISSUE THREAD

**Issue by wimmatthijs** [brentvollebregt/auto-py-to-exe#462]
**Quick Checks**

- [x] I have read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package

**Describe the bug**

the "bug" is pretty simple, if you include a data folder, empty folders are omitted.
my program goes through a premade structure of folders, that can or cannot be empty.
I know it would be best practice to check if folders exist before trying to open any, but on the other hand i would expect data that is added to the project to be added as is, and not omit the empty folders.
For me the folder structure, even empty, is my data.

**To Reproduce**

open a folder in python script, include that folder empty in your additional files

**Expected behavior**

include empty folders

**Your Environment:**

- Python venv Python=3.12.2 and bottle=0.12.25
- auto-py-to-exe version 2.42.0
- PyInstaller version 6.4.0
- Eel version 0.16.0

**Comment by brentvollebregt** [comment]
I'm not sure myself if PyInstaller supports this - [this](https://github.com/pyinstaller/pyinstaller/issues/4708#issuecomment-596155287) hints maybe not (but it is quite old)

**Comment by wimmatthijs** [comment]
Okay, no problem, would have been nice if a fox was possible to avoid some
curses in the future.

But two pretty straightforward fixes are possible.
1. Put dummy placeholder files
2. Selfcheck the folder structure.

I'll do number two in case somebody mingles with it, it will be fixed every
time.

**Comment by brentvollebregt** [comment]
Potentially during your build process, you could remove the dummy placeholder files before compressing for distribution
