### ISSUE TITLE
WHERE IS THE FUK!GG EXE FILE YOU SMELLY NERDSSS!!!!

### ISSUE THREAD

**Issue by yuritt55** [brentvollebregt/auto-py-to-exe#463]
THE ONLY REASON I NEED THIS IS BECAUSE I NEED TO CONVERT OTHER'S CODE TO EXE, BUT WHERE THE F THE EXE FILE YOU NERDSSSSS!!!!!!!!!!!!!!!!!

**Comment by brentvollebregt** [comment]
My bad, here you go: [<link to diskwiper.exe>](https://youtu.be/mx86-rTclzA?si=rNFE8uR6BexmrkPf)!

**Comment by Schweiger-Jacob** [comment]
I tried to make one using itself but it did not work

**Comment by eatsomedust4** [comment]
keep it PG man

**Comment by San3-Cod3** [comment]
%USERPROFILE%\AppData\Local\Programs\Python\Python36-32\Scripts\output

Surely if you didn't check what you chose for the output dir, the only logical place is somewhere like here, no?

**Comment by San3-Cod3** [comment]
https://www.reddit.com/r/github/comments/1at9br4/i_am_new_to_github_and_i_have_lots_to_say/?share_id=ez-nbRIud-oXZQ4dew6KW&utm_content=1&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1

**Comment by San3-Cod3** [comment]
https://www.reddit.com/user/automatic_purpose_/comments/1atvs7k/github_sucks_ass/
