### ISSUE TITLE
Child process died calling import_library() with args=('pyqtgraph.canvas',) and kwargs={}

### ISSUE THREAD

**Issue by snowuyl** [brentvollebregt/auto-py-to-exe#465]
**Quick Checks**

- [ ] I have read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
yes
- [ ] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
yes
- [ ] I have made sure my application/script runs before trying to package
yes

**Describe the bug**
I use auto-py-to-exe to create executable file. But it failed with the following error messages. 
File "C:\Users\broth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyInstaller\isolated\_parent.py", line 307, in call
    raise SubprocessDiedError(
PyInstaller.isolated._parent.SubprocessDiedError: Child process died calling import_library() with args=('pyqtgraph.canvas',) and kwargs={}. Its exit code was 3221225725.
Traceback (most recent call last):
  File "C:\Users\broth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument

**Expected behavior**

auto-py-to-exe can generate executable file successfully.

**Your Environment:**
- Python version (`python --version`): v3.11.8
- auto-py-to-exe version (`pip show auto-py-to-exe`): v2.42.0
- PyInstaller version (`pip show pyinstaller`): v6.4.0
- Eel version (`pip show eel`): v0.16.0

**Comment by snowuyl** [comment]
Procedure to reproduce this issue.
1. Unzipping PyQtGraph.zip to D:\ folder
2. pyinstaller --onefile D:\PyQtGraph\main.py

**Comment by snowuyl** [comment]
[PyQtGraph.zip](https://github.com/brentvollebregt/auto-py-to-exe/files/14381347/PyQtGraph.zip)

**Comment by brentvollebregt** [comment]
That script in the zip uses numpy, PyQt6 and pyqtgraph but I do not see any reproduction steps outlining these. To make this whole process a lot easier, could you follow [this template](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and make sure to add reproduction steps with a **minimal reproducible example** - you can put the python code in tripple backticks. I imagine this error only occurs when using one of the libraries, not all 3 at once.

**Comment by snowuyl** [comment]
Thanks for your reply! I can generate main.exe successfully after installing pyqtgraph from https://github.com/pyqtgraph/pyqtgraph master branch.
