### ISSUE TITLE
Pyinstaller Version Control

### ISSUE THREAD

**Issue by mcagriaksoy** [brentvollebregt/auto-py-to-exe#467]
**New Feature Description**

I have a version of Pyinstaller which is not updated for many months I guess. When I opened the auto-py-to-exe I have seen my PyInstaller version. I guess, We can add a popup or some kind of warning to inform the version of pyinstaller is not Latest!
Otherwise, the auto-py-to-exe working good but, the user may want to everything is up-to-date!

**Reason For New Feature**

Inform user which version of PyInstaller is using currently. Which version of version is latest. Then, user can decide update it now or later..

**Comment by brentvollebregt** [comment]
Great idea! We can request `https://api.github.com/repos/pyinstaller/pyinstaller/releases/latest` and compare it to `from PyInstaller import __version__ as pyinstaller_version_string`. Need to make sure this is done in an async way to not hold up the UI from loading.
