### ISSUE TITLE
Pyinstaller 5.X.X is better?

### ISSUE THREAD

**Issue by mcagriaksoy** [brentvollebregt/auto-py-to-exe#468]
**New Feature Description**
Hello, again me. In windows 11, defender does not like the PyInstaller version 6.X.X. If user change their PyInstaller version to 5.x.x *currently latest one is 5.13.2* Windows Defender won`t cause any false positive alert. Maybe we can inform the user if they have faced some kind of alert caused by their antivirus?

Basically the problem caused by the --windowed parameter in pyinstaller. Also we can add some information on this parameter frontend side? The PyInstaller5 is using different "python windowed" src. So..

More information at: https://stackoverflow.com/questions/77239487/win32ctypes-pywin32-pywintypes-error-when-using-pyinstaller-in-vs-code-possib

**Reason For New Feature**

Make auto-py-to-exe great again?!

**Comment by brentvollebregt** [comment]
Looks like you're seeing something similar to this: https://github.com/pyinstaller/pyinstaller/issues/7967

I wouldn't say Pyinstaller 5.X.X is "better" - just that the binaries in the outputs can be different and seen differently by different antivirus vendors.

**Comment by mcagriaksoy** [comment]
So, what do you think can we add some information message somewhere else?

For example, for windows defender is angry when we use pyinstaller 6.x.x with windowed feature.
For example, for avast is angry when we use icon option. 
and so on..

**Comment by brentvollebregt** [comment]
I can chuck some notes in the help post under the ["My Antivirus Detected the exe as a Virus"](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#my-antivirus-detected-the-exe-as-a-virus) section.

Aside from those two points, are you aware of anything else specific? Or maybe other GitHub issues that discuss these specifics more?

**Comment by brentvollebregt** [comment]
Also looking for an existing GitHub issue of this one,

> For example, for avast is angry when we use icon option.

Was that just an example or an example of an actual thing that could be added (something that is happening)?

**Comment by mcagriaksoy** [comment]
Yes, I have seen the virus alert on Avast antivirus when I set the icon on .exe. Also some people mentioned that problem here: https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

**Comment by brentvollebregt** [comment]
I'm not keen to recommend not adding an icon, but have added a couple of good answers from that SO question - thank you!
