### ISSUE TITLE
auto-py-to-exe and configparser issue

### ISSUE THREAD

**Issue by AlexiJemano** [brentvollebregt/auto-py-to-exe#470]
For some context I will say that the conversion was successful no errors but when i try to run the exe. a cmd appears says something fast and despairs (SEE THE LINK FOR VIDEO AND SCREENSHOT, ITS HARD TO EXPLAINE) 

Video (How I run the .exe) - https://drive.google.com/file/d/1gNkeBaVFX-smVcsCEkh1c5aKvLmc0v-V/view?usp=sharing
Screenshot (The error) - https://drive.google.com/file/d/1s4bLmp5GMoHFeLOM9HXgvXLHnU1rlOMC/view?usp=sharing

(sorry for my bad English)

**Comment by brentvollebregt** [comment]
Have you followed the debugging steps from the help post? What did you get from that? It would also be great if you could fill out the issue template - it can help us get to a solution much faster.

**Comment by AlexiJemano** [comment]
> Have you followed the debugging steps from the help post? What did you get from that? It would also be great if you could fill out the issue template - it can help us get to a solution much faster.

I followed "The exe Runs But Does Some Unexpected Things" but it didnt help

**Comment by AlexiJemano** [comment]
Also when i try to use One File methoed it runs in task manager but I dont see anything

**Comment by AlexiJemano** [comment]
Idk if it will help but the log while converting seems ok 
Full log:
Running auto-py-to-exe v2.42.0
Building directory: C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc
Provided command: pyinstaller --noconfirm --onedir --console --icon "C:/Users/Administrator/Documents/IT/Python/pythonProject3/data/worldtorrent.ico"  "C:/Users/Administrator/Documents/IT/Python/pythonProject3/main.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onedir --console --icon C:/Users/Administrator/Documents/IT/Python/pythonProject3/data/worldtorrent.ico C:/Users/Administrator/Documents/IT/Python/pythonProject3/main.py --distpath C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc\application --workpath C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc\build --specpath C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc

32167 INFO: PyInstaller: 6.5.0, contrib hooks: 2024.3
32186 INFO: Python: 3.11.4 (conda)
32218 INFO: Platform: Windows-10-10.0.22621-SP0
32234 INFO: wrote C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc\main.spec
32255 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Administrator\\Documents\\IT\\Python\\pythonProject3']
34116 INFO: checking Analysis
34121 INFO: Building Analysis because Analysis-00.toc is non existent
34124 INFO: Initializing module dependency graph...
34138 INFO: Caching module graph hooks...
34187 INFO: Analyzing base_library.zip ...
46278 INFO: Loading module hook 'hook-encodings.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
50932 INFO: Loading module hook 'hook-heapq.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
51743 INFO: Loading module hook 'hook-pickle.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
55569 INFO: Caching module dependency graph...
55773 INFO: Running Analysis Analysis-00.toc
55797 INFO: Looking for Python shared library...
55834 INFO: Using Python shared library: C:\ProgramData\anaconda3\python311.dll
55850 INFO: Analyzing C:\Users\Administrator\Documents\IT\Python\pythonProject3\main.py
56055 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
56177 INFO: Loading module hook 'hook-pygame.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\pygame\\__pyinstaller'...
56617 INFO: Loading module hook 'hook-numpy.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\_pyinstaller'...
57647 INFO: Loading module hook 'hook-difflib.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
57930 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
58167 INFO: Loading module hook 'hook-xml.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
59212 INFO: Loading module hook 'hook-platform.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
60615 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
60947 INFO: Loading module hook 'hook-psutil.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
62992 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
71006 INFO: Processing pre-safe import module hook win32com from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
71107 INFO: Loading module hook 'hook-win32com.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
71123 INFO: Loading module hook 'hook-pythoncom.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
71255 INFO: Loading module hook 'hook-pywintypes.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
71767 INFO: Processing pre-safe import module hook distutils from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-distutils.py'.
71788 INFO: Processing pre-find module path hook distutils from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
72239 INFO: Loading module hook 'hook-distutils.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
72596 INFO: Loading module hook 'hook-pandas.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
78502 INFO: Loading module hook 'hook-pytz.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
79722 INFO: Processing pre-safe import module hook six.moves from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
80972 INFO: Loading module hook 'hook-scipy.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
81007 INFO: Loading module hook 'hook-pytest.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
81294 INFO: Loading module hook 'hook-importlib_metadata.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
81483 INFO: Loading module hook 'hook-py.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
82813 INFO: Loading module hook 'hook-packaging.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
82939 INFO: Loading module hook 'hook-pygments.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
95669 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
96450 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
96598 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
106226 INFO: Loading module hook 'hook-matplotlib.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
106804 INFO: Processing pre-safe import module hook gi from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-gi.py'.
106977 INFO: Loading module hook 'hook-PIL.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
107101 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
110610 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
110734 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
111733 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
112738 INFO: Loading module hook 'hook-jinja2.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
116536 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
117411 INFO: Loading module hook 'hook-IPython.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
120618 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
121331 INFO: Loading module hook 'hook-wcwidth.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
123378 INFO: Loading module hook 'hook-jedi.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
125261 INFO: Loading module hook 'hook-parso.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
125965 INFO: Loading module hook 'hook-docutils.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
141833 INFO: Loading module hook 'hook-sphinx.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
171513 INFO: Loading module hook 'hook-babel.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
174403 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
177902 INFO: Loading module hook 'hook-nbformat.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
178205 INFO: Loading module hook 'hook-jsonschema.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
179136 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
179574 INFO: Loading module hook 'hook-charset_normalizer.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
179809 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
187713 INFO: Loading module hook 'hook-bcrypt.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
187908 INFO: Loading module hook 'hook-certifi.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
189056 INFO: Loading module hook 'hook-platformdirs.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
190245 INFO: Loading module hook 'hook-zmq.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
195428 INFO: Loading module hook 'hook-nacl.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
197139 INFO: Loading module hook 'hook-PyQt5.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
198259 INFO: Loading module hook 'hook-shelve.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
198509 INFO: Loading module hook 'hook-scipy.linalg.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
199057 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
199635 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
199776 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
202164 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
203531 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
205327 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
207655 INFO: Loading module hook 'hook-pyarrow.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
213192 INFO: Loading module hook 'hook-dask.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
214912 INFO: Loading module hook 'hook-numba.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
214943 INFO: Loading module hook 'hook-llvmlite.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
223310 INFO: Loading module hook 'hook-lz4.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
223486 INFO: Loading module hook 'hook-h5py.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
224596 INFO: Loading module hook 'hook-bokeh.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
229126 INFO: Loading module hook 'hook-xyzservices.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
231187 INFO: Loading module hook 'hook-pandas.plotting.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
232874 INFO: Loading module hook 'hook-botocore.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
236623 INFO: Loading module hook 'hook-sqlalchemy.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
241715 INFO: Loading module hook 'hook-argon2.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
241989 INFO: Loading module hook 'hook-notebook.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
246090 INFO: Loading module hook 'hook-anyio.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
256012 INFO: Loading module hook 'hook-keyring.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
263478 INFO: Loading module hook 'hook-boto3.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
279285 INFO: Loading module hook 'hook-openpyxl.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
279552 INFO: Loading module hook 'hook-lxml.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
283082 INFO: Loading module hook 'hook-lxml.etree.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
285721 INFO: Loading module hook 'hook-tables.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
286643 INFO: Loading module hook 'hook-pandas.io.clipboard.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
286669 INFO: Loading module hook 'hook-qtpy.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
286677 INFO: hook-qtpy: selected 'PyQt5' as Qt bindings because hook for 'PyQt5' has been run before.
286682 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
286931 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
288240 INFO: Processing module hooks...
289876 INFO: Loading module hook 'hook-lxml.isoschematron.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
289990 INFO: Processing pre-safe import module hook tensorflow from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-tensorflow.py'.
290184 INFO: Loading module hook 'hook-zope.interface.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
292050 INFO: Loading module hook 'hook-gevent.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
299413 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
303587 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
303604 INFO: Matplotlib backend selection method: automatic discovery of used backends
304151 INFO: Trying determine the default backend as first importable candidate from the list: ['QtAgg', 'Qt5Agg', 'Gtk4Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
304978 INFO: Selected matplotlib backends: ['QtAgg']
304999 INFO: Loading module hook 'hook-matplotlib.backends.backend_qtagg.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
305021 INFO: Loading module hook 'hook-matplotlib.backends.qt_compat.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
305048 INFO: hook-matplotlib.backends.qt_compat: selected 'PyQt5' as Qt bindings because hook for 'PyQt5' has been run before.
305070 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
306121 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
309743 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
310539 INFO: Loading module hook 'hook-setuptools._distutils.command.check.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
314695 INFO: Loading module hook 'hook-sqlalchemy.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
315092 WARNING: Hidden import "MySQLdb" not found!
315111 WARNING: Hidden import "psycopg2" not found!
318045 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
318062 INFO: checking Tree
318082 INFO: Building Tree because Tree-00.toc is non existent
318085 INFO: Building Tree Tree-00.toc
318226 INFO: checking Tree
318239 INFO: Building Tree because Tree-01.toc is non existent
318247 INFO: Building Tree Tree-01.toc
318290 INFO: checking Tree
318300 INFO: Building Tree because Tree-02.toc is non existent
318315 INFO: Building Tree Tree-02.toc
318334 INFO: Loading module hook 'hook-lxml.objectify.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
318528 INFO: Performing binary vs. data reclassification (7930 entries)
322925 INFO: Looking for ctypes DLLs
324784 INFO: Analyzing run-time hooks ...
324845 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
324859 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
324880 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
324890 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
324901 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks'...
324919 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
324934 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
324950 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_traitlets.py'
324964 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pywintypes.py'
324982 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
324999 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
325037 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pythoncom.py'
325046 INFO: Including run-time hook 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
325488 INFO: Looking for dynamic libraries
339797 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\ProgramData\\anaconda3\\Lib\\site-packages\\pygame']
339817 INFO: Extra DLL search directories (PATH): []
348935 WARNING: Library not found: could not resolve 'msmpi.dll', dependency of 'C:\\ProgramData\\anaconda3\\Library\\bin\\mkl_blacs_msmpi_ilp64.2.dll'.
348958 WARNING: Library not found: could not resolve 'pgf90.dll', dependency of 'C:\\ProgramData\\anaconda3\\Library\\bin\\mkl_pgi_thread.2.dll'.
348971 WARNING: Library not found: could not resolve 'pgmath.dll', dependency of 'C:\\ProgramData\\anaconda3\\Library\\bin\\mkl_pgi_thread.2.dll'.
348978 WARNING: Library not found: could not resolve 'pgc.dll', dependency of 'C:\\ProgramData\\anaconda3\\Library\\bin\\mkl_pgi_thread.2.dll'.
349006 WARNING: Library not found: could not resolve 'impi.dll', dependency of 'C:\\ProgramData\\anaconda3\\Library\\bin\\mkl_blacs_intelmpi_ilp64.2.dll'.
349024 WARNING: Library not found: could not resolve 'impi.dll', dependency of 'C:\\ProgramData\\anaconda3\\Library\\bin\\mkl_blacs_intelmpi_lp64.2.dll'.
349048 WARNING: Library not found: could not resolve 'msmpi.dll', dependency of 'C:\\ProgramData\\anaconda3\\Library\\bin\\mkl_blacs_msmpi_lp64.2.dll'.
349072 WARNING: Library not found: could not resolve 'sycl6.dll', dependency of 'C:\\ProgramData\\anaconda3\\Library\\bin\\omptarget.sycl.wrap.dll'.
349654 INFO: Warnings written to C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc\build\main\warn-main.txt
350654 INFO: Graph cross-reference written to C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc\build\main\xref-main.html
351206 INFO: checking PYZ
351214 INFO: Building PYZ because PYZ-00.toc is non existent
351220 INFO: Building PYZ (ZlibArchive) C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc\build\main\PYZ-00.pyz
362267 INFO: Building PYZ (ZlibArchive) C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc\build\main\PYZ-00.pyz completed successfully.
362493 INFO: checking PKG
362513 INFO: Building PKG because PKG-00.toc is non existent
362528 INFO: Building PKG (CArchive) main.pkg
362632 INFO: Building PKG (CArchive) main.pkg completed successfully.
362652 INFO: Bootloader C:\ProgramData\anaconda3\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
362653 INFO: checking EXE
362668 INFO: Building EXE because EXE-00.toc is non existent
362700 INFO: Building EXE from EXE-00.toc
362717 INFO: Copying bootloader EXE to C:\Users\ADMINI~1\AppData\Local\Temp\tmpeyv966sc\build\main\main.exe
362757 INFO: Copying icon to EXE
362773 INFO: Copying 0 resources to EXE
362789 INFO: Embedding manifest in EXE
362829 INFO: Appending PKG archive to EXE
362901 INFO: Fixing EXE headers
363382 INFO: Building EXE from EXE-00.toc completed successfully.
363500 INFO: checking COLLECT
363531 INFO: Building COLLECT because COLLECT-00.toc is non existent
363534 INFO: Building COLLECT COLLECT-00.toc
389786 INFO: Building COLLECT COLLECT-00.toc completed successfully.

Moving project to: C:\Users\Administrator\Documents\IT\Python\pythonProject3\output
Complete.

**Comment by brentvollebregt** [comment]
Have you [followed the debugging section](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging)? When following this, you should get the underlying error. "Failed to execute script" is not the actual error.

And again, it would be great if you could fill out the issue template - it can help us get to a solution faster.
