### ISSUE TITLE
Warning coloring problem

### ISSUE THREAD

**Issue by mcagriaksoy** [brentvollebregt/auto-py-to-exe#475]
**Quick Checks**

- [X] I have read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [X] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [X] I have made sure my application/script runs before trying to package

**Describe the bug**
As you remember, version 2.43.0 I have added a warning for Pyinstaller version check. If the current version is obsolete, it warns the user to update the pyinstaller.
I have tested the warning before with "white backscreen" mode. Now, I realized that in "Night mode" the message cannot be read.
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/20202577/c7819aa2-4aca-47c7-ab7b-4760692cf5bc)

**Your Environment:**

- Python version (`python --version`): 3.12.2
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.43.2
- PyInstaller version (`pip show pyinstaller`): 5.13.2
- Eel version (`pip show eel`):  0.16.0

**Comment by brentvollebregt** [comment]
This should be fixed in [auto-py-to-exe 2.43.3](https://github.com/brentvollebregt/auto-py-to-exe/releases/tag/v2.43.3) - you can use `python -m pip install auto-py-to-exe --upgrade` to upgrade auto-py-to-exe.

Thank you very much for raising this!

**Comment by mcagriaksoy** [comment]
yes, working thanks for quick fix also!
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/20202577/2768dea6-5fbe-49b1-910f-51d14506a93e)
