### ISSUE TITLE
Python Dash app to .exe issues using auto-py-to-exe (pyinstaller)

### ISSUE THREAD

**Issue by hodumAL** [brentvollebregt/auto-py-to-exe#48]
First of all - I love the GUI it is very intuitive but I am running into issues. 0

I currently have a dash app that I can run locally but want to have a .exe file or a way to deploy this app on other machines without the requirement to install python, python libraries etc.

I have put my virtual environment into a requirements.txt so the folder looks like app.py requirements.txt

When I run the app locally it runs perfectly fine. When I convert to an exe file using auto-py-to-exe selecting one directory and enable recursion limit I run into issues. The .exe runs but then get FileNotFoundError regarding dash_renderer\react@15.4.2.min.js? I look into the folder that was created w the .exe and do not see dash_renderer installed at all but dash_renderer exists in the requirements.txt file in the folder (in the original app folder - not in the .exe output folder). Is this an issue with my virtual environment or is it something to do with certain .dll files not being included? Here is the output after running auto py to exe:

Building in the current instances temporary directory at C:\Users\USER\AppData\Local\Temp\tmpvg1lctln
To get a new temporary directory, restart this application
Set Recursion Limit to 5000
Executing: pyinstaller -y "C:/Users/user.name/Desktop/Projects/vcs_projects/farmers_portfolio/run.py"
106414 INFO: PyInstaller: 3.5.dev0+g73dfb3ad
106414 INFO: Python: 3.6.5
106414 INFO: Platform: Windows-10-10.0.16299-SP0
106416 INFO: wrote C:\Users\ALEX~1.HOD\AppData\Local\Temp\tmpvg1lctln\run.spec
106427 INFO: UPX is not available.
106429 INFO: Extending PYTHONPATH with paths
['C:\\Users\\user.name\\Desktop\\Projects\\vcs_projects\\farmers_portfolio',
'C:\\Users\\ALEX~1.HOD\\AppData\\Local\\Temp\\tmpvg1lctln']
106430 INFO: checking Analysis
106430 INFO: Building Analysis because Analysis-00.toc is non existent
106430 INFO: Initializing module dependency graph...
106437 INFO: Initializing module graph hooks...
106443 INFO: Analyzing base_library.zip ...
112064 INFO: running Analysis Analysis-00.toc
112086 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
required by c:\users\user.name\appdata\local\continuum\anaconda3\python.exe
112920 INFO: Caching module hooks...
112953 INFO: Analyzing C:\Users\user.name\Desktop\Projects\vcs_projects\farmers_portfolio\run.py
114021 INFO: Processing pre-safe import module hook six.moves
115107 INFO: Processing pre-safe import module hook urllib3.packages.six.moves
122816 INFO: Processing pre-find module path hook distutils
125282 INFO: Processing pre-find module path hook site
125284 INFO: site: retargeting to fake-dir 'c:\\users\\user.name\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
127756 INFO: Processing pre-safe import module hook setuptools.extern.six.moves
369862 INFO: Processing pre-safe import module hook win32com
426203 INFO: Loading module hooks...
426203 INFO: Loading module hook "hook-babel.py"...
426401 INFO: Loading module hook "hook-certifi.py"...
426404 INFO: Loading module hook "hook-cryptography.py"...
426900 INFO: Loading module hook "hook-distutils.py"...
426903 INFO: Loading module hook "hook-docutils.py"...
428773 INFO: Loading module hook "hook-encodings.py"...
428912 INFO: Loading module hook "hook-gevent.py"...
429178 INFO: Determining a mapping of distributions to packages...
569758 WARNING: Unable to find package for requirement greenlet from package gevent.
569758 INFO: Packages required by gevent:
['cffi']
570514 INFO: Loading module hook "hook-IPython.py"...
570547 INFO: Excluding import 'gtk'
570564 INFO: Excluding import 'matplotlib'
570582 INFO: Removing import of matplotlib from module IPython.core.pylabtools
570582 INFO: Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
570582 INFO: Removing import of matplotlib.figure from module IPython.core.pylabtools
570582 INFO: Removing import of matplotlib.pyplot from module IPython.core.pylabtools
570584 INFO: Excluding import 'PySide'
570604 INFO: Removing import of PySide from module IPython.external.qt_loaders
570605 INFO: Excluding import 'PyQt4'
570625 INFO: Removing import of PyQt4 from module IPython.external.qt_loaders
570626 INFO: Excluding import 'PyQt5'
570642 INFO: Removing import of PyQt5 from module IPython.external.qt_loaders
570642 INFO: Removing import of PyQt5.QtWidgets from module IPython.external.qt_loaders
570643 INFO: Removing import of PyQt5.QtGui from module IPython.external.qt_loaders
570643 INFO: Removing import of PyQt5.QtCore from module IPython.external.qt_loaders
570643 INFO: Removing import of PyQt5.QtSvg from module IPython.external.qt_loaders
570644 INFO: Excluding import 'tkinter'
570658 INFO: Removing import of tkinter from module IPython.lib.clipboard
570660 INFO: Loading module hook "hook-jedi.py"...
570669 INFO: Loading module hook "hook-jinja2.py"...
570670 INFO: Loading module hook "hook-jsonschema.py"...
570675 INFO: Loading module hook "hook-lib2to3.py"...
570682 INFO: Loading module hook "hook-lxml.etree.py"...
570684 INFO: Loading module hook "hook-matplotlib.backends.py"...
571605 INFO: Matplotlib backend "GTK": ignored
Gtk* backend requires pygtk to be installed.
572280 INFO: Matplotlib backend "GTKAgg": ignored
Gtk* backend requires pygtk to be installed.
572723 INFO: Matplotlib backend "GTKCairo": ignored
No module named 'gtk'
573367 INFO: Matplotlib backend "GTK3Agg": ignored
The Gtk3 backend requires PyGObject or pgi
573808 INFO: Matplotlib backend "GTK3Cairo": ignored
cairo backend requires that cairocffi or pycairo is installed
574390 INFO: Matplotlib backend "MacOSX": ignored
cannot import name '_macosx'
575645 INFO: Matplotlib backend "nbAgg": added
576412 INFO: Matplotlib backend "Qt4Agg": added
576859 INFO: Matplotlib backend "Qt4Cairo": ignored
cairo backend requires that cairocffi or pycairo is installed
577540 INFO: Matplotlib backend "Qt5Agg": added
577938 INFO: Matplotlib backend "Qt5Cairo": ignored
cairo backend requires that cairocffi or pycairo is installed
578601 INFO: Matplotlib backend "TkAgg": added
579076 INFO: Matplotlib backend "TkCairo": ignored
cairo backend requires that cairocffi or pycairo is installed
580305 INFO: Matplotlib backend "WebAgg": added
580942 INFO: Matplotlib backend "WX": ignored
Matplotlib backend_wx and backend_wxagg require wxPython>=2.9
581365 INFO: Matplotlib backend "WXAgg": ignored
No module named 'wx'
581789 INFO: Matplotlib backend "WXCairo": ignored
No module named 'wx'
582370 INFO: Matplotlib backend "agg": added
582837 INFO: Matplotlib backend "cairo": ignored
cairo backend requires that cairocffi or pycairo is installed
583268 INFO: Matplotlib backend "gdk": ignored
No module named 'gobject'
583888 INFO: Matplotlib backend "pdf": added
584678 INFO: Matplotlib backend "pgf": added
585310 INFO: Matplotlib backend "ps": added
585951 INFO: Matplotlib backend "svg": added
586569 INFO: Matplotlib backend "template": added
587131 INFO: Loading module hook "hook-matplotlib.py"...
587625 INFO: Loading module hook "hook-numpy.core.py"...
587749 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
587758 INFO: Loading module hook "hook-numpy.py"...
587761 INFO: Loading module hook "hook-openpyxl.py"...
587778 INFO: Loading module hook "hook-pandas.py"...
588999 INFO: Loading module hook "hook-PIL.Image.py"...
589734 INFO: Loading module hook "hook-PIL.py"...
589749 INFO: Excluding import 'PySide'
589765 INFO: Removing import of PySide from module PIL.ImageQt
589766 INFO: Import to be excluded not found: 'FixTk'
589766 INFO: Excluding import 'PyQt4'
589779 INFO: Removing import of PyQt4 from module PIL.ImageQt
589780 INFO: Excluding import 'PyQt5'
589799 INFO: Removing import of PyQt5.QtGui from module PIL.ImageQt
589800 INFO: Removing import of PyQt5.QtCore from module PIL.ImageQt
589801 INFO: Excluding import 'tkinter'
589820 INFO: Removing import of tkinter from module PIL.ImageTk
589820 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
589834 INFO: Import to be excluded not found: 'FixTk'
589835 INFO: Excluding import 'tkinter'
589848 INFO: Loading module hook "hook-pkg_resources.py"...
591649 INFO: Loading module hook "hook-pycparser.py"...
591868 INFO: Loading module hook "hook-pydoc.py"...
591869 INFO: Loading module hook "hook-pygments.py"...
593927 INFO: Loading module hook "hook-PyQt5.py"...
594650 WARNING: Hidden import "PyQt5.sip" not found!
594651 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
594771 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
594952 INFO: Loading module hook "hook-PyQt5.QtSvg.py"...
595615 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
595866 INFO: Loading module hook "hook-pytest.py"...
597029 INFO: Loading module hook "hook-pythoncom.py"...
598003 INFO: Loading module hook "hook-pytz.py"...
598201 INFO: Loading module hook "hook-pywintypes.py"...
599221 INFO: Loading module hook "hook-scipy.linalg.py"...
599224 INFO: Loading module hook "hook-scipy.py"...
599227 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
599234 INFO: Loading module hook "hook-scipy.special._ellip_h..."...
599235 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
599237 INFO: Loading module hook "hook-setuptools.py"...
600732 INFO: Loading module hook "hook-sphinx.py"...
608140 INFO: Loading module hook "hook-sqlalchemy.py"...
608539 INFO: Found 6 sqlalchemy hidden imports
608542 WARNING: Hidden import "MySQLdb" not found!
608563 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
608564 WARNING: Hidden import "sqlalchemy.orm.state", "sqlalchemy.orm.strategies" not found!
608590 INFO: Excluding import 'sqlalchemy.testing'
608609 INFO: Removing import of sqlalchemy.testing.util from module sqlalchemy.orm.util
608611 INFO: Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing
608611 INFO: Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing
608611 INFO: Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing
608611 INFO: Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing
608611 INFO: Removing import of sqlalchemy.testing.warnings from module sqlalchemy.testing
608611 INFO: Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing
608612 INFO: Removing import of sqlalchemy.testing.util from module sqlalchemy.testing
608612 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing
608612 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing
608612 INFO: Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.warnings
608613 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.warnings
608613 INFO: Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing.assertions
608613 INFO: Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing.assertions
608613 INFO: Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing.assertions
608613 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertions
608613 INFO: Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.assertions
608614 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.assertions
608614 INFO: Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing.util
608614 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.util
608614 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.util
608614 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.config
608614 INFO: Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.engines
608615 INFO: Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.engines
608615 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.engines
608615 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.engines
608616 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.exclusions
608617 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.exclusions
608617 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertsql
608617 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.mock
608618 INFO: Loading module hook "hook-sqlite3.py"...
608761 INFO: Loading module hook "hook-sysconfig.py"...
608764 INFO: Loading module hook "hook-tables.py"...
608766 INFO: Loading module hook "hook-win32com.py"...
609011 INFO: Loading module hook "hook-xml.dom.domreg.py"...
609013 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
609014 INFO: Loading module hook "hook-xml.py"...
609015 INFO: Loading module hook "hook-zmq.py"...
611116 INFO: Loading module hook "hook-_tkinter.py"...
611390 INFO: checking Tree
611390 INFO: Building Tree because Tree-00.toc is non existent
611390 INFO: Building Tree Tree-00.toc
611589 INFO: checking Tree
611589 INFO: Building Tree because Tree-01.toc is non existent
611589 INFO: Building Tree Tree-01.toc
612413 INFO: Looking for ctypes DLLs
612561 INFO: Analyzing run-time hooks ...
612633 INFO: Including run-time hook 'pyi_rth__tkinter.py'
612636 INFO: Including run-time hook 'pyi_rth_pkgres.py'
612640 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
612643 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
612651 INFO: Including run-time hook 'pyi_rth_qt5.py'
612653 INFO: Including run-time hook 'pyi_rth_traitlets.py'
612656 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
612659 INFO: Including run-time hook 'pyi_rth_mpldata.py'
612829 INFO: Looking for dynamic libraries
621944 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_blacs_mpich2_ilp64.dll
623445 WARNING: lib not found: tbb.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_tbb_thread.dll
625914 WARNING: lib not found: impi.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_blacs_intelmpi_lp64.dll
626136 WARNING: lib not found: impi.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_blacs_intelmpi_ilp64.dll
626969 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_blacs_mpich2_lp64.dll
628323 WARNING: lib not found: pgc14.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
628437 WARNING: lib not found: pgf90.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
628550 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
629057 WARNING: lib not found: msmpi.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_blacs_msmpi_ilp64.dll
629937 WARNING: lib not found: msmpi.dll dependency of c:\users\user.name\appdata\local\continuum\anaconda3\Library\bin\mkl_blacs_msmpi_lp64.dll
646009 INFO: Looking for eggs
646009 INFO: Using Python library c:\users\user.name\appdata\local\continuum\anaconda3\python36.dll
646010 INFO: Found binding redirects: 
[]
646090 INFO: Warnings written to C:\Users\ALEX~1.HOD\AppData\Local\Temp\tmpvg1lctln\build\run\warn-run.txt
647792 INFO: Graph cross-reference written to C:\Users\ALEX~1.HOD\AppData\Local\Temp\tmpvg1lctln\build\run\xref-run.html
648295 INFO: checking PYZ
648295 INFO: Building PYZ because PYZ-00.toc is non existent
648295 INFO: Building PYZ (ZlibArchive) C:\Users\ALEX~1.HOD\AppData\Local\Temp\tmpvg1lctln\build\run\PYZ-00.pyz
657533 INFO: Building PYZ (ZlibArchive) C:\Users\ALEX~1.HOD\AppData\Local\Temp\tmpvg1lctln\build\run\PYZ-00.pyz completed successfully.
658148 INFO: checking PKG
658148 INFO: Building PKG because PKG-00.toc is non existent
658148 INFO: Building PKG (CArchive) PKG-00.pkg
658409 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
658413 INFO: Bootloader c:\users\user.name\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
658413 INFO: checking EXE
658414 INFO: Building EXE because EXE-00.toc is non existent
658414 INFO: Building EXE from EXE-00.toc
658415 INFO: Appending archive to EXE C:\Users\ALEX~1.HOD\AppData\Local\Temp\tmpvg1lctln\build\run\run.exe
658450 INFO: Building EXE from EXE-00.toc completed successfully.
658459 INFO: checking COLLECT
658460 INFO: Building COLLECT because COLLECT-00.toc is non existent
658460 INFO: Building COLLECT COLLECT-00.toc
687473 INFO: Building COLLECT COLLECT-00.toc completed successfully.
Moving project to: output/
Complete.

Any help would be GREATLY appreciated. Thanks in advance

**Comment by brentvollebregt** [comment]
So looking at those output logs, it's clear to see that PyInstaller has done **exactly** what you told it to do. I can see you have just selected the file and expected everything to work.

I am certain that after packages are built using this tool that a message appears at the bottom of the window saying "*Something wrong with your exe? Read this post on how to fix common issues for possible solutions.*"Did you read this? This post offers a lot of help and covers most of the things I know people do wrong when using this application (like you have in this situation).

You would have noticed in the application that there are many other fields and drop down areas. One particular dropdown you may want to take note of is "Additional Files". When you read the article I have mentioned (if you haven't already), you will understand what files need to be added here and why. 

I remember seeing your comment on the YouTube video associated with this video, what happened to that? Generally GitHub issues are made for an issue with the project in the repository, not your own application. I help individual cases out on YouTube but this repo is for the project. However if you do feel this is an issue with auto-py-to-exe, then great! We will look into this and get it fixed ASAP!

**Comment by hodumAL** [comment]
Hey there, I appreciate the help and apologize for posting on Github. I had
posted on StackOverflow to no avail and I thought i had posted on the
YouTube video associated with it. I have checked out the common issues and
they helped me reach the point I was at. I will look more into the
"Additional Files" portion.
Thanks again for your help and the GUI does help make pyinstaller a lot
more intuitive.

**Comment by brentvollebregt** [comment]
I recommend copying the file you expect to be in the package into the correct location. Try running the script then and see if the error is resolved. If so, you can add this to the additional files section and fill in the fields appropriately.

**Comment by brentvollebregt** [comment]
Please don't feel you have done anything wrong, I just expect people to have read the post as it appears right in front of them after a build. It used to be only in the README file but too many people were saying this tool wasn't working and not putting the effort in to read it so I moved it to the UI itself.

**Comment by brentvollebregt** [comment]
No more information provided so I assume this is fixed.
