### ISSUE TITLE
Script requiring input

### ISSUE THREAD

**Issue by olawalejuwonm** [brentvollebregt/auto-py-to-exe#483]
Thanks for the awesome project, I was able to turn my script to exe, but the script needs user input to run, I got this when i try to run the generated exe
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/52759812/aab6a917-433a-46c2-b338-710c1da7f749)

**Comment by brentvollebregt** [comment]
Could you fill out the template you cleared? This will give context for me to help you. 

Did you package using windowed mode (no console) - if so, how would the input be entered?

**Comment by olawalejuwonm** [comment]
Yes I packaged using windowed mode (no console) and removed all print function.
I expect that there will be a file picker




**My Environment:**

- Python version (`python --version`):Python 3.12.2
- auto-py-to-exe version (`pip show auto-py-to-exe`): Version: 2.43.3
- PyInstaller version (`pip show pyinstaller`): 6.6.0 
- Eel version (`pip show eel`): Version: 0.16.0

**Comment by brentvollebregt** [comment]
auto-py-to-exe does not add anything extra to your application - it packages as it is. When you packaged using the windowed mode, you asked for there to be no console - this means things like `print` and `input` will no longer work by default.

---

In the [debugging steps](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging) that was linked in the first comment on this issue, it states,

> As basic as it sounds, the first step of debugging is to make sure your script works as a .py file before you package it. This is very important.

And then goes on to say,

> If you are wanting to use the "Window Based" option, run your script using pythonw.exe - this executable can be found beside python.exe.

Following this, you would have had issues running your script with Python itself. If it doesn't work with Python, it won't work after packaging.

Outlined under "[When running my script with pythonw.exe, it doesn't work](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#when-running-my-script-with-pythonwexe-it-doesnt-work)", I show how you can redirect `print` elsewhere. I do not have a solution for `input` as you would need to build a UI for something like that.

**Comment by olawalejuwonm** [comment]
How do i build such ui please?

**Comment by brentvollebregt** [comment]
Python has a built-in library called "tkinter", [here is a decent tutorial](https://realpython.com/python-gui-tkinter/). There are lots of other libraries too - search "python GUI" in Google to see what else is available.

**Comment by olawalejuwonm** [comment]
After building with tkinter will I be able to still build with
auto-py-to-exe ?

**Comment by brentvollebregt** [comment]
Yes, tkinter is just a library in Python - you will still be able to package using auto-py-to-exe afterwards.

Alternatively, you could skip needing a GUI if you're fine with providing input in the console. If so, use the console mode.

**Comment by brentvollebregt** [comment]
auto-py-to-exe can be used on Mac OS. We use PyInstaller under the hood - you can check out the Mac OS support here: https://pyinstaller.org/en/v4.1/usage.html#building-mac-os-x-app-bundles

**Comment by olawalejuwonm** [comment]
I mean that can be used for building macOs app

**Comment by brentvollebregt** [comment]
auto-py-to-exe can build Mac OS X app bundles as described in the link I sent before

**Comment by olawalejuwonm** [comment]
I've read but I don't understand how to do that, especially specifying the
flag. Likewise, will it be possible to build for Mac on windows?

**Comment by brentvollebregt** [comment]
> I've read but I don't understand how to do that, especially specifying the flag.

Use the tool on Mac OS and it will build a Mac OS App Bundle. Use windows mode and the output should then create an OS X application named `[myscript].app`.

> Likewise, will it be possible to build for Mac on windows?

No, this is from the [PyInstaller docs](https://pyinstaller.org/en/stable/#pyinstaller-manual),

> PyInstaller is tested against Windows, MacOS X, and Linux. However, it is not a cross-compiler; to make a Windows app you run PyInstaller on Windows, and to make a Linux app you run it on Linux, etc.

**Comment by olawalejuwonm** [comment]
Thanks for the explanation.

**Comment by olawalejuwonm** [comment]
@brentvollebregt I have changed the implementation to use tkinter
But this is what I got when I try to run the file
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/52759812/4f3b77f4-0854-4caf-969b-386de1cc1949)

**Comment by brentvollebregt** [comment]
A Google search for "pyinstaller the specified module could not be found" brings up [this result which describes the same issue you have show](https://stackoverflow.com/questions/47289279/error-loading-python-dll-loadlibrary-the-specified-module-could-not-be-found).
