### ISSUE TITLE
how can we change the running command ? 

### ISSUE THREAD

**Issue by xalteropsx** [brentvollebregt/auto-py-to-exe#489]
is their a way to change runtime directory cause exe run always store temp in temporary folder and c drive many time slower then other drive  like i have many ssd i dont want c drive to load more junk  also is their a way to change command line like python run panda i want to change uvicorn run etc

**Comment by brentvollebregt** [comment]
`--build-directory-override` sets the directory where auto-py-to-exe packages your application. If you don't want your exe decompressing to a temp directory, do not use "one file" mode.

> i didnt understand how can we change running method from existing venv file

Packaging your application will make it work the same as doing `python my_script.py` - if you want to do anything fancy, you need to do it in Python.
