### ISSUE TITLE
exit() not available 

### ISSUE THREAD

**Issue by IXIInternational** [brentvollebregt/auto-py-to-exe#49]
I have an exit() in my script and it crashes with:
NameError: name 'exit' is not defined
[15088] Failed to execute script main

Please help

BTW Sorry for the CAPS TITLE._.

**Comment by brentvollebregt** [comment]
`exit()` comes from the `sys` module (I assume this is the one you are using) . Did you import sys? 
I imagine you would have the same error if you actually run the script with Python by itself.

**Comment by IXIInternational** [comment]
Thanks. 
I could bypass the problem with os.abort().

**Comment by brentvollebregt** [comment]
Cool. Importing sys and calling `sys.exit()` will produce the exact same exception and result as `exit`.

Closing due to this being resolved.
