### ISSUE TITLE
Error: tkinter not found

### ISSUE THREAD

**Issue by yumianhuli1** [brentvollebregt/auto-py-to-exe#495]
OS:win11
python3.8.10
run auto-py-to-exe        
Error: tkinter not found
For linux, you can install tkinter by executing: "sudo apt-get install python3-tk"
plz take a look ,thanks!

**Comment by yumianhuli1** [comment]
> Did you follow the instructions in the error? Looks like you don't have tkinter installed.

Hi！First, I don't need to install this library and second I installed this dependency, but still reported this error

**Comment by brentvollebregt** [comment]
If you run `from tkinter import Tk` in the same Python environment you are trying to run auto-py-to-exe with, what do you get?
