### ISSUE TITLE
Doesnt open with Run option on linux

### ISSUE THREAD

**Issue by forbiden-west** [brentvollebregt/auto-py-to-exe#496]
App maded a launchable app on linux, but it doesn't open like Right Click>Run
App only opens at terminal
(i cant put code, code is contain server connection data)
- Python version: 3.12
- auto-py-to-exe version: 2.44.1
- PyInstaller version: 6.9.0
- Eel version: 0.17.0

**Comment by brentvollebregt** [comment]
Could you please complete the template you cleared - without reproduction steps, I don't have a lot to go off.

If the app can be executed through the terminal, it sounds like it has been packaged correctly? Not sure what you mean by "code is contain server connection data".
