### ISSUE TITLE
Issue in One file mode with additional assets

### ISSUE THREAD

**Issue by jatin69** [brentvollebregt/auto-py-to-exe#5]
I first tried `one directory mode`, with additional asset files to make sure everything is fine. The resultant exe in the directory works as intended. 
Then i switched to `one file mode`, made an exe, but the exe crashes.
Console says, its because it can't find the assets.
I think it might be an inherent pyinstaller issue, as per [this article](https://pythonhosted.org/PyInstaller/operating-mode.html#how-the-one-file-program-works) 
Do you have any fixes? suggestions? What should I do?

Everything works fine in one directory mode, but not in one file mode. 
![bugfix4](https://user-images.githubusercontent.com/13359891/37510251-877eb1ec-2920-11e8-9bba-0b9c65825e91.PNG)

**Comment by jatin69** [comment]
Found a solution [here](https://stackoverflow.com/a/13790741/5371996)
Works fine now.

**Comment by brentvollebregt** [comment]
That commit shouldn't be here sorry, messed that up.
