### ISSUE TITLE
Windows 10 

### ISSUE THREAD

**Issue by jatankshirsagar** [brentvollebregt/auto-py-to-exe#503]
**Quick Checks**
I am able to generate the exe using the tool on a Ubuntu but when I go to my windows 10 laptop and try running the generated exe it is giving me an error as seen in the image

![image](https://github.com/user-attachments/assets/19eac489-3290-4201-8e59-bd79e467c574)

**Your Environment:**

- Python version (`python --version`):
- auto-py-to-exe version (`pip show auto-py-to-exe`):
- PyInstaller version (`pip show pyinstaller`):
- Eel version (`pip show eel`):

**Comment by brentvollebregt** [comment]
Please read the help post: [Can I Create an Executable on One Operating System and Run it on Another?](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#can-i-create-an-executable-on-one-operating-system-and-run-it-on-another)

> PyInstaller is tested against Windows, MacOS X, and Linux. However, it is not a cross-compiler; to make a Windows app you run PyInstaller on Windows, and to make a Linux app you run it on Linux, etc.
