### ISSUE TITLE
PydanticImportError

### ISSUE THREAD

**Issue by Mina4ever** [brentvollebregt/auto-py-to-exe#509]
**Quick Checks**

- [Y] I have read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [Y] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [Y] I have made sure my application/script runs before trying to package

**Describe the bug**

Trying to open the extracted exe and I am facing below error 
"pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details."

**To Reproduce**

_Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):_

1-run auto-py-to-exe on python command
2-Select py file from GUI and process
3-Trying to open the extracted exe and I am facing below error 
"pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details."

```python
# If you have example code, please provide a minimal reproducible example:
# https://stackoverflow.com/help/minimal-reproducible-example

print("Hello World")
```

**Expected behavior**

I want the exe file to be executed correctly but it generates the error "pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.10/migration/#basesettings-has-moved-to-pydantic-settings for more details.", I tryed to modify the source code but it written by pyc not py

**Your Environment:**

- Python version (`Python 3.11.10`):
- auto-py-to-exe version (`2.44.4`):
- PyInstaller version (`6.11.1`):
- Eel version (`0.18.1`):

**Comment by Mina4ever** [comment]
yes I have read the help post

**Comment by brentvollebregt** [comment]
I just did the following:

1. Ran `auto-py-to-exe` to open auto-py-to-exe
2. Selected my .py file from GUI and packaged it
   The file contains,
   ```py
   print("Hello World")
   ```
3. Ran the package exe

And I get no error. It appears your reproduction steps are missing some code and additional steps to reproduce the error. I am unable to help without proper reproduction steps.

Searching for your error leads me to [this SO answer](https://stackoverflow.com/a/76670657). I recommend creating a new Python virtual environment, install the libraries you need and `auto-py-to-exe`, and make sure your script is using the correct import for the correct version of `pydantic` you have installed.

I can't imagine this error would have not appeared when you ran it before packaging - unless you ran it with one version of `pydantic` and packaged in an environment with a different version of `pydantic`.

**Comment by Mina4ever** [comment]
[DataQuilaty.txt](https://github.com/user-attachments/files/17970194/DataQuilaty.txt)
py script attached

**Comment by brentvollebregt** [comment]
Could you provide a minimal reproducible example? I can't imagine having `cx_Oracle` or `pandas_profiling` in the script is causing the issue. If so, it needs to be noted.

Also how did using a virtual environment go? (the second part of my reply)

**Comment by Mina4ever** [comment]
first, yes , it's conda virtual environment, with below specs:
Python version (Python 3.11.10)
auto-py-to-exe version (2.44.4)
PyInstaller version (6.11.1)
[error.txt](https://github.com/user-attachments/files/18041427/error.txt)

Eel version (0.18.1)
 
Second: I could find the issue in one of "pandas_profiling" Py file, I have fixed it, however I faced another issue (attached) 

Worth to say that i need to convert the shared PY file as is and it's doesn't make sense to my to convert any dumpy py file to exe

**Comment by Mina4ever** [comment]
It works, I copied python library "ydata_profiling" files from virtual environment folder to "_internal" in my app path .
Thank you so much for your support
