### ISSUE TITLE
Informative text on command line interface.

### ISSUE THREAD

**Issue by mcagriaksoy** [brentvollebregt/auto-py-to-exe#510]
**New Feature Description**

Hi Brent,
I think a text which displays in command line to inform user program is running might be helpful.

**Reason For New Feature**
It is because when user runs the auto-py-to-exe, it opens a web browser and/or tab automatically, but it might be missing by the user, or user might minimize the browser.

![image](https://github.com/user-attachments/assets/0d39945d-28cd-41ed-82c5-968300b76cf5)

So that, when user opens the command line interface, cannot see anything and might understand that software cannot responding.
I think we can add an informative text like:
- Please do not close this window, software is running at web-browser.
- Please continue on browser etc. etc.

What do you think?

**Comment by brentvollebregt** [comment]
Yea, this is a really good idea!

There are 4 different states the UI can be displayed:

1. Chrome's app mode is automatically opened (default)
2. Edge's app mode is automatically opened (default if Chrome is not installed)
3. The default browser is automatically opened (default if Chrome and Edge are not installed)
4. Nothing is automatically opened and a message is printed out

https://github.com/brentvollebregt/auto-py-to-exe/blob/3059fd5fef2d4f46fe54ef694d2a4920344562a6/auto_py_to_exe/ui.py#L190-L201

For 1, something like,

```
The interface is being opened in a new Chrome window
Please do not close this terminal while using auto-py-to-exe - the process will end when the window is closed
```

For 2, something like,

```
The interface is being opened in a new Edge window
Please do not close this terminal while using auto-py-to-exe - the process will end when the window is closed
```

For 3, something like,

```
The interface is being opened in your default browser
Please do not close this terminal while using auto-py-to-exe - the process will end when the tab is closed
```

For 4, something like,

```
Server starting at http://localhost:{port}/index.html
You may end this process using Ctrl+C when finished using auto-py-to-exe
```

**Comment by brentvollebregt** [comment]
Just pushed to master - I'll get this out tomorrow if I get time.

**Comment by mcagriaksoy** [comment]
wow it was fast :)
