### ISSUE TITLE
Please reverse #187 (Open in Edge's app mode when Chrome isn't available)

### ISSUE THREAD

**Issue by Alexander020304** [brentvollebregt/auto-py-to-exe#513]
your now open edge instead of my system defaults.
Please do not hard code if chrome don't exit to use edge. I hate edge
I do not use chrome.

Thanks you for your time.

**Comment by brentvollebregt** [comment]
You can use --default-browser or -db when opening auto-py-to-exe to use the default browser.

**Comment by Alexander020304** [comment]
sorry; i just saw the change; and i am been work through too many libraries; can you make --db option by default thou?

**Comment by brentvollebregt** [comment]
Currently, the order is:

1. Chrome App Mode
2. Edge App Mode
3. Default browser

This has been done to try to make the GUI look as it does in the README. At the moment I am not looking to make `--default-browser` the default.
