### ISSUE TITLE
可以发布一个exe版本吗？

### ISSUE THREAD

**Issue by WEI9899** [brentvollebregt/auto-py-to-exe#516]
可以发布一个exe版本吗？因为一移动文件 又要重新配置解析器

**Comment by mostypc123** [comment]
if google translate is right, you are asking about a feature (exe version of autopytoexe) that was requested like 500000000000000000000000 times, and @brentvollebregt said that its not possible.

from issue #267:
> Since the exe would be using it's own internal version of Python, you would have to add the site-packages folder manually to tell PyInstaller where to look for modules. Even if this was done, you would need to be sure the two versions of Python were the same (the internal one and the one installed globally on the host).

**Comment by brentvollebregt** [comment]
Thanks @mostypc123, I have updated the title of #267 to make it easier to find hopefully.

I will close this as a duplicate.
