### ISSUE TITLE
UI is closing immediately. 

### ISSUE THREAD

**Issue by snehitvaddi** [brentvollebregt/auto-py-to-exe#55]
when I'm running run.py, Im getting UI for just a fraction of seconds and immediately it is closing.

**Comment by brentvollebregt** [comment]
What version are you using?

**Comment by brentvollebregt** [comment]
Also can you run it using something like the terminal so you can see the error in the output.

**Comment by snehitvaddi** [comment]
Thank you @brentvollebregt, It worked fine when I reinstalled and run through terminal.
