### ISSUE TITLE
I can open DevTools

### ISSUE THREAD

**Issue by tinshade** [brentvollebregt/auto-py-to-exe#59]
I don't know if you know this and couldn't find a workaround but I can simply press **F12** to open **DevTools** for your application. Alongside that, I can do pretty much everything I can with Chrome except browsing, of course.

If you know a way to fix this, please tell me how to. I am currently working on a Python - EEL project and I find this to be a major issue.

Thanks in advance.
![Issue](https://user-images.githubusercontent.com/22311804/59277734-52892b80-8c7e-11e9-90b3-fdadff929e13.png)

**Comment by brentvollebregt** [comment]
I am fully aware of this and have no issues with it being available. 

I don't really see a reason why this should be blocked as I have no problem with people executing commands and looking at the source. This is run on their machine so there is no issue.

Thank you very much for raising this. If you want to stop Chrome DevTools being opened in your application, I recommend re-thinking why this is required and remembering to never trust the client side;  the client and server should be completely separate with the server doing necessary checks.

**Comment by brentvollebregt** [comment]
Why do you believe this is an issue? What needs to be prevented in this applications interface?

**Comment by tinshade** [comment]
I am writing this application for professional use. Opening of DevTools in an EXE is not a good idea, neither a good impact, let alone the security and code integrity concerns.

**Comment by brentvollebregt** [comment]
I meant what are the reasons for auto-py-to-exe as you have opened the issue on the repository for auto-py-to-exe.
