### ISSUE TITLE
Counter Intuitive Icon Action

### ISSUE THREAD

**Issue by jatin69** [brentvollebregt/auto-py-to-exe#6]
As we are on an issue spree, let's go through this as well.
By default, The icons face upward, but after clicking, the content expands downward. This is counter-intuitive.
![bugfix5](https://user-images.githubusercontent.com/13359891/37525119-e6280258-2951-11e8-8e95-7e9ede14bba9.PNG)

I suggest flipping the original button. By default, it should face downwards, when clicked, the content expands downward, the icon now transforms 180 degrees and face upward. Now I know that to collapse the expansion, I need to click this, and the expansion will collapse in the upward direction.

Not really a big issue, but aesthetics matter. 🙈

**Comment by brentvollebregt** [comment]
I was thinking the exact same thing a while ago but decided not to change it but now that there is a second option, I feel it should be done.
