### ISSUE TITLE
convert to EXE?

### ISSUE THREAD

**Issue by SirAxolot** [brentvollebregt/auto-py-to-exe#60]
Can you convert all of this to a single exe file?
Thanks!

**Comment by brentvollebregt** [comment]
What is the benefit of packing this project into an executable?

**Comment by SirAxolot** [comment]
People without pip can use it.

**Comment by brentvollebregt** [comment]
There are instructions in the readme on how to install with without pip.

**Comment by SirAxolot** [comment]
Also, downloading and running it wouldn't be so complicated, so some less techy people (like me) can use it.

**Comment by brentvollebregt** [comment]
> "downloading and running it wouldn't be so complicated"

It takes one command to install this and a second to run it. As I describe in the readme:
 - Install: `python -m pip install auto-py-to-exe`
 - Run: `auto-py-to-exe`

What is so complicated about that? Also this tool is made to package a Python script to an executable so you can run it on machines without Python - that is how you show a "Py-App to someone who doesn't have Python".

I don't think I quite get what you're getting at sorry?

**Comment by brentvollebregt** [comment]
Closing due to no response for over a month.
