### ISSUE TITLE
Cannot Identify Chrome Correctly to Run Application

### ISSUE THREAD

**Issue by SirAxolot** [brentvollebregt/auto-py-to-exe#61]
I followed all of the instructions but it didn't work.

**Comment by brentvollebregt** [comment]
This is very very vague. What doesn't work; auto-py-to-exe, your executable, Python, pip?

Could you please give details about what your are executing this on, an example of what you are trying to do (smallest reproducible example) and steps to reproduce your error.

**Comment by SirAxolot** [comment]
I downloaded it as instructed on [https://pypi.org/project/auto-py-to-exe/](url)'s Installing Via PyPI section, but when I tried to run it I got this error: 
Traceback (most recent call last):
  File "c:\users\saulr\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)  File "c:\users\saulr\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)  File "C:\Users\Saulr\AppData\Local\Programs\Python\Python37-32\Scripts\auto-py-to-exe.exe\__main__.py", line 9, in <module>
  File "c:\users\saulr\appdata\local\programs\python\python37-32\lib\site-packages\auto_py_to_exe\__main__.py", line 371, in run
    eel.start('main.html', size=(650, 612), options={'port': 0})  File "c:\users\saulr\appdata\local\programs\python\python37-32\lib\site-packages\eel\__init__.py", line 120, in start
    brw.open(start_urls, options)  File "c:\users\saulr\appdata\local\programs\python\python37-32\lib\site-packages\eel\browsers.py", line 35, in open
    chm.run(options, start_urls)  File "c:\users\saulr\appdata\local\programs\python\python37-32\lib\site-packages\eel\chrome.py", line 11, in run
    stdout=sps.PIPE, stderr=sps.PIPE, stdin=sps.PIPE)  File "c:\users\saulr\appdata\local\programs\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)  File "c:\users\saulr\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by brentvollebregt** [comment]
When does this error appear; when installing or running? Also what command are you executing?

**Comment by angryparizval** [comment]
i am having the same issue, after doing the pip install for requirements i do  "python -m auto_py-to_exe" and it gives me the exact same error except at the end i get "OSError: [WinError 87] The parameter is incorrect" instead of his "FileNotFoundError: [WinError 2] The system cannot find the file specified"

**Comment by brentvollebregt** [comment]
> python -m auto_py-to_exe

The readme states to use `python -m auto_py_to_exe` as the module is `auto_py_to_exe`

**Comment by angryparizval** [comment]
sorry typo in my comment that is exactly what im running ("python -m auto_py_to_exe"

**Comment by brentvollebregt** [comment]
If you execute `dir` on Windows or `ls` on Linux in the terminal you have open, what is the output?

**Comment by angryparizval** [comment]
is that with the directory changed or base command prompt?

**Comment by brentvollebregt** [comment]
In the **exact** same place you are trying to execute `python -m auto_py_to_exe`

**Comment by angryparizval** [comment]
C:\Users\Ryan\Desktop\python2exe\auto-py-to-exe-master>dir
 Volume in drive C has no label.
 Volume Serial Number is D602-FFB0

 Directory of C:\Users\Ryan\Desktop\python2exe\auto-py-to-exe-master

07/09/2019  04:41 AM    <DIR>          .
07/09/2019  04:41 AM    <DIR>          ..
07/09/2019  04:41 AM                63 .gitignore
07/23/2019  07:18 PM    <DIR>          auto_py_to_exe
07/09/2019  04:41 AM             1,072 LICENSE
07/09/2019  04:41 AM               323 MANIFEST.in
07/09/2019  04:41 AM             5,049 README.md
07/23/2019  07:19 PM                30 requirements.txt
07/09/2019  04:41 AM               362 run.py
07/09/2019  04:41 AM             1,482 setup.py
               7 File(s)          8,381 bytes
               3 Dir(s)     329,568,256 bytes free

**Comment by brentvollebregt** [comment]
So you are saying, if you execute `python -m auto_py_to_exe` when your working directory is `C:\Users\Ryan\Desktop\python2exe\auto-py-to-exe-master` you get an error? Could you please paste the full output here?

**Comment by angryparizval** [comment]
C:\Users\Ryan\Desktop\python2exe\auto-py-to-exe-master>python -m auto_py_to_exe
Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)  File "C:\Users\Ryan\Desktop\python2exe\auto-py-to-exe-master\auto_py_to_exe\__main__.py", line 386, in <module>
    run()  File "C:\Users\Ryan\Desktop\python2exe\auto-py-to-exe-master\auto_py_to_exe\__main__.py", line 376, in run
    eel.start('main.html', size=(650, 612), options={'port': 0})  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\__init__.py", line 120, in start
    brw.open(start_urls, options)  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\browsers.py", line 35, in open
    chm.run(options, start_urls)  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\chrome.py", line 11, in run
    stdout=sps.PIPE, stderr=sps.PIPE, stdin=sps.PIPE)  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)OSError: [WinError 87] The parameter is incorrect

**Comment by brentvollebregt** [comment]
If you execute `python -m auto_py_to_exe --no-chrome`, what occurs?

**Comment by angryparizval** [comment]
i think it worked, is this correct?
![Capture](https://user-images.githubusercontent.com/53240846/61755359-369c9d80-ad85-11e9-8702-f88bdf10ea8d.PNG)

**Comment by brentvollebregt** [comment]
Yep, that worked. Do you have Chrome installed? The issue here was that it could not start Chrome, I guess this as `chm.run(options, start_urls)` was part of the stacktrace.

**Comment by angryparizval** [comment]
yeah i have chrome installed, Thanks for the help!

**Comment by brentvollebregt** [comment]
Very interesting, it must not be in a place Eel expects. I'll look into adding some warnings for this; thank you very much for being so co-operative!

**Comment by angryparizval** [comment]
i am always happy to help a fellow coder debug, nothing more satisfying then having a near perfect code!

**Comment by brentvollebregt** [comment]
I'll leave this open until I add some sort of warning for the user. I'll close it when the changes are on PyPI.

**Comment by SirAxolot** [comment]
How do you mute a thread?

**Comment by brentvollebregt** [comment]
You can unsubscribe from notifications for this issue by click "Unsubscribe" on the right hand side column on desktop.

**Comment by brentvollebregt** [comment]
Hey @angryparizval could you get a value for me when you're free? Execute the following:
```python
import eel
import os

chrome = eel.chrome.get_instance_path()
print ('eel.chrome.get_instance_path():', chrome)
print ('type:', type(chrome))
print ('Path exsits?:', os.path.exists(chrome))
```
What is the output? I just curious what eel was picking up as the Chrome location for you. I have a feeling that the exe it is finding doesn't exist, hence then `os.path.exists` call.

**Comment by angryparizval** [comment]
i get false

**Comment by angryparizval** [comment]
C:\Users\Ryan\Desktop>thingie.py
eel.chrome.get_instance_path():
type: <class 'str'>
Path exsits?: False

**Comment by brentvollebregt** [comment]
Oh! Very interesting; this is a bug in Eel. I'll account for this in the next commit. 

Once again, thank you very much.
