### ISSUE TITLE
exe fails

### ISSUE THREAD

**Issue by BriP47** [brentvollebregt/auto-py-to-exe#62]
exe fails to open. no errors reported in console. no errors reported in debug. This is a great program and I really want to get it to work. I am using Pmw. could that be the cause?

Running auto-py-to-exe v2.6.3
Building in the current instances temporary directory at C:\Users\BRIAN'~1\AppData\Local\Temp\tmpgbe7o0mk
To get a new temporary directory, restart this application
Recursion Limit is set to 5000
Executing: pyinstaller -y --add-data "C:/Users/Brian's computer/Pictures/Python Trials/current_reading.txt";"." --add-data "C:/Users/Brian's computer/Pictures/Python Trials/weekly_data.txt";"." "C:/Users/Brian's computer/Pictures/Python Trials/energy.py"
858962 INFO: PyInstaller: 3.4
858962 INFO: Python: 3.7.3
858962 INFO: Platform: Windows-10-10.0.17763-SP0
858964 INFO: wrote C:\Users\BRIAN'~1\AppData\Local\Temp\tmpgbe7o0mk\energy.spec
858967 INFO: UPX is not available.
858970 INFO: Extending PYTHONPATH with paths
["C:\\Users\\Brian's computer\\Pictures\\Python Trials",
 "C:\\Users\\BRIAN'~1\\AppData\\Local\\Temp\\tmpgbe7o0mk"]
858971 INFO: checking Analysis
858972 INFO: Building Analysis because Analysis-01.toc is non existent
858973 INFO: Initializing module dependency graph...
858978 INFO: Initializing module graph hooks...
858985 INFO: Analyzing base_library.zip ...
864106 INFO: running Analysis Analysis-01.toc
864113 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\brian's computer\appdata\local\programs\python\python37-32\python.exe
864196 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python.exe
864263 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python.exe
864313 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python.exe
864381 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python.exe
864431 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python.exe
864527 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
864596 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
864646 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
864713 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
864762 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
864827 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
864895 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
864947 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
865013 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
865078 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
865129 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
865194 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
865247 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
865313 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
865379 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
865429 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
865495 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\VCRUNTIME140.dll
865501 INFO: Caching module hooks...
865516 INFO: Analyzing C:\Users\Brian's computer\Pictures\Python Trials\energy.py
865751 INFO: Loading module hooks...
865751 INFO: Loading module hook "hook-encodings.py"...
865891 INFO: Loading module hook "hook-pydoc.py"...
865893 INFO: Loading module hook "hook-xml.py"...
866274 INFO: Loading module hook "hook-_tkinter.py"...
866342 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_tkinter.pyd
866396 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_tkinter.pyd
866618 INFO: checking Tree
866618 INFO: Building Tree because Tree-02.toc is non existent
866634 INFO: Building Tree Tree-02.toc
866744 INFO: checking Tree
866744 INFO: Building Tree because Tree-03.toc is non existent
866744 INFO: Building Tree Tree-03.toc
866829 INFO: Looking for ctypes DLLs
866829 INFO: Analyzing run-time hooks ...
866834 INFO: Including run-time hook 'pyi_rth__tkinter.py'
866849 INFO: Looking for dynamic libraries
866929 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_ssl.pyd
866992 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_ssl.pyd
867046 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\pyexpat.pyd
867112 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\pyexpat.pyd
867175 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\pyexpat.pyd
867229 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\pyexpat.pyd
867292 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\pyexpat.pyd
867346 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_hashlib.pyd
867430 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_lzma.pyd
867490 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_lzma.pyd
867557 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_socket.pyd
867627 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_bz2.pyd
867688 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_bz2.pyd
867744 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_bz2.pyd
867801 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_bz2.pyd
867861 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_bz2.pyd
867928 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\unicodedata.pyd
867987 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\unicodedata.pyd
868044 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\unicodedata.pyd
868109 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\select.pyd
868179 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_tkinter.pyd
868238 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\_tkinter.pyd
868310 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libssl-1_1.dll
868373 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libssl-1_1.dll
868430 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libssl-1_1.dll
868487 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libssl-1_1.dll
868594 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
868661 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
868723 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
868779 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
868844 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
868908 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
868968 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
869029 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
869108 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
869174 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\libcrypto-1_1.dll
869245 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tk86t.dll
869304 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tk86t.dll
869368 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tk86t.dll
869428 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tk86t.dll
869490 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tk86t.dll
869551 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tk86t.dll
869617 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tk86t.dll
869682 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tk86t.dll
869778 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
869840 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
869897 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
869955 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
870014 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
870072 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
870138 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
870198 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
870259 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\brian's computer\appdata\local\programs\python\python37-32\DLLs\tcl86t.dll
870273 INFO: Looking for eggs
870273 INFO: Using Python library c:\users\brian's computer\appdata\local\programs\python\python37-32\python37.dll
870273 INFO: Found binding redirects: 
[]
870283 INFO: Warnings written to C:\Users\BRIAN'~1\AppData\Local\Temp\tmpgbe7o0mk\build\energy\warn-energy.txt
870377 INFO: Graph cross-reference written to C:\Users\BRIAN'~1\AppData\Local\Temp\tmpgbe7o0mk\build\energy\xref-energy.html
870461 INFO: Appending 'datas' from .spec
870467 INFO: checking PYZ
870467 INFO: Building PYZ because PYZ-01.toc is non existent
870467 INFO: Building PYZ (ZlibArchive) C:\Users\BRIAN'~1\AppData\Local\Temp\tmpgbe7o0mk\build\energy\PYZ-01.pyz
871391 INFO: Building PYZ (ZlibArchive) C:\Users\BRIAN'~1\AppData\Local\Temp\tmpgbe7o0mk\build\energy\PYZ-01.pyz completed successfully.
871416 INFO: checking PKG
871417 INFO: Building PKG because PKG-01.toc is non existent
871417 INFO: Building PKG (CArchive) PKG-01.pkg
871443 INFO: Building PKG (CArchive) PKG-01.pkg completed successfully.
871446 INFO: Bootloader c:\users\brian's computer\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
871447 INFO: checking EXE
871447 INFO: Building EXE because EXE-01.toc is non existent
871447 INFO: Building EXE from EXE-01.toc
871448 INFO: Appending archive to EXE C:\Users\BRIAN'~1\AppData\Local\Temp\tmpgbe7o0mk\build\energy\energy.exe
871453 INFO: Building EXE from EXE-01.toc completed successfully.
871459 INFO: checking COLLECT
871459 INFO: Building COLLECT because COLLECT-01.toc is non existent
871460 INFO: Removing dir C:\Users\BRIAN'~1\AppData\Local\Temp\tmpgbe7o0mk\application\energy
871839 INFO: Building COLLECT COLLECT-01.toc
873785 INFO: Building COLLECT COLLECT-01.toc completed successfully.
Moving project to: C:\Users\Brian's computer\Pictures\Python Trials\debug
Complete.

**Comment by brentvollebregt** [comment]
Could you please provide a Python script to reproduce this issue.

**Comment by BriP47** [comment]
Thank you so much for such a prompt response.
The script calculates gas and electricity costs from meter readings input by the user:- 

from tkinter import*
from tkinter import messagebox
import math
import Pmw

window = Tk()
window.title("Energy Calculator")
window.geometry('400x300')
window.resizable(0,0)


def clicked_3():
    saveFile = open('weekly_data.txt','a')
    text1 = (txt4.get())
    text2 = (txt6.get()) 
    text3 = txt2.get()
    text4 = txt11.get()
    text5 = txt10.get()
    saveFile.write(text1 + " ")
    saveFile.write(text2 + " ")
    saveFile.write(text3 + " ")
    saveFile.write(text4 + " ")    
    saveFile.write(text5 + "\n")
        
    saveFile.close()
    
    
    
btn3 = Button(window, text="Save Data", command=clicked_3, takefocus = 0)
btn3.place(x= 260,y= 500)

#ELECTRICITY
txt1 = Pmw.EntryField(label_text = 'Previous:         ', entry_width = 10, entry_justify = "center", labelpos = 'w', value = '', validate = {'validator' : Pmw.integervalidator}, errorbackground = "white")
txt1.place(x=183,y=20)
txt1.component('entry').configure(takefocus=0)

txt2 = Pmw.EntryField(label_text = 'Current:           ', entry_width = 10, entry_justify = "center", labelpos = 'w', value = '', validate = {'validator' : Pmw.integervalidator}, errorbackground = "white")
txt2.place(x=183,y=50)
#txt2.component("entry").focus_force()

from datetime import datetime
from datetime import  timedelta
today = datetime.today()  
format = "%d/%m/%Y"
s = today.strftime(format)
EndDate = today + timedelta(days=-7)
PlusWeek = EndDate.strftime(format)

lbl1 = Label(window, text = "Electricity", takefocus = 0)
lbl1.place(x = 265, y = 1)
#lbl2 = Label(window, text = "Previous", takefocus = 0)
#lbl2.place(x = 180, y = 20)
#lbl3 = Label(window, text = "Present", takefocus = 0)
#lbl3.place(x = 180, y = 50)
lbl5 = Label(window, text = "Cost     " + chr(163), takefocus = 0)
lbl5.place(x = 40, y = 135)
txt3 = Entry(window, width = 10,justify = "center", takefocus = 0)
txt3.insert(0, PlusWeek)
txt3.place(x = 10, y = 20)
txt4 = Entry(window, width = 10,justify = "center", takefocus = 0)
txt4.insert(0, s)
txt4.place(x = 10, y = 50)
txt10 = Entry(window, width = 10,justify = "center", takefocus = 0)
txt10.place(x = 260, y = 135)
txt11 = Entry(window, width = 10,justify = "center", takefocus = 0)
txt11.place(x = 100, y = 135)

elec_unit_cost = 14.5428
elec_day_cost = 19.03
elec_discount = 21.43/365

current_reading_file = open('current_reading.txt', 'r')
current_reading_lines = current_reading_file.readlines()
current_reading_file.close()

txt1.insert(0,current_reading_lines[1])


def clicked_1():
    if int(txt1.get()) > int(txt2.get()):
        messagebox.showinfo("Check", "Previous reading is greater than Current reading")
        txt2.clear()
        return    
        
    txt10.delete(0,END)
    a = datetime.strptime(txt3.get(),"%d/%m/%Y")
    b = datetime.strptime(txt4.get(),"%d/%m/%Y")
    elec_days = (b - a).days
   
    elec_used = int(txt2.get()) - int(txt1.get())
    elec_cost = ((elec_used * elec_unit_cost) + (elec_days * elec_day_cost))/100 - (elec_days * elec_discount)
    vat = elec_cost * 5/100
    elec_cost = elec_cost + vat
    txt10.insert(0,'% 1.2f' % elec_cost)
    total = float(txt10.get()) + float(txt11.get())
    lbl8.configure(text ='% 1.2f' % total, takefocus = 0)
    if txt1.get() != "" and txt2.get() != "" and txt5.get() != "" and txt6.get() != "":
        btn3.place(x= 260,y= 250)    
    
btn1 = Button(window, text="Calculate", command=clicked_1, takefocus = 0)
btn1.place(x= 260,y= 85)


#GAS

lbl6 = Label(window, text = "Gas", takefocus = 0)
lbl6.place(x = 120, y = 1)

lbl8 = Label(window, takefocus = 0)
lbl8.place(x = 200, y = 185)

lbl9 = Label(window, text = "Total cost     " + chr(163), takefocus = 0)
lbl9.place(x = 120, y = 185)

txt5 = Pmw.EntryField(label_text = None, entry_width = 10, entry_justify = "center", labelpos = 'e', value = '', validate = {'validator' : Pmw.integervalidator}, errorbackground = "white")
txt5.place(x=100,y=20)
txt5.component('entry').configure(takefocus=0)

txt7 = Pmw.EntryField(label_text = 'Calorific \nvalue', entry_width = 5, entry_justify = "center", labelpos = 'e', value = '39.1', validate = {'validator' : Pmw.realvalidator}, errorbackground = "white")
txt7.place(x=10,y=85)

txt6 = Pmw.EntryField(label_text = None, entry_width = 10, entry_justify = "center", labelpos = 'e', value = '', validate = {'validator' : Pmw.integervalidator}, errorbackground = "white")
txt6.place(x=100,y=50)
txt6.component("entry").focus_force()

txt5.insert(0,current_reading_lines[0])

def clicked_2():
    if int(txt5.get()) > int(txt6.get()):
        messagebox.showinfo("Check", "Previous reading is greater than Current reading")
        txt6.clear()
        return
    
    txt11.delete(0,END)
    a = datetime.strptime(txt3.get(),"%d/%m/%Y")
    b = datetime.strptime(txt4.get(),"%d/%m/%Y")
    gas_days = (b - a).days  
    
    gas_unit_cost = 2.8858
    gas_day_cost = 21.76
    gas_discount = 21.43/365
    
    volume_correction = 1.02264
    calorific_value = 39.5
    conversion_factor = 3.6
    
    gas_used = ((int(txt6.get()) - int(txt5.get())) * volume_correction * float(txt7.get())) / conversion_factor
    
    gas_cost = (gas_used * gas_unit_cost)/100
    
    gas_cost = gas_cost + ((gas_days * gas_day_cost))/100 - (gas_days * gas_discount)
    
    vat = gas_cost * 5/100
    gas_cost = gas_cost + vat   
    txt11.insert(0, '% 1.2f' % gas_cost)
    if str(txt10.get()) != '' and str(txt11.get()) != '':
        total = float(txt10.get()) + float(txt11.get())
        lbl8.configure(text ='% 1.2f' % total, takefocus = 0)
        
    if txt1.get() != "" and txt2.get() != "" and txt5.get() != "" and txt6.get() != "":
        btn3.place(x= 260,y= 250)
    
btn2 = Button(window, text="Calculate", command=clicked_2, takefocus = 0)
btn2.place(x= 100,y= 85)
   
    
def on_closing():
    if messagebox.askyesno("Save", "Do you want to save current readings?"):
        text1 = txt6.get() + '\n'
        text2 = txt2.get()
        # notifies Python that you are opening this file, with the intention to write
        saveFile = open('current_reading.txt','w')
        
        # actually writes the information
        saveFile.write(text1)
        saveFile.write(text2)
        # It is important to remember to actually close the file, otherwise it will
        # hang for a while and could cause problems in your script
        saveFile.close()        
        window.destroy()
    else:
        window.destroy()
window.protocol("WM_DELETE_WINDOW", on_closing)


window.mainloop()

**Comment by BriP47** [comment]
Did not mean to close! Sorry, new to this.

**Comment by brentvollebregt** [comment]
Can you please provide a minimal working example demonstrating the issue; not your whole script. Also does this work when not using Pmw?

**Comment by BriP47** [comment]
because I am new to this, I do not understand what a 'minimal working example' is, sorry. I have tried various files from the Pmw_demos examples and none of them will compile with auto-py-to-exe. I have also tried to bundle the pmw files with bundlepmw.py, but even after modifying that file to Python 3 standard, can not get it to work. Thank you for your continuing help.

**Comment by BriP47** [comment]
Further, all my other programmes that do not use Pmw do work perfectly with auto-py-to-exe.

**Comment by brentvollebregt** [comment]
You said,

> no errors reported in console. no errors reported in debug

What exactly did you try?

**Comment by BriP47** [comment]
compiled my program in Wing personal 7. console screen did not show any errors. used auto-py-to exe to produce exe with debugging. could not find any errors. when executing myprogramme.exe console screen appears with no info in it, then disappears without programme starting.

**Comment by brentvollebregt** [comment]
Have you executed the output executable using cmd to preserve output? I don't see how this would crash and not provide an error message unless stderr is being routed somewhere else.

**Comment by BriP47** [comment]
No, I had not done that. Have just done as you suggested with the following console output:

Microsoft Windows [Version 10.0.17763.557]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Brian's computer\Pictures\Python Trials\debug\energy>energy.exe
Traceback (most recent call last):
  File "energy.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\brian's computer\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Pmw\__init__.py", line 28, in <module>
FileNotFoundError: [WinError 3] The system cannot find the path specified: "C:\\Users\\Brian's computer\\Pictures\\Python Trials\\debug\\energy\\Pmw"
[2672] Failed to execute script energy

**Comment by BriP47** [comment]
I realise that you are 12 hrs ahead in NZ and asleep! Further to my last comment, I have finally managed to compile bundlepmw.py into Pmw.py. I have placed this file, with Pmwblt.py and Pmwcolor.py in the same folder as my programme, energy.py and converted it again using auto-py-to-exe. I now get the following from the cmd console:

Microsoft Windows [Version 10.0.17763.557]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Brian's computer\Pictures\Python Trials\debug\energy>energy
Traceback (most recent call last):
  File "energy.py", line 4, in <module>
  File "C:\Users\Brian's computer\Pictures\Python Trials\debug\energy\Pmw.py", line 17
    raise ValueError, 'Dynamic versioning not available'
                    ^
SyntaxError: invalid syntax
[11888] Failed to execute script energy

**Comment by BriP47** [comment]
Finally, I have cracked it! It was Pmw. Had to make some Python3 updates to Pmw.py Now when I run the exe generated by auto-py-to-exe the programme runs, with the following console output:

Microsoft Windows [Version 10.0.17763.557]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Brian's computer\Pictures\Python Trials\debug\energy>energy

C:\Users\Brian's computer\Pictures\Python Trials\debug\energy>

I now have a working version of Pmw.py which you may need. How can I send it to you? just copy and paste into this comments box? Thank you for your help, it pushed me in the right direction!!

**Comment by brentvollebregt** [comment]
It's good to hear that you got it working, great job! If you want to provide an example for others, you can put your code between three '`', for example.

\`\`\`python
your code...
\`\`\`

This allows the code to format and make it easier to read.

**Comment by BriP47** [comment]
Can not put it in comment, comment is too long (above 65536 characters) However file was generated using bundlepmw.py in Pmw_2_0_1 bin folder. First of all open and run this file and then clear all errors by updating each error to conform to Python 3 syntax. Then in cmd line run this file with the path to Pmw_2_0_1 folder lib. Then open the resulting Pmw.py file, run it and correct all the errors by updating to Python 3 syntax. When completed, copy Pmw.py to working folder your py programme is in together with PmwColor.py and PmwBlt.py from the Pmw_2_0_1 lib folder.
I then included the three files as Additional Files in auto-py-to-exe.
