### ISSUE TITLE
setup installed as you said. But, after running python run.py - only chrome browser will open  what's gone wrong?

### ISSUE THREAD

**Issue by kiranhy** [brentvollebregt/auto-py-to-exe#63]
setup installed as you said. But, after running python run.py - only chrome browser will open 
what's gone wrong?

**Comment by brentvollebregt** [comment]
This is a bit vague to understand what's actually wrong here. auto-py-to-exe uses Chrome by default as stated in README.md, what's wrong with that?

**Comment by brentvollebregt** [comment]
Closing due to no response for three months.
