### ISSUE TITLE
Cannot work "Additinal Files('--add-data')" validly on Mac.

### ISSUE THREAD

**Issue by KagenoMoheji** [brentvollebregt/auto-py-to-exe#65]
I want to build executable application(One File) for Mac with auto-py-to-exe.
But my python scripts has matplotlib in Japanese, so I need to add 'ipaexg.ttf'.

So, I add a folder has it to "Additinal Files".

Although an executable application is built, it shows an error below.
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/4n/8l851g4133d320y_9r6vz18r0000gn/T/_MEIiDpsB0/modules/../config/font/ipaexg.ttf'
```

When build in the same way on Windows, it works well.
Only on Mac, why?

**Comment by brentvollebregt** [comment]
In the help post linked at the bottom of every build in the UI, I describe that it is a lot easier to initially debug while using one directory mode (not one file). When using one directory mode can you verify if the file was placed in the correct directory or not?

**Comment by KagenoMoheji** [comment]
Thanks for early response.
When build by "One Directory", I can verify the existence of `config/font/ipaexg.ttf` in the right part of an image.
Maybe it is the correct location.

But "One Directory" also shows the same error.

![スクリーンショット 2019-07-21 21 37 41](https://user-images.githubusercontent.com/37401955/61591316-7d14bf80-ac00-11e9-899f-0bd58c6dc26a.png)

**Comment by KagenoMoheji** [comment]
Oops!
By adding an empty folder "modules" to a folder has executable application, I resolved the error!

But hmm..., it's a bullish way...
