### ISSUE TITLE
One EXE file

### ISSUE THREAD

**Issue by TrackRunny** [brentvollebregt/auto-py-to-exe#66]
Quick question I want to make it so my python files can go into **one** exe file and then you can just run it and then everything will work. I checked the stackoverflow page for how to do that, but I really don't understand it much. I also checked the website to where it has the code snippet but I'm not sure what to do with that code. Can anyone help me with this?

**Comment by brentvollebregt** [comment]
Did you read my post on [Issues When Using auto-py-to-exe](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/)? In the post, I talk about [adding the path wrapper](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#the-one-file-resource-wrapper) so Python can find your files when in both one file and one directory mode.

I recommend getting the one directory mode setup working correctly first when adding the path snippet before you try using one file mode.

**Comment by brentvollebregt** [comment]
@TrackRunny did you solve the issue?

**Comment by TrackRunny** [comment]
Coming back to this after one month, let me try what you said. I totally forgot about this.

**Comment by brentvollebregt** [comment]
No further information provided. Closing the issue.
