### ISSUE TITLE
Seems to convert okay but then when I run the .exe nothing happens. 

### ISSUE THREAD

**Issue by sanjayrastogi92** [brentvollebregt/auto-py-to-exe#69]
I have written a simple hello program in python and I've converted that file to .exe.
File seems to be converted okay but on clicking it, nothing happens.

**Comment by brentvollebregt** [comment]
There is a link that appears at the bottom of the UI after every build that asks "Something wrong with your exe? Read [this post on how to fix common issues](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/) for possible solutions", this link is also clearly shown in the README.

After following the debugging section in this article, what is appearing in the console? I can't really help with just "clicking it, nothing happens" sorry.

**Comment by brentvollebregt** [comment]
@sanjayrastogi92 have you solved your issue?

**Comment by brentvollebregt** [comment]
No further information provided. Closing the issue.
