### ISSUE TITLE
can´t open pictures

### ISSUE THREAD

**Issue by Vllme** [brentvollebregt/auto-py-to-exe#7]
If i try to run the .exe file it sys, that it can open a sertaint picture

**Comment by brentvollebregt** [comment]
Have you packed it into a onefile?

**Comment by brentvollebregt** [comment]
It's been two days and im assuming you didn't think about where [assets are unpacked too](https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile/13790741#13790741).

Re-open the issue if there is still something wrong.
