### ISSUE TITLE
auto-py-to-exe disappears immediately when run

### ISSUE THREAD

**Issue by Dulce06** [brentvollebregt/auto-py-to-exe#70]
I tried to open this application but doesn't work. When I run this, I can see the graphical interface for a second and then it disappears immediately. 

How to fox this?

Thanks

**Comment by brentvollebregt** [comment]
When you run what? Could you please give some details on how you are using this application and what disappears? auto-py-to-exe uses Chrome which I have never heard of opening and disappearing immediately (in the context of this application).

**Comment by Dulce06** [comment]
You heard me right. I did run auto-py-to-exe on cmd but I could see some random window opening up and closed immediately.

**Comment by brentvollebregt** [comment]
Could you please give some more detail, there isn't much here I can use to reproduce the error. Currently what I understand is that when you execute `auto-py-to-exe` in a terminal, the Chrome window appears and disappears immediately.

Are there any errors? What OS are you using? What version of Python are you using? What are you actually executing? Where are you executing it? How did you install the project?

**Comment by brentvollebregt** [comment]
@Dulce06 any further information on this?

**Comment by brentvollebregt** [comment]
No further information provided. Closing the issue.
