### ISSUE TITLE
UPX is not working.. think a '=' is missing from the command line?

### ISSUE THREAD

**Issue by soliverc** [brentvollebregt/auto-py-to-exe#72]
I specified my UPX directory `C:\Stuff\Gooey\upx`

But in the output I see `244089 INFO: UPX is not available.`

Looking at the code in the "Current Command" window it says:

`pyinstaller -y -F -w --upx-dir C:\Stuff\Gooey\upx  "C:/Stuff/Gooey/group_experiment.py"`

Should it not be: `--upx-dir=C:\Stuff\Gooey\upx` with an equal `=` sign?

**Comment by brentvollebregt** [comment]
I see what's being said here. If you put `--upx-dir=C:\Stuff\Gooey\upx` in the "Extra Command Data" at the bottom of the advanced tab, does it then work?

Looking at the [docs](https://pyinstaller.readthedocs.io/en/stable/usage.html#general-options), they list it as `--upx-dir UPX_DIR` but then [proceed to use it](https://pyinstaller.readthedocs.io/en/stable/usage.html#shortening-the-command) like `--upx-dir=/usr/local/share/` in the examples.

**Comment by soliverc** [comment]
Ok I have tried both

```
pyinstaller -y -F -w --upx-dir C:/Allegiant/Gooey/upx --upx-dir=C:\Allegiant\Gooey\upx  "C:/Allegiant/Gooey/group_experiment.py"
```
and 
```
pyinstaller -y -F -w --upx-dir=C:\Allegiant\Gooey\upx  "C:/Allegiant/Gooey/group_experiment.py"
```
Both have the output `upx is not available`. 

Upx just needs to be unzipped into a folder, correct? I downloaded upx from both https://upx.github.io and https://github.com/upx/upx. Both show this error.

**Comment by brentvollebregt** [comment]
I have not used UPX before so I'm not sure about the format that UPX must be in but it seems like all you need to do is to get a [release](https://github.com/upx/upx/releases), extract it, and specify --upx-dir as the directory containing the exe.

I recommend testing with PyInstaller directly before testing with auto-py-to-exe to verify that the UPX command is working/not working.

**Comment by brentvollebregt** [comment]
@soliverc did you solve this in the end?

**Comment by soliverc** [comment]
Hey @brentvollebregt , sorry. I never got around to testing the Pyinstaller library itself. The UPX issue wasn't vital so I just left it as it is due to time constraints.

**Comment by brentvollebregt** [comment]
That's ok. I'll close this issue but if someone else has the same issue, I am happy to open this back up.

**Comment by soliverc** [comment]
No probs.
