### ISSUE TITLE
Missing Python 3.8 support

### ISSUE THREAD

**Issue by reirose** [brentvollebregt/auto-py-to-exe#74]

**Comment by brentvollebregt** [comment]
I'm not able to test 3.8 at the moment, but are there any issues you have discovered? Or is the issue that I am not stating that 3.8 is supported?

**Comment by brentvollebregt** [comment]
pyinstaller/pyinstaller#4311 has been closed but we will have to wait for the new release to PyPI before 3.8 can be officially supported.

**Comment by unbeatable-101** [comment]
Using the dev branch of pyinstaller, I have not had any issues on python 3.9.

**Comment by brentvollebregt** [comment]
Yes, but there needs to be a release that officially supports Python 3.8 otherwise we will probably run into issues around pip. 

You can install pyinstaller manually if you want, this tool should work with the latest.

**Comment by unbeatable-101** [comment]
In the readme, pyinstaller lists 3.5-3.8 as supported

**Comment by brentvollebregt** [comment]
@unbeatable-101 yes, I understand that. But that is the master branch, which has not been released to PyPI officially yet.

As [judge2020's comment](https://github.com/pyinstaller/pyinstaller/issues/4311#issuecomment-688532918) in pyinstaller#4311 linked above stated:
> the PR was merged in 96ad296, so it's there, but there hasn't been a release yet. If you install from the develop branch instead of pypi (see below), you should have the relevant commit and the latest changes, although there might be more bugs than in a release.

If you go to [pypi.org/project/pyinstaller/](https://pypi.org/project/pyinstaller/) and look at the supported Python versions, it clearly states:
> Works out-of-the-box with any Python version 3.5-3.7.

**Comment by unbeatable-101** [comment]
4.0 has been released, and the website says `Works out-of-the-box with any Python version 3.5-3.9.`

**Comment by brentvollebregt** [comment]
Thanks for letting me know @unbeatable-101 - I'll take a look at making PyInstaller 4.1 a required dependency for the project to support Python 3.8 + 3.9

**Comment by brentvollebregt** [comment]
auto-py-to-exe 2.7.9 has been just released which should fix this
