### ISSUE TITLE
ptyhon/pyinstaller :  eel to exe tells me:   ( filenotfounderror: [errno 2] no such file or directory: 'eel' ) in auto-py-to-exe-master ,or   [ permission is denied in cmd ]>>>   when I tried in cmd . my OS win32bit python3.7 #52

### ISSUE THREAD

**Issue by BMarquiz** [brentvollebregt/auto-py-to-exe#75]
ptyhon/pyinstaller : eel to exe tells me: ( filenotfounderror: [errno 2] no such file or directory: 'eel' ) in auto-py-to-exe-master ,or[ permission is denied in cmd ]>>>win32bit python3.7 #52

my command line : pyinstaller -y -F -i "C:/Users/Broo/Desktop/Barq/barq.ico" --add-data "C:/Users/Broo/Desktop/Barq/web";"web/" --add-data "C:/Users/Broo/Desktop/Barq/web/order.html";"." --add-data "C:/Users/Broo/Desktop/Barq/web/page1.html";"." --add-data "C:/Users/Broo/Desktop/Barq/web/page2.html";"." -m eel --hidden-import win32com  "C:/Users/Broo/Desktop/Barq/pass.py"

**Comment by BMarquiz** [comment]
@brentvollebregt  my project designed to work with internet connection.please tell me what to do.

**Comment by brentvollebregt** [comment]
Where does this error appear? What actions do you perform to get this error?

**Comment by BMarquiz** [comment]
@brentvollebregt  when I tried to convert my python project to exe with eel libarary in auto-py-to-exe-master  during the Process, this error came up.

**Comment by BMarquiz** [comment]
@brentvollebregt  Thank you I've tried to start my command with python -m eel ..... 
and it's worked correctly.

**Comment by brentvollebregt** [comment]
Why is the value supplied to `-m` `eel`? 

-m is used to *"Add manifest FILE or XML to the exe"*; this should be a file path. PyInstaller is looking for a file named `eel` (as that is what you have told it to look for) but it doesn't exist.

**Comment by brentvollebregt** [comment]
I looked at your recent activity and noticed you opened an issue at samuelhwilliams/Eel#202, is this now solved?

**Comment by brentvollebregt** [comment]
@BMarquiz have you solved your issue?

**Comment by brentvollebregt** [comment]
Closing due to no response from @BMarquiz
