### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by DanPostar** [brentvollebregt/auto-py-to-exe#79]
Using cached https://files.pythonhosted.org/packages/7b/84/2dc373eb6493e00c884cc11e6c059ec97abae2678d42f06bf780570b0193/gevent_websocket-0.10.1-py3-none-any.whl
Collecting gevent (from gevent-websocket->bottle-websocket->Eel==0.11.0->auto-py-to-exe)
  Using cached https://files.pythonhosted.org/packages/ed/27/6c49b70808f569b66ec7fac2e78f076e9b204db9cf5768740cff3d5a07ae/gevent-1.4.0.tar.gz
    **ERROR: Command errored out with exit status 1:**
     command: 'c:\users\danpo\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\danpo\\AppData\\Local\\Temp\\pip-install-zz0rycn9\\gevent\\setup.py'"'"'; __file__='"'"'C:\\Users\\danpo\\AppData\\Local\\Temp\\pip-install-zz0rycn9\\gevent\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\danpo\AppData\Local\Temp\pip-install-zz0rycn9\gevent\
    Complete output (113 lines):
    Traceback (most recent call last):
      File "c:\users\danpo\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\danpo\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules

**Comment by brentvollebregt** [comment]
This has been discussed in samuelhwilliams/Eel#214 by samuelhwilliams

>I think this is not strictly an issue with Eel, but a recent regression affecting Python 3.8 on Windows setuptools < 42.0.0.
> 
> This is based on a little googling, which showed up the following:
> 
> - numpy/numpy#14873
> - pypa/setuptools#1874
> - https://setuptools.readthedocs.io/en/latest/history.html#v42-0-0
> 
> I think it was fixed in setuptools 42.0.0, so possibly upgrading to that will help. An alternative workaround may be to downgrade to Python 3.7.x. I'm not sure I see that there's anything to be done in Eel at the moment though.

So as Samuel mentioned, I recommend updating your setuptools.

Also as a side note; this project does not support Python 3.8 currently as PyInstaller does not support 3.8 yet.

**Comment by brentvollebregt** [comment]
Closing due to no response from the issue author.
