### ISSUE TITLE
Do you have plans for Linux  OSs?

### ISSUE THREAD

**Issue by ReddyKilowatt** [brentvollebregt/auto-py-to-exe#83]
This is a very useful project, I will use it on Windows but would like
to be able to deploy Linux apps too. PyInstaller is already cross-platform, do you have any plans to make this work on Linux too?

**Comment by brentvollebregt** [comment]
This project should also work on Linux. What issues are you having?

**Comment by ReddyKilowatt** [comment]
None yet, as I haven't tried it there. I thought the references to "exe" meant ".exe", which is the suffix for executable binaries for Windows. I'll try it on Linux then.

**Comment by brentvollebregt** [comment]
@ReddyKilowatt did you find any issues?

**Comment by ReddyKilowatt** [comment]
I didn’t try it yet. Let’s close this issue for now.
