### ISSUE TITLE
Getting unknown Error EXE - http://python.org/dev/peps/pep-0263/ for details

### ISSUE THREAD

**Issue by sameerCoder** [brentvollebregt/auto-py-to-exe#86]
Hi , 
I have simple tkinter gui py code for which i am making Exe , Exe made successfully even extra module like pandastable also embedded perfectly but i have size issue - 
1- My EXE folder is of memory 900 MB which is very huge as my script is of kb only .
Isn't there any way to reduce the exe folder size ?

**Comment by brentvollebregt** [comment]
This is more of a PyInstaller feature rather than an auto-py-to-exe issue. 
Setup a new virtual environment and install only the packages you need. Then use auto-py-to-exe in this environment and see if you get a different build size; I am guessing you might have a large list of installed modules which are being unnecessarily added. 
Also how is that title related to your description?

**Comment by sameerCoder** [comment]
Hi Brentvollebregt,
Thanks for such a quick response . isn't there any way I can delete un
required modules so that my file exe file folder has less memory size .
thank you.

**Comment by brentvollebregt** [comment]
You can exclude them using the `--exclude-module` input; you need to know the modules to exclude first.

Did you create a new environment and package as I described before? Will help identify that this is the problem. (Not actually a problem with auto-py-to-exe in this case)

**Comment by sameerCoder** [comment]
HI Brentvollebregt ,
I have created env as suggested by you . size is less but if same exe if i
want to run on different linux machine how i can do that ?
Do i have to installed the required modules and then run the exe . I am
trying to run on different linux machine then i am getting Error










*[accountname@iitmlogin4 walps2_pandastable]$ ./walps2_pandastable
Traceback (most recent call last):  File "walps2_pandastable.py", line 73,
in <module>  File "walps2_pandastable.py", line 2, in functionwork  File
"/home/username/anaconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py",
line 623, in exec_module  File "tkinter/__init__.py", line 36, in
<module>ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found
(required by
/path/swan/AdcirSwan/TamilNadu/CoupledModel/walpscouplemodel/PYthon_Exe/walps2_pandastable/./libX11.so.6)[11080]
Failed to execute script walps2_pandastableHOW i can run by  EXE on another
linux machine / HPC ?*
*Thank you.*

**Comment by brentvollebregt** [comment]
As noted in [PyInstallers FAQ](https://github.com/pyinstaller/pyinstaller/wiki/FAQ#frequently-asked-questions), PyInstaller is not a cross-compiler. So to get the project running on a Linux machine, you will need to have Python set up and modules installed so you can run the project. You can then package the script on Linux so you can distribute for Linux machines.

What error are you gettting?

**Comment by sameerCoder** [comment]
Hi,
Thanks for quick reply   ,
I am trying to run on different linux machine then i am getting Error










*[accountname@iitmlogin4 walps2_pandastable]$ ./walps2_pandastableTraceback
(most recent call last):  File "walps2_pandastable.py", line 73, in
<module>  File "walps2_pandastable.py", line 2, in functionwork  File
"/home/username/anaconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py",
line 623, in exec_module  File "tkinter/__init__.py", line 36, in
<module>ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found
(required by
/path/swan/AdcirSwan/TamilNadu/CoupledModel/walpscouplemodel/PYthon_Exe/walps2_pandastable/./libX11.so.6)[11080]
Failed to execute script walps2_pandastableHOW i can run by  EXE on another
linux machine / HPC ?*
*Thank you.*

**Comment by brentvollebregt** [comment]
It seems that whatever module you are using, libgcc is required. You are running this on a machine where GLIBC_2.14 is not available.

**Comment by sameerCoder** [comment]
Hi ,
      Fine , i will installed GLIBC_2.14 into the machine and let you know
its working fine or not . Thank  you.

**Comment by brentvollebregt** [comment]
There has been no further discussion on this issue for more than three months now so I'm assuming that this has been resolved and will close the issue.
