### ISSUE TITLE
Two Error- Segmentation fault (core dumped) & MatplotlibDeprecationWarning: 

### ISSUE THREAD

**Issue by sameerCoder** [brentvollebregt/auto-py-to-exe#87]
Hi ,
1- My py got converted to Exe but while running the .exe file using ./filenameexe i am getting some segmentation fault & running is getting exit, 
Kindly let me know how to solve this Segmentation fault error .
run fun
/home/sakib/anaconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py:623: MatplotlibDeprecationWarning: 
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Segmentation fault (core dumped)
2- Is there any way i can modules version in exe folder ?
Thank you.

**Comment by brentvollebregt** [comment]
Where did you build the executable? Where are you running the executable? Have you been able to get a basic example to work?

**Comment by sameerCoder** [comment]
Yes basic example is working fine when I am making my basic example exe on
linux machine and its working fine but the exe made of matplotlib module /
advance py file then I am getting error - segmentation fault ,
My exe half working fine as print statement is working but after getting
segmentation error exe stop working
What I have to do to solve this problem?

**Comment by brentvollebregt** [comment]
Unless you have used hidden imports that aren't being added, this will be a PyInstaller issue and not directly linked to auto-py-to-exe.

If you copy the text shown in the "Current Command" textbox and use this to build you executable, do you get the same error?

**Comment by sameerCoder** [comment]
HI,
All modules are prefect in EXE folder as i am not getting any modules Error
in EXE and even all the extra required modules i have added into my exe
folder by writing modules names into hidden imports.
So the modules is correct but i think some memory issue is there that's why
i am getting segmentation error after few lines run of exe .
How to remove this segmentation error while running exe  ?
Thank you.

**Comment by sameerCoder** [comment]
Hi,
          kindly find the screenshot of Error with this email as an
attachment .

**Comment by brentvollebregt** [comment]
There is no screenshot that has been sent. I do not believe this is an auto-py-to-exe issue sorry, you will need to report the issue to [PyInstallers GitHub repository](https://github.com/pyinstaller/pyinstaller/issues) as I cannot help with the information provided.

They may have some ideas if you give enough information but the best thing you could do is identify the culprit line.

**Comment by sameerCoder** [comment]
Thank you for quick response , i will report issue to Pyintallers ,
*1- Can you tell me is there any way i can find  Modules version in my EXE
Folder , i have numpy modules folder in my EXE folder but i am not able to
findout which version of numpy i am using in EXE folder .*

**Comment by brentvollebregt** [comment]
The module version should be the same version of the module in the environment that you used to package the executable. Before reporting this to PyInstaller, I highly recommend you identify the culprit line(s) and module(s) though trial and error.

**Comment by sameerCoder** [comment]
Ok Brent , Even the module env is same as of package
executable and i don't think there is any error in modules , i think error
is in using computer memory while running
                      the EXE file . I am doing experiment on this exe so
that i can find out the culprit .
Thank you.

**Comment by Legorooj** [comment]
@brentvollebregt please close this; this is PyInstaller not your tool.
