### ISSUE TITLE
Pre Complied BootLoader missing

### ISSUE THREAD

**Issue by JCastix** [brentvollebregt/auto-py-to-exe#88]
using auto-py-to-exe with Python 3.7 (64 bit) on Wimdows 10 It is throwing this error:
Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>

**Comment by brentvollebregt** [comment]
If you copy the text shown in the "Current Command" textbox and use this to build you executable, do you get the same error?

**Comment by JCastix** [comment]
Brent,

Thanks for the response, I’m not sure. How do I do that?  From the Command Line?

Thanks

**Comment by brentvollebregt** [comment]
Yes, you need to execute this from the command line

**Comment by JCastix** [comment]
Ok, thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JCastix** [comment]
Brent,

Sorry, no go its throwing the same exception?

**Comment by brentvollebregt** [comment]
That's ok, that means this is a [PyInstaller](https://github.com/pyinstaller/pyinstaller) issue and not an auto-py-to-exe issue.

Have you done much searching on this error? There are some basic steps [here](https://stackoverflow.com/a/57077536) and some checks you could make [here](https://github.com/pyinstaller/pyinstaller/issues/4318).

**Comment by JCastix** [comment]
Yes,

Just I thought I'd pass along, and being thorough.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
