### ISSUE TITLE
[On Mac] Creating .exe file instead of Unix executable application

### ISSUE THREAD

**Issue by leonatez** [brentvollebregt/auto-py-to-exe#89]
Dear everyone,

I am a Mac user. I was trying to convert a .py file to .exe file to be executed on Windows OS (on another machine).
I tried all options but still couldn't create a .exe app for Windows. All I have after the conversion is just Unix Executable file which run perfectly on my Mac, not my colleagues' PC.
Could you please guide how I can convert to a Windows .exe file on my Mac?
Thank you very much!

**Comment by brentvollebregt** [comment]
Are you packaging on MacOS and then trying to execute it on Windows? This will definitely not work as  [Pyinstaller is not a cross compiler](https://github.com/pyinstaller/pyinstaller/wiki/FAQ#features).

PyInstaller has bundled your script and the Python interpreter required to run a Python script, this interpreter will be specific to your OS so it will not work on another OS unless you provide it a different interpreter (or something to wrap it).

A simple Google search provided [this stackoverflow question](https://stackoverflow.com/a/42059844):

> For pyinstaller, they have clearly mentioned that packaging Windows binaries while running under OS X is NOT supported, and recommended to use Wine for this.

**Comment by leonatez** [comment]
Thank you so much! I tried to search many keywords like "auto-py-to-exe not generated exe only UNIX" but couldn't find your attached topic. Since I'm newbie, I don't know how to search in an expert-way :)
Hope my topic would help newbie like me to find this answer!
