### ISSUE TITLE
Selecting Multiple Additional Files

### ISSUE THREAD

**Issue by William-Lake** [brentvollebregt/auto-py-to-exe#9]
Hello! First off- Thanks for making this! You did a great job and it's been an awesome resource.

I had a quick idea that I thought would be helpful to pass along. In short, adding the ability to select multiple files when adding to the 'Additional Files' section would be incredibly useful. At the moment, if you try to select multiple files in the Native File Dialog via Ctrl-Click or Shift-Click you only end up selecting the last File clicked. This means you have to select each file individually, which can be time consuming with large amounts.

Thanks again!

**Comment by brentvollebregt** [comment]
This is a very good idea. I know that although my search button only finds files, you can actually put a folder in the 'file' input and the folder contents will be placed into the destination.

I am quite busy right now (uni) so I can't implement this right now but I can in the future when I have time. Sorry about that.

**Comment by brentvollebregt** [comment]
Thanks for bringing this up. Hopefully this fixes your issue. Also thank you for waiting.
If an issue does still persist or a new one has just been introduced feel free to re-open this.

**Comment by William-Lake** [comment]
Hi! I'm sorry for the wait, I'm also working on wrapping up a few classes. Thanks so much for your help! I appreciate all your work.
