### ISSUE TITLE
EXE does not work in another computer

### ISSUE THREAD

**Issue by AragonGrosso** [brentvollebregt/auto-py-to-exe#90]
Hi,

I have created an EXE from a PY file, and it is working perfectly in my computer. The problem is when I try to run that EXE in another computer (same OS). The error is "Failed to execute script _scriptname_".

I am using the folder and Window based options. Y tried both including PY file into the folder and not.

Thank you in advance.

**Comment by brentvollebregt** [comment]
In the README under *Issues Using the Tool*, there is a link to a help article that I wrote. I **highly** recommend you read this, especially the area on [Debugging](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging).

Following the steps in the article will help you identify the hidden error being thrown.

**Comment by jrcribb** [comment]
Do you have an error message to show us?

**Comment by brentvollebregt** [comment]
There has been no response in more than three months so I'm going to assume this was resolved.
