### ISSUE TITLE
I want to run exe file into that system in which I don't have Python installed, is it possible?

### ISSUE THREAD

**Issue by hemangbhavasar** [brentvollebregt/auto-py-to-exe#91]
I tried that but found difficulty to convert completely into exe.

Scenario: I have python scripts that take input from the user and open the browser (via chromedriver) and add fill those values to automate user's work.

I have two .py files in which one is calling others.

PyQt file is a UI python script, by which the user can enter inputs and based on inputs main.py will run.

Problem: When I am trying to convert into exe by using "auto-py-to-exe", it making exe file but when I am running that exe file into that system in which I don't have Python installed, it's giving me an error.

So is there any way by which I can make exe file and run the script in that system also in which Python is not installed?

I would be very grateful if you can help me with this.

**Comment by brentvollebregt** [comment]
Did you read my post on [Issues When Using auto-py-to-exe](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/)? This is linked at the bottom of the UI after every build and in the README of this repository; I highly recommend you give it a read.

In the post I discuss a [debugging](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging) method to identify the error.

Could you please provide the error you have gotten? You said:

> it's giving me an error

but never supplied the error?

**Comment by ravigupta-art** [comment]
@hemangbhavasar  As program 'auto-py-to-exe' uses Pyinstaller to compile the executable files, it should be able to bundle all the dependencies in one file if you choose the option.

With pyinstaller, we can provide the flag -F to bundle all the files and generate an exe. 

As @brentvollebregt  mentioned, you need to provide an detailed output/error.

**Comment by hemangbhavasar** [comment]
Hi,

I am able to create a exe file but my issue is when I am trying to run the
exe file in other system in which I don't have python, it not working as
properly as it is doing in the system in which python installed.

So it would be great if you can help me with this.

BR
HEMANG BHAVASAR

**Comment by ravigupta-art** [comment]
@hemangbhavasar 
The solution I am providing is not directly related to 'auto-py-to-exe'. As 'auto-py-to-exe' uses Pyinstaller for genrerating the executable. Why don't you try to use command-line interface with Pyintstaller to generate the exe?

I simply used Pyinstaller in my project at 'ravigupta-art/IgnouPercentageCalculator' and the executable generated works across different machines with supported OS and platform.

A Pyinstaller command would look like this:
`$ pyinstaller -wF --add-data "data_filename.extention:." your_main_pythonfile.py`

Here the flag '-w' generates a a single window while running the app. '-F' flag is used to bundle all the dependencies and generate a single executable  file. '--add-data' add the extra or data files that are required/called within your main python app. Next is the data file name to added with the path (in my case it is simply '.' as the data file is located in the same folder as the python file. ( I am referring to this part "data_filename.extention:.")

And then comes the name of the python file.

Note: You need to in the same directory as the python file. Else, provide the path to the file in pyinstaller command.

If you are using windows the command would be like this:
`$ pyinstaller -wF --add-data "data_filename.extention;." your_main_pythonfile.py`

Note the difference, the ':' is replaced with ';' in the command for windows.

**Comment by brentvollebregt** [comment]
@hemangbhavasar the debugging method I linked above does not require Python after you have packaged your script. You need to look at the output to stdout on the machine that it doesn't work on.

**Comment by hemangbhavasar** [comment]
Thanks,

I will try today and let you know.

Again thank you.

BR
Hemang Bhavasar

**Comment by ScotterMonk** [comment]
Hope this is the place to post this:
I want to offer $100 bounty (wish I could afford more!) for someone to convert my simple Python 2D game to an EXE. I built the game using Python 3.8 - 64bit in Windows and it uses the following dependencies: import arcade, from arcade.gui import *, import math, import random, import os, import pyautogui, from datetime import datetime, timedelta

**Comment by hemangbhavasar** [comment]
> @hemangbhavasar
> The solution I am providing is not directly related to 'auto-py-to-exe'. As 'auto-py-to-exe' uses Pyinstaller for genrerating the executable. Why don't you try to use command-line interface with Pyintstaller to generate the exe?
> 
> I simply used Pyinstaller in my project at ['ravigupta-art/IgnouPercentageCalculator'](https://github.com/ravigupta-art/IgnouPercentageCalculator) and the executable generated works across different machines with supported OS and platform.
> 
> A Pyinstaller command would look like this:
> `$ pyinstaller -wF --add-data "data_filename.extention:." your_main_pythonfile.py`
> 
> Here the flag '-w' generates a a single window while running the app. '-F' flag is used to bundle all the dependencies and generate a single executable file. '--add-data' add the extra or data files that are required/called within your main python app. Next is the data file name to added with the path (in my case it is simply '.' as the data file is located in the same folder as the python file. ( I am referring to this part "data_filename.extention:.")
> 
> And then comes the name of the python file.
> 
> Note: You need to in the same directory as the python file. Else, provide the path to the file in pyinstaller command.
> 
> If you are using windows the command would be like this:
> `$ pyinstaller -wF --add-data "data_filename.extention;." your_main_pythonfile.py`
> 
> Note the difference, the ':' is replaced with ';' in the command for windows.

Thanks for details.
I saw you repository for calculator but in that also you have created a exe file from a python file.
But in my case I am using 3 python files and one chromedriver file and I want to convert that into a exe.

If you have any solution for that, please let me know. :)

Thanks,
Hemang Bhavasar

**Comment by hemangbhavasar** [comment]
> @hemangbhavasar the debugging method I linked above does not require Python after you have packaged your script.
> 
> Look at the output to stdout on the machine that it doesn't work on - what is the output? An error?

I am getting below error...
"No module named "xml.dom"

**Comment by ravigupta-art** [comment]
> > @hemangbhavasar
> > The solution I am providing is not directly related to 'auto-py-to-exe'. As 'auto-py-to-exe' uses Pyinstaller for genrerating the executable. Why don't you try to use command-line interface with Pyintstaller to generate the exe?
> > I simply used Pyinstaller in my project at ['ravigupta-art/IgnouPercentageCalculator'](https://github.com/ravigupta-art/IgnouPercentageCalculator) and the executable generated works across different machines with supported OS and platform.
> > A Pyinstaller command would look like this:
> > `$ pyinstaller -wF --add-data "data_filename.extention:." your_main_pythonfile.py`
> > Here the flag '-w' generates a a single window while running the app. '-F' flag is used to bundle all the dependencies and generate a single executable file. '--add-data' add the extra or data files that are required/called within your main python app. Next is the data file name to added with the path (in my case it is simply '.' as the data file is located in the same folder as the python file. ( I am referring to this part "data_filename.extention:.")
> > And then comes the name of the python file.
> > Note: You need to in the same directory as the python file. Else, provide the path to the file in pyinstaller command.
> > If you are using windows the command would be like this:
> > `$ pyinstaller -wF --add-data "data_filename.extention;." your_main_pythonfile.py`
> > Note the difference, the ':' is replaced with ';' in the command for windows.
> 
> Thanks for details.
> I saw you repository for calculator but in that also you have created a exe file from a python file.
> But in my case I am using 3 python files and one chromedriver file and I want to convert that into a exe.
> 
> If you have any solution for that, please let me know. :)
> 
> Thanks,
> Hemang Bhavasar

Please share link to your repo. I will see, if something can be done.

**Comment by brentvollebregt** [comment]
@hemangbhavasar when you got the error:

> "No module named "xml.dom"

Was there a stacktrace with the error? It could help track down the module that is causing this and potentially lead to a recommendation for a module name to be added to --hidden-import

**Comment by brentvollebregt** [comment]
@ScotterMonk, probably not the most ideal place as GitHub Issues are for bug/feature requests - also this issue is to sort out hemangbhavasar's issue. I recommend adding a comment on [the video associated](https://www.youtube.com/watch?v=OZSZHmWSOeM) or [post I wrote for help on this tool](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/) where I help people with questions; I could take at your situation there.

**Comment by hemangbhavasar** [comment]
> > > @hemangbhavasar
> > > The solution I am providing is not directly related to 'auto-py-to-exe'. As 'auto-py-to-exe' uses Pyinstaller for genrerating the executable. Why don't you try to use command-line interface with Pyintstaller to generate the exe?
> > > I simply used Pyinstaller in my project at ['ravigupta-art/IgnouPercentageCalculator'](https://github.com/ravigupta-art/IgnouPercentageCalculator) and the executable generated works across different machines with supported OS and platform.
> > > A Pyinstaller command would look like this:
> > > `$ pyinstaller -wF --add-data "data_filename.extention:." your_main_pythonfile.py`
> > > Here the flag '-w' generates a a single window while running the app. '-F' flag is used to bundle all the dependencies and generate a single executable file. '--add-data' add the extra or data files that are required/called within your main python app. Next is the data file name to added with the path (in my case it is simply '.' as the data file is located in the same folder as the python file. ( I am referring to this part "data_filename.extention:.")
> > > And then comes the name of the python file.
> > > Note: You need to in the same directory as the python file. Else, provide the path to the file in pyinstaller command.
> > > If you are using windows the command would be like this:
> > > `$ pyinstaller -wF --add-data "data_filename.extention;." your_main_pythonfile.py`
> > > Note the difference, the ':' is replaced with ';' in the command for windows.
> > 
> > 
> > Thanks for details.
> > I saw you repository for calculator but in that also you have created a exe file from a python file.
> > But in my case I am using 3 python files and one chromedriver file and I want to convert that into a exe.
> > If you have any solution for that, please let me know. :)
> > Thanks,
> > Hemang Bhavasar
> 
> Please share link to your repo. I will see, if something can be done.

Hi Ravi,

I sent you invite please check.

Thanks for help in adavance.

**Comment by hemangbhavasar** [comment]
Somehow are watching couple of videos and all the above suggestions, I am able to create exe but when I tried to run that exe file in another system rather then exe file is created, I am not able to run the exe file.

It now showing any error, but now working as expected. :(

**Comment by ravigupta-art** [comment]
> > > > @hemangbhavasar
> > > > The solution I am providing is not directly related to 'auto-py-to-exe'. As 'auto-py-to-exe' uses Pyinstaller for genrerating the executable. Why don't you try to use command-line interface with Pyintstaller to generate the exe?
> > > > I simply used Pyinstaller in my project at ['ravigupta-art/IgnouPercentageCalculator'](https://github.com/ravigupta-art/IgnouPercentageCalculator) and the executable generated works across different machines with supported OS and platform.
> > > > A Pyinstaller command would look like this:
> > > > `$ pyinstaller -wF --add-data "data_filename.extention:." your_main_pythonfile.py`
> > > > Here the flag '-w' generates a a single window while running the app. '-F' flag is used to bundle all the dependencies and generate a single executable file. '--add-data' add the extra or data files that are required/called within your main python app. Next is the data file name to added with the path (in my case it is simply '.' as the data file is located in the same folder as the python file. ( I am referring to this part "data_filename.extention:.")
> > > > And then comes the name of the python file.
> > > > Note: You need to in the same directory as the python file. Else, provide the path to the file in pyinstaller command.
> > > > If you are using windows the command would be like this:
> > > > `$ pyinstaller -wF --add-data "data_filename.extention;." your_main_pythonfile.py`
> > > > Note the difference, the ':' is replaced with ';' in the command for windows.
> > > 
> > > 
> > > Thanks for details.
> > > I saw you repository for calculator but in that also you have created a exe file from a python file.
> > > But in my case I am using 3 python files and one chromedriver file and I want to convert that into a exe.
> > > If you have any solution for that, please let me know. :)
> > > Thanks,
> > > Hemang Bhavasar
> > 
> > 
> > Please share link to your repo. I will see, if something can be done.
> 
> Hi Ravi,
> 
> I sent you invite please check.
> 
> Thanks for help in adavance.

Ok, I will try to look through it.

**Comment by hemangbhavasar** [comment]
Hey Ravi, Did you get a chance to look at my issue?

**Comment by hemangbhavasar** [comment]
Thanks to all.... 
I found the solution and now it it working. :)

**Comment by yoshihikoueno** [comment]
@hemangbhavasar Could you provide the solution you found? It might be helpful for other people facing similar problems.
