### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\x90'

### ISSUE THREAD

**Issue by reygarcia10** [brentvollebregt/auto-py-to-exe#93]
**auto-py-to-exe: 3.6.6**

Hi!
I can't run this simple app.
Any ideas?

**Environment**
PyInstaller: 3.6
Python: 3.6.8
Platform: Windows-10-10.0.18362-SP0

Error:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/36060173/79284070-80c33300-7e6e-11ea-84aa-692af0772650.png">
<img width="345" alt="image" src="https://user-images.githubusercontent.com/36060173/79283991-4c4f7700-7e6e-11ea-9dc9-50c3257b3061.png">
<img width="280" alt="image" src="https://user-images.githubusercontent.com/36060173/79284019-62f5ce00-7e6e-11ea-9afd-81a03a73ebc1.png">

Sample code:
print('Hello World!')

Output:
Running auto-py-to-exe v2.6.6
Building in the current instances temporary directory at C:\Users\reynaldo\AppData\Local\Temp\tmp7324buft
To get a new temporary directory, restart this application
Recursion Limit is set to 5000
Executing: pyinstaller -y  "C:/Users/reynaldo/Desktop/hello/hello.py"
67197 INFO: PyInstaller: 3.6
67197 INFO: Python: 3.6.8
67197 INFO: Platform: Windows-10-10.0.18362-SP0
67197 INFO: wrote C:\Users\reynaldo\AppData\Local\Temp\tmp7324buft\hello.spec
67197 INFO: UPX is not available.
67213 INFO: Extending PYTHONPATH with paths
['C:\\Users\\reynaldo\\Desktop\\hello',
 'C:\\Users\\reynaldo\\AppData\\Local\\Temp\\tmp7324buft']
67213 INFO: checking Analysis
67213 INFO: Building Analysis because Analysis-00.toc is non existent
67213 INFO: Initializing module dependency graph...
67213 INFO: Caching module graph hooks...
67228 INFO: Analyzing base_library.zip ...
71072 INFO: Caching module dependency graph...
71134 INFO: running Analysis Analysis-00.toc
71164 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\reynaldo\AppData\Local\Programs\Python\Python36\python.exe
71244 INFO: Analyzing C:\Users\reynaldo\Desktop\hello\hello.py
71244 INFO: Processing module hooks...
71244 INFO: Loading module hook "hook-encodings.py"...
71322 INFO: Loading module hook "hook-pydoc.py"...
71322 INFO: Loading module hook "hook-xml.py"...
71620 INFO: Looking for ctypes DLLs
71620 INFO: Analyzing run-time hooks ...
71620 INFO: Looking for dynamic libraries
71729 INFO: Looking for eggs
71729 INFO: Using Python library C:\Users\reynaldo\AppData\Local\Programs\Python\Python36\python36.dll
71729 INFO: Found binding redirects: 
[]
71729 INFO: Warnings written to C:\Users\reynaldo\AppData\Local\Temp\tmp7324buft\build\hello\warn-hello.txt
71757 INFO: Graph cross-reference written to C:\Users\reynaldo\AppData\Local\Temp\tmp7324buft\build\hello\xref-hello.html
71761 INFO: checking PYZ
71761 INFO: Building PYZ because PYZ-00.toc is non existent
71761 INFO: Building PYZ (ZlibArchive) C:\Users\reynaldo\AppData\Local\Temp\tmp7324buft\build\hello\PYZ-00.pyz
72115 INFO: Building PYZ (ZlibArchive) C:\Users\reynaldo\AppData\Local\Temp\tmp7324buft\build\hello\PYZ-00.pyz completed successfully.
72123 INFO: checking PKG
72123 INFO: Building PKG because PKG-00.toc is non existent
72123 INFO: Building PKG (CArchive) PKG-00.pkg
72139 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
72139 INFO: Bootloader C:\Users\reynaldo\AppData\Local\Programs\Python\Python36\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
72139 INFO: checking EXE
72139 INFO: Building EXE because EXE-00.toc is non existent
72139 INFO: Building EXE from EXE-00.toc
72139 INFO: Appending archive to EXE C:\Users\reynaldo\AppData\Local\Temp\tmp7324buft\build\hello\hello.exe
72234 INFO: Building EXE from EXE-00.toc completed successfully.
72234 INFO: checking COLLECT
72234 INFO: Building COLLECT because COLLECT-00.toc is non existent
72234 INFO: Building COLLECT COLLECT-00.toc
72660 INFO: Building COLLECT COLLECT-00.toc completed successfully.
Moving project to: C:\Users\reynaldo\Desktop\auto-py-to-exe-2.6.6\output
Complete.

**Comment by brentvollebregt** [comment]
Have you tried to run this script with Python itself?

**Comment by reygarcia10** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/36060173/79356648-18b73000-7ef4-11ea-80d7-753726c3c56d.png">

I trying different versions of PyInstaller but nothing.

**Comment by jrcribb** [comment]
Can you send us the error executing the program in C:\Users\reynaldo\Desktop\auto-py-to-exe-2.6.6\output ?

**Comment by jrcribb** [comment]
Are you compiling from linux to windows?

**Comment by jrcribb** [comment]
You can't use the exe executing "python hello.exe". You must execute "hello.exe"  without quotes

**Comment by reygarcia10** [comment]
> You can't use the exe executing "python hello.exe". You must execute "hello.exe" without quotes


[output.zip](https://github.com/brentvollebregt/auto-py-to-exe/files/4482844/output.zip)
[hello.zip](https://github.com/brentvollebregt/auto-py-to-exe/files/4482845/hello.zip)

yes I know, I do it because i want to see the error

**Comment by jrcribb** [comment]
![image](https://user-images.githubusercontent.com/2317928/79376087-04912400-7f30-11ea-9c3e-5306969cbda9.png)

**Comment by reygarcia10** [comment]
yeah you right, something is wrong in my windows version "Windows-10-10.0.18362-SP0". I tried another windows version and it works well.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/36060173/79377670-e36d0b00-7f10-11ea-9e03-3c04ccca551d.png">
